force-app/main/default/objects/SEL_ApplicationLog__c/SEL_ApplicationLog__c.object-meta.xml
<CustomObject>
    <description>Logs generated from application exceptions. Part of the Salesforce Enterprise Library (SEL) by Macjules Sevilla.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_Exception__c.field-meta.xml
<CustomField>
    <fullName>SEL_Exception__c</fullName>
    <description>Represents the exception type.</description>
    <label>Exception</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_Method__c.field-meta.xml
<CustomField>
    <fullName>SEL_Method__c</fullName>
    <description>The method where the exception originated.</description>
    <label>Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_Source__c.field-meta.xml
<CustomField>
    <fullName>SEL_Source__c</fullName>
    <description>The class name where the exception occurred.</description>
    <label>Source</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/recordTypes/Exception.recordType-meta.xml
<RecordType>
    <fullName>Exception</fullName>
    <active>true</active>
    <label>Exception</label>
</RecordType>

force-app/main/default/classes/SEL_ApexErrorBatch_TEST.cls
/*-----------------------------------------------------------------------------------------
DESCRIPTION	:	Unit test class for ApexErrorBatch and BatchApexError Trigger.
AUTHOR		:	Macjules Sevilla
LIBRARY		:	Salesforce Enterprise Library (SEL) - Logging Framework
VERSION		:	2.0

HISTORY		:
Date			Author				Comment
NOV-11-2021		Macjules Sevilla	Initial version
-----------------------------------------------------------------------------------------*/
@IsTest
public with sharing class SEL_ApexErrorBatch_TEST 
{
	@IsTest
	@SuppressWarnings('PMD.EmptyCatchBlock, PMD.SOQLSelectorPattern')
	private static void apexErrorBatchTrigger() 
	{
		// TEST
		try 
		{
			Test.startTest();
			Database.executeBatch(new SEL_ApexErrorBatch());
			Test.stopTest();
		} 
		catch(Exception ex) 
		{
			// KEEP THIS SECTION EMPTY
		}
		
		// FORCE PLATFORM EVENT TO RUN
		Test.getEventBus().deliver();
		
		// ASSERT
		SEL_ApplicationLog__c log = [SELECT Id, SEL_Exception__c, SEL_Method__c FROM SEL_ApplicationLog__c WHERE SEL_Source__c =: 'SEL_ApexErrorBatch' LIMIT 1];
		//System.debug(log);
		System.assert(log.SEL_Exception__c.equalsIgnoreCase('MathException'), 'The exception must be set to MathException.');
		System.assert(log.SEL_Method__c.equalsIgnoreCase('EXECUTE'), 'The method must be set to EXECUTE.');
	}
}