force-app/main/default/objects/SEL_ApplicationLog__c/SEL_ApplicationLog__c.object-meta.xml
<CustomObject>
    <description>Logs generated from application exceptions. Part of the Salesforce Enterprise Library (SEL) by Macjules Sevilla.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_Exception__c.field-meta.xml
<CustomField>
    <fullName>SEL_Exception__c</fullName>
    <description>Represents the exception type.</description>
    <label>Exception</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_Message__c.field-meta.xml
<CustomField>
    <fullName>SEL_Message__c</fullName>
    <description>The short version of the exception message.</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_Method__c.field-meta.xml
<CustomField>
    <fullName>SEL_Method__c</fullName>
    <description>The method where the exception originated.</description>
    <label>Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_Source__c.field-meta.xml
<CustomField>
    <fullName>SEL_Source__c</fullName>
    <description>The class name where the exception occurred.</description>
    <label>Source</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/recordTypes/Exception.recordType-meta.xml
<RecordType>
    <fullName>Exception</fullName>
    <active>true</active>
    <label>Exception</label>
</RecordType>

force-app/main/default/classes/SEL_LoggingService_TEST.cls
/*-----------------------------------------------------------------------------
DESCRIPTION	:	Test class for Logging Service.
AUTHOR		:	Macjules Sevilla
LIBRARY		:	Salesforce Enterprise Library (SEL) - Logging Framework
VERSION		:	2.0

Time (MS)		Method
262				ExceptionInfo
20 				logBatchApexErrorEvent
13 				save
-----------------------------------------------------------------------------*/
@IsTest
public with sharing class SEL_LoggingService_TEST 
{
	@IsTest
	@SuppressWarnings('PMD.CodeBestPracticesAvoidEmptyQueries, PMD.SOQLSelectorPattern')
	private static void exceptionInfo() 
	{
		try 
		{
			throw new DmlException('Test Dml Error');    
		} 
		catch (Exception ex) 
		{
			Test.startTest();

			SEL_LoggingService.log(ex);

			Test.stopTest();   

			SEL_ApplicationLog__c log = [SELECT SEL_Source__c, SEL_Method__c, SEL_Message__c, SEL_Exception__c FROM SEL_ApplicationLog__c WHERE SEL_Source__c =: 'SEL_LoggingService_TEST' ORDER BY CreatedDate DESC LIMIT 1];
			System.assert(log.SEL_Method__c == 'exceptionInfo', 'The method name in the application log must be exceptionInfo');
			System.assert(log.SEL_Message__c == 'Test Dml Error', 'The message in the application log must be Test Dml Error');
			System.assert(log.SEL_Exception__c == 'DmlException', 'The type name in the application log must be DmlException');

			// NOTE
			// If there is a need to create the SELECTOR layer for application log objects, then move the SOQL above into that class
		} 
	}

	@IsTest
	@SuppressWarnings('PMD.CodeBestPracticesAvoidEmptyQueries, PMD.SOQLSelectorPattern')
	private static void logBatchApexErrorEvent()
	{
		Test.startTest();

		// TEST
		SEL_LoggingService.log(new List<BatchApexErrorEvent>());
		List<SEL_ApplicationLog__c> logs = [SELECT Id FROM	SEL_ApplicationLog__c WHERE RecordTypeId =: SEL_ApplicationLogs.RECORD_TYPE_ID_EXCEPTION];
		
		// NOTE
		// If there is a need to create the SELECTOR layer for application log objects, then move the SOQL above into that class

		// ASSERT
		System.assert(logs.isEmpty(), 'No application log record must be returned.');

		Test.stopTest();
	}

	@IsTest
	private static void save()
	{
		Test.startTest();

		try 
		{
			SEL_LoggingService log = new SEL_LoggingService();
			log.publish();
		} 
		catch (Exception ex) 
		{
			// ASSERT
			System.assert(ex.getTypeName().contains('IllegalArgumentException'), 'Calling the save button without parameters throws an exception.');
		}
		
		Test.stopTest();
	}
}