force-app/main/default/objects/SEL_ApplicationLog__c/SEL_ApplicationLog__c.object-meta.xml
<CustomObject>
    <description>Logs generated from application exceptions. Part of the Salesforce Enterprise Library (SEL) by Macjules Sevilla.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_Category__c.field-meta.xml
<CustomField>
    <fullName>SEL_Category__c</fullName>
    <description>Use this to categorise the type of application log.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_Details__c.field-meta.xml
<CustomField>
    <fullName>SEL_Details__c</fullName>
    <description>Contains the serialized version of the SEL_AsyncDml__e.</description>
    <label>Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_ErrorId__c.field-meta.xml
<CustomField>
    <fullName>SEL_ErrorId__c</fullName>
    <description>In Flows, this is populated with Interview ID. 
In Apex Batch, this is populated with Async Apex Job ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>In Flows, this is populated with Interview ID. 
In Apex Batch, this is populated with Async Apex Job ID.</inlineHelpText>
    <label>Error ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_Exception__c.field-meta.xml
<CustomField>
    <fullName>SEL_Exception__c</fullName>
    <description>Represents the exception type.</description>
    <label>Exception</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_Message__c.field-meta.xml
<CustomField>
    <fullName>SEL_Message__c</fullName>
    <description>The short version of the exception message.</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_Method__c.field-meta.xml
<CustomField>
    <fullName>SEL_Method__c</fullName>
    <description>The method where the exception originated.</description>
    <label>Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_RunningUserId__c.field-meta.xml
<CustomField>
    <fullName>SEL_RunningUserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user that experienced the issue.</description>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ApplicationLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_Source__c.field-meta.xml
<CustomField>
    <fullName>SEL_Source__c</fullName>
    <description>The class name where the exception occurred.</description>
    <label>Source</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/fields/SEL_Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>SEL_Stacktrace__c</fullName>
    <description>The entire stack trace of the exception.</description>
    <label>Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SEL_ApplicationLog__c/recordTypes/Exception.recordType-meta.xml
<RecordType>
    <fullName>Exception</fullName>
    <active>true</active>
    <label>Exception</label>
</RecordType>

force-app/main/default/objects/SEL_AsyncDml__e/SEL_AsyncDml__e.object-meta.xml
<CustomObject>
    <description>Processes the DML operations asynchronously. This is part of the Salesforce Enterprise Library (SEL) created by Macjules Sevilla.</description>
    <label>Async DML Platform Event</label>
    <pluralLabel>Async DML Platform Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/SEL_AsyncDml__e/fields/SEL_Action__c.field-meta.xml
<CustomField>
    <fullName>SEL_Action__c</fullName>
    <description>Can be one of the following values: insert, update, upsert, delete or undelete.</description>
    <label>Action</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_AsyncDml__e/fields/SEL_Object__c.field-meta.xml
<CustomField>
    <fullName>SEL_Object__c</fullName>
    <description>The object API of the record to process.</description>
    <label>Object</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_AsyncDml__e/fields/SEL_Record__c.field-meta.xml
<CustomField>
    <fullName>SEL_Record__c</fullName>
    <description>The serialized version of the record to process. This is not bulkified, i.e. one event message equals one record.</description>
    <label>Record</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SEL_LoggingService.cls
/*-------------------------------------------------------------------------------------------
DESCRIPTION	:	Service layer for Logging services.
AUTHOR		:	Macjules Sevilla
LIBRARY		:	Salesforce Enterprise Library (SEL) - Logging Framework
VERSION		:	2.0

HISTORY		:
Date			Author				Comment
FEB-11-2021		Macjules Sevilla	Initial version
AUG-27-2021		Macjules Sevilla	Added category field and support to BatchApexErrorEvent
JAN-14-2022		Macjules Sevilla	Added running user field.
-------------------------------------------------------------------------------------------*/
@SuppressWarnings('PMD.ExcessivePublicCount')
public inherited sharing class SEL_LoggingService 
{
	// PROPERTIES
	public List<SEL_LoggingService.Message> messages = new List<SEL_LoggingService.Message>();

	// DESCRIPTION
	// Use this method to log an exception while defaulting the type to APEX
	public static void log(Exception ex)
	{
		SEL_LoggingService.log(ex, SEL_ApplicationLogs.TYPE_APEX);
	}

	// DESCRIPTION
	// Use this method to log an exception
	public static void log(Exception ex, String category)
	{
		if(ex == null) { return; }

		ExceptionInfo info = new ExceptionInfo(ex);

		SEL_LoggingService.Message log = new SEL_LoggingService.Message();
		log.category = category;
		log.exceptionType = info.exceptionType;
		log.runningUser = UserInfo.getUserId();
		log.source = info.className;
		log.stacktrace = ex.getStackTraceString();
		log.method = info.Method;
		log.message = ex.getMessage();

		SEL_LoggingService service = new SEL_LoggingService();
		service.messages.add(log);
		service.publish();
	}

	// DESCRIPTION
	// Use this method on BatchApexErrorEvent Platform Event ONLY. This is not using
	// custom platform event as this method is called from a platform event.
	@SuppressWarnings('PMD.TestDoNotUseIsRunningTest')
	public static void log(List<BatchApexErrorEvent> events)
	{
		if((events == null || events.isEmpty()) && !Test.isRunningTest()) { return; }

		List<SEL_ApplicationLog__c> logs = new List<SEL_ApplicationLog__c>();

		for(BatchApexErrorEvent e : events)
		{
			SEL_ApplicationLog__c log = new SEL_ApplicationLog__c(
				RecordTypeId = SEL_ApplicationLogs.RECORD_TYPE_ID_EXCEPTION,
				SEL_Category__c = SEL_ApplicationLogs.TYPE_BATCH,
				SEL_Details__c = 'JobScope: ' + e.JobScope + '/nRequestId: ' + e.RequestId?.left(50),
				SEL_ErrorId__c = e.AsyncApexJobId?.left(100),
				SEL_Exception__c = e.ExceptionType?.replace('System.', '').left(255),
				SEL_Message__c = e.Message.left(255),
				SEL_Method__c = e.Phase?.left(50),
				SEL_RunningUserId__c = UserInfo.getUserId(),
				SEL_Source__c = e.StackTrace.replace('Class.', '').substringBefore('.'),
				SEL_Stacktrace__c = e.StackTrace
			);
			logs.add(log);
		}

		if(Schema.sObjectType.SEL_ApplicationLog__c.isCreateable())
		{
			insert logs;
		}
	}
	public static void log(String category, String className,String methodName,String message)
	{

		SEL_LoggingService.Message log = new SEL_LoggingService.Message();
		log.category = category;
		//log.exceptionType = info.exceptionType;
		log.runningUser = UserInfo.getUserId();
		log.source = className;
		log.stacktrace = message;
		log.method = methodName;
		log.message = message;

		SEL_LoggingService service = new SEL_LoggingService();
		service.messages.add(log);
		service.publish();
	}
	
	// DESCRIPTION
	// Save the ApplicationLog via platform event
	public void publish()
	{
		if(messages.size() > 0)
		{
			List<SEL_AsyncDml__e> events = new List<SEL_AsyncDml__e>();

			for(SEL_LoggingService.Message m : this.messages)
			{
				// Write exception details to Application Log
				SEL_ApplicationLog__c log = new SEL_ApplicationLog__c(
					RecordTypeId = SEL_ApplicationLogs.RECORD_TYPE_ID_EXCEPTION,
					SEL_Category__c = m?.category,
					SEL_ErrorId__c = m?.errorId?.left(100),
					SEL_Exception__c = m?.exceptionType?.left(255),
					SEL_Message__c = m?.message?.left(255),
					SEL_Method__c = m?.method?.left(50),
					SEL_RunningUserId__c = m?.runningUser,
					SEL_Source__c = m?.source?.left(50),
					SEL_Stacktrace__c = m?.stacktrace
				);

				// Platform Event to issue DML
				SEL_AsyncDml__e event = new SEL_AsyncDml__e(
					SEL_Action__c = SEL_CoreConstants.DML_INSERT,
					SEL_Object__c = SEL_ApplicationLogs.OBJECT_API,
					SEL_Record__c = JSON.serialize(log)
				);
				events.add(event);
			}

			Eventbus.publish(events);
		}
	}

	// DESCRIPTION
	// Detects the class, method, and exception type from Exception class
	@TestVisible
	private without sharing class ExceptionInfo
	{
		public String className { get; private set; }
		public String method { get; private set; }
		public String exceptionType { get; private set; }

		public ExceptionInfo(Exception ex)
		{
			String classAndMethod = ex.getStackTraceString().substringBefore(':').replace('Class.', '');
			this.className = classAndMethod.substringBefore('.');
			this.method = classAndMethod.substringAfter('.');
			this.exceptionType = ex.getTypeName().replace('System.', '');
		}
	}

	// CLASS
	// Wrapper class containing all data fields to log
	public without sharing class Message
	{
		public Id runningUser { get; set; }
		public String category { get; set; }
		public String errorId { get; set; }
		public String exceptionType { get; set; }
		public String source { get; set; }
		public String stacktrace { get; set; }
		public String method { get; set; }
		public String message { get; set; }
	}
}