force-app/main/default/objects/SPEN_Plot__c/SPEN_Plot__c.object-meta.xml
<CustomObject>
    <description>Plot object is created to store the Plot records related to a connections case</description>
    <label>Plot</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Plot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Plot__c/fields/SPEN_CaseRecord__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CaseRecord__c</fullName>
    <description>This field is for SPEN Connections process</description>
    <label>Case Record</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Plots</relationshipLabel>
    <relationshipName>Plots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_Plot__c/fields/SPEN_TechnologyType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_TechnologyType__c</fullName>
    <description>This field is for Connections process</description>
    <label>Technology Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Engine (combustion / reciprocating)</fullName>
            </value>
            <value>
                <fullName>Steam turbine (thermal power plant)</fullName>
            </value>
            <value>
                <fullName>Gas turbine (OCGT)</fullName>
            </value>
            <value>
                <fullName>Steam - gas turbine (CCGT)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Data not available</fullName>
            </value>
            <value>
                <fullName>Geothermal power plant</fullName>
            </value>
            <value>
                <fullName>Fuel cell</fullName>
            </value>
            <value>
                <fullName>Photovoltaic</fullName>
            </value>
            <value>
                <fullName>Storage - Chemical</fullName>
            </value>
            <value>
                <fullName>Storage - Electrical</fullName>
            </value>
            <value>
                <fullName>Storage - Mechanical - Compressed Air</fullName>
            </value>
            <value>
                <fullName>Storage - Mechanical - Liquid Air</fullName>
            </value>
            <value>
                <fullName>Storage - Mechanical - Pumped Hydro</fullName>
            </value>
            <value>
                <fullName>Storage - Mechanical - Flywheel</fullName>
            </value>
            <value>
                <fullName>Storage - Thermal</fullName>
            </value>
            <value>
                <fullName>Storage - Electrochemical (Batteries)</fullName>
            </value>
            <value>
                <fullName>Storage - Other</fullName>
            </value>
            <value>
                <fullName>Hydro - Run of river</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_PlotSelectorTEST.cls
@IsTest
public with sharing class SPEN_PlotSelectorTEST 
{
    
    @IsTest
    private static void testPlotsFromCase()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user);
        PermissionSet ps1 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_ContactAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps1.Id);
        PermissionSet ps2 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_CaseAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps2.Id);
        PermissionSet ps3 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_IVROperatinghoursAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps3.Id);
        PermissionSet ps4 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_PlotAccessCRUD'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps4.Id);
        
        System.runAs(user)
        {   
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
            List<Case> testCase = SPEN_TestDataFactory.createListOfCases(1);
            insert testCase;
            List<SPEN_Plot__c> plot=SPEN_TestDataFactory.createPlotRecords(SPEN_TestDataFactoryConstants.SINGLE_REC);
            plot[0].SPEN_CaseRecord__c=testCase[0].Id;
            insert plot;
            SPEN_PlotSelector.getPlotsFromCase(testCase[0].Id);
            SPEN_PlotSelector.getActivePlotsCountFromCase(testCase[0].Id);
            Assert.isNotNull(plot[0].SPEN_TechnologyType__c, 'Photovoltaic');
            Test.stopTest();            
        }
    }   
}