force-app/main/default/objects/SPEN_Invoice__c/SPEN_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Invoice__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_Invoice__c/fields/SPEN_InvoicedOutcome__c.field-meta.xml
<CustomField>
    <fullName>SPEN_InvoicedOutcome__c</fullName>
    <label>Invoice Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Issued</fullName>
                <default>true</default>
                <label>Issued</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Redirected</fullName>
            </value>
            <value>
                <fullName>Re-issued</fullName>
            </value>
            <value>
                <fullName>Written Off</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Negotiated Settlement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Invoice__c/recordTypes/SPEN_ThirdPartyDamage.recordType-meta.xml
<RecordType>
    <fullName>SPEN_ThirdPartyDamage</fullName>
    <active>true</active>
    <description>Record type for the Third Party Damage type invoices related to Third party damage cases</description>
    <label>Third Party Damage</label>
</RecordType>

force-app/main/default/classes/SPEN_InvoiceService.cls
/*-----------------------------------------------------------------------------
DESCRIPTION :   Service Class for Invoice Trigger
LIBRARY     :   Salesforce Enterprise Library (SEL) - Core
VERSION     :   1.0
Date        :   JULY-17-2023:  
-----------------------------------------------------------------------------*/
public with sharing class SPEN_InvoiceService
{
    public static void afterInvoiceInsert(List<sObject> invoiceNewList)
    {
        List<SPEN_Invoice__c> invList = invoiceNewList;
        Set<Id> caseIds = new Set<Id>();
        Id thirdPartyDamageRTId = Schema.SObjectType.SPEN_Invoice__c.getRecordTypeInfosByDeveloperName().get('SPEN_ThirdPartyDamage').getRecordTypeId();
        Map<Id, Case> casesWithNonCancelledInvoices = New Map<Id, Case>();
        
        for(SPEN_Invoice__c inv : invList) 
        {
            if(inv.RecordTypeId == thirdPartyDamageRTId && inv.SPEN_InvoicedOutcome__c != 'Cancelled')
            {
                caseIds.add(inv.SPEN_Case__c);
            }
        }
        
        if(!caseIds.isEmpty())
        {
            //Quering related case with non cancelled invoices
            casesWithNonCancelledInvoices = SPEN_InvoiceSelector.getInvoicesRelatedToCases(caseIds);

            //Collect the invoices to cancel
            List<SPEN_Invoice__c> invoiceListToCancel = new List<SPEN_Invoice__c>();
            
            //Iterate over new Invoices and associated cases
            if(!casesWithNonCancelledInvoices.isEmpty())
            {
                for(SPEN_Invoice__c inv : invList)
                {
                    Case relCase = casesWithNonCancelledInvoices.get(inv.SPEN_Case__c);
                    if(relCase!=null && !relCase.Invoices__r.isEmpty())
                    {    
                        for(SPEN_Invoice__c relInvoice : relCase.Invoices__r)
                        {
                            if(relInvoice.SPEN_InvoicedOutcome__c != 'Cancelled' && relInvoice.id !=inv.Id)
                            {
                                relInvoice.SPEN_InvoicedOutcome__c = 'Cancelled';
                                invoiceListToCancel.add(relInvoice);
                            }
                        }
                    }
                }
            
                //Cancel the Non-Cancelled Invoices
                if (!invoiceListToCancel.isEmpty())
                {
                    update invoiceListToCancel;
                }
        	}
   		}
	}
}