force-app/main/default/objects/SPEN_IVR__c/SPEN_IVR__c.object-meta.xml
<CustomObject>
    <description>This object will hold IVR flow details.</description>
    <label>IVR</label>
    <nameField>
        <label>IVR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/SPEN_IVROperatinghours__c.object-meta.xml
<CustomObject>
    <description>IVR Operating hours object is operating on time based on start time and end time.</description>
    <label>IVR Operating hours</label>
    <nameField>
        <label>IVR Operating hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Operating hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_IVR__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVR__c</fullName>
    <description>IVR field is in master details relationship with IVR object and IVR Operating hours</description>
    <label>IVR</label>
    <referenceTo>SPEN_IVR__c</referenceTo>
    <relationshipLabel>IVR Operating hours</relationshipLabel>
    <relationshipName>IVR_Operating_hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>IVR Message field is in master details relationship with IVR Message object and IVR Operating hours</description>
    <label>IVR Message</label>
    <referenceTo>SPEN_IVRMessage__c</referenceTo>
    <relationshipLabel>IVR Operating hours</relationshipLabel>
    <relationshipName>IVR_Operating_hours</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SPEN_OutboundCommsCheckerSelectorTEST.cls
@IsTest
@SuppressWarnings('PMD.SOQLSelectorPattern')
public class SPEN_OutboundCommsCheckerSelectorTEST {
    @IsTest
    private static void testgetIfIn(){
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user); 
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_VoiceAlertAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps.Id); 
        PermissionSet ps1 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_PSRAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps1.Id);
        PermissionSet ps2 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_ContactAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps2.Id);
        PermissionSet ps3 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_IVROperatinghoursAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps3.Id);
        System.runAs(user)
        {
             	SPEN_IVRMessage__c ivrMessage = SPEN_TestDataFactory.createIVRMessage(1);
            	insert ivrMessage;
            	List<SPEN_IVR__c> ivrList=SPEN_TestDataFactory.createIVRrecord(SPEN_TestDataFactoryConstants.SINGLE_REC);
            	insert ivrList;
            	List<SPEN_IVROperatingHours__c> operatingList=SPEN_TestDataFactory.createIVROperatingHoursrecord(SPEN_TestDataFactoryConstants.SINGLE_REC,                                                                                                 ivrList[0].Id,ivrMessage.Id);
            	insert operatingList;
            
            	Test.startTest();
            	List<SPEN_IVROperatingHours__c> testList=SPEN_OutboundCommsCheckerSelector.getIfInRestricedDate(operatingList[0].Id);
            	List<SPEN_IVROperatingHours__c> testList2=SPEN_OutboundCommsCheckerSelector.getIfInRestricedDate(NULL);
            	List<SPEN_IVROperatingHours__c> testList1=SPEN_OutboundCommsCheckerSelector.getIfInStartEndTime(operatingList[0].Id);
            	Assert.isNotNull(testList);
            	Assert.isNotNull(testList1);
            	Test.stopTest();
        }
    }
        /*static void testThrowAnException() {
    	Exception capturedException;

    	try {
        	throwAnException();
    	} 	catch (Exception e) {
        	capturedException = e;
    	}

    	System.assertNotEquals(null, capturedException, 'Exception should be thrown');
    	System.assertEquals(AuraHandledException.class.getName(), capturedException.getTypeName(), 'AuraHandledException is expected');
    	System.assertEquals('The message that you can get in a test', capturedException.getMessage(), 'Specific error message is expected');
		}*/
    }