force-app/main/default/objects/SPEN_IVR__c/SPEN_IVR__c.object-meta.xml
<CustomObject>
    <description>This object will hold IVR flow details.</description>
    <label>IVR</label>
    <nameField>
        <label>IVR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <externalId>true</externalId>
    <inlineHelpText>This value must not be changed if IVR uses this message template.</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/recordTypes/SMS.recordType-meta.xml
<RecordType>
    <fullName>SMS</fullName>
    <active>true</active>
    <label>SMS</label>
</RecordType>

force-app/main/default/objects/SPEN_IVROperatinghours__c/SPEN_IVROperatinghours__c.object-meta.xml
<CustomObject>
    <description>IVR Operating hours object is operating on time based on start time and end time.</description>
    <label>IVR Operating hours</label>
    <nameField>
        <label>IVR Operating hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Operating hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_EndTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EndTime__c</fullName>
    <description>End time field will collect the ending time of IVR Operating hours</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>Holds the external Id.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isActive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_IVR__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVR__c</fullName>
    <description>IVR field is in master details relationship with IVR object and IVR Operating hours</description>
    <label>IVR</label>
    <referenceTo>SPEN_IVR__c</referenceTo>
    <relationshipLabel>IVR Operating hours</relationshipLabel>
    <relationshipName>IVR_Operating_hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>IVR Message field is in master details relationship with IVR Message object and IVR Operating hours</description>
    <label>IVR Message</label>
    <referenceTo>SPEN_IVRMessage__c</referenceTo>
    <relationshipLabel>IVR Operating hours</relationshipLabel>
    <relationshipName>IVR_Operating_hours</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_StartTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_StartTime__c</fullName>
    <description>Start time field will collect the starting time of IVR Operating hours</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/SPEN_IvrOperatingHoursSelectorTest.cls
@isTest
@SuppressWarnings('PMD.SOQLSelectorPattern')
public with sharing class SPEN_IvrOperatingHoursSelectorTest {
    @testSetup static void setup(){
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user);
        PermissionSet ps1 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_IVROperatinghoursAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps1.Id);
        System.runAs(user)
        {
            test.startTest();
        	List<SPEN_IVR__c> iVRList = SPEN_TestDataFactory.createIVRrecord(1);
            Insert iVRList;
            SPEN_IVRMessage__c iVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
            Insert iVRMessage;
            Id iVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('SMS Blackout Window').getRecordTypeId();
            List<SPEN_IVROperatingHours__c> ivrOperHourList = SPEN_TestDataFactory.createIVROperatingHoursrecord(2,iVRList[0].id,iVRMessage.id);
            for(SPEN_IVROperatingHours__c ivr : ivrOperHourList)
            {
                ivr.RecordTypeId = iVROperatingHoursRecordTypeId;
                ivr.SPEN_isActive__c = TRUE;
                ivr.SPEN_StartTime__c = system.now().time() - 10;
                ivr.SPEN_EndTime__c = system.now().time() - 5;
            }
            Insert ivrOperHourList;
            test.stopTest();
    	}        
    }
    @isTest
    public static void getIVROperatingHourTypeCheckTestPos()
    {
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);       
        System.runAs(user)
        {
            test.startTest();
            Id iVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('SMS Blackout Window').getRecordTypeId();
        	SPEN_IVROperatingHours__c ivroh=SPEN_IvrOperatingHoursSelector.getIVROperatingHourTypeCheck(iVROperatingHoursRecordTypeId);
            Assert.AreEqual(ivroh.RecordTypeId,iVROperatingHoursRecordTypeId);
            test.stopTest();
    	}
    }
    @isTest
    public static void getIVROperatingHourTypeCheckTestNeg()
    {
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);       
        System.runAs(user)
        {
            test.startTest();
            Id iVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('VA Blackout Window').getRecordTypeId();
        	SPEN_IVROperatingHours__c ivroh=SPEN_IvrOperatingHoursSelector.getIVROperatingHourTypeCheck(iVROperatingHoursRecordTypeId);
            Assert.areEqual(ivroh,new SPEN_IVROperatingHours__c());
            test.stopTest();
    	}
    }
    @isTest
    public static void getIVROperatingHoursTestPos()
    {
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);       
        System.runAs(user)
        {
            test.startTest();
        	List<SPEN_IVROperatingHours__c> ivroh=SPEN_IvrOperatingHoursSelector.getIVROperatingHours('SMS Blackout Window');
            Assert.isTrue(ivroh!=null);
            test.stopTest();
    	}
    }
    @isTest
    public static void getIVROperatingHoursTestNeg()
    {
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);       
        System.runAs(user)
        {
            test.startTest();
            try{
                List<SPEN_IVROperatingHours__c> ivroh=SPEN_IvrOperatingHoursSelector.getIVROperatingHours('Test');
            	Assert.areEqual(ivroh,new SPEN_IVROperatingHours__c());
            }catch(Exception e){
                Assert.isNotNull(e);
        	}
            test.stopTest();
    	}
    }
    @isTest
    public static void getIVROperatingHoursTestPos1()
    {
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);       
        System.runAs(user)
        {
            test.startTest();
            Set<Id> currentidset= new Set<Id>();
            Map<id,string> recMap = new Map<id,string>();
            List<SPEN_IVR__c> iVRList = SPEN_TestDataFactory.createIVRrecord(1);
            Insert iVRList;
            SPEN_IVRMessage__c iVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
            iVRmessage.SPEN_ExternalId__c = 'Test12345678';    
            Insert iVRMessage;
            Id iVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('SMS Blackout Window').getRecordTypeId();
            recMap.put(iVROperatingHoursRecordTypeId,'SMS Blackout Window');
            List<SPEN_IVROperatingHours__c> ivrOperHourList = SPEN_TestDataFactory.createIVROperatingHoursrecord(1,iVRList[0].id,iVRMessage.id);
            for(SPEN_IVROperatingHours__c ivr : ivrOperHourList)
            {
                ivr.RecordTypeId = iVROperatingHoursRecordTypeId;
                ivr.SPEN_isActive__c = true;
                ivr.SPEN_StartTime__c = system.now().time() + 10;
                ivr.SPEN_EndTime__c = system.now().time() +5;
            }
            try{
                Insert ivrOperHourList;
            	currentidset.add(ivrOperHourList[0].id);
        		List<SPEN_IVROperatingHours__c> ivroh=SPEN_IvrOperatingHoursSelector.getIVROperatingHours(recMap.keyset(),currentidset);
            	Assert.isTrue(ivroh!=null);
            }catch(Exception e){
                  Assert.isTrue(e!=null);
            }
            test.stopTest();
    	}
    }
    @isTest
    public static void getIVROperatingHoursTestNeg1()
    {
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);       
        System.runAs(user)
        {
            test.startTest();
            List<SPEN_IVR__c> iVRList = SPEN_TestDataFactory.createIVRrecord(1);
            Insert iVRList;
            SPEN_IVRMessage__c iVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
            iVRmessage.SPEN_ExternalId__c = 'Test1234567';    
            insert iVRMessage;
            Id iVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('SMS Blackout Window').getRecordTypeId();
            List<SPEN_IVROperatingHours__c> ivrOperHourList = SPEN_TestDataFactory.createIVROperatingHoursrecord(1,iVRList[0].id,iVRMessage.id);
            for(SPEN_IVROperatingHours__c ivr : ivrOperHourList)
            {
                ivr.RecordTypeId = iVROperatingHoursRecordTypeId;
                ivr.SPEN_isActive__c = False;
                ivr.SPEN_StartTime__c = system.now().time() - 10;
                ivr.SPEN_EndTime__c = system.now().time() - 5;
            }
            Insert ivrOperHourList;
            try{
             	List<SPEN_IVROperatingHours__c> ivroh=SPEN_IvrOperatingHoursSelector.getIVROperatingHours(NULL,NULL);
            	Assert.areEqual(ivroh,new SPEN_IVROperatingHours__c());
            }catch(Exception e){
                Assert.isNotNull(e);
            }
            test.stopTest();
    	}
    }
}