force-app/main/default/objects/SPEN_IVR__c/SPEN_IVR__c.object-meta.xml
<CustomObject>
    <description>This object will hold IVR flow details.</description>
    <label>IVR</label>
    <nameField>
        <label>IVR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVR__c/fields/SPEN_CallGroup__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CallGroup__c</fullName>
    <label>Call Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SPEN_CallGroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/SPEN_CallGroup.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General Enquiries</fullName>
    </customValue>
    <customValue>
        <fullName>MPAS</fullName>
    </customValue>
    <customValue>
        <fullName>PSR</fullName>
    </customValue>
    <customValue>
        <fullName>SPD</fullName>
    </customValue>
    <customValue>
        <fullName>SPM</fullName>
    </customValue>
    <customValue>
        <fullName>Unclassified</fullName>
    </customValue>
    <customValue>
        <fullName>Streetworks_South</fullName>
    </customValue>
    <customValue>
        <fullName>Streetworks_North</fullName>
    </customValue>
    <customValue>
        <fullName>Debt</fullName>
    </customValue>
    <customValue>
        <fullName>DefaultVoiceChannel</fullName>
    </customValue>
    <customValue>
        <fullName>Faults</fullName>
    </customValue>
    <customValue>
        <fullName>CSAT</fullName>
    </customValue>
    <customValue>
        <fullName>Storm Bureau</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints-SPD</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints-SPM</fullName>
    </customValue>
    <customValue>
        <fullName>Social Obs</fullName>
    </customValue>
    <customValue>
        <fullName>SPD SEN</fullName>
    </customValue>
    <customValue>
        <fullName>SPM SEN</fullName>
    </customValue>
    <customValue>
        <fullName>NRSWA-North</fullName>
    </customValue>
    <customValue>
        <fullName>NRSWA-South</fullName>
    </customValue>
    <customValue>
        <fullName>3PD</fullName>
    </customValue>
    <customValue>
        <fullName>SPD Old</fullName>
    </customValue>
    <customValue>
        <fullName>SPM Old</fullName>
    </customValue>
    <customValue>
        <fullName>Connections</fullName>
    </customValue>
    <customValue>
        <fullName>MOP</fullName>
    </customValue>
    <customValue>
        <fullName>Voice Alerts</fullName>
    </customValue>
    <customValue>
        <fullName>GE Surveys</fullName>
    </customValue>
    <customValue>
        <fullName>LCT Surveys</fullName>
    </customValue>
    <customValue>
        <fullName>Faults Surveys</fullName>
    </customValue>
    <customValue>
        <fullName>Planned Works Surveys</fullName>
    </customValue>
    <description>Group related IVR numbers together based on purpose.</description>
    <masterLabel>Call Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SPEN_IVRSelector.cls
/*------------------------------------------------------------------------------------
DESCRIPTION	:	Selector class of IVR Object
LIBRARY		:	SPEN
VERSION		:	1.0

HISTORY		:
Date			Author				Comment
25.07.2023      shubhi V            created for remediation
------------------------------------------------------------------------------------*/
public with sharing class SPEN_IVRSelector {
        
    public static List<SPEN_IVR__c> getIvrSelector(List<String> externalIdSet){
        List<SPEN_IVR__c > lstIVR = new List<SPEN_IVR__c >();
        if(externalIdSet!=null && !externalIdSet.isEmpty()){
            lstIVR = [SELECT SPEN_CallGroup__c,SPEN_ExternalId__c FROM SPEN_IVR__c	
                WHERE SPEN_ExternalId__c IN:externalIdSet WITH SECURITY_ENFORCED];
        }
        return lstIVR;
    }
}