force-app/main/default/objects/SPEN_IVR__c/SPEN_IVR__c.object-meta.xml
<CustomObject>
    <description>This object will hold IVR flow details.</description>
    <label>IVR</label>
    <nameField>
        <label>IVR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/recordTypes/SMS.recordType-meta.xml
<RecordType>
    <fullName>SMS</fullName>
    <active>true</active>
    <label>SMS</label>
</RecordType>

force-app/main/default/objects/SPEN_IVROperatinghours__c/SPEN_IVROperatinghours__c.object-meta.xml
<CustomObject>
    <description>IVR Operating hours object is operating on time based on start time and end time.</description>
    <label>IVR Operating hours</label>
    <nameField>
        <label>IVR Operating hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Operating hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_EndTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EndTime__c</fullName>
    <description>End time field will collect the ending time of IVR Operating hours</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isActive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_IVR__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVR__c</fullName>
    <description>IVR field is in master details relationship with IVR object and IVR Operating hours</description>
    <label>IVR</label>
    <referenceTo>SPEN_IVR__c</referenceTo>
    <relationshipLabel>IVR Operating hours</relationshipLabel>
    <relationshipName>IVR_Operating_hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>IVR Message field is in master details relationship with IVR Message object and IVR Operating hours</description>
    <label>IVR Message</label>
    <referenceTo>SPEN_IVRMessage__c</referenceTo>
    <relationshipLabel>IVR Operating hours</relationshipLabel>
    <relationshipName>IVR_Operating_hours</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_StartTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_StartTime__c</fullName>
    <description>Start time field will collect the starting time of IVR Operating hours</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/SPEN_IVROperatingHoursHandlerTest.cls
@IsTest
@SuppressWarnings('PMD.SOQLSelectorPattern')
public class SPEN_IVROperatingHoursHandlerTest 
{    
    @testSetup static void setup(){
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user);
        PermissionSet ps1 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_IVROperatinghoursAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps1.Id);        
    }
    @isTest
    public static void activeRecordValidationTestPositive1()
    {
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);       
        System.runAs(user)
        {
            test.startTest();
        	List<SPEN_IVR__c> iVRList = SPEN_TestDataFactory.createIVRrecord(1);
            Insert iVRList;
            SPEN_IVRMessage__c iVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
            Insert iVRMessage;
            Id iVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('SMS Blackout Window').getRecordTypeId();
            List<SPEN_IVROperatingHours__c> ivrOperHourList = SPEN_TestDataFactory.createIVROperatingHoursrecord(2,iVRList[0].id,iVRMessage.id);
            for(SPEN_IVROperatingHours__c ivr : ivrOperHourList)
            {
                ivr.RecordTypeId = iVROperatingHoursRecordTypeId;
                ivr.SPEN_isActive__c = TRUE;
                ivr.SPEN_StartTime__c = system.now().time() - 10;
                ivr.SPEN_EndTime__c = system.now().time() - 5;
            }
            Insert ivrOperHourList;
            SPEN_IVROperatingHoursHandler.ActiveRecordValidation(ivrOperHourList,NULL);
            
            for(SPEN_IVROperatingHours__c ivr: ivrOperHourList )
            {
                ivr.SPEN_StartTime__c = system.now().time() - 15;
                ivr.SPEN_EndTime__c = system.now().time() - 10;
            }
            update ivrOperHourList;
            Assert.isNotNull(ivrOperHourList);
            test.stopTest();
    	}
    }
    @isTest
    public static void activeRecordValidationTestPostive2()
    {
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);       
        System.runAs(user)
        {
            test.startTest();
        	List<SPEN_IVR__c> iVRList = SPEN_TestDataFactory.createIVRrecord(1);
            Insert iVRList;
            SPEN_IVRMessage__c iVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
            Insert iVRMessage;
            Id iVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('SMS Blackout Window').getRecordTypeId();
            List<SPEN_IVROperatingHours__c> ivrOperHourList = SPEN_TestDataFactory.createIVROperatingHoursrecord(2,iVRList[0].id,iVRMessage.id);
            for(SPEN_IVROperatingHours__c ivr : ivrOperHourList)
            {
                ivr.RecordTypeId = iVROperatingHoursRecordTypeId;
                ivr.SPEN_isActive__c = TRUE;
                ivr.SPEN_StartTime__c = system.now().time() - 10;
                ivr.SPEN_EndTime__c = system.now().time() +10;
            }
            try{
                Insert ivrOperHourList;
            }catch(Exception e){
                Assert.isTrue(e!=null, 'there is validation error in ivr insertion');
            }
            test.stopTest();
    	}
    }
    @isTest
    public static void activeRecordValidationTestNegative()
    {
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);       
        System.runAs(user)
        {
            test.startTest();
            List<SPEN_IVROperatingHours__c> ivrOperHourList=new List<SPEN_IVROperatingHours__c>();
             SPEN_IVROperatingHoursHandler.ActiveRecordValidation(ivrOperHourList,null);
             Assert.isTrue(ivrOperHourList.isEmpty(), 'there is no error for null params');
            test.stopTest();
    	}
    }
}