force-app/main/default/objects/SPEN_BatchSettings__mdt/SPEN_BatchSettings__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata to be used for configuring settings for batch classes</description>
    <label>Batch Setting</label>
    <pluralLabel>Batch Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SPEN_BatchSettings__mdt/fields/SPEN_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BatchSize__c</fullName>
    <defaultValue>200</defaultValue>
    <description>Scope of the batch - defaulted to 200</description>
    <inlineHelpText>Scope of the batch - defaulted to 200</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_Incident_to_case_status_mapping__mdt/SPEN_Incident_to_case_status_mapping__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata to store the Incident to case status mapping</description>
    <label>SPEN Incident to case status mapping</label>
    <pluralLabel>SPEN Incident to case status mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SPEN_Incident_to_case_status_mapping__mdt/fields/SPEN_CaseStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CaseStatus__c</fullName>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Restored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Incident_to_case_status_mapping__mdt/fields/SPEN_IncidentStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentStatus__c</fullName>
    <label>Incident Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>Delog</fullName>
            </value>
            <value>
                <fullName>Reports OS</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Pre-arranged</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Merge</fullName>
            </value>
            <value>
                <fullName>Pending Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_Message__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Message__c</fullName>
    <description>It hold the message on IVR Message object</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/recordTypes/SMS.recordType-meta.xml
<RecordType>
    <fullName>SMS</fullName>
    <active>true</active>
    <label>SMS</label>
</RecordType>

force-app/main/default/objects/SPEN_Sms__c/SPEN_Sms__c.object-meta.xml
<CustomObject>
    <description>Represents a single SMS message.</description>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMSes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_CaseId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The case record that generated the SMS.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>SMSes</relationshipLabel>
    <relationshipName>SPEN_SMSes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_ContactId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The recipient of the SMS message.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SMSes</relationshipLabel>
    <relationshipName>SPEN_SMSes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <description>Indicates the event that triggered the SMS record to be created. In IVR scenarios, this is used to look up the message template.</description>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPAS Inquiry</fullName>
            </value>
            <value>
                <fullName>Supplier Inquiry</fullName>
            </value>
            <value>
                <fullName>Case Creation</fullName>
            </value>
            <value>
                <fullName>Merged from SP to Network</fullName>
            </value>
            <value>
                <fullName>3-Hour Comfort Call</fullName>
            </value>
            <value>
                <fullName>3rd Call Received</fullName>
            </value>
            <value>
                <fullName>Dropped Supply with Notice</fullName>
            </value>
            <value>
                <fullName>Dropped Supply without Notice</fullName>
            </value>
            <value>
                <fullName>Estimated Restoration Time Extended</fullName>
            </value>
            <value>
                <fullName>Incident Created</fullName>
            </value>
            <value>
                <fullName>Incident Restored</fullName>
            </value>
            <value>
                <fullName>Resource Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Resource Dispatched</fullName>
            </value>
            <value>
                <fullName>MPAS Out-Of-Area Inquiry</fullName>
            </value>
            <value>
                <fullName>Resource ETA Change</fullName>
            </value>
            <value>
                <fullName>Medically Dependent by District</fullName>
            </value>
            <value>
                <fullName>Planned Outage Communication</fullName>
            </value>
            <value>
                <fullName>On Demand</fullName>
            </value>
            <value>
                <fullName>Connections</fullName>
            </value>
            <value>
                <fullName>HV proactive contact</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>Complaint Case Creation</fullName>
            </value>
            <value>
                <fullName>GE Closure Survey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>SMSes</relationshipLabel>
    <relationshipName>SMSes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_IvrMessageId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IvrMessageId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the SMS message template to be used.</description>
    <label>Message Template</label>
    <referenceTo>SPEN_IVRMessage__c</referenceTo>
    <relationshipLabel>SMSes</relationshipLabel>
    <relationshipName>SPEN_SMSes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_Message__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Message__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Actual message sent to the customer.</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_MessageType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MessageType__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_Mobile__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Mobile__c</fullName>
    <complianceGroup>PII;GDPR</complianceGroup>
    <description>The recipient&apos;s mobile number.</description>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Represents the status of message deliverability.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Undelivered</fullName>
            </value>
            <value>
                <fullName>Potentially Duplicate</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/SPEN_VoiceAlert__c/SPEN_VoiceAlert__c.object-meta.xml
<CustomObject>
    <label>Voice Alert</label>
    <nameField>
        <label>Voice Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voice Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_ContactId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Voice Alerts</relationshipLabel>
    <relationshipName>SPEN_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <label>Event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Voice Alerts</relationshipLabel>
    <relationshipName>SPEN_VoiceAlertIncident</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Various status for voice alert</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/recordTypes/Instant.recordType-meta.xml
<RecordType>
    <fullName>Instant</fullName>
    <active>true</active>
    <label>Instant</label>
</RecordType>

force-app/main/default/classes/SPEN_SyncIncidentUtility.cls
/*-----------------------------------------------------------------------------
DESCRIPTION :   Utility class to handle incident reparent sync call.
VERSION     :   1.0

HISTORY     :
Date            Author              Comment
DEC-01-2023     Shubhi Vijayvergia        Initial version
-----------------------------------------------------------------------------*/
public class SPEN_SyncIncidentUtility {
    /***********************************************************
    @Author: Shubhi Vijayvergia
    @Date: 11/22/2023
    @purpose: Method invoked from SPEN_SyncIncidentDetails and SPEN_IncidentQueueableClass 
		for incident reparenting
    ***************************************************************/ 
     //As part of CRMD-5175 
    public static void incidentReparentSyncCall(list<case> caseList,Incident newIncident){
        List<Incident> inciupdate = new List<Incident>();
        Set<Id> mergedIncidentIdSet = new Set<Id>();
        Set<Id> caseIdIncTypeChangeSet = new Set<Id>();
        List<Case> caseUpdList = new List<Case>();
        
        Map<String,String> incCaseMap = new Map<String,String>();
        
        try{
            for(SPEN_Incident_to_case_status_mapping__mdt mdtRec : [SELECT SPEN_IncidentStatus__c,SPEN_CaseStatus__c FROM SPEN_Incident_to_case_status_mapping__mdt]){
            incCaseMap.put(mdtRec.SPEN_IncidentStatus__c,mdtRec.SPEN_CaseStatus__c);
            }
            for(Case c : caseList){
                if(c.SPEN_Incident__c!=null){
                    //below check added as Incident controller can cancel and link the call log to new INC without merge also
                    if(c.SPEN_Incident__c != newIncident.Id){
                        mergedIncidentIdSet.add(c.SPEN_Incident__c);
                        c.SPEN_Incident__c = newIncident.Id;
                        c.SPEN_IsMerge__c=true;
                        if(incCaseMap.containsKey(newIncident.SPEN_IncidentStatus__c)){
                            if(c.Status != incCaseMap.get(newIncident.SPEN_IncidentStatus__c)){
                                c.Status=incCaseMap.get(newIncident.SPEN_IncidentStatus__c);
                            }
                        }
                        Set<String> setCaseIncType = SPEN_ImpactedPremisesConstants.SETCASEINCTYPE;
                        if(setCaseIncType.contains(newIncident.SPEN_IncidentType__c) && c.SPEN_Incident__r.SPEN_IncidentType__c ==SPEN_ImpactedPremisesConstants.SPENSP){
                            caseIdIncTypeChangeSet.add(c.Id);
                        }
                        caseUpdList.add(c);
                    }
                    else{
                        if(incCaseMap.containsKey(c.SPEN_Incident__r.SPEN_IncidentStatus__c)){
                            if(c.Status != incCaseMap.get(c.SPEN_Incident__r.SPEN_IncidentStatus__c)){
                                c.Status=incCaseMap.get(c.SPEN_Incident__r.SPEN_IncidentStatus__c);
                                caseUpdList.add(c);
                            }
                        }
                    }
                }else{
                    c.SPEN_Incident__c = newIncident.Id;
                    if(incCaseMap.containsKey(newIncident.SPEN_IncidentStatus__c)){
                        if(c.Status != incCaseMap.get(newIncident.SPEN_IncidentStatus__c)){
                            c.Status=incCaseMap.get(newIncident.SPEN_IncidentStatus__c);
                        }
                    }
                    caseUpdList.add(c);
                }
            }
            
            if(!caseUpdList.isEmpty()){
                update caseUpdList;
            }
            if(!caseIdIncTypeChangeSet.isEmpty()){
                List<Case> lstNewCases = [SELECT id, SPEN_Incident__c, SPEN_PreferredMethodofContact__c,
                                          SPEN_Incident__r.SPEN_IncidentType__c,SPEN_CaseCategoryOutcome__c,ContactId,
                                          SPEN_CallerMobileTelephone__c,SPEN_CallerTelephone__c
                                          FROM Case WHERE Id IN: caseIdIncTypeChangeSet];
                
                SPEN_IVRMessageSelector ivrSel = new SPEN_IVRMessageSelector();
                SPEN_IVRMessage__c ivrMsg= ivrSel.selectByExternalId(SPEN_ImpactedPremisesConstants.SMSSINGLEPREMISENETWORKFAULT);
                SPEN_IVRMessage__c ivrNetworkFault= ivrSel.selectByExternalId(SPEN_ImpactedPremisesConstants.VASINGLEPREMISENETWORKFAULT);
                
                RecordType recType=[select id,RecordType.name from RecordType  where RecordType.name =:SPEN_ImpactedPremisesConstants.SMS_CASERECORDTYPE LIMIT 1];
                Id VoiceAlertRecordTypeId = Schema.SObjectType.SPEN_VoiceAlert__c.getRecordTypeInfosByName().get(SPEN_ImpactedPremisesConstants.INSTANT).getRecordTypeId();
                List<SPEN_SMS__c> smsLst=new List<SPEN_SMS__c>();
                List<SPEN_VoiceAlert__c> lstVoiceAlert = new List<SPEN_VoiceAlert__c>();
                List<Id> lstOfCaseIds = new List<Id>();
                for(Case c : lstNewCases){
                    if((c.SPEN_PreferredMethodofContact__c == SPEN_ImpactedPremisesConstants.T_PREFEREDMETHODOFCONTACT && c.SPEN_CallerMobileTelephone__c != Null) || (c.SPEN_PreferredMethodofContact__c == Null && c.SPEN_CallerMobileTelephone__c != Null))
                    {
                        //Send SMS
                        String mobNo= (c.SPEN_CallerMobileTelephone__c !=Null && c.SPEN_CallerMobileTelephone__c.startsWith('0')) ? '+44'+c.SPEN_CallerMobileTelephone__c.removeStart('0'):c.SPEN_CallerMobileTelephone__c ;
                        SPEN_SMS__c sms= new SPEN_SMS__c(SPEN_ContactId__c=c.ContactId,
                                                         SPEN_IvrMessageId__c=ivrMsg.id,
                                                         SPEN_Message__c = ivrMsg.SPEN_IVRMessage__c,
                                                         SPEN_Status__c=SPEN_ImpactedPremisesConstants.SMSREADYSTATUS,
                                                         SPEN_Event__c= SPEN_ImpactedPremisesConstants.MERGEDFROMSPTONETWORK,
                                                         SPEN_Mobile__c=mobNo,
                                                         RecordTypeId=recType.id,
                                                         SPEN_CaseId__c=c.id,
                                                         SPEN_IncidentId__c=c.SPEN_Incident__c,
                                                         SPEN_MessageType__c= SPEN_ImpactedPremisesConstants.OUTBOUND);
                        smsLst.add(sms);
                    }else if((c.SPEN_PreferredMethodofContact__c ==SPEN_ImpactedPremisesConstants.H_PREFEREDMETHODOFCONTACT && c.SPEN_CallerTelephone__c != null) || (c.SPEN_PreferredMethodofContact__c==null && c.SPEN_CallerTelephone__c != null)){
                        lstOfCaseIds.add(c.Id);
                    }
                }
                Boolean isSMSOptOut = SPEN_BlockOutWindowPeriodClass.checkBlackoutWindowPeriod(SPEN_ImpactedPremisesConstants.SMSBLACKOUTWINDOW);
                if(smsLst != null && !smsLst.isEmpty()  && isSMSOptOut){
                    insert smsLst;
                }
                
                Boolean isVAOptOut = SPEN_BlockOutWindowPeriodClass.checkBlackoutWindowPeriod(SPEN_ImpactedPremisesConstants.VABLACKOUTWINDOW);
                
                if(!lstOfCaseIds.isEmpty() && isVAOptOut){
                    Integer voiceAlertBatchSize=Integer.valueof(SPEN_BatchSettings__mdt.getInstance('SPEN_InsertVoiceBatchSize').SPEN_BatchSize__c);
                    Database.executeBatch(new SPEN_VoiceAlertServiceBatch(lstOfCaseIds,ivrNetworkFault.SPEN_IVRMessage__c,VoiceAlertRecordTypeId),voiceAlertBatchSize);               
                 }
                
            }
            
            for(Incident ic : [SELECT Id,ParentIncidentId, SPEN_IncidentStatus__c,(Select Id from Cases__r) FROM Incident WHERE id IN: mergedIncidentIdSet]){
                if(ic.Cases__r.size() == 0){
                    inciupdate.add(new Incident(Id=ic.Id,SPEN_IncidentStatus__c = SPEN_ImpactedPremisesConstants.MERGED,ParentIncidentId=newIncident.Id));
                }
            }
            if(inciupdate.size()>0){
                update inciupdate;
            }
        }catch(Exception ex){
            SEL_LoggingService.log(ex);
        }
        
    }

}