force-app/main/default/objects/SPEN_BatchSettings__mdt/SPEN_BatchSettings__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata to be used for configuring settings for batch classes</description>
    <label>Batch Setting</label>
    <pluralLabel>Batch Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SPEN_BatchSettings__mdt/fields/SPEN_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BatchSize__c</fullName>
    <defaultValue>200</defaultValue>
    <description>Scope of the batch - defaulted to 200</description>
    <inlineHelpText>Scope of the batch - defaulted to 200</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/SPEN_CommunicationScheduler__c.object-meta.xml
<CustomObject>
    <description>Use this object to immediately or schedule a bulk outbound communication via SMS, Voice Alerts, etc.</description>
    <label>Communication Scheduler</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Schedulers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_District__c.field-meta.xml
<CustomField>
    <fullName>SPEN_District__c</fullName>
    <label>District</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <description>The event that initiated the creation of Communication Scheduler.</description>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3-Hour Comfort Call</fullName>
            </value>
            <value>
                <fullName>3rd Call Received</fullName>
            </value>
            <value>
                <fullName>Dropped Supply with Notice</fullName>
            </value>
            <value>
                <fullName>Dropped Supply without Notice</fullName>
            </value>
            <value>
                <fullName>Estimated Restoration Time Extended</fullName>
            </value>
            <value>
                <fullName>Incident Created</fullName>
            </value>
            <value>
                <fullName>Incident Restored</fullName>
            </value>
            <value>
                <fullName>Resource Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Resource Dispatched</fullName>
            </value>
            <value>
                <fullName>Medically Dependent by District</fullName>
            </value>
            <value>
                <fullName>Planned Outage Communication</fullName>
            </value>
            <value>
                <fullName>On Demand</fullName>
            </value>
            <value>
                <fullName>HV proactive contact</fullName>
            </value>
            <value>
                <fullName>15days Task Creation non LVHV</fullName>
            </value>
            <value>
                <fullName>5 Days System Email LVHV</fullName>
            </value>
            <value>
                <fullName>15 Days System Email LVHV</fullName>
            </value>
            <value>
                <fullName>10 Days Task Creation LVHV</fullName>
            </value>
            <value>
                <fullName>20 Days Task Creation LVHV</fullName>
            </value>
            <value>
                <fullName>10 Days System Email Non LVHV</fullName>
            </value>
            <value>
                <fullName>45 Days System email Non LVHV</fullName>
            </value>
            <value>
                <fullName>60 Days task Create Non LVHV</fullName>
            </value>
            <value>
                <fullName>Customer Engagement Task PUM/PDM</fullName>
            </value>
            <value>
                <fullName>Customer Engagement Task HOD</fullName>
            </value>
            <value>
                <fullName>Customer Engagement Task PM</fullName>
            </value>
            <value>
                <fullName>Annual Meeting Prior 14 Days</fullName>
            </value>
            <value>
                <fullName>ITT Issued Due Date Prior 1 day</fullName>
            </value>
            <value>
                <fullName>Energisation Date Prior 14 days</fullName>
            </value>
            <value>
                <fullName>Stage 1 Energisation Date to PM</fullName>
            </value>
            <value>
                <fullName>MTM 2 Offer Expire To NGESO CCM 14 Days</fullName>
            </value>
            <value>
                <fullName>BiAnnual Meeting Prior 14 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Communication Schedulers</relationshipLabel>
    <relationshipName>SPEN_CommunicationSchedulers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_Message__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Message__c</fullName>
    <description>The template or customised message to be broadcasted.</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_MessagingTaskId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MessagingTaskId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Message Task that created the Communication Scheduler.</description>
    <label>Messaging Task</label>
    <referenceTo>SPEN_MessagingTask__c</referenceTo>
    <relationshipLabel>Communication Schedulers</relationshipLabel>
    <relationshipName>SPEN_CommunicationSchedulers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_NonPSRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NonPSRMessage__c</fullName>
    <description>This field holds the message value of Non PSR</description>
    <label>Non PSR Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_PremiseQuery__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseQuery__c</fullName>
    <label>SPEN Premise Query</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_SendSMSMCtocalledin__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SendSMSMCtocalledin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field refers to Send SMS to Non PSR Called in functionality</description>
    <label>Send SMS to Non PSR Called in</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_SendSMSMCtoPSR__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SendSMSMCtoPSR__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field refers to Send SMS to PSR Customers in Scope functionality</description>
    <label>Send SMS to PSR Customers in Scope</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_SendSMStoAllCustomerinScope__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SendSMStoAllCustomerinScope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Field refers to Send SMS to Non PSR Customers in Scope functionality</description>
    <label>Send SMS to Non PSR Customers in Scope</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_SendSMStoPSRCalledin__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SendSMStoPSRCalledin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send SMS to PSR Called in</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_SendVAtoAllCustomerinScope__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SendVAtoAllCustomerinScope__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send VA to Non PSR Customers in Scope</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_SendVAtoPSRCalledin__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SendVAtoPSRCalledin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send VA to PSR Called in</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_SendVoiceAlerttocalledin__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SendVoiceAlerttocalledin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send VA to Non PSR Called in</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_SendVoiceAlerttoPSR__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SendVoiceAlerttoPSR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send VA to PSR Customers in Scope</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/SPEN_IVROperatinghours__c.object-meta.xml
<CustomObject>
    <description>IVR Operating hours object is operating on time based on start time and end time.</description>
    <label>IVR Operating hours</label>
    <nameField>
        <label>IVR Operating hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Operating hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_EndTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EndTime__c</fullName>
    <description>End time field will collect the ending time of IVR Operating hours</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isActive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_StartTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_StartTime__c</fullName>
    <description>Start time field will collect the starting time of IVR Operating hours</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/SPEN_MessagingTask__c.object-meta.xml
<CustomObject>
    <description>This object allows agents to set up and configure broadcast messaging via SMS, Voice Alerts, etc.</description>
    <label>Messaging Task</label>
    <nameField>
        <displayFormat>MST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messaging Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <description>Indicates what event triggered the creation of the Messaging Task record</description>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3-Hour Comfort Call</fullName>
            </value>
            <value>
                <fullName>3rd Call Received</fullName>
            </value>
            <value>
                <fullName>Dropped Supply with Notice</fullName>
            </value>
            <value>
                <fullName>Dropped Supply without Notice</fullName>
            </value>
            <value>
                <fullName>Estimated Restoration Time Extended</fullName>
            </value>
            <value>
                <fullName>Incident Created</fullName>
            </value>
            <value>
                <fullName>Incident Restored</fullName>
            </value>
            <value>
                <fullName>Resource Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Resource Dispatched</fullName>
            </value>
            <value>
                <fullName>On Demand</fullName>
            </value>
            <value>
                <fullName>HV proactive contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The incident record that created the Messaging Task</description>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Messaging Tasks</relationshipLabel>
    <relationshipName>SPEN_MessagingTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_PremiseIds__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseIds__c</fullName>
    <label>PremiseIds</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_District__c.field-meta.xml
<CustomField>
    <fullName>SPEN_District__c</fullName>
    <formula>If(ISPICKVAL(SPEN_Zone__r.SPEN_Type__c, &apos;Zone&apos;), SPEN_Zone__r.SPEN_Parent__r.Name , &apos;&apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SPEN_SMSCtrlInvokedByFlow.cls
/**
 * @description       : This class is called from flow.
 * @author            : ramesh.c.singh@accenture.com
 * @group             : 
 * @last modified on  : 01-24-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class SPEN_SMSCtrlInvokedByFlow {

    @InvocableMethod(Label='Invoke apex method to process SMS with Batch')
    public static void callBatchApexFromFlow(List<Id> lstComScheId){
       

        Id vABroadCastRecTypeId = Schema.SObjectType.SPEN_CommunicationScheduler__c.getRecordTypeInfosByName().get('Voice Alert Broadcast').getRecordTypeId();

        Id smsBroadCastRecTypeId = Schema.SObjectType.SPEN_CommunicationScheduler__c.getRecordTypeInfosByName().get('SMS Broadcast').getRecordTypeId();
       
        Map<SPEN_CommunicationScheduler__c, Id> mapOfCommSchVsIncident = new map<SPEN_CommunicationScheduler__c, Id>();

        Map<SPEN_CommunicationScheduler__c, Id> mapOfCommSchVsIncidentVA = new map<SPEN_CommunicationScheduler__c, Id>();

        Map<SPEN_CommunicationScheduler__c, List<Boolean>> mapOfCommSchedulerWithCheckboxes = new Map<SPEN_CommunicationScheduler__c, List<Boolean>>();

        Map<SPEN_CommunicationScheduler__c, List<Boolean>> mapOfCommSchedulerWithCheckboxesVA = new Map<SPEN_CommunicationScheduler__c, List<Boolean>>();
        
        Map<String, SPEN_CommunicationScheduler__c> mapDistrictToCommSch = new Map<String, SPEN_CommunicationScheduler__c>();

        Map<String, SPEN_CommunicationScheduler__c> mapDistrictToCommSchVA = new Map<String, SPEN_CommunicationScheduler__c>();

        //[CRMD:4073]
        List<SPEN_CommunicationScheduler__c> listPremiseSMSCommSch = new List<SPEN_CommunicationScheduler__c>();
        List<SPEN_CommunicationScheduler__c> listPremiseVACommSch = new List<SPEN_CommunicationScheduler__c>();
        //On Demand List intialize
        List<SPEN_CommunicationScheduler__c> listOnDemandPremiseVACommSch = new List<SPEN_CommunicationScheduler__c>();
        List<SPEN_CommunicationScheduler__c> listOnDemandPremiseSMSCommSch = new List<SPEN_CommunicationScheduler__c>();

         for(SPEN_CommunicationScheduler__c commSch  : [select id, name,recordTypeId, SPEN_IncidentId__c, SPEN_Event__c, SPEN_IncidentId__r.SPEN_IncidentCategory__c,SPEN_SendSMSMCtoPSR__c,SPEN_SendSMStoAllCustomerinScope__c,SPEN_SendSMSMCtocalledin__c,SPEN_Message__c,SPEN_NonPSRMessage__c,SPEN_District__c,SPEN_SendVAtoAllCustomerinScope__c,SPEN_SendSMStoPSRCalledin__c,SPEN_SendVoiceAlerttocalledin__c,SPEN_SendVoiceAlerttoPSR__c,SPEN_SendVAtoPSRCalledin__c,SPEN_PremiseQuery__c,SPEN_MessagingTaskId__r.SPEN_PremiseIds__c  from SPEN_CommunicationScheduler__c where Id IN :lstComScheId   WITH SECURITY_ENFORCED]){
            if(commSch.recordTypeId == smsBroadCastRecTypeId &&  commSch.SPEN_IncidentId__c == null && commSch.SPEN_Event__c == 'Medically Dependent by District' && commSch.SPEN_District__c != null ){
                mapDistrictToCommSch.put(commSch.SPEN_District__c.toLowerCase(), commSch);
            }
            else if(commSch.recordTypeId == vABroadCastRecTypeId &&  commSch.SPEN_IncidentId__c == null && commSch.SPEN_Event__c == 'Medically Dependent by District' && commSch.SPEN_District__c != null ){
                mapDistrictToCommSchVA.put(commSch.SPEN_District__c.toLowerCase(), commSch);
            }
            //[CRMD:4073] S
           /* else if(commSch.recordTypeId == smsBroadCastRecTypeId &&  commSch.SPEN_IncidentId__c == null && commSch.SPEN_Event__c == 'Planned Outage Communication' && commSch.SPEN_PremiseQuery__c != null ){
                listPremiseSMSCommSch.add(commSch);
            }
            else if(commSch.recordTypeId == vABroadCastRecTypeId &&  commSch.SPEN_IncidentId__c == null && commSch.SPEN_Event__c == 'Planned Outage Communication' && commSch.SPEN_PremiseQuery__c != null ){
                listPremiseVACommSch.add(commSch);
            }
            //[CRMD:4073] E */
            else if(commSch.recordTypeId == smsBroadCastRecTypeId && commSch.SPEN_Event__c == 'On Demand'){
                listOnDemandPremiseSMSCommSch.add(commSch);
            }
            else if(commSch.recordTypeId == vABroadCastRecTypeId && commSch.SPEN_Event__c == 'On Demand'){
                listOnDemandPremiseVACommSch.add(commSch);
            }
            else if(commSch.recordTypeId == smsBroadCastRecTypeId && commSch.SPEN_IncidentId__c !=null){
                mapOfCommSchVsIncident.put(commSch, commSch.SPEN_IncidentId__c);
                List<Boolean> lstOfCommSchedulerCheckboxes = new List<Boolean>();
                lstOfCommSchedulerCheckboxes.add(commSch.SPEN_SendSMSMCtoPSR__c);
                lstOfCommSchedulerCheckboxes.add(commSch.SPEN_SendSMStoAllCustomerinScope__c);
                lstOfCommSchedulerCheckboxes.add(commSch.SPEN_SendSMStoPSRCalledin__c);
                lstOfCommSchedulerCheckboxes.add(commSch.SPEN_SendSMSMCtocalledin__c);
                mapOfCommSchedulerWithCheckboxes.put(commSch,lstOfCommSchedulerCheckboxes);
            }
            else if(commSch.recordTypeId == vABroadCastRecTypeId && commSch.SPEN_IncidentId__c !=null){
                mapOfCommSchVsIncidentVA.put(commSch, commSch.SPEN_IncidentId__c);
                List<Boolean> lstOfCommSchedulerCheckboxesforVA = new List<Boolean>();
                lstOfCommSchedulerCheckboxesforVA.add(commSch.SPEN_SendVoiceAlerttoPSR__c);
                lstOfCommSchedulerCheckboxesforVA.add(commSch.SPEN_SendVAtoAllCustomerinScope__c);
                lstOfCommSchedulerCheckboxesforVA.add(commSch.SPEN_SendVAtoPSRCalledin__c);
                lstOfCommSchedulerCheckboxesforVA.add(commSch.SPEN_SendVoiceAlerttocalledin__c);
                mapOfCommSchedulerWithCheckboxesVA.put(commSch,lstOfCommSchedulerCheckboxesforVA);
            }
         }

         //Calculation of blackout window period.
         Boolean isOptoutForSMS = checkBlackoutWindowPeriod('SMS Blackout Window');
         Boolean isOptoutForVA = checkBlackoutWindowPeriod('VA Blackout Window');
         Integer customLabelValueSMS=Integer.valueOf(System.Label.SPEN_InsertSMSBatchSize);
         //Integer customLabelValueVA=Integer.valueOf(System.Label.SPEN_InsertVABatchSize);
         Integer customLabelValueVA=Integer.valueof(SPEN_BatchSettings__mdt.getInstance('SPEN_InsertVoiceBatchSize').SPEN_BatchSize__c);

         // send sms functionality to psr, nonpsr, psr called in , non-psr called in customer 
         if(!mapOfCommSchVsIncident.isEmpty() && !mapOfCommSchedulerWithCheckboxes.isEmpty() && isOptoutForSMS){
            
            Database.executeBatch(new SPEN_InsertSMSBatch(mapOfCommSchVsIncident, mapOfCommSchedulerWithCheckboxes, 1),customLabelValueSMS);
         }
         if(!mapOfCommSchVsIncidentVA.isEmpty() && !mapOfCommSchedulerWithCheckboxesVA.isEmpty() && isOptoutForVA){
            
            Database.executeBatch(new SPEN_InsertVoice_AlertBatch(mapOfCommSchVsIncidentVA, mapOfCommSchedulerWithCheckboxesVA, 1),customLabelValueVA);
         }
         if(!mapDistrictToCommSch.isEmpty()){
           Database.executeBatch(new SPEN_InsertSMSBatch(mapDistrictToCommSch), customLabelValueSMS);
        }
        if(!mapDistrictToCommSchVA.isEmpty()){
            Database.executeBatch(new SPEN_InsertVoice_AlertBatch(mapDistrictToCommSchVA), customLabelValueVA);
         }
       /*  if(!listPremiseSMSCommSch.isEmpty()){
            String query = 'SELECT id FROM SPEN_Premise__c WHERE '+ listPremiseSMSCommSch[0].SPEN_PremiseQuery__c;
            List<SPEN_Premise__c> lstPrem = Database.query(query);
            Set<String> setPremId = new Set<String>();
            for(SPEN_Premise__c prem: lstPrem)
                setPremId.add(prem.id);
            Database.executeBatch(new SPEN_InsertSMSBatch(setPremId,listPremiseSMSCommSch), 200);
         }
         if(!listPremiseVACommSch.isEmpty()){
            String query = 'SELECT id FROM SPEN_Premise__c WHERE '+ listPremiseVACommSch[0].SPEN_PremiseQuery__c;
            List<SPEN_Premise__c> lstPrem = Database.query(query);
            Set<String> setPremId = new Set<String>();
            for(SPEN_Premise__c prem: lstPrem)
                setPremId.add(prem.id);
            Database.executeBatch(new SPEN_InsertVoice_AlertBatch(setPremId,listPremiseVACommSch), 200);
         }*/
         if(!listOnDemandPremiseSMSCommSch.isEmpty()){
            Database.executeBatch(new SPEN_InsertSMSBatch(listOnDemandPremiseSMSCommSch), 200);
         }
         if(!listOnDemandPremiseVACommSch.isEmpty()){
            Database.executeBatch(new SPEN_InsertVoice_AlertBatch(listOnDemandPremiseVACommSch), 200);
         }
    }


    // Method to check SMS Black out window period to send the Communication by sms.
    public static Boolean checkBlackoutWindowPeriod(String typeCheck){
        Boolean result = false;
        Id recTypeIdOfBlackoutWindowRT = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get(typeCheck).getRecordTypeId();
       
        List<SPEN_IVROperatingHours__c> lstIvrHour = [select Id, Name,SPEN_StartTime__c,SPEN_EndTime__c, RecordTypeId from  SPEN_IVROperatingHours__c where RecordTypeId = :recTypeIdOfBlackoutWindowRT and SPEN_isActive__c = true WITH SECURITY_ENFORCED limit 1]; 
        
        if(!lstIvrHour.isEmpty() && lstIvrHour[0] != null){
            if(lstIvrHour[0].SPEN_StartTime__c == null && lstIvrHour[0].SPEN_EndTime__c == null){
                result = true;
            }
            else if((lstIvrHour[0].SPEN_StartTime__c < lstIvrHour[0].SPEN_EndTime__c) && ((System.now().time() < lstIvrHour[0].SPEN_StartTime__c && System.now().time() < lstIvrHour[0].SPEN_EndTime__c) || (System.now().time() > lstIvrHour[0].SPEN_StartTime__c && System.now().time() > lstIvrHour[0].SPEN_EndTime__c))){
             
                 result = true;
             }
             else if((lstIvrHour[0].SPEN_StartTime__c > lstIvrHour[0].SPEN_EndTime__c) && (System.now().time() < lstIvrHour[0].SPEN_StartTime__c && System.now().time() > lstIvrHour[0].SPEN_EndTime__c)){
                 result = true;
             }
            
        }
        return result;
    }
}