force-app/main/default/objects/SPEN_BatchSettings__mdt/SPEN_BatchSettings__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata to be used for configuring settings for batch classes</description>
    <label>Batch Setting</label>
    <pluralLabel>Batch Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SPEN_BatchSettings__mdt/fields/SPEN_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BatchSize__c</fullName>
    <defaultValue>200</defaultValue>
    <description>Scope of the batch - defaulted to 200</description>
    <inlineHelpText>Scope of the batch - defaulted to 200</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/fields/SPEN_Value__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/SPEN_MessagingTask__c.object-meta.xml
<CustomObject>
    <description>This object allows agents to set up and configure broadcast messaging via SMS, Voice Alerts, etc.</description>
    <label>Messaging Task</label>
    <nameField>
        <displayFormat>MST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messaging Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <description>Indicates what event triggered the creation of the Messaging Task record</description>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3-Hour Comfort Call</fullName>
            </value>
            <value>
                <fullName>3rd Call Received</fullName>
            </value>
            <value>
                <fullName>Dropped Supply with Notice</fullName>
            </value>
            <value>
                <fullName>Dropped Supply without Notice</fullName>
            </value>
            <value>
                <fullName>Estimated Restoration Time Extended</fullName>
            </value>
            <value>
                <fullName>Incident Created</fullName>
            </value>
            <value>
                <fullName>Incident Restored</fullName>
            </value>
            <value>
                <fullName>Resource Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Resource Dispatched</fullName>
            </value>
            <value>
                <fullName>On Demand</fullName>
            </value>
            <value>
                <fullName>HV proactive contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The incident record that created the Messaging Task</description>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Messaging Tasks</relationshipLabel>
    <relationshipName>SPEN_MessagingTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/recordTypes/Incident.recordType-meta.xml
<RecordType>
    <fullName>Incident</fullName>
    <active>true</active>
    <description>When the Messaging Task record is driven from an Incident event</description>
    <label>Incident</label>
</RecordType>

force-app/main/default/classes/SPEN_IncidentQueueableClass.cls
public with sharing class SPEN_IncidentQueueableClass implements Queueable
{
    public SPEN_SyncIncidentDetailsWrapper.sdifIncidentScopeChanged incidentWrapper;
    public List<Incident> incidentRecordsList = new List<Incident>(); 
    public Incident incidentObjScopeChanged;
    SPEN_MessagingTaskService msgTaskSrv=new SPEN_MessagingTaskService();
    Id recTypeId= Schema.SObjectType.SPEN_MessagingTask__c.getRecordTypeInfosByDeveloperName().get(SPEN_ImpactedPremisesConstants.INCIDENTNAME).getRecordTypeId();
    Set<Id> premSet=new Set<Id>();
    public List<String> callRef = new List<String>();
    public List<String> incStrLst = new List<String>();
    
    public SPEN_IncidentQueueableClass(SPEN_SyncIncidentDetailsWrapper.sdifIncidentScopeChanged incidentWrapper) 
    {
        this.incidentWrapper = incidentWrapper;
    }
    public void execute(QueueableContext context) 
    { 
        SPEN_SyncIncidentDetailsWrapper.sdifIncidentScopeChanged  incScopeCngd = incidentWrapper;
        incidentRecordsList = [SELECT Id,SPEN_IncidentID__c,SPEN_IncidentType__c,SPEN_IncidentStatus__c,SPEN_droppedsupply__c,(select id from SPEN_MessagingTasks__r where SPEN_Event__c = '3rd Call Received') FROM Incident WHERE SPEN_IncidentReference__c = :incScopeCngd.IncidentScopeChangedStc[0].incidentReference limit 1];
        if(!incidentRecordsList.isEmpty()){
            incidentObjScopeChanged = incidentRecordsList[0];
            List<Id> lstId = new List<Id>();
            for(Integer i=0; i<incScopeCngd.IncidentScopeChangedStc[0].calls.size() ; i++)
            {
                if(!incScopeCngd.IncidentScopeChangedStc[0].calls[i].callReference.contains(SPEN_ImpactedPremisesConstants.CALL)){
                    lstId.add(incScopeCngd.IncidentScopeChangedStc[0].calls[i].callReference);
                }
                
            }
            for(Case cCall : [Select id,SPEN_AddressPremise__c from Case where Id in :lstId])
            {
                premSet.add(cCall.SPEN_AddressPremise__c);
            }
            for(Case csObj: [Select id,SPEN_AddressPremise__c from Case where SPEN_Incident__r.SPEN_IncidentReference__c =:incScopeCngd.IncidentScopeChangedStc[0].incidentReference])
            {
                premSet.add(csObj.SPEN_AddressPremise__c);
            }
            if(!premSet.isEmpty()  && incidentObjScopeChanged != Null && premSet.size()>2 && !incidentObjScopeChanged.SPEN_droppedsupply__c && incidentObjScopeChanged.SPEN_MessagingTasks__r.isEmpty())
            {
                SPEN_ConfigurableSettings__c MessageINCType = [SELECT SPEN_Value__c FROM SPEN_ConfigurableSettings__c WHERE Name='MessagingTaskType3rdCall' Limit 1];
                List<String> MessageINCTypeList = MessageINCType.SPEN_Value__c.split(',');
                if(MessageINCTypeList.contains(String.ValueOf(incidentObjScopeChanged.SPEN_IncidentType__c))){
                    msgTaskSrv.createMessagingTask(SPEN_ImpactedPremisesConstants.THIRDCALL,incidentObjScopeChanged.id,recTypeId,Null,'New');
                }
            }
            for(SPEN_SyncIncidentDetailsWrapper.Calls callRefValues : incScopeCngd.IncidentScopeChangedStc[0].calls)
            {
                if(!(callRefValues.callReference.contains(SPEN_ImpactedPremisesConstants.CALL))){
                    callRef.add(callRefValues.callReference);
                }
            }
             /**Modified by : Rahul Kumar 
             * Description : If low volume case is there process immediately or send it to batch to process in async mode. This limit can be configured at any time in SPEN_BatchSettings custom metadata
             * 
             *  */ 
            Cases.isScopeChangedCase=true; //added by shubhi v :CRMD-9236

             Map<String,Integer> incCaseMap = new Map<String,Integer>();
            
             for(SPEN_BatchSettings__mdt mdtRec : [SELECT Id, DeveloperName, SPEN_BatchSize__c FROM SPEN_BatchSettings__mdt]){
                 incCaseMap.put(mdtRec.DeveloperName,Integer.valueOf(mdtRec.SPEN_BatchSize__c));
                 
             }
 
             if(!incCaseMap.isEmpty() && incCaseMap.containsKey(SPEN_ImpactedPremisesConstants.INCOMINGCASEVOLUMECOUNT) && callRef.size() <= incCaseMap.get(SPEN_ImpactedPremisesConstants.INCOMINGCASEVOLUMECOUNT)){
             
                 List<Case> caseList= [SELECT Id,Status,SPEN_IsMerge__c,SPEN_Incident__c,SPEN_Incident__r.ParentIncidentId,SPEN_Incident__r.SPEN_IncidentStatus__c,SPEN_Incident__r.SPEN_IncidentType__c 
                                       FROM Case WHERE Id =:callRef];
                 SPEN_SyncIncidentUtility.incidentReparentSyncCall(caseList,incidentObjScopeChanged);
             
             }
             else{
                 // process with Batch....
                 Database.executeBatch(new SPEN_IncidentScopeChangedProcessingBatch(incidentObjScopeChanged, callRef),200);
             }
             
         }
         
        
    }
}