force-app/main/default/objects/SPEN_Land__c/SPEN_Land__c.object-meta.xml
<CustomObject>
    <label>Land</label>
    <nameField>
        <label>Land Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_LandAssociation__c/SPEN_LandAssociation__c.object-meta.xml
<CustomObject>
    <description>Created as part of ESC-131.</description>
    <label>Land Contact</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Land Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Land Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_LandAssociation__c/fields/SPEN_Land__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Land__c</fullName>
    <label>Land</label>
    <referenceTo>SPEN_Land__c</referenceTo>
    <relationshipLabel>Land Associations</relationshipLabel>
    <relationshipName>Land_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SPEN_RefreshSAPVendorInvocableTest.cls
/* File Name: SPEN_RefreshSAPVendorInvocableTest
 * Description: Test class for SPEN_RefreshSAPVendorInvocable class
 * Author: Anwesha Dey
 * Version: 1.0
 * History:
 * Date            Author              Comment
 * May-20-2024     Anwesha Dey    Initial version
 *
 */
@isTest
public class SPEN_RefreshSAPVendorInvocableTest {
    
   
    public static testMethod void vendorSyncTest(){
        
        User u = SPEN_TestDataUtility.createuser('System Administrator');
        Database.insert(u);                     
        System.runAs(u){
            SPEN_Land__c land = SPEN_TestDataUtility.createLandRec();
            Account vendorAccount=SPEN_TestDataUtility.createVendorAccount();
            SPEN_LandAssociation__c vendorLandContact=SPEN_TestDataUtility.createVendorLandContact(vendorAccount,land);
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new SPEN_SAPVendorMockResponse());
            List<Account> vendorAccountToBeSync=SPEN_RefreshSAPVendorInvocable.getVendorAccount(land.Id);
            SPEN_RefreshSAPVendorInvocable.syncVendorRequest(vendorAccountToBeSync);
            Account updatedVendorAccount=[Select id,SPEN_AccountLastSynchronised__c from Account where Id=:vendorAccount.Id];
            Test.stopTest();                
            system.assertEquals(System.now().date(), updatedVendorAccount.SPEN_AccountLastSynchronised__c.date());           
        }
        
    }

}