force-app/main/default/objects/SPEN_SiteDetails__c/SPEN_SiteDetails__c.object-meta.xml
<CustomObject>
    <label>Site Details</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Site Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_SiteDetails__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Site Details</relationshipLabel>
    <relationshipName>Site_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_SiteDetails__c/fields/SPEN_LocationOfWorks__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LocationOfWorks__c</fullName>
    <description>CRMD - 7409 Site Detail</description>
    <label>Location of Works</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_SiteDetails__c/fields/SPEN_PowerOn_Additional_Coordinates__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PowerOn_Additional_Coordinates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PowerOn Additional Coordinates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_SiteDetails__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_SiteDetails__c/fields/SPEN_SurfaceType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SurfaceType__c</fullName>
    <description>CRMD- 7409</description>
    <label>Surface Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Carriageway</fullName>
            </value>
            <value>
                <fullName>Cycleway</fullName>
            </value>
            <value>
                <fullName>Footpath</fullName>
            </value>
            <value>
                <fullName>Footway</fullName>
            </value>
            <value>
                <fullName>Unmade</fullName>
            </value>
            <value>
                <fullName>Verge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_SiteDetails__c/recordTypes/NRSWA.recordType-meta.xml
<RecordType>
    <fullName>NRSWA</fullName>
    <active>true</active>
    <label>NRSWA</label>
</RecordType>

force-app/main/default/classes/SPEN_SiteDetailsTriggerHandlerTest.cls
@isTest
@SuppressWarnings('PMD.SOQLSelectorPattern')
public class SPEN_SiteDetailsTriggerHandlerTest {
    Public static Id recordTypeIdQuery = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_Query').getRecordTypeId();
    @isTest
    public static void siteDetailsTriggerHandlerTest(){
        Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
        Test.startTest();
        Case caseRecord = new Case();
        caseRecord.RecordTypeId = recordTypeIdQuery;
        caseRecord.SPEN_Type__c='NRSWA';
        caseRecord.Origin='PowerOn';
        caseRecord.SPEN_ConnectionDistrict__c='test';
        caseRecord.SPEN_SPDSPMIndicator__c='SPD';
        caseRecord.SPEN_QueryReason__c='Other';
        insert caseRecord;
        List<SPEN_SiteDetails__c> sdList = new List<SPEN_SiteDetails__c>();
        SPEN_SiteDetails__c sd = new SPEN_SiteDetails__c();
        sd.SPEN_PowerOn_Additional_Coordinates__c = true;
        sd.SPEN_SurfaceType__c ='Carriageway';
        sd.SPEN_Status__c = 'Open';
        sd.SPEN_Case__c =caseRecord.Id;
        insert sd;
        sdList.add(sd);
        SPEN_SiteDetails__c sd1 = new SPEN_SiteDetails__c();
        sd1.SPEN_PowerOn_Additional_Coordinates__c = true;
        sd1.SPEN_SurfaceType__c ='	Cycleway';
        sd1.SPEN_Status__c = 'Open';
        sd1.SPEN_Case__c =caseRecord.Id;
        insert sd1;
        sdList.add(sd1);
        
        SPEN_SiteDetailsTriggerHandler.createQueryCase(sdList);
        //SPEN_SiteDetailsTriggerInterface sti = new SPEN_SiteDetailsTriggerInterface();
        Assert.areEqual('Open',  sd.SPEN_Status__c, 'Site Details status');

        //Added to cover blocks in interface class
        sd1.SPEN_LocationOfWorks__c = 'Test';
        update sd1;
        SPEN_SiteDetailsTriggerInterface obj = new SPEN_SiteDetailsTriggerInterface(); 
        Map<Id, sObject> deleteMap = new Map<Id,sObject>();
        deleteMap.put(sd1.id,sd1);
        obj.beforeDelete(deleteMap);
        obj.afterDelete(deleteMap);
        obj.afterUndelete(deleteMap);
        Test.stopTest();
    }
}