force-app/main/default/objects/SEL_IntegrationSetting__mdt/SEL_IntegrationSetting__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata to store the integration configuration settings</description>
    <label>SEL Integration Setting</label>
    <pluralLabel>SEL Integration Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SPEN_IntegrationRequest__c/SPEN_IntegrationRequest__c.object-meta.xml
<CustomObject>
    <description>Integration Request object has been set up to use for IVR Integration.</description>
    <label>Integration Request</label>
    <nameField>
        <label>Integration Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Result__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Result__c</fullName>
    <label>Result</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/SPEN_MPAN__c.object-meta.xml
<CustomObject>
    <description>MPAN object is used to see MPAN related data.</description>
    <label>MPAN/Meter</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MPAN Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPAN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_AccountNumberMPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AccountNumberMPAN__c</fullName>
    <description>The account number associated with a call - PO map this to the MPAN. Question - what if there are multiple MPANS associated? Can this be cross checked</description>
    <externalId>true</externalId>
    <label>MPAN</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_PingResult__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PingResult__c</fullName>
    <label>Ping Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Energized</fullName>
            </value>
            <value>
                <fullName>Deenergized</fullName>
            </value>
            <value>
                <fullName>Timed-Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_PremiseRetailer__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseRetailer__c</fullName>
    <description>Retailier (supplier) for premise. Originates from ADQM</description>
    <label>Premise - Retailer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_SmartMeterPingDateTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SmartMeterPingDateTime__c</fullName>
    <description>Timestamp created to store value when Ping request sent</description>
    <label>Smart Meter Ping DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Status of the smart meter - energised, de-energised</description>
    <label>Smart Meter Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SPEN_MeterPingIntegrationRequest.cls
/**********************************************************************************************
* @Author:      Debapriya Saha
* @Date:        15/11/2022
* @Description: AdditionalService class from SPEN_IntegrationRequestService
* @Revision(s): [Date] - [Change Reference] - [Changed By] - [Description]   
***********************************************************************************************/
public with sharing class SPEN_MeterPingIntegrationRequest extends SEL_IntegrationsOutboundMessageBase{
    
    public static Id intgReqRecordId;
    public static Id ivrToEcosintgMpanId;
    //String meterVal;
    
    public SPEN_MeterPingIntegrationRequest() 
    {
        super('GetTechDetailsMPANMockAPI');
    }
    
    //public void send(Id intgReqRecordId, String accountNumberMPAN, String suppliermpidValue)
    public void send(Id intgReqRecordId, String accountNumberMPAN)
    {
        try
        {
            SPEN_IntegrationRequest__c inteReqRecord = SPEN_IntegrationRequestSelector.getIntegrationRequestRecord(intgReqRecordId);            
            SPEN_MPAN__c ivrToEcosMpanRcrd = SPEN_MPANSelector.getRecordForMpan(accountNumberMPAN); 
            
            //SPEN_MPAN__c ivrToEcosMpanRcrd = SPEN_MPANSelector.getMpanRecordForMeterPing(accountNumberMPAN);
            //HttpRequest request = super.getHttpRequest(ivrToEcosMpanRcrdAfterPingStatus);
            
            HttpRequest request = super.getHttpRequest(ivrToEcosMpanRcrd);
            //System.debug('request : '+request);
            
            if(super.getIsMockingEnabled())
            {
                /*
                SPEN_LastGaspMockIntegrationService.getMockResponse(ivrToEcosMpanRcrd.Id);
                //SPEN_MPAN__c ivrToEcosMpanRcrdAfterPingStatus = SPEN_MPANSelector.getMpanRecord(ivrToEcosMpanRcrd.Id);
                //ivrToEcosMpanRcrdAfterPingStatus.SPEN_PremiseRetailer__c = suppliermpidValue;
                //ivrToEcosMpanRcrdAfterPingStatus.SPEN_Status__c = ivrToEcosMpanRcrdAfterPingStatus.SPEN_PingResult__c;
                //update(ivrToEcosMpanRcrdAfterPingStatus);
                
                HttpResponse response = super.send(request);
                if(response.getStatusCode() == 200)
				{  
                    System.debug('response.getStatusCode() == 200');
                   	List<String> mpanPostCode = new List<String>();

                    SPEN_MPANWrapper wrapper = (SPEN_MPANWrapper) System.JSON.deserialize(response.getBody(), SPEN_MPANWrapper.class);
                    for(SPEN_MPANWrapper.UtilityMatches val : wrapper.UtilityMatches)
					{
                        for(SPEN_MPANWrapper.Meters nextVal : val.Meters)
						{
                            for(SPEN_MPANWrapper.Parameters metVal: nextVal.MeterDetails)
							{
                                mpanPostCode.add(metVal.Value);
                            }
                        }
                    }
                    if(!mpanPostCode.isEmpty())
					{
                      SPEN_MPAN__c mpan = new SPEN_MPAN__c();
                      //mpan.Id = ivrToEcosMpanRcrdAfterPingStatus.Id;
                      mpan.Id = ivrToEcosMpanRcrd.Id;
                      mpan.SPEN_AccountNumberMPAN__c = mpanPostCode[0];
                      update(mpan);
                    }
                    
                    //SPEN_MPAN__c mpanRcrd = SPEN_MPANSelector.getMpanRecordForMeterPing(accountNumberMPAN);
                    SPEN_MPAN__c mpanRcrd = SPEN_MPANSelector.getRecordForMpan(accountNumberMPAN);
                    inteReqRecord.SPEN_Result__c= mpanRcrd.SPEN_PingResult__c;
                    inteReqRecord.SPEN_Status__c= 'completed';
                    update(inteReqRecord);
                } 
                */
            }
			
           	else 
            {
                SEL_IntegrationSetting__mdt cmt = new SEL_IntegrationsSelector().selectByDeveloperName('SDIFPingMeterAPI');
                //system.debug('cmt'+cmt);
                SEL_IntegrationsTransformService ser = new SEL_IntegrationsTransformService(cmt);
                
                System.debug(JSON.serialize(ivrToEcosMpanRcrd));
                String message = ser.generateMessage(ivrToEcosMpanRcrd);
                System.debug('Expected Message'+message);
                ivrToEcosMpanRcrd.SPEN_SmartMeterPingDateTime__c = system.now();
                ivrToEcosMpanRcrd.SPEN_PingResult__c = '';
                update ivrToEcosMpanRcrd;
            	System.enqueueJob(new SPEN_SDIFPingMeterQueueable(intgReqRecordId,message));
            }
        }
        catch(Exception ex)
        {
            SEL_LoggingService.log(ex);
			throw ex;
        }
    }
   
}