force-app/main/default/objects/SEL_IntegrationSetting__mdt/SEL_IntegrationSetting__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata to store the integration configuration settings</description>
    <label>SEL Integration Setting</label>
    <pluralLabel>SEL Integration Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SEL_IntegrationSetting__mdt/fields/SEL_IsMockingEnabled__c.field-meta.xml
<CustomField>
    <fullName>SEL_IsMockingEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if mocking is enabled. Make sure you turn this off in production.</description>
    <label>Is Mocking Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/SPEN_IntegrationRequest__c.object-meta.xml
<CustomObject>
    <description>Integration Request object has been set up to use for IVR Integration.</description>
    <label>Integration Request</label>
    <nameField>
        <label>Integration Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_IntegrationRequestServiceClass__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IntegrationRequestServiceClass__c</fullName>
    <label>Integration Request Service Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Records__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Records__c</fullName>
    <label>Records</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/SPEN_MPAN__c.object-meta.xml
<CustomObject>
    <description>MPAN object is used to see MPAN related data.</description>
    <label>MPAN/Meter</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MPAN Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPAN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_AccountNumberMPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AccountNumberMPAN__c</fullName>
    <description>The account number associated with a call - PO map this to the MPAN. Question - what if there are multiple MPANS associated? Can this be cross checked</description>
    <externalId>true</externalId>
    <label>MPAN</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_LastGasp__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LastGasp__c</fullName>
    <description>field to get the last gasp details from sdif</description>
    <label>Last Gasp Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_PingResult__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PingResult__c</fullName>
    <label>Ping Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Energized</fullName>
            </value>
            <value>
                <fullName>Deenergized</fullName>
            </value>
            <value>
                <fullName>Timed-Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Status of the smart meter - energised, de-energised</description>
    <label>Smart Meter Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SPEN_LastGaspMockIntegrationService.cls
/*-----------------------------------------------------------------------------
DESCRIPTION	:	Apex class for the Last Gasp Mock API. 
LIBRARY		:	Salesforce Enterprise Library - Integration Framework
VERSION		:	1.0

HISTORY		:
Date			Author		    Comment
OCT-27-2022		Smita Raikar     Initial version

-----------------------------------------------------------------------------*/
public with sharing class SPEN_LastGaspMockIntegrationService 
{
    @AuraEnabled
    public static void getMockResponse(Id recordId) 
    {
        SPEN_MPAN__c mpanRec = SPEN_MPANSelector.getMpanRecord(recordId);
        SPEN_IntegrationRequest__c intReq = new SPEN_IntegrationRequest__c();
        intReq.SPEN_IntegrationRequestServiceClass__c = 'SPEN_MeterPingService';
        intReq.SPEN_Records__c = mpanRec.SPEN_AccountNumberMPAN__c;
        intReq.SPEN_Status__c = 'Processing';
        insert intReq;
        //system.debug('recID >> ' + recordId);
        
        /*HttpResponse httpResponse;
httpResponse=sendRequest(recordId);
//System.debug('response' + httpResponse);
if(httpResponse.getStatusCode() == 200){
SPEN_MPAN__c mpan = new SPEN_MPAN__c();
mpan.Id = recordId;
mpan.SPEN_PingResult__c = 'Energized';
//mpan.SPEN_LastGasp__c= DateTime.now();
System.debug('LastGasp--->>' +mpan.SPEN_LastGasp__c);
Database.SaveResult dataSaveRes = Database.update(mpan);
System.debug('database res' +dataSaveRes);
}
*/
        
    }
    /*
@TestVisible
public static HttpResponse sendRequest(Id recordId){

Id mpanId=recordId;
//System.debug('mpanId' + mpanId);
SPEN_MPAN__c mpanobj;
if(mpanId != null)
mpanobj=[Select id, Name, SPEN_Status__c,SPEN_AccountNumberMPAN__c, SPEN_LastGasp__c,SPEN_PingResult__c FROM SPEN_MPAN__c WHERE id=:mpanId];
SEL_IntegrationSetting__mdt s = new SEL_IntegrationsSelector().selectByDeveloperName('LastGaspMockAPI');
//system.debug('setting---->>>'+s);
SEL_IntegrationsTransformService dms=new SEL_IntegrationsTransformService(s);
//system.debug('dms-->>'+dms);
httpRequest httpRequest = new httpRequest();
Http httpObject = new Http();
HttpResponse httpResponse;
//System.debug('XML--->>'+dms.generateMessage(mpanobj));
if(s.SEL_IsMockingEnabled__c==true){
httpRequest.setHeader('Content-type', 'application/xml');
httpRequest.setEndpoint('https://test.salesforce.com');
httpRequest.setMethod('POST');
httpRequest.setBody(dms.generateMessage(mpanobj));
httpResponse = httpObject.send(httpRequest);

system.debug('Response received -->>>> '+httpResponse);

//system.debug('Response received body - '+httpResponse.getBody());
}
return httpResponse;
}
*/ 
}