force-app/main/default/objects/SEL_IntegrationSetting__mdt/SEL_IntegrationSetting__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata to store the integration configuration settings</description>
    <label>SEL Integration Setting</label>
    <pluralLabel>SEL Integration Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SEL_IntegrationSetting__mdt/fields/SEL_HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>SEL_HttpMethod__c</fullName>
    <label>HTTP Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEL_IntegrationValue__mdt/SEL_IntegrationValue__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata is used to store headers.</description>
    <label>SEL Integration Value</label>
    <pluralLabel>SEL Integration Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/SEL_IntegrationValue__mdt/fields/SEL_IntegrationSettingId__c.field-meta.xml
<CustomField>
    <fullName>SEL_IntegrationSettingId__c</fullName>
    <label>Integration Setting</label>
    <referenceTo>SEL_IntegrationSetting__mdt</referenceTo>
    <relationshipLabel>Http Request Integration Values</relationshipLabel>
    <relationshipName>SEL_IntegrationValues</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/SPEN_IntegrationRequest__c.object-meta.xml
<CustomObject>
    <description>Integration Request object has been set up to use for IVR Integration.</description>
    <label>Integration Request</label>
    <nameField>
        <label>Integration Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Result__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Result__c</fullName>
    <label>Result</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/SPEN_MPAN__c.object-meta.xml
<CustomObject>
    <description>MPAN object is used to see MPAN related data.</description>
    <label>MPAN/Meter</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MPAN Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPAN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_DCCServiceFlag__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DCCServiceFlag__c</fullName>
    <label>DCC Service Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Installed Not Commissioned</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Non-Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_LastEchoesSyncDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LastEchoesSyncDate__c</fullName>
    <label>Last Ecoes Sync Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_MeterType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MeterType__c</fullName>
    <label>Meter Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>MPAN</relationshipLabel>
    <relationshipName>MPAN</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Status of the smart meter - energised, de-energised</description>
    <label>Smart Meter Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_SupplierMPID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SupplierMPID__c</fullName>
    <label>Supplier MPID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_SupplierName__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SupplierName__c</fullName>
    <label>Supplier Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_DCCServiceFlag__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DCCServiceFlag__c</fullName>
    <description>select the DCC service flag from list.</description>
    <label>DCC Service Flag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Installed Not Commissioned</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Non-Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_MPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MPAN__c</fullName>
    <description>A text box to capture MPAN number to be sent to ADQM.</description>
    <label>MPAN</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Unique SPEN identifier for a premise</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_SupplierDetails__c/SPEN_SupplierDetails__c.object-meta.xml
<CustomObject>
    <label>Supplier Details</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_SupplierDetails__c/fields/SPEN_SupplierPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SupplierPhoneNumber__c</fullName>
    <label>Supplier Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/SPEN_MeterDetailsIntegrationRequest.cls
/**********************************************************************************************
* @Author:      Ayush Mittal
* @Date:        12/01/2023
* @Description: SPEN_MeterDetailsIntegrationRequest class
* @Revision(s): [Date] - [Change Reference] - [Changed By] - [Description]   
***********************************************************************************************/
public class SPEN_MeterDetailsIntegrationRequest 
{
    public string dccServiceFlagValue;
    public String suppMpidValue;
    public String meterTypeValue;
    
    public void send(Id intgReqRecordId, String mpanNumber)
    {
        try
        {
            SPEN_IntegrationRequest__c intgReqRecord = SPEN_IntegrationRequestSelector.getIntegrationRequestRecord(intgReqRecordId);
            SPEN_MPAN__c mpanRcd = SPEN_MPANSelector.getRecordForMpan(mpanNumber);
            SPEN_SupplierDetails__c suppDetails = new SPEN_SupplierDetails__c();
            
            String resultStr ='';
            String jsonString = '{'+
                '   \"Authentication\":{'+
                '       \"Key\": \"'+System.Label.SPEN_SearchUtilityAddressEndPointKey+'\"'+
                '   }'+','+
                '   \"ParameterSets\":[{'+
                '       \"Parameters\":[{'+
                '       	\"Key\": \"'+'MPAN'+'\",'+
                '       	\"Value\": \"'+mpanNumber+'\"'+
                		'}'+
                		']'+
                	'}'+']'+
                '}';
            
            //system.debug('jsonString'+jsonString);
            SPEN_EcoesSmartMeterWrapper testBody = SPEN_EcoesSmartMeterWrapper.parse(jsonString);
            system.debug('testBody----->'+testBody);
            //system.debug('JSON.serialize(testBody) --------->>>>>'+ JSON.serialize(testBody));
			List<SEL_IntegrationValue__mdt> intValuesAll = SEL_IntegrationValue__mdt.getAll().values();
            SEL_IntegrationSetting__mdt cmt = new SEL_IntegrationsSelector().selectByDeveloperName(SEL_IntegrationConstants.ECOES_MPAN_DETAILS);
            SEL_IntegrationsTransformService ser = new SEL_IntegrationsTransformService(cmt);

            List<SEL_IntegrationValue__mdt> intValues = new List<SEL_IntegrationValue__mdt>();

            for(SEL_IntegrationValue__mdt intValueInstance : intValuesAll)
            {
                if(intValueInstance.SEL_IntegrationSettingId__r.DeveloperName == SEL_IntegrationConstants.ECOES_MPAN_DETAILS)
                {
                    intValues.add(intValueInstance);
                }
                else
                {
                    continue;
                }
            }
            HttpRequest req = new HttpRequest();
            
            List<Map<String,String>> lstMapIntValues = ser.groupValuesByType(intValues);
            //System.debug('exepected values.. '+lstMapIntValues);
            req = SPEN_IntegrationUtility.prepareRequestsWithBearerToken(lstMapIntValues, req);
            req.setMethod(cmt.SEL_HttpMethod__c);
            //System.debug('req : '+req);
            req.setBody(JSON.serialize(testBody));
            Http http = new Http();
            HTTPResponse res = http.send(req);
            resultStr = res.getBody();
            
            system.debug('res --------->>>>>'+ res);
            //system.debug('resultStr --------->>>>>'+ resultStr);
            
            if(res.getStatusCode() == 200 || res.getStatusCode() == 201)
            {    
                //system.debug('AFTER GETTING RESPONSE');
				if(resultStr.containsIgnoreCase('MissingMPANFault') || resultStr.startsWithIgnoreCase('<Fault'))         
                {
                    intgReqRecord.SPEN_Status__c = 'Completed';
                    intgReqRecord.SPEN_Result__c = 'MPAN core '+mpanNumber+' was not found.';
                    update intgReqRecord;
                }
				else
				{
					SPEN_GetMeterDetailsWrapper getMeterDetailsWrapper = (SPEN_GetMeterDetailsWrapper) System.JSON.deserialize(res.getBody(), SPEN_GetMeterDetailsWrapper.class);
					//system.debug('getMeterDetailsWrapper ---->'+getMeterDetailsWrapper);
                
					if(getMeterDetailsWrapper.Results[0].Errors.isEmpty() && !getMeterDetailsWrapper.Results[0].UtilityMatches.isEmpty())
					{
						for(SPEN_GetMeterDetailsWrapper.UtilityMatches val : getMeterDetailsWrapper.Results[0].UtilityMatches)
						{
							for(SPEN_GetMeterDetailsWrapper.Parameters nextVal : val.UtilityDetails)
							{
								if(nextVal.key == 'dcc_service_flag')
								{
									dccServiceFlagValue = nextVal.Value;
								}
								if(nextVal.key == 'supplier_mpid')
								{
									suppMpidValue = nextVal.Value;
								}
							}
							
							for(SPEN_GetMeterDetailsWrapper.Meters nextValue : val.Meters)
							{
								for(SPEN_GetMeterDetailsWrapper.Parameters nextValForMeter : nextValue.MeterDetails)
								{
									if(nextValForMeter.key == 'meter_type')
									{
										meterTypeValue = nextValForMeter.Value;
									}
								}
							}                         
						}
						//system.debug('mpanRcd--------->'+mpanRcd);
						if(mpanRcd.Id!=null)
						{
							if(suppMpidValue!=null)
							{
								suppDetails	= SPEN_SupplierDetailsSelector.getSupplierDetailsRecord(suppMpidValue);
								mpanRcd.SPEN_SupplierMPID__c = suppMpidValue;
								mpanRcd.SPEN_SupplierName__c = suppDetails.Name;
								mpanRcd.SPEN_SupplierPhoneNumber__c = suppDetails.SPEN_SupplierPhoneNumber__c;
							}
							mpanRcd.SPEN_MeterType__c = meterTypeValue;
							mpanRcd.SPEN_DCCServiceFlag__c = dccServiceFlagValue;
							mpanRcd.SPEN_LastEchoesSyncDate__c = system.now();
							
							intgReqRecord.SPEN_Status__c = 'Completed';
							//intgReqRecord.SPEN_Result__c = mpanRcd.SPEN_Premise__r.SPEN_PremiseId__c;
							update mpanRcd;
							update intgReqRecord;
						}
						else
						{
							intgReqRecord.SPEN_Status__c = 'Completed';
							intgReqRecord.SPEN_Result__c = 'The MPAN Number '+mpanNumber+' does not exist in SF Database';
							update intgReqRecord;
						}
					}
				}
            }
        }
        catch(Exception ex)
        {
            SEL_LoggingService.log(ex);
            throw ex;            
        }
    }
}