force-app/main/default/objects/SEL_BatchStep__c/SEL_BatchStep__c.object-meta.xml
<CustomObject>
    <label>Batch Step</label>
    <nameField>
        <displayFormat>BAS{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_BatchId__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchId__c</fullName>
    <label>Batch</label>
    <referenceTo>SEL_Batch__c</referenceTo>
    <relationshipLabel>Batch Steps</relationshipLabel>
    <relationshipName>SEL_BatchSteps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchSize__c</fullName>
    <label>Batch Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_Sequence__c.field-meta.xml
<CustomField>
    <fullName>SEL_Sequence__c</fullName>
    <label>Sequence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SEL_BatchStepsSelector.cls
/*-----------------------------------------------------------------------------
DESCRIPTION	:	Selector class of the BatchStep__c custom object.
AUTHOR		:	Macjules Sevilla
LIBRARY		:	Salesforce Enterprise Library - Batch Framework
VERSION		:	1.0

HISTORY		:
Date			Author				Comment
AUG-27-2021		Macjules Sevilla	Initial version
-----------------------------------------------------------------------------*/
public inherited sharing class SEL_BatchStepsSelector 
{
	// DESCRIPTION
	// Returns the list of SEL_BatchStep__c records that are
	// associated to the parameter batch ID.
	public List<SEL_BatchStep__c> selectByBatchId(Id batchId) 
	{
		List<SEL_BatchStep__c> result = new List<SEL_BatchStep__c>(); 
		
		if(batchId != null) 
		{  
			result = [
				SELECT		Id, SEL_BatchId__c, SEL_BatchSize__c, SEL_Sequence__c, SEL_Status__c
				FROM		SEL_BatchStep__c
				WHERE		SEL_BatchId__c =: batchId 
				WITH		SECURITY_ENFORCED
				ORDER BY 	SEL_Sequence__c
			];
		}


		return result;
	}
}