force-app/main/default/objects/SPEN_MPAN__c/SPEN_MPAN__c.object-meta.xml
<CustomObject>
    <description>MPAN object is used to see MPAN related data.</description>
    <label>MPAN/Meter</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MPAN Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPAN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MPAN__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Macjules: TO BE DELETED</description>
    <label>[TO BE DELETED] ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_AccountNumberMPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AccountNumberMPAN__c</fullName>
    <description>The account number associated with a call - PO map this to the MPAN. Question - what if there are multiple MPANS associated? Can this be cross checked</description>
    <externalId>true</externalId>
    <label>MPAN</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_DCCServiceFlag__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DCCServiceFlag__c</fullName>
    <label>DCC Service Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Installed Not Commissioned</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Non-Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_LastEchoesSyncDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LastEchoesSyncDate__c</fullName>
    <label>Last Ecoes Sync Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_LastGasp__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LastGasp__c</fullName>
    <description>field to get the last gasp details from sdif</description>
    <label>Last Gasp Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_MeterType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MeterType__c</fullName>
    <label>Meter Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_PingResult__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PingResult__c</fullName>
    <label>Ping Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Energized</fullName>
            </value>
            <value>
                <fullName>Deenergized</fullName>
            </value>
            <value>
                <fullName>Timed-Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>MPAN</relationshipLabel>
    <relationshipName>MPAN</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_PremiseMeterType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseMeterType__c</fullName>
    <description>Type of the Premise - Meter</description>
    <label>Premise - Meter Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <label>Smartmeter</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>Token Meter</label>
            </value>
            <value>
                <fullName>K</fullName>
                <label>Key Meter</label>
            </value>
            <value>
                <fullName>N</fullName>
                <isActive>false</isActive>
                <label>N</label>
            </value>
            <value>
                <fullName>S1</fullName>
                <isActive>false</isActive>
                <label>S1</label>
            </value>
            <value>
                <fullName>S2A</fullName>
                <isActive>false</isActive>
                <label>S2A</label>
            </value>
            <value>
                <fullName>S2AD</fullName>
                <isActive>false</isActive>
                <label>S2AD</label>
            </value>
            <value>
                <fullName>S2ADE</fullName>
                <isActive>false</isActive>
                <label>S2ADE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_SmartMeterPingDateTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SmartMeterPingDateTime__c</fullName>
    <description>Timestamp created to store value when Ping request sent</description>
    <label>Smart Meter Ping DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_SupplierMPID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SupplierMPID__c</fullName>
    <label>Supplier MPID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_SupplierName__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SupplierName__c</fullName>
    <label>Supplier Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_AccountNumberMPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AccountNumberMPAN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account number is look up with Account Number (MPAN) field of MPAN object</description>
    <label>Account Number (MPAN)</label>
    <referenceTo>SPEN_MPAN__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_DCCServiceFlag__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DCCServiceFlag__c</fullName>
    <description>select the DCC service flag from list.</description>
    <label>DCC Service Flag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Installed Not Commissioned</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Non-Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_MPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MPAN__c</fullName>
    <description>A text box to capture MPAN number to be sent to ADQM.</description>
    <label>MPAN</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Unique SPEN identifier for a premise</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SPEN_MPANSelector.cls
/*-----------------------------------------------------------------------------
DESCRIPTION	:	Apex  Class to hold without sharing methods. 
LIBRARY		:	Salesforce Enterprise Library - Smart Meter Connection
VERSION		:	1.0

HISTORY		:
Date			Author				Comment
OCT-20-2022		Dhara Desai			Initial version
DEC-29-2022		Macjules Sevilla	Refactored but names should be fixed
-----------------------------------------------------------------------------*/
public with sharing class SPEN_MPANSelector
{
	// TODO: The method name should be selectById
	public static SPEN_MPAN__c getMpanRecord(Id recordId)
	{
		List<SPEN_MPAN__c> results = new List<SPEN_MPAN__c>();

		if(recordId != null)
		{
			results = [	
				SELECT	Id,
						SPEN_AccountNumberMPAN__c,
						SPEN_PingResult__c,
						SPEN_LastGasp__c,
						ExternalId__c 
				FROM	SPEN_MPAN__c 
				WHERE	Id =: recordId
				WITH	SECURITY_ENFORCED
				LIMIT	:(Limits.getLimitQueryRows()-Limits.getQueryRows())
			];
		}

		return results.size() == 0 ? new SPEN_MPAN__c() : results[0];
	}

	// TODO: Method name should be selectByAccountNumber
	public static SPEN_MPAN__c getMpanRecordForMeterPing(String accountNumberMPAN)
	{
		List<SPEN_MPAN__c> results = new List<SPEN_MPAN__c>();

		if(String.isNotBlank(accountNumberMPAN))
		{
			results = [
				SELECT	Id,
						SPEN_AccountNumberMPAN__c,
						SPEN_PingResult__c,
						SPEN_LastGasp__c,
						ExternalId__c 
				FROM	SPEN_MPAN__c 
				WHERE	Id =: accountNumberMPAN
				WITH	SECURITY_ENFORCED
				LIMIT	:(Limits.getLimitQueryRows()-Limits.getQueryRows())
			];
		}
		
		return results.size() == 0 ? new SPEN_MPAN__c() : results[0];
	}

	// TODO: Method name should be selectByAccountNumber
	// TODO: Should be merged with the previous method. The previous method looks wrong
	public static SPEN_MPAN__c getRecordForMpan(String accNumberMPAN)
	{
		List<SPEN_MPAN__c> results = new List<SPEN_MPAN__c>();

		if(String.isNotBlank(accNumberMPAN))
		{
			results = [
				SELECT	Id,
						SPEN_Premise__c,
						SPEN_Premise__r.SPEN_PremiseId__c,
						SPEN_DCCServiceFlag__c,
						SPEN_AccountNumberMPAN__c,
						SPEN_LastEchoesSyncDate__c,
						SPEN_SmartMeterPingDateTime__c,
						SPEN_MeterType__c,
						SPEN_PingResult__c,
						SPEN_PremiseMeterType__c,
						SPEN_SupplierMPID__c,
						SPEN_SupplierName__c,
						SPEN_SupplierPhoneNumber__c 
				FROM	SPEN_MPAN__c
				WHERE	SPEN_AccountNumberMPAN__c =: accNumberMPAN
				WITH	SECURITY_ENFORCED 
				LIMIT	:(Limits.getLimitQueryRows()-Limits.getQueryRows())];
		}
		
		return results.size() == 0 ? new SPEN_MPAN__c() : results[0];
	}
}