force-app/main/default/objects/SPEN_MPAN__c/SPEN_MPAN__c.object-meta.xml
<CustomObject>
    <description>MPAN object is used to see MPAN related data.</description>
    <label>MPAN/Meter</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MPAN Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPAN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_AccountNumberMPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AccountNumberMPAN__c</fullName>
    <description>The account number associated with a call - PO map this to the MPAN. Question - what if there are multiple MPANS associated? Can this be cross checked</description>
    <externalId>true</externalId>
    <label>MPAN</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_ConnectionStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ConnectionStatus__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <label>Connection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disconnected</fullName>
            </value>
            <value>
                <fullName>Unmetered Supply</fullName>
            </value>
            <value>
                <fullName>Energised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>MPAN</relationshipLabel>
    <relationshipName>MPAN</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_AccountNumberMPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AccountNumberMPAN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account number is look up with Account Number (MPAN) field of MPAN object</description>
    <label>Account Number (MPAN)</label>
    <referenceTo>SPEN_MPAN__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_BuildingNameNumber__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BuildingNameNumber__c</fullName>
    <externalId>true</externalId>
    <label>Building Name/Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_FlatNumber__c.field-meta.xml
<CustomField>
    <fullName>SPEN_FlatNumber__c</fullName>
    <description>It holds the premise flat number</description>
    <label>Flat Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_MPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MPAN__c</fullName>
    <description>A text box to capture MPAN number to be sent to ADQM.</description>
    <label>MPAN</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PlotNumber__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PlotNumber__c</fullName>
    <label>Plot Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PostCode__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PostCode__c</fullName>
    <description>It takes the premise postal code</description>
    <externalId>true</externalId>
    <label>Post Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Unique SPEN identifier for a premise</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_Zone__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SPEN_Zone__c.SPEN_Type__c</field>
            <operation>equals</operation>
            <value>Zone</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/SPEN_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_BroadcastMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BroadcastMessage__c</fullName>
    <label>IVR  Message Assigned</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_Parent__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Zone</relationshipLabel>
    <relationshipName>Zone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SPEN_PremiseSelector.cls
public class SPEN_PremiseSelector 
{
	public static SPEN_Premise__c getPremiseRecord(String premiseId)
    {
        SPEN_Premise__c premiseRecord = [SELECT Id, SPEN_PremiseID__c,SPEN_FlatNumber__c,SPEN_Zone__c,SPEN_PostCode__c,SPEN_BuildingNameNumber__c,SPEN_AccountNumberMPAN__c FROM SPEN_Premise__c WHERE SPEN_PremiseID__c =: premiseId WITH SECURITY_ENFORCED];
        return premiseRecord;
    }
    
    public static SPEN_Premise__c getPremiseIVRMessages(String premiseId)
    {
        SPEN_Premise__c premiseRecord = [select id, SPEN_Zone__c, SPEN_Zone__r.SPEN_BroadcastMessage__c, SPEN_Zone__r.SPEN_Parent__c, SPEN_Zone__r.SPEN_Parent__r.SPEN_BroadcastMessage__c,  SPEN_Zone__r.SPEN_Parent__r.SPEN_Parent__c ,SPEN_Zone__r.SPEN_Parent__r.SPEN_Parent__r.SPEN_BroadcastMessage__c from SPEN_Premise__c WHERE Id =: premiseId WITH SECURITY_ENFORCED];
        return premiseRecord;
    }
    
    public static List<SPEN_Premise__c> getPresmise(Set<Id> contactId){
        List<SPEN_Premise__c> sPremises = [select id, SPEN_PremiseId__c from SPEN_Premise__c where id in(select SPEN_Premise__c from contact where id=:contactId)];
        return sPremises;
    }
    
    public static SPEN_Premise__c getPremiseFromUniqueCustomerId(String customerId)
    {
        List<SPEN_Premise__c> results = new List<SPEN_Premise__c>();
        
        results = [
            SELECT Id,SPEN_PremiseId__c FROM SPEN_Premise__c 
            WHERE SPEN_PremiseId__c =: customerId 
            WITH SECURITY_ENFORCED
            LIMIT:(Limits.getLimitQueryRows()-Limits.getQueryRows())
        ];
        
        return results.size() == 0 ? new SPEN_Premise__c() : results[0];
    }   
    public static Map<Id,Integer> getPremiseEnergisedMPANCount(Set<Id> premIds)
    {
        List<SPEN_MPAN__c> mpanLst = new List<SPEN_MPAN__c>();
        Map<Id,Integer> premiseIdEnergisedMPANCount = new Map<Id,Integer>();
        List<SPEN_Premise__c> premRcdList = [select Id, (Select Id from MPAN__r where SPEN_ConnectionStatus__c = 'Energised') from SPEN_Premise__c where id in :premIds];
        
        for(SPEN_Premise__c premRcd: premRcdList)
        {
            mpanLst = premRcd.MPAN__r;
            premiseIdEnergisedMPANCount.put(premRcd.Id, mpanLst.size());
        }
        return premiseIdEnergisedMPANCount;
    }
    public static List<SPEN_MPAN__c> getPremiseForMPAN(Set<Id> premIds)
    {
        List<SPEN_MPAN__c> mpanLst = new List<SPEN_MPAN__c>();
        List<SPEN_Premise__c> premRcdList = [select Id, (Select Id from MPAN__r where SPEN_ConnectionStatus__c = 'Energised') from SPEN_Premise__c where id in :premIds];
        
        for(SPEN_Premise__c premRcd: premRcdList)
        {
            mpanLst = premRcd.MPAN__r;
        }
        return mpanLst;
    }
//CRMD-10729 - S 
     public static Map<Id,Id> getPremiseFromMPAN(Set<Id> mPANIds)
    {
        List<SPEN_MPAN__c> mpanLst = new List<SPEN_MPAN__c>();
        Map<Id,Id> mPANVsPremiseMap = new Map<Id,Id>();
        mpanLst = [select id,SPEN_Premise__c from SPEN_MPAN__c where id IN:mPANIds];
        for(SPEN_MPAN__c mPANrec: mpanLst)
        {
            mPANVsPremiseMap.put(mPANrec.Id, mPANrec.SPEN_Premise__c);
        }
        return mPANVsPremiseMap;
    } //CRMD-10729 - E
    public static Map<Id,SPEN_Premise__c> getcaseRelatedPremiseRecord(Set<Id> premIdset)
    {
        Map<Id,SPEN_Premise__c> premiseMap=new Map<Id,SPEN_Premise__c>();
        if(premIdset != null && !premIdset.isEmpty()){
        List<SPEN_Premise__c> premiseList = [SELECT Id, SPEN_PremiseID__c,SPEN_FlatNumber__c,SPEN_PlotNumber__c,SPEN_Zone__c,SPEN_PostCode__c,SPEN_BuildingNameNumber__c,SPEN_AccountNumberMPAN__c FROM SPEN_Premise__c WHERE Id IN : premIdset WITH SECURITY_ENFORCED];
            for(SPEN_Premise__c premise:premiseList){
                premiseMap.put(premise.Id,premise);
            }
    }
        return premiseMap;
    }
}