force-app/main/default/objects/SPEN_MPAN__c/SPEN_MPAN__c.object-meta.xml
<CustomObject>
    <description>MPAN object is used to see MPAN related data.</description>
    <label>MPAN/Meter</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MPAN Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPAN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MPAN__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Macjules: TO BE DELETED</description>
    <label>[TO BE DELETED] ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_LastGasp__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LastGasp__c</fullName>
    <description>field to get the last gasp details from sdif</description>
    <label>Last Gasp Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/recordTypes/SPEN_MPAN.recordType-meta.xml
<RecordType>
    <fullName>SPEN_MPAN</fullName>
    <active>true</active>
    <description>Create record type for SPEN MPAN</description>
    <label>SPEN MPAN</label>
</RecordType>

force-app/main/default/classes/SPEN_ReceiveEndDevicePingStatus.cls
@RestResource(urlMapping='/SPEN_MPAN/*')
global with sharing class SPEN_ReceiveEndDevicePingStatus {
@HttpGet
    global static SPEN_MPAN__c doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String extId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        SPEN_MPAN__c result;
        if(extId != null)
        	result = [SELECT Id FROM SPEN_MPAN__c WHERE ExternalId__c = :extId];
        return result;
    }
  
  @HttpPatch
    global static ID doPatch() {
        RestRequest request = RestContext.request;
        String mpanId = request.requestURI.substring(
        request.requestURI.lastIndexOf('/')+1);
        SPEN_MPAN__c mpanObj;
        if(mpanId != null)
        	mpanObj = [SELECT Id,SPEN_LastGasp__c FROM SPEN_MPAN__c WHERE Id = :mpanId];
        // Deserialize the JSON string into name-value pairs
        Map<String, Object> params = (Map<String, Object>)JSON.deserializeUntyped(request.requestbody.tostring());
        // Iterate through each parameter field and value
        for(String fieldName : params.keySet()) {
            // Set the field and value on the Case sObject
            //system.debug('fieldName'+fieldName);
            //system.debug('fieldValue'+params.get(fieldName));
            mpanObj.put(fieldName, params.get(fieldName));
        }
        update mpanObj;
        return mpanObj.Id;
    }    
}