force-app/main/default/objects/SPEN_MPAN__c/SPEN_MPAN__c.object-meta.xml
<CustomObject>
    <description>MPAN object is used to see MPAN related data.</description>
    <label>MPAN/Meter</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MPAN Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPAN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_AccountNumberMPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AccountNumberMPAN__c</fullName>
    <description>The account number associated with a call - PO map this to the MPAN. Question - what if there are multiple MPANS associated? Can this be cross checked</description>
    <externalId>true</externalId>
    <label>MPAN</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_LastGasp__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LastGasp__c</fullName>
    <description>field to get the last gasp details from sdif</description>
    <label>Last Gasp Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SPEN_EndDeviceStatusCallback_Test.cls
@isTest
public class SPEN_EndDeviceStatusCallback_Test {
@isTest
    static void getmpanRecords(){
        SPEN_MPAN__c mpanUpdate = new SPEN_MPAN__c();
        String lastGaspDateTime = '2021-11-02T02:32:23.0000000+01:00';
        mpanUpdate.SPEN_AccountNumberMPAN__c = '123';
        insert mpanUpdate;
        mpanUpdate.SPEN_LastGasp__c=Datetime.valueOfGmt(lastGaspDateTime.replace('T', ' '));
        update mpanUpdate;
        Test.startTest();
        //String reqStr='<soapenv:Body><ReceiveEndDevicePingStatus xmlns="ENMAC/TCS"><StatusReading>	<status>Processing</status><EndDeviceAsset><mRID>123</mRID></EndDeviceAsset></StatusReading><EndDeviceStatusCallbackContext><correlationID>123</correlationID></EndDeviceStatusCallbackContext></ReceiveEndDevicePingStatus></soapenv:Body>';
        String reqStr='<?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns:end="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><SDIFReceiveEndDevicePingStatus xmlns="SDIF"><StatusReading xmlns="SDIF"><status>Processing</status><EndDeviceAsset xmlns="SDIF"><mRID>123</mRID></EndDeviceAsset></StatusReading><EndDeviceStatusCallbackContext xmlns="SDIF"><correlationID>123</correlationID></EndDeviceStatusCallbackContext></SDIFReceiveEndDevicePingStatus></soap:Body></soap:Envelope>';

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/EndDeviceOperation/';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.requestBody = Blob.valueOf(reqStr);
        RestContext.request = req;
        RestContext.response= res;

        Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass ());
        SPEN_EndDeviceStatusCallbackService.dopost();
        Test.stopTest();
       
      }
}