force-app/main/default/objects/SPEN_MPAN__c/SPEN_MPAN__c.object-meta.xml
<CustomObject>
    <description>MPAN object is used to see MPAN related data.</description>
    <label>MPAN/Meter</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MPAN Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPAN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_AccountNumberMPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AccountNumberMPAN__c</fullName>
    <description>The account number associated with a call - PO map this to the MPAN. Question - what if there are multiple MPANS associated? Can this be cross checked</description>
    <externalId>true</externalId>
    <label>MPAN</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>MPAN</relationshipLabel>
    <relationshipName>MPAN</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_AccountNumberMPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AccountNumberMPAN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account number is look up with Account Number (MPAN) field of MPAN object</description>
    <label>Account Number (MPAN)</label>
    <referenceTo>SPEN_MPAN__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_BuildingNameNumber__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BuildingNameNumber__c</fullName>
    <externalId>true</externalId>
    <label>Building Name/Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_FlatNumber__c.field-meta.xml
<CustomField>
    <fullName>SPEN_FlatNumber__c</fullName>
    <description>It holds the premise flat number</description>
    <label>Flat Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PostCode__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PostCode__c</fullName>
    <description>It takes the premise postal code</description>
    <externalId>true</externalId>
    <label>Post Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Unique SPEN identifier for a premise</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_Zone__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SPEN_Zone__c.SPEN_Type__c</field>
            <operation>equals</operation>
            <value>Zone</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/SPEN_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SPEN_PremisesSelector.cls
public with sharing class SPEN_PremisesSelector 
//extends fflib_SObjectSelector
	//implements SPEN_IPremisesSelector
{
    /*public static SPEN_IPremisesSelector newInstance()
	{
		return (SPEN_IPremisesSelector) Application.Selector.newInstance(SPEN_Premise__c.SObjectType);
	}
	 
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			SPEN_Premise__c.Id,
			SPEN_Premise__c.SPEN_PremiseID__c,
			SPEN_Premise__c.SPEN_PostCode__c,
            SPEN_Premise__c.SPEN_BuildingNameNumber__c,
            SPEN_Premise__c.SPEN_Zone__c,
            SPEN_Premise__c.SPEN_FlatNumber__c,    
            SPEN_Premise__c.SPEN_AccountNumberMPAN__c,
            SPEN_Premise__c.SPEN_AccountNumberMPAN__r.SPEN_AccountNumberMPAN__c    
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return SPEN_Premise__c.SObjectType;
	}

	public List<SPEN_Premise__c> selectById(Set<Id> idSet)
	{
		return (List<SPEN_Premise__c>) selectSObjectsById(idSet);
	}
	
    public List<SPEN_Premise__c> selectByExternalId(Set<String> premiseExternalIds,String externalField)
	{
		return (List<SPEN_Premise__c>) selectSObjectsByExternalId(premiseExternalIds,'SPEN_PremiseID__c');
	}
    
	public List<SPEN_Premise__c> selectByCustomerContact(List<Contact> contacts)
	{
		// Related Premises
		Set<String> premiseExternalIds = new Set<String>();
		for (Contact con : (List<Contact>) contacts)
		{
			if (con.SPEN_CustomerID__c != null)
			{
				premiseExternalIds.add(con.SPEN_CustomerID__c);
			}
		}
		return selectByExternalId(premiseExternalIds,'SPEN_PremiseID__c');
	}*/
    
	public static SPEN_Premise__c getPremiseRecord(String premiseId)
    {
        //SPEN_Premise__c premiseRecord = [SELECT Id, SPEN_PremiseID__c,SPEN_Zone__c,SPEN_AccountNumberMPAN__c FROM SPEN_Premise__c WHERE SPEN_PremiseID__c =: premiseId WITH SECURITY_ENFORCED];
        SPEN_Premise__c premiseRecord = [SELECT Id, SPEN_PremiseID__c,SPEN_FlatNumber__c,SPEN_PostCode__c,SPEN_BuildingNameNumber__c,SPEN_Zone__c FROM SPEN_Premise__c WHERE SPEN_PremiseID__c =: premiseId WITH SECURITY_ENFORCED];
        return premiseRecord;
    }
    public static List<SPEN_Premise__c> premDetailsForSyncContactsBatchService(Set<String> premiseExtIdSet){
        List<SPEN_Premise__c> premIdList = new List<SPEN_Premise__c>();
        premIdList = [Select Id,SPEN_PremiseID__c
                                         FROM SPEN_Premise__c
                                         WHERE SPEN_PremiseID__c IN: premiseExtIdSet
                     					 WITH SECURITY_ENFORCED];
        return premIdList;
    }
    
    public static List<SPEN_Premise__c> getPresmise(Set<Id> contactId){
		List<SPEN_Premise__c> sPremises = new List<SPEN_Premise__c>();
		if(!contactId.isEmpty()){
    		 sPremises = [select id, SPEN_PremiseId__c from SPEN_Premise__c where id in(select SPEN_Premise__c from contact where id=:contactId)];
		}
        return sPremises;
	
    }
    
    public static SPEN_Premise__c getPremiseFromUniqueCustomerId(String customerId)
    {
        List<SPEN_Premise__c> results = new List<SPEN_Premise__c>();
        
        results = [
            SELECT Id,SPEN_PremiseId__c FROM SPEN_Premise__c 
            WHERE SPEN_PremiseId__c =: customerId 
            WITH SECURITY_ENFORCED
            LIMIT:(Limits.getLimitQueryRows()-Limits.getQueryRows())
        ];
        
        return results.size() == 0 ? new SPEN_Premise__c() : results[0];
    }
	public List<SPEN_Premise__c> getPremiseForBeforeTrigger(Set<String> setPremiseId)
	{
		List<SPEN_Premise__c> results = new List<SPEN_Premise__c>();
		if(!setPremiseId.isEmpty())
		{
			results = [SELECT id, SPEN_PremiseId__c
						FROM SPEN_Premise__c 
						WHERE id IN:setPremiseId];
		}
		return results;
	}
}