force-app/main/default/objects/SPEN_IntegrationRequest__c/SPEN_IntegrationRequest__c.object-meta.xml
<CustomObject>
    <description>Integration Request object has been set up to use for IVR Integration.</description>
    <label>Integration Request</label>
    <nameField>
        <label>Integration Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_IntegrationRequestServiceClass__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IntegrationRequestServiceClass__c</fullName>
    <label>Integration Request Service Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Records__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Records__c</fullName>
    <label>Records</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/SPEN_MPAN__c.object-meta.xml
<CustomObject>
    <description>MPAN object is used to see MPAN related data.</description>
    <label>MPAN/Meter</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MPAN Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPAN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MPAN__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Macjules: TO BE DELETED</description>
    <label>[TO BE DELETED] ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_AccountNumberMPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AccountNumberMPAN__c</fullName>
    <description>The account number associated with a call - PO map this to the MPAN. Question - what if there are multiple MPANS associated? Can this be cross checked</description>
    <externalId>true</externalId>
    <label>MPAN</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_DCCServiceFlag__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DCCServiceFlag__c</fullName>
    <label>DCC Service Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Installed Not Commissioned</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Non-Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_LastGasp__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LastGasp__c</fullName>
    <description>field to get the last gasp details from sdif</description>
    <label>Last Gasp Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_PingResult__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PingResult__c</fullName>
    <label>Ping Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Energized</fullName>
            </value>
            <value>
                <fullName>Deenergized</fullName>
            </value>
            <value>
                <fullName>Timed-Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_PingResultFormula__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PingResultFormula__c</fullName>
    <formula>IF(NOT(ISBLANK(TEXT( SPEN_PingResult__c ))), TEXT(SPEN_PingResult__c ),
IF( AND(NOT(ISBLANK(SPEN_SmartMeterPingDateTime__c)),(NOW() - SPEN_SmartMeterPingDateTime__c) *24*60 &gt;=1 ), &apos;Timed-Out&apos;,&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ping Result</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Status of the smart meter - energised, de-energised</description>
    <label>Smart Meter Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SPEN_TestSmartMeterConnService.cls
/*-----------------------------------------------------------------------------
DESCRIPTION	:	Apex Service class for smart meter 
LIBRARY		:	Salesforce Enterprise Library - Smart Meter Connection
VERSION		:	1.0

HISTORY		:
Date			Author		    Comment
OCT-21-2022		Dhara Desai     Initial version
-----------------------------------------------------------------------------*/
public with sharing class SPEN_TestSmartMeterConnService {
    @AuraEnabled
    public static SPEN_MPAN__c getMPANDetails(Id recId){
        SPEN_LastGaspMockIntegrationService.getMockResponse(recId);
        //SPEN_TestMPANDetailsMock testMock = new SPEN_TestMPANDetailsMock();
        SPEN_MPAN__c mpanMock = SPEN_MPANSelector.getMpanRecord(recId);
        //testMock.send(recId);
        return mpanMock;
    }
    @AuraEnabled
    public static SPEN_MPAN__c getPingValue(Id recId){
      /*  SPEN_MPAN__c mpanMock = SPEN_MPANSelector.getMpanRecord(recId);
        mpanMock.SPEN_PingResult__c = 'TimedOut';
        Database.SaveResult dataSaveRes = Database.update(mpanMock);*/
        SPEN_MPAN__c mpanMock = [SELECT	Id,
						SPEN_AccountNumberMPAN__c,
						SPEN_PingResult__c,
						SPEN_LastGasp__c,
						ExternalId__c,
                        SPEN_PingResultFormula__c,
                        SPEN_DCCServiceFlag__c
				FROM	SPEN_MPAN__c 
				WHERE	Id = :recId
				WITH	SECURITY_ENFORCED LIMIT 1];
        
        return mpanMock;
    }
	@AuraEnabled
	public static void fetchMpanDetails(Id recId)
	{
		SPEN_MPAN__c mpanRec = SPEN_MPANSelector.getMpanRecord(recId);
		
		SPEN_IntegrationRequest__c intReq = new SPEN_IntegrationRequest__c();
		intReq.SPEN_IntegrationRequestServiceClass__c = 'SPEN_GetMeterDetailsByMpanService';
		intReq.SPEN_Records__c = mpanRec.SPEN_AccountNumberMPAN__c;
		intReq.SPEN_Status__c = 'Processing';
		insert intReq;
	}
}