force-app/main/default/objects/SPEN_IntegrationRequest__c/SPEN_IntegrationRequest__c.object-meta.xml
<CustomObject>
    <description>Integration Request object has been set up to use for IVR Integration.</description>
    <label>Integration Request</label>
    <nameField>
        <label>Integration Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_RelatedRecord__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelatedRecord__c</fullName>
    <description>Should be updated with zone id when we are updating the message details in integration request record</description>
    <label>Related Record</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Response__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Response__c</fullName>
    <label>Response</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <externalId>true</externalId>
    <inlineHelpText>This value must not be changed if IVR uses this message template.</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/recordTypes/Zone.recordType-meta.xml
<RecordType>
    <fullName>Zone</fullName>
    <active>true</active>
    <label>Zone</label>
</RecordType>

force-app/main/default/objects/SPEN_Zone__c/SPEN_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <label>IVR Message Temporary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_IVRMessageTemplate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessageTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IVR Message Template</label>
    <referenceTo>SPEN_IVRMessage__c</referenceTo>
    <relationshipLabel>Zone</relationshipLabel>
    <relationshipName>Zone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_IVRTemplateBody__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRTemplateBody__c</fullName>
    <label>IVR Template Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_OverwriteToChild__c.field-meta.xml
<CustomField>
    <fullName>SPEN_OverwriteToChild__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overwrite To Child</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_Parent__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Zone</relationshipLabel>
    <relationshipName>Zone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>District</fullName>
            </value>
            <value>
                <fullName>Zone</fullName>
            </value>
            <value>
                <fullName>Town</fullName>
            </value>
            <value>
                <fullName>Blanket</fullName>
                <isActive>false</isActive>
                <label>Blanket</label>
            </value>
            <value>
                <fullName>World</fullName>
                <isActive>false</isActive>
                <label>World</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_TestdataSelector.cls
/*-----------------------------------------------------------------------------
DESCRIPTION :   Test class for queries in test class
AUTHOR      :   Shubhi Vijayvergia
HISTORY     :
Date            Author              Comment
Jun-27-2023     Shubhi Vijayvergia         Initial version
-----------------------------------------------------------------------------*/
/* note for any existing query please add fields in the same query 
 only if the access is there in devops permissionset group
/*---------------------------------------------------------------------------------*/
@isTest
public with sharing class SPEN_TestdataSelector {
    //method to fetch profile
    public static Profile getProfile(String profileName){
        Profile p;
        if(String.isNotBlank(profileName)){
            p= [SELECT Id FROM Profile WHERE Name =:profileName LIMIT 1];
        }
        return p;
    }
    //method to fetch permission set group
    public static PermissionSetGroup getPSGroup(String psGroupName){
        PermissionSetGroup pg=new PermissionSetGroup();
        if(String.isNotBlank(psGroupName)){
            pg= [SELECT Id,Status FROM PermissionSetGroup WHERE DeveloperName =:psGroupName LIMIT 1]; 
        }
        return pg;
    }
    //method to fetch permission set
    public static PermissionSet getPermissionSet(String psName){
        PermissionSet ps1=new PermissionSet();
        if(String.isNotBlank(psName)){
            ps1 = [SELECT Id FROM PermissionSet WHERE Name =: psName];
        }
        return ps1;
    }
    //meythod to fetch user
    public static User getuser(String firstName){
        User user =new User();
        if(String.isNotBlank(firstName)){
            user= [SELECT id FROM user where firstname=:firstName AND isActive=true limit 1];
        }
        return user;
    }
    public static User getuserProfile(String profileName){
        User user =new User();
        if(String.isNotBlank(profileName)){
            user= [SELECT id FROM user where profile.Name=:profileName AND isActive=true limit 1];
        }
        return user;
    }
    //method to fetch ivrmessagge
    public static SPEN_iVRmessage__c getIVRMessage(String externalId){
        SPEN_iVRmessage__c iVRmessage=new SPEN_iVRmessage__c();
        if(String.isNotBlank(externalId)){
            iVRmessage =  [SELECT id,SPEN_iVRmessage__c FROM SPEN_iVRmessage__c WHERE SPEN_ExternalId__c=:externalId limit 1]; 
        }
        return iVRmessage;
    }
    //method to fetcvh zone filtering type
    public static SPEN_Zone__c getZone(String type){
        SPEN_Zone__c zone=new SPEN_Zone__c();
        if(String.isNotblank(type)){
            zone= [SELECT id,SPEN_Parent__c,SPEN_Type__c,SPEN_IVRMessageTemplate__c,SPEN_OverwriteToChild__c,SPEN_IVRTemplateBody__c
                        FROM SPEN_Zone__c WHERE SPEN_Type__c=:type limit 1];

        }
        return zone;
    }
    //method to fetcvh zone filtering type
    public static SPEN_Zone__c getZone(Id id){
        SPEN_Zone__c zone=new SPEN_Zone__c();
        if(id!=null){
            zone= [SELECT id,SPEN_Parent__c,SPEN_Type__c,SPEN_IVRMessageTemplate__c,SPEN_OverwriteToChild__c,SPEN_IVRTemplateBody__c
                        FROM SPEN_Zone__c WHERE Id=:id limit 1];

        }
        return zone;
    }
    //method to fetch IR
    public static  SPEN_IntegrationRequest__c getIR(Id id){
        SPEN_IntegrationRequest__c ir=new SPEN_IntegrationRequest__c();
        if(id!=null){
            ir= [Select id,SPEN_RelatedRecord__c,SPEN_Response__c from SPEN_IntegrationRequest__c where SPEN_RelatedRecord__c=:id];
        }
        return ir;
    }
    //get listviews
   	public static List<ListView> getListViews(String type){
        List<ListView> listViewList=new List<ListView>();
        if(String.isNotBlank(type)){
    		listViewList=[SELECT Id, Name FROM ListView WHERE SobjectType =:type order by Name];
        }
        return listViewList;
	}

}