force-app/main/default/objects/SPEN_IntegrationRequest__c/SPEN_IntegrationRequest__c.object-meta.xml
<CustomObject>
    <description>Integration Request object has been set up to use for IVR Integration.</description>
    <label>Integration Request</label>
    <nameField>
        <label>Integration Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_IntegrationRequestServiceClass__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IntegrationRequestServiceClass__c</fullName>
    <label>Integration Request Service Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Records__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Records__c</fullName>
    <label>Records</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Result__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Result__c</fullName>
    <label>Result</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/SPEN_MPAN__c.object-meta.xml
<CustomObject>
    <description>MPAN object is used to see MPAN related data.</description>
    <label>MPAN/Meter</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MPAN Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPAN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_AccountNumberMPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AccountNumberMPAN__c</fullName>
    <description>The account number associated with a call - PO map this to the MPAN. Question - what if there are multiple MPANS associated? Can this be cross checked</description>
    <externalId>true</externalId>
    <label>MPAN</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_PingResult__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PingResult__c</fullName>
    <label>Ping Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Energized</fullName>
            </value>
            <value>
                <fullName>Deenergized</fullName>
            </value>
            <value>
                <fullName>Timed-Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_PremiseMeterType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseMeterType__c</fullName>
    <description>Type of the Premise - Meter</description>
    <label>Premise - Meter Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <label>Smartmeter</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>Token Meter</label>
            </value>
            <value>
                <fullName>K</fullName>
                <label>Key Meter</label>
            </value>
            <value>
                <fullName>N</fullName>
                <isActive>false</isActive>
                <label>N</label>
            </value>
            <value>
                <fullName>S1</fullName>
                <isActive>false</isActive>
                <label>S1</label>
            </value>
            <value>
                <fullName>S2A</fullName>
                <isActive>false</isActive>
                <label>S2A</label>
            </value>
            <value>
                <fullName>S2AD</fullName>
                <isActive>false</isActive>
                <label>S2AD</label>
            </value>
            <value>
                <fullName>S2ADE</fullName>
                <isActive>false</isActive>
                <label>S2ADE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Status of the smart meter - energised, de-energised</description>
    <label>Smart Meter Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SPEN_EndDeviceStatusCallbackService.cls
@RestResource(urlMapping = '/EDS/ReceiveEndDevicePingStatus/*')
global class SPEN_EndDeviceStatusCallbackService {
    
    @HttpPost
    global static SPEN_MPAN__c dopost(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;   
        SPEN_MPAN__c mpan = new SPEN_MPAN__c();
        
        List<String> strList = new List<String>();
        //system.debug('req' +req.requestBody);

        SPEN_EnddeviceXMLNodes.SoapBodyNode MPANNODE = New SPEN_EnddeviceXMLNodes.SoapBodyNode();
        strList = req.requestBody.toString().split('<soapenv:Body>');
        //system.debug('strList' +strList);
        
		/*String newStr = req.requestBody.toString().replace(strList[0],'').replace('</soapenv:Envelope>', '');
        newStr = newStr.replaceAll('soapenv:', '');
        String soapNoNullString = newStr.replaceAll('end:', '');
        soapNoNullString = soapNoNullString.replaceAll(':end', '');
        //system.debug('newStr' +newStr);*/
        strList = req.requestBody.toString().split('<soap:Body>');
		String newStr = req.requestBody.toString().replace(strList[0],'').replace('</soap:Envelope>', '');
        //String req2 =  newStr.substring(0, newStr.length()-16);   
        String soapString = newStr.replaceAll('soap:', '');
        String soapNoNullString = soapString.replaceAll('xsi:nil=\"true\"', '');
        soapNoNullString = soapNoNullString.replaceAll('xmlns:ns2=\"SDIF\"','');// added for actual 2 namespace in request
        soapNoNullString = soapNoNullString.replaceAll('ns2:', '');
        soapNoNullString = soapNoNullString.replaceAll(':ns2', '');
        soapNoNullString = soapNoNullString.replaceAll('ns3:', '');
        soapNoNullString = soapNoNullString.replaceAll(':ns3', '');
        soapNoNullString = soapNoNullString.replaceAll('xmlns:ns3=\"http://ge.com/dsp/bf/service/commonfault\"', '');
        
        //system.debug('soapNoNullString-->' +soapNoNullString);
        
        MPANNODE.load(soapNoNullString);
        string JSONSTRING =JSON.serialize(MPANNODE);
        //system.debug('JSONSTRING' +JSONSTRING);

        SPEN_CallbackServiceWrapper callBackWrapper = (SPEN_CallbackServiceWrapper) System.JSON.deserialize(JSON.serialize(MPANNODE), SPEN_CallbackServiceWrapper.class);
        system.debug('callBackWrapper ---->'+callBackWrapper);
        
        if(!callBackWrapper.SDIFReceiveEndDevicePingStatus.isEmpty()) 
        {
            mpan = [SELECT Id,SPEN_AccountNumberMPAN__c,SPEN_PingResult__c,SPEN_PremiseMeterType__c FROM SPEN_MPAN__c WHERE SPEN_AccountNumberMPAN__c = :callBackWrapper.SDIFReceiveEndDevicePingStatus[0].StatusReading[0].EndDeviceAsset[0].mRID WITH SECURITY_ENFORCED];
            //system.debug('mpan----------->'+mpan);
            mpan.SPEN_PingResult__c = callBackWrapper.SDIFReceiveEndDevicePingStatus[0].StatusReading[0].status;
            //system.debug('SPEN_PingResult__c '+mpan.SPEN_PingResult__c);
            update mpan;
            
            List<SPEN_IntegrationRequest__c> intRqstRcd = [Select Id,SPEN_Result__c,SPEN_Status__c,SPEN_Records__c,SPEN_IntegrationRequestServiceClass__c 
                                                     from SPEN_IntegrationRequest__c where SPEN_IntegrationRequestServiceClass__c='SPEN_MeterPingService' and SPEN_Status__c ='Processing' 
                                                     order by LastModifiedById DESC];
            
            List<SPEN_IntegrationRequest__c> intToUpdate  = new List<SPEN_IntegrationRequest__c>();
            for(SPEN_IntegrationRequest__c intRqst : intRqstRcd)
            {
                if(intRqst.SPEN_Records__c == mpan.SPEN_AccountNumberMPAN__c)
                {
                    //system.debug('intRqst.SPEN_Records__c ----->'+intRqst.SPEN_Records__c);
                    intRqst.SPEN_Status__c = 'Completed';
                    intRqst.SPEN_Result__c = mpan.SPEN_PingResult__c;
                    intToUpdate.add(intRqst);
                } 
            }
			update intToUpdate;
            //system.debug('intToUpdate----->'+ intToUpdate);
        }
    	
        return mpan;
    }
}