force-app/main/default/objects/SPEN_IntegrationRequest__c/SPEN_IntegrationRequest__c.object-meta.xml
<CustomObject>
    <description>Integration Request object has been set up to use for IVR Integration.</description>
    <label>Integration Request</label>
    <nameField>
        <label>Integration Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ErrorMessage__c</fullName>
    <label>Error Message</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_IntegrationRequestServiceClass__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IntegrationRequestServiceClass__c</fullName>
    <label>Integration Request Service Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_RelatedRecord__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelatedRecord__c</fullName>
    <description>Should be updated with zone id when we are updating the message details in integration request record</description>
    <label>Related Record</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_RequestedBy__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RequestedBy__c</fullName>
    <label>Requested By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Response__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Response__c</fullName>
    <label>Response</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseAsyncCalloutResponse.cls
@RestResource(urlMapping ='/SDIFLogCallReply/*')
global with sharing class CaseAsyncCalloutResponse {
    
	@HttpPost
    global static Case updateCase(){
        
        List<String> strList = new List<String>();
        Case cseObjFromPowerOn = new Case();
        RestRequest req = RestContext.request;
        //String cseId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
       	CaseXmlNodes.SoapBodyNode csePowerOn = new CaseXmlNodes.SoapBodyNode();
        strList = req.requestBody.toString().split('<soap:Body>');
		String newStr = req.requestBody.toString().replace(strList[0],'').replace('</soap:Envelope>', '');
        String replacedString = newStr.replaceAll('soap:', '');
        //system.debug('replacedString: '+replacedString);
        csePowerOn.load(replacedString);
        
        PowerOnToCaseWrapper cseWrapper = (PowerOnToCaseWrapper) System.JSON.deserialize(JSON.serialize(csePowerOn), PowerOnToCaseWrapper.class);
		system.debug('cseWrapper: '+cseWrapper);
        
        for(PowerOnToCaseWrapper.SDIFLogCallReply cseLogCall: cseWrapper.SDIFLogCallReply){ 
            
            cseObjFromPowerOn = [Select Id,SPEN_PowerOnCallReference__c,CaseNumber,RecordType.DeveloperName,CreatedById from Case WHERE CaseNumber =: string.valueof(cseLogCall.logCallReplyStc[0].correlationID).leftPad(8,'0')];
            if(cseLogCall.logCallReplyStc[0].callReference != NULL)
            {
               cseObjFromPowerOn.SPEN_PowerOnCallReference__c	 =  cseLogCall.logCallReplyStc[0].callReference; 
            }
            else{
                if(cseObjFromPowerOn.RecordType.DeveloperName == 'SPEN_UnplannedFault'){
                    List<SPEN_IntegrationRequest__c> intRequestValue =[SELECT Id from SPEN_IntegrationRequest__c  WHERE SPEN_RelatedRecord__c=:cseObjFromPowerOn.Id AND SPEN_IntegrationRequestServiceClass__c='SDIFLogCallReply'];
                    if(intRequestValue.isEmpty() && cseLogCall.logCallReplyStc[0].status =='1668'){
                        Set<Id> idValues = new Set<Id>();
                        idValues.add(cseObjFromPowerOn.Id);
                        //CaseCallouts.postCallout(idValues,true);
                        Id jobId= System.enqueueJob(new SPEN_CaseCalloutQueueable(idValues));
                    }
                    SPEN_IntegrationRequest__c intReqst = new SPEN_IntegrationRequest__c();
            		intReqst.SPEN_Status__c = 'Failed';
            		intReqst.SPEN_RequestedBy__c = cseObjFromPowerOn.CreatedById;
            		intReqst.SPEN_IntegrationRequestServiceClass__c = 'SDIFLogCallReply';
                    intReqst.SPEN_RelatedRecord__c = cseObjFromPowerOn.Id;
                    intReqst.SPEN_Response__c = replacedString;
                    intReqst.SPEN_ErrorMessage__c = cseLogCall.logCallReplyStc[0].errorMsg;
                    insert intReqst;
                    //system.debug('==intReqst=='+intReqst);
                    //system.debug('cseObjFromPowerOn.SPEN_PowerOnCallReference__c: '+cseObjFromPowerOn.SPEN_PowerOnCallReference__c);
                }  
            }   
        }
        upsert cseObjFromPowerOn;
        return cseObjFromPowerOn;  
    }  
}