force-app/main/default/objects/SPEN_Incident_to_case_status_mapping__mdt/SPEN_Incident_to_case_status_mapping__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata to store the Incident to case status mapping</description>
    <label>SPEN Incident to case status mapping</label>
    <pluralLabel>SPEN Incident to case status mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SPEN_Incident_to_case_status_mapping__mdt/fields/SPEN_CaseStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CaseStatus__c</fullName>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Restored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Incident_to_case_status_mapping__mdt/fields/SPEN_IncidentStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentStatus__c</fullName>
    <label>Incident Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>Delog</fullName>
            </value>
            <value>
                <fullName>Reports OS</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Pre-arranged</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Merge</fullName>
            </value>
            <value>
                <fullName>Pending Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_Message__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Message__c</fullName>
    <description>It hold the message on IVR Message object</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/recordTypes/SMS.recordType-meta.xml
<RecordType>
    <fullName>SMS</fullName>
    <active>true</active>
    <label>SMS</label>
</RecordType>

force-app/main/default/objects/SPEN_IVROperatinghours__c/SPEN_IVROperatinghours__c.object-meta.xml
<CustomObject>
    <description>IVR Operating hours object is operating on time based on start time and end time.</description>
    <label>IVR Operating hours</label>
    <nameField>
        <label>IVR Operating hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Operating hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_EndTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EndTime__c</fullName>
    <description>End time field will collect the ending time of IVR Operating hours</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isActive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>IVR Message field is in master details relationship with IVR Message object and IVR Operating hours</description>
    <label>IVR Message</label>
    <referenceTo>SPEN_IVRMessage__c</referenceTo>
    <relationshipLabel>IVR Operating hours</relationshipLabel>
    <relationshipName>IVR_Operating_hours</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_StartTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_StartTime__c</fullName>
    <description>Start time field will collect the starting time of IVR Operating hours</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/SPEN_Sms__c.object-meta.xml
<CustomObject>
    <description>Represents a single SMS message.</description>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMSes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_CaseId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The case record that generated the SMS.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>SMSes</relationshipLabel>
    <relationshipName>SPEN_SMSes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_ContactId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The recipient of the SMS message.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SMSes</relationshipLabel>
    <relationshipName>SPEN_SMSes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <description>Indicates the event that triggered the SMS record to be created. In IVR scenarios, this is used to look up the message template.</description>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPAS Inquiry</fullName>
            </value>
            <value>
                <fullName>Supplier Inquiry</fullName>
            </value>
            <value>
                <fullName>Case Creation</fullName>
            </value>
            <value>
                <fullName>Merged from SP to Network</fullName>
            </value>
            <value>
                <fullName>3-Hour Comfort Call</fullName>
            </value>
            <value>
                <fullName>3rd Call Received</fullName>
            </value>
            <value>
                <fullName>Dropped Supply with Notice</fullName>
            </value>
            <value>
                <fullName>Dropped Supply without Notice</fullName>
            </value>
            <value>
                <fullName>Estimated Restoration Time Extended</fullName>
            </value>
            <value>
                <fullName>Incident Created</fullName>
            </value>
            <value>
                <fullName>Incident Restored</fullName>
            </value>
            <value>
                <fullName>Resource Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Resource Dispatched</fullName>
            </value>
            <value>
                <fullName>MPAS Out-Of-Area Inquiry</fullName>
            </value>
            <value>
                <fullName>Resource ETA Change</fullName>
            </value>
            <value>
                <fullName>Medically Dependent by District</fullName>
            </value>
            <value>
                <fullName>Planned Outage Communication</fullName>
            </value>
            <value>
                <fullName>On Demand</fullName>
            </value>
            <value>
                <fullName>Connections</fullName>
            </value>
            <value>
                <fullName>HV proactive contact</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>Complaint Case Creation</fullName>
            </value>
            <value>
                <fullName>GE Closure Survey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>SMSes</relationshipLabel>
    <relationshipName>SMSes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_IvrMessageId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IvrMessageId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refers to the SMS message template to be used.</description>
    <label>Message Template</label>
    <referenceTo>SPEN_IVRMessage__c</referenceTo>
    <relationshipLabel>SMSes</relationshipLabel>
    <relationshipName>SPEN_SMSes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_Message__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Message__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Actual message sent to the customer.</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_MessageType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MessageType__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_Mobile__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Mobile__c</fullName>
    <complianceGroup>PII;GDPR</complianceGroup>
    <description>The recipient&apos;s mobile number.</description>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Represents the status of message deliverability.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Undelivered</fullName>
            </value>
            <value>
                <fullName>Potentially Duplicate</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/SPEN_VoiceAlert__c/SPEN_VoiceAlert__c.object-meta.xml
<CustomObject>
    <label>Voice Alert</label>
    <nameField>
        <label>Voice Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voice Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_BroadcastMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BroadcastMessage__c</fullName>
    <label>Broadcast Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_CalledInTelephone__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CalledInTelephone__c</fullName>
    <label>Called In Telephone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_ContactId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Voice Alerts</relationshipLabel>
    <relationshipName>SPEN_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <label>Event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Voice Alerts</relationshipLabel>
    <relationshipName>SPEN_VoiceAlertIncident</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Various status for voice alert</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/recordTypes/Instant.recordType-meta.xml
<RecordType>
    <fullName>Instant</fullName>
    <active>true</active>
    <label>Instant</label>
</RecordType>

force-app/main/default/classes/SPEN_IncidentReparentBatch.cls
/*-----------------------------------------------------------------------------------------
DESCRIPTION  :  
AUTHOR    : 
LIBRARY    :  Salesforce Enterprise Library (SEL) 
VERSION    :  1.0

HISTORY    :
Date      Author        Comment
NOV-11-2021      Initial version
-----------------------------------------------------------------------------------------*/
public with sharing class SPEN_IncidentReparentBatch implements Database.Batchable<sObject>, Database.Stateful, Database.RaisesPlatformEvents
{
    Id incidentId;
    //List<Incident> incToUpdate = new List<Incident>();
    List<String> callRef = new List<String>();
    List<Incident> inciupdate = new List<Incident>();
    Incident newIncident = new Incident();

    public SPEN_IncidentReparentBatch(Incident incNew, List<String> cRef)
    {
        incidentId=incNew.Id;
        newIncident=incNew;
        callRef = cRef;
    }

    public Database.QueryLocator start(Database.BatchableContext bc)
    {
        return Database.getQueryLocator([Select Id,Status,SPEN_IsMerge__c,SPEN_Incident__c,SPEN_Incident__r.ParentIncidentId,SPEN_Incident__r.SPEN_IncidentStatus__c,SPEN_Incident__r.SPEN_IncidentType__c from CASE where Id =:callRef]);
    }
    public void execute(Database.BatchableContext bc, List<Case> caseList)
    {
        Set<Id> mergedIncidentIdSet = new Set<Id>();
        Set<Id> caseIdIncTypeChangeSet = new Set<Id>();
        List<Case> caseUpdList = new List<Case>();
        List<SPEN_Incident_to_case_status_mapping__mdt> incToCaseLst = [SELECT SPEN_IncidentStatus__c,SPEN_CaseStatus__c FROM SPEN_Incident_to_case_status_mapping__mdt];
        Map<String,String> incCaseMap = new Map<String,String>();
        for(SPEN_Incident_to_case_status_mapping__mdt mdtRec : incToCaseLst){
            incCaseMap.put(mdtRec.SPEN_IncidentStatus__c,mdtRec.SPEN_CaseStatus__c);
        }
        for(Case c : caseList)
        {
            if(c.SPEN_Incident__c!=null)
            {
                //below check added as Incident controller can cancel and link the call log to new INC without merge also
				if(c.SPEN_Incident__c != incidentId)
                {
                    mergedIncidentIdSet.add(c.SPEN_Incident__c);
                    c.SPEN_Incident__c = incidentId;
                    c.SPEN_IsMerge__c=true;
                    if(incCaseMap.containsKey(newIncident.SPEN_IncidentStatus__c)){
                        if(c.Status != incCaseMap.get(newIncident.SPEN_IncidentStatus__c)){
                            c.Status=incCaseMap.get(newIncident.SPEN_IncidentStatus__c);
                        }
                    }
                    Set<String> setCaseIncType = new Set<String> {'HV_N','HV_S','LV'};
                    if(setCaseIncType.contains(newIncident.SPEN_IncidentType__c) && c.SPEN_Incident__r.SPEN_IncidentType__c =='SP'){
                        caseIdIncTypeChangeSet.add(c.Id);
                    }
                    caseUpdList.add(c);
                }
                else{
                    //c.SPEN_Incident__c = incidentId;
                    if(incCaseMap.containsKey(c.SPEN_Incident__r.SPEN_IncidentStatus__c)){
                        if(c.Status != incCaseMap.get(c.SPEN_Incident__r.SPEN_IncidentStatus__c)){
                            c.Status=incCaseMap.get(c.SPEN_Incident__r.SPEN_IncidentStatus__c);
                            caseUpdList.add(c);
                        }
                    }
                }
            }
            else
            {
                c.SPEN_Incident__c = incidentId;
                if(incCaseMap.containsKey(newIncident.SPEN_IncidentStatus__c)){
                    if(c.Status != incCaseMap.get(newIncident.SPEN_IncidentStatus__c)){
                        c.Status=incCaseMap.get(newIncident.SPEN_IncidentStatus__c);
                    }
                }
                caseUpdList.add(c);
            }
        }
        /*for(Incident incRec : [Select id,ParentIncidentId from Incident where id IN: mergedIncidentIdSet])
        {
			incRec.ParentIncidentId = incidentId;
			incToUpdate.add(incRec);            
        }*/
        //update caseList;
        if(!caseUpdList.isEmpty()){
            update caseUpdList;
        }
        if(!caseIdIncTypeChangeSet.isEmpty()){
            List<Case> lstNewCases = [SELECT id, SPEN_Incident__c, SPEN_PreferredMethodofContact__c,
            SPEN_Incident__r.SPEN_IncidentType__c,SPEN_CaseCategoryOutcome__c,ContactId,
            SPEN_CallerMobileTelephone__c,SPEN_CallerTelephone__c
            FROM Case WHERE Id IN: caseIdIncTypeChangeSet];

            SPEN_IVRMessageSelector ivrSel = new SPEN_IVRMessageSelector();
            SPEN_IVRMessage__c ivrMsg= ivrSel.selectByExternalId('SMS – Single Premise – Network Fault');
            SPEN_IVRMessage__c ivrNetworkFault= ivrSel.selectByExternalId('Single Premise Network Fault VA');
    
            RecordType recType=[select id,RecordType.name from RecordType  where RecordType.name ='Case' LIMIT 1];
            Id voiceAlertRecordTypeId = Schema.SObjectType.SPEN_VoiceAlert__c.getRecordTypeInfosByName().get('Instant').getRecordTypeId();
            List<SPEN_SMS__c> smsLst=new List<SPEN_SMS__c>();
            List<SPEN_VoiceAlert__c> lstVoiceAlert = new List<SPEN_VoiceAlert__c>();
            for(Case c : lstNewCases){
                if((c.SPEN_PreferredMethodofContact__c == 'T' && c.SPEN_CallerMobileTelephone__c != Null) || (c.SPEN_PreferredMethodofContact__c == Null && c.SPEN_CallerMobileTelephone__c != Null))
                {
                    //Send SMS
                    String mobNo= (c.SPEN_CallerMobileTelephone__c !=Null && c.SPEN_CallerMobileTelephone__c.startsWith('0')) ? '+44'+c.SPEN_CallerMobileTelephone__c.removeStart('0'):c.SPEN_CallerMobileTelephone__c ;
                    SPEN_SMS__c sms= new SPEN_SMS__c(SPEN_ContactId__c=c.ContactId,
                    SPEN_IvrMessageId__c=ivrMsg.id,
                    SPEN_Message__c = ivrMsg.SPEN_IVRMessage__c,
                    SPEN_Status__c='Ready',
                    SPEN_Event__c='Merged from SP to Network',
                    SPEN_Mobile__c=mobNo,
                    RecordTypeId=recType.id,
                    SPEN_CaseId__c=c.id,
                    SPEN_IncidentId__c=c.SPEN_Incident__c,
                    SPEN_MessageType__c='Outbound');
                    smsLst.add(sms);
                }
                else if((c.SPEN_PreferredMethodofContact__c =='H' && c.SPEN_CallerTelephone__c != null) || (c.SPEN_PreferredMethodofContact__c==null && c.SPEN_CallerTelephone__c != null))
                {
                    SPEN_VoiceAlert__c objVoiceAlert = new SPEN_VoiceAlert__c();
                    objVoiceAlert.SPEN_CalledInTelephone__c = c.SPEN_CallerTelephone__c;
                    objVoiceAlert.SPEN_ContactId__c = c.ContactId;
                    objVoiceAlert.RecordTypeId = voiceAlertRecordTypeId;
                    objVoiceAlert.SPEN_IncidentId__c =c.SPEN_Incident__c;
                    objVoiceAlert.SPEN_BroadcastMessage__c = ivrNetworkFault.SPEN_IVRMessage__c;
                    objVoiceAlert.SPEN_Status__c = 'Ready';
                    lstVoiceAlert.add(objVoiceAlert);
                }
            }
            Boolean isSMSOptOut = checkBlackoutWindowPeriod('SMS Blackout Window');
            //System.debug('isSMSOptOut >>'+isSMSOptOut);
            //System.debug('smsLst >>'+smsLst);            
            if(smsLst != null && !smsLst.isEmpty()  && isSMSOptOut)
                insert smsLst;
                
            Boolean isVAOptOut = checkBlackoutWindowPeriod('VA Blackout Window');
            //System.debug('isVAOptOut >>'+isVAOptOut);
            
            if(lstVoiceAlert != null && !lstVoiceAlert.isEmpty() && isVAOptOut){
                insert lstVoiceAlert;
                //System.debug('lstVoiceAlert >>'+lstVoiceAlert);
                //Call VA Batch
                SPEN_VoiceAlertService.isServiceCall(lstVoiceAlert);
            }
        }
        /*if(!incToUpdate.isEmpty()){
            update incToUpdate;
        }*/

        for(Incident ic : [SELECT Id,ParentIncidentId, SPEN_IncidentStatus__c,(Select Id from Cases__r) FROM Incident WHERE id IN: mergedIncidentIdSet])
        {
            if(ic.Cases__r.size() == 0)
            {
                //ic.SPEN_IncidentStatus__c = 'Merged';
                inciupdate.add(new Incident(Id=ic.Id,SPEN_IncidentStatus__c = 'Merged',ParentIncidentId=incidentId));
            }
        }
    }
   
    public void finish(Database.BatchableContext bc)
    {
        if(!inciupdate.isEmpty())
        {
          update inciupdate;
        }
    }

    public static Boolean checkBlackoutWindowPeriod(String typeCheck){
        Boolean result = false;
        Id recTypeIdOfBlackoutWindowRT = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get(typeCheck).getRecordTypeId();
       
        List<SPEN_IVROperatingHours__c> lstIvrHour = [select Id, Name,SPEN_StartTime__c,SPEN_EndTime__c, RecordTypeId from  SPEN_IVROperatingHours__c where RecordTypeId = :recTypeIdOfBlackoutWindowRT and SPEN_isActive__c = true WITH SECURITY_ENFORCED limit 1]; 
        
        if(!lstIvrHour.isEmpty() && lstIvrHour[0] != null){
            if(lstIvrHour[0].SPEN_StartTime__c == null && lstIvrHour[0].SPEN_EndTime__c == null){
                result = true;
            }
            else if((lstIvrHour[0].SPEN_StartTime__c < lstIvrHour[0].SPEN_EndTime__c) && ((System.now().time() < lstIvrHour[0].SPEN_StartTime__c && System.now().time() < lstIvrHour[0].SPEN_EndTime__c) || (System.now().time() > lstIvrHour[0].SPEN_StartTime__c && System.now().time() > lstIvrHour[0].SPEN_EndTime__c))){
             
                 result = true;
             }
             else if((lstIvrHour[0].SPEN_StartTime__c > lstIvrHour[0].SPEN_EndTime__c) && (System.now().time() < lstIvrHour[0].SPEN_StartTime__c && System.now().time() > lstIvrHour[0].SPEN_EndTime__c)){
                 result = true;
             }
            
        }
        return result;
    }
}