force-app/main/default/objects/SEL_BatchStepTemplate__mdt/SEL_BatchStepTemplate__mdt.object-meta.xml
<CustomObject>
    <label>Batch Step Template</label>
    <pluralLabel>Batch Step Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/SEL_BatchStepTemplate__mdt/fields/SEL_BatchTemplateId__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchTemplateId__c</fullName>
    <label>Batch Template</label>
    <referenceTo>SEL_BatchTemplate__mdt</referenceTo>
    <relationshipLabel>Batch Step Templates</relationshipLabel>
    <relationshipName>SEL_BatchStepTemplates</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/SEL_BatchTemplate__mdt/SEL_BatchTemplate__mdt.object-meta.xml
<CustomObject>
    <label>Batch Template</label>
    <pluralLabel>Batch Templates</pluralLabel>
</CustomObject>

force-app/main/default/classes/SEL_BatchStepTemplates.cls
/*-----------------------------------------------------------------------------
DESCRIPTION	:	Domain class of the SEL_BatchStepTemplate__mdt custom metadata type
AUTHOR		:	Macjules Sevilla
LIBRARY		:	Salesforce Enterprise Library - Batch Framework
VERSION		:	1.0

HISTORY		:
Date			Author				Comment
AUG-23-2021		Macjules Sevilla	Initial version
-----------------------------------------------------------------------------*/
public inherited sharing class SEL_BatchStepTemplates 
{
	// DESCRIPTION
	// Group BatchStepTemplate__mdt by the parent template name
	public static Map<String, List<SEL_BatchStepTemplate__mdt>> groupByTemplate(List<SEL_BatchStepTemplate__mdt> steps)
	{
		Map<String, List<SEL_BatchStepTemplate__mdt>> result = new Map<String, List<SEL_BatchStepTemplate__mdt>>();

		// NOTE
		// If the parameter is null, return an empty Map
		if(!(steps == null || steps.isEmpty()))
		{ 
			for(SEL_BatchStepTemplate__mdt step : steps)
			{
				String templateName = Test.isRunningTest() ? 'SEL_BatchStepTemplate' : step.SEL_BatchTemplateId__r.MasterLabel;
				if(result.containsKey(templateName))
				{
					result.get(templateName).add(step);
				}
				else 
				{
					result.put(templateName, new List<SEL_BatchStepTemplate__mdt> { step });
				}
			}
		}

		return result;
	}
}