force-app/main/default/objects/SEL_BatchStepTemplate__mdt/SEL_BatchStepTemplate__mdt.object-meta.xml
<CustomObject>
    <label>Batch Step Template</label>
    <pluralLabel>Batch Step Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/SEL_BatchStepTemplate__mdt/fields/SEL_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchSize__c</fullName>
    <label>Batch Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStepTemplate__mdt/fields/SEL_BatchTemplateId__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchTemplateId__c</fullName>
    <label>Batch Template</label>
    <referenceTo>SEL_BatchTemplate__mdt</referenceTo>
    <relationshipLabel>Batch Step Templates</relationshipLabel>
    <relationshipName>SEL_BatchStepTemplates</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStepTemplate__mdt/fields/SEL_Class__c.field-meta.xml
<CustomField>
    <fullName>SEL_Class__c</fullName>
    <label>Class</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStepTemplate__mdt/fields/SEL_Sequence__c.field-meta.xml
<CustomField>
    <fullName>SEL_Sequence__c</fullName>
    <label>Sequence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SEL_BatchTemplate__mdt/SEL_BatchTemplate__mdt.object-meta.xml
<CustomObject>
    <label>Batch Template</label>
    <pluralLabel>Batch Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/SEL_BatchTemplate__mdt/fields/SEL_IsActive__c.field-meta.xml
<CustomField>
    <fullName>SEL_IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SEL_BatchStepTemplatesSelector.cls
/*-----------------------------------------------------------------------------
DESCRIPTION	:	Selector class of the SEL_BatchStepTemplate__mdt custom metadata type
AUTHOR		:	Macjules Sevilla
LIBRARY		:	Salesforce Enterprise Library - Batch Framework
VERSION		:	1.0

HISTORY		:
Date			Author				Comment
AUG-27-2021		Macjules Sevilla	Initial version
-----------------------------------------------------------------------------*/
public inherited sharing class SEL_BatchStepTemplatesSelector 
{
	// DESCRIPTION
	// Returns all active SEL_BatchStepTemplate__mdt related to a batch name
	public List<SEL_BatchStepTemplate__mdt> selectByTemplate(Set<String> batchNames)
	{
        List<SEL_BatchStepTemplate__mdt> result = new List<SEL_BatchStepTemplate__mdt>();

		if(batchNames != null && !batchNames.isEmpty()) 
        {
            result = [
                SELECT		SEL_BatchSize__c, SEL_BatchTemplateId__r.MasterLabel, SEL_Class__c, SEL_Sequence__c
                FROM		SEL_BatchStepTemplate__mdt
                WHERE		SEL_IsActive__c = true AND SEL_BatchTemplateId__r.MasterLabel IN :batchNames
                WITH		SECURITY_ENFORCED
                ORDER BY	SEL_Sequence__c 
            ];
        }

        return result;
	}
}