force-app/main/default/objects/SFBG_Question__c/SFBG_Question__c.object-meta.xml
<CustomObject>
    <description>Represents a Question record. Part of the Dynamic Questionnaire asset created by Macjules Sevilla.</description>
    <label>Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SFBG_ExternalId__c</fullName>
    <description>Uniquely identifies a Question record. Populate this field for data seeding.</description>
    <externalId>true</externalId>
    <inlineHelpText>The Name field should match the value of this field.</inlineHelpText>
    <label>External ID</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_HelpText__c.field-meta.xml
<CustomField>
    <fullName>SFBG_HelpText__c</fullName>
    <description>Help text to display in the custom rendering engine.</description>
    <inlineHelpText>Fill this out only if you want a help text to show up in the questionnaire form.</inlineHelpText>
    <label>Help Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_Question__c.field-meta.xml
<CustomField>
    <fullName>SFBG_Question__c</fullName>
    <description>The question to display in the custom rendering engine.</description>
    <label>Question</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_QuestionnaireId__c.field-meta.xml
<CustomField>
    <fullName>SFBG_QuestionnaireId__c</fullName>
    <description>The questionnaire record where this question record is related.</description>
    <label>Questionnaire</label>
    <referenceTo>SFBG_Questionnaire__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>SFBG_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_QuestionToDisplayId__c.field-meta.xml
<CustomField>
    <fullName>SFBG_QuestionToDisplayId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use this to open the next question if the Question Type is Textbox.</description>
    <label>Question To Display</label>
    <referenceTo>SFBG_Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>QuestionsToDisplayFromQuestion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFBG_Questionnaire__c/SFBG_Questionnaire__c.object-meta.xml
<CustomObject>
    <description>Represents a Questionnaire record. Part of the Dynamic Questionnaire asset created by Macjules Sevilla.</description>
    <label>Questionnaire</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SFBG_Questionnaire__c/fields/SFBG_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SFBG_ExternalId__c</fullName>
    <description>Uniquely identifies a Questionnaire record. Populate this field for data seeding.</description>
    <externalId>true</externalId>
    <inlineHelpText>Populate using a Questionnaire short name that uniquely identifies a questionnaire record followed by version number.</inlineHelpText>
    <label>External ID</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SFBG_Questionnaire__c/fields/SFBG_StartingQuestionId__c.field-meta.xml
<CustomField>
    <fullName>SFBG_StartingQuestionId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The starting question of the questionnaire.</description>
    <label>Starting Question</label>
    <referenceTo>SFBG_Question__c</referenceTo>
    <relationshipLabel>Questionnaires with Starting Question Record</relationshipLabel>
    <relationshipName>QuestionnairesWithStartingQuestionId</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFBG_Questionnaire__c/fields/SFBG_Version__c.field-meta.xml
<CustomField>
    <fullName>SFBG_Version__c</fullName>
    <description>Use to track different versions of the questionnaire.</description>
    <label>Version</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SFBG_QuestionWrapperController.cls
public with sharing class SFBG_QuestionWrapperController {
    // wrapper class with @AuraEnabled and {get;set;} properties 
    public class QuestionListWrapper{
        @AuraEnabled
        public SFBG_Question__c quesRecord{get;set;}
        @AuraEnabled
        public SFBG_Question__c firstQuesRecord{get;set;}
    }
    public class QuestionnaireWrapper{
        @AuraEnabled
        public SFBG_Questionnaire__c questionnaireRecord{get;set;}
    }
    @AuraEnabled(cacheable=true)
    public static List<QuestionnaireWrapper> getAllQuestionnaire(String launchVal){
        List<QuestionnaireWrapper> quesCollectionWrapperList = new List<QuestionnaireWrapper>();
        List<SFBG_Questionnaire__c> quesList;
        if(launchVal != null){
        	quesList = [SELECT Id, Name,SFBG_ExternalId__c,SFBG_StartingQuestionId__c,SFBG_Version__c 
                        FROM SFBG_Questionnaire__c
                        WHERE Name =: launchVal];
    	}
        if(quesList != null && !quesList.isEmpty()){
            for(SFBG_Questionnaire__c qs : quesList){
                QuestionnaireWrapper qWrapper = new QuestionnaireWrapper();
                qWrapper.questionnaireRecord = qs;
                quesCollectionWrapperList.add(qWrapper);
            }
        }
        return quesCollectionWrapperList;
    }
    @AuraEnabled(cacheable=true)
    public static List<QuestionListWrapper> getAllQuestions(Id questionnaireId, Id firstquesId){
        List<QuestionListWrapper> quesWrapperList = new List<QuestionListWrapper>();
        List<QuestionListWrapper> firstQuesRecordList = new List<QuestionListWrapper>();
        List<SFBG_Question__c> qList;
        if(questionnaireId != null){
        	qList = [SELECT Name,Id,SFBG_ExternalId__c,SFBG_HelpText__c,SFBG_Question__c,SFBG_QuestionnaireId__c,
                     SFBG_QuestionToDisplayId__c,SFBG_QuestionnaireId__r.Name,RecordType.DeveloperName
                     FROM SFBG_Question__c
                     WHERE SFBG_QuestionnaireId__c =: questionnaireId];
        }
        if(qList != null && !qList.isEmpty()){
            for(SFBG_Question__c acc : qList){
                QuestionListWrapper qWrapper = new QuestionListWrapper();
                if(acc.Id == firstquesId){
                    qWrapper.firstQuesRecord = acc;
                }
                qWrapper.quesRecord = acc;
                quesWrapperList.add(qWrapper);
            }
        }
        return quesWrapperList;
    }
}