force-app/main/default/objects/SFBG_Question__c/SFBG_Question__c.object-meta.xml
<CustomObject>
    <description>Represents a Question record. Part of the Dynamic Questionnaire asset created by Macjules Sevilla.</description>
    <label>Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SFBG_ExternalId__c</fullName>
    <description>Uniquely identifies a Question record. Populate this field for data seeding.</description>
    <externalId>true</externalId>
    <inlineHelpText>The Name field should match the value of this field.</inlineHelpText>
    <label>External ID</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_InformationCategory__c.field-meta.xml
<CustomField>
    <fullName>SFBG_InformationCategory__c</fullName>
    <description>Information to be displayed is of the following category</description>
    <label>Information Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_IsActive__c.field-meta.xml
<CustomField>
    <fullName>SFBG_IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If TRUE, then the rendering engine will display the question.</description>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_Question__c.field-meta.xml
<CustomField>
    <fullName>SFBG_Question__c</fullName>
    <description>The question to display in the custom rendering engine.</description>
    <label>Question</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_QuestionnaireId__c.field-meta.xml
<CustomField>
    <fullName>SFBG_QuestionnaireId__c</fullName>
    <description>The questionnaire record where this question record is related.</description>
    <label>Questionnaire</label>
    <referenceTo>SFBG_Questionnaire__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>SFBG_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/fields/SPEN_CallOutcome__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CallOutcome__c</fullName>
    <label>Call Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SPEN_CategoryOutcome</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/recordTypes/Radio.recordType-meta.xml
<RecordType>
    <fullName>Radio</fullName>
    <active>true</active>
    <label>Radio</label>
</RecordType>

force-app/main/default/objects/SFBG_Questionnaire__c/SFBG_Questionnaire__c.object-meta.xml
<CustomObject>
    <description>Represents a Questionnaire record. Part of the Dynamic Questionnaire asset created by Macjules Sevilla.</description>
    <label>Questionnaire</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SFBG_Questionnaire__c/fields/SFBG_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SFBG_ExternalId__c</fullName>
    <description>Uniquely identifies a Questionnaire record. Populate this field for data seeding.</description>
    <externalId>true</externalId>
    <inlineHelpText>Populate using a Questionnaire short name that uniquely identifies a questionnaire record followed by version number.</inlineHelpText>
    <label>External ID</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SFBG_Questionnaire__c/fields/SFBG_IsActive__c.field-meta.xml
<CustomField>
    <fullName>SFBG_IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If TRUE, then the questionnaire can be instantiated by the rendering engine.</description>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SFBG_Questionnaire__c/fields/SFBG_StartingQuestionId__c.field-meta.xml
<CustomField>
    <fullName>SFBG_StartingQuestionId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The starting question of the questionnaire.</description>
    <label>Starting Question</label>
    <referenceTo>SFBG_Question__c</referenceTo>
    <relationshipLabel>Questionnaires with Starting Question Record</relationshipLabel>
    <relationshipName>QuestionnairesWithStartingQuestionId</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFBG_Questionnaire__c/fields/SFBG_Version__c.field-meta.xml
<CustomField>
    <fullName>SFBG_Version__c</fullName>
    <description>Use to track different versions of the questionnaire.</description>
    <label>Version</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SFBG_QuestionWrapperControllerTest.cls
@isTest
public class SFBG_QuestionWrapperControllerTest {
    @testSetup static void setup(){
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user);  

    }

	@isTest 
    private static void test()
    {
       
        SFBG_Questionnaire__c quest = new SFBG_Questionnaire__c();
        quest.Name = 'Flood Damage';
        quest.SFBG_ExternalId__c = 'Flood Damage-V1';
        quest.SFBG_IsActive__c = true;
        //quest.SFBG_StartingQuestionId__r.SFBG_ExternalId__c = 
        quest.SFBG_Version__c = 1;
        insert quest;
        
        SFBG_Question__c question = new SFBG_Question__c();
        question.Name = 'FloodDamage-V1-Q1';
        question.SFBG_ExternalId__c = 'FloodDamage-V1-Q1';
        //question.SFBG_QuestionnaireId__r.SFBG_ExternalId__c = quest.SFBG_ExternalId__c;
        //question.SFBG_QuestionnaireId__r.Name = quest.SFBG_ExternalId__r.Name;
        question.SFBG_IsActive__c = true;
        question.SFBG_Question__c = 'Is the water covering, or about to cover any Scottish Power Equipment?';
        question.SFBG_InformationCategory__c = '';
        question.RecordTypeId = Schema.SObjectType.SFBG_Question__c.getRecordTypeInfosByDeveloperName().get('Radio').getRecordTypeId();
        question.SPEN_CallOutcome__c = '';
        question.SFBG_QuestionnaireId__c= quest.ID;
		insert  question;       
        SFBG_Questionnaire__c sfbgQues = new SFBG_Questionnaire__c();
        sfbgQues.Name = 'questionname';
        sfbgQues.SFBG_ExternalId__c = 'questionname';
        sfbgQues.SFBG_StartingQuestionId__c = question.Id;
        sfbgQues.SFBG_Version__c = 1;
        sfbgQues.SFBG_IsActive__c = true;        
        insert sfbgQues;
        
        Account ac = new Account();
        ac.Name='Test Question';
        insert ac;
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);
        System.runAs(user)
        { 
            Test.startTest();
            //SPEN_TestDataFactory.prepareQuestionnaireData('Question',2);
            List<SFBG_QuestionWrapperController.QuestionnaireWrapper> resultQ=SFBG_QuestionWrapperController.getAllQuestionnaire('questionname1');
            //SPEN_TestDataFactory.prepareQuestionnaireData('Question',2);
            Assert.isTrue(resultQ!=null,'Question data not available');
            Id accid;
            List<SFBG_QuestionWrapperController.QuestionListWrapper> resultQL=SFBG_QuestionWrapperController.getAllQuestions(quest.ID, accid);
            Assert.isTrue(resultQL!=null,'Question List not available');
            Test.stopTest();
        }
    }
    @isTest 
    private static void testNegative()
    {
       
        SFBG_Questionnaire__c quest = new SFBG_Questionnaire__c();
        quest.Name = 'Flood Damage';
        quest.SFBG_ExternalId__c = 'Flood Damage-V1';
        quest.SFBG_IsActive__c = true;
        //quest.SFBG_StartingQuestionId__r.SFBG_ExternalId__c = 
        quest.SFBG_Version__c = 1;
        insert quest;
        
        SFBG_Question__c question = new SFBG_Question__c();
        question.Name = 'FloodDamage-V1-Q1';
        question.SFBG_ExternalId__c = 'FloodDamage-V1-Q1';
        //question.SFBG_QuestionnaireId__r.SFBG_ExternalId__c = quest.SFBG_ExternalId__c;
        //question.SFBG_QuestionnaireId__r.Name = quest.SFBG_ExternalId__r.Name;
        question.SFBG_IsActive__c = true;
        question.SFBG_Question__c = 'Is the water covering, or about to cover any Scottish Power Equipment?';
        question.SFBG_InformationCategory__c = '';
        question.RecordTypeId = Schema.SObjectType.SFBG_Question__c.getRecordTypeInfosByDeveloperName().get('Radio').getRecordTypeId();
        question.SPEN_CallOutcome__c = '';
        question.SFBG_QuestionnaireId__c= quest.ID;
		insert  question;       
        SFBG_Questionnaire__c sfbgQues = new SFBG_Questionnaire__c();
        sfbgQues.Name = 'questionname';
        sfbgQues.SFBG_ExternalId__c = 'questionname';
        sfbgQues.SFBG_StartingQuestionId__c = question.Id;
        sfbgQues.SFBG_Version__c = 1;
        sfbgQues.SFBG_IsActive__c = true;        
        insert sfbgQues;
        
        Account ac = new Account();
        ac.Name='Test Question';
        insert ac;
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);
        System.runAs(user)
        { 
            Test.startTest();
            //SPEN_TestDataFactory.prepareQuestionnaireData('Question',2);
            List<SFBG_QuestionWrapperController.QuestionnaireWrapper> resultQ=SFBG_QuestionWrapperController.getAllQuestionnaire('');
            //SPEN_TestDataFactory.prepareQuestionnaireData('Question',2);
            Assert.isTrue(resultQ!=null,'Question data not available');
            Id accid;
            try{
                List<SFBG_QuestionWrapperController.QuestionListWrapper> resultQL=SFBG_QuestionWrapperController.getAllQuestions(accid, accid);
            	Assert.isTrue(resultQL!=null,'Question List not available');
            }catch(Exception e){
                Assert.isTrue(e!=null,'Exception occur');
            }
            
            Test.stopTest();
        }
    }
}