force-app/main/default/objects/SPEN_Job__c/SPEN_Job__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store L&amp;P Job records</description>
    <label>Job</label>
    <nameField>
        <label>Job Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Job__c/fields/SPEN_JobStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_JobStatus__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Job Released</fullName>
            </value>
            <value>
                <fullName>Full Job Released</fullName>
            </value>
            <value>
                <fullName>Job Released -Completion Certificate Required</fullName>
            </value>
            <value>
                <fullName>Job Released - Awaiting Final Land Right Invoicing</fullName>
            </value>
            <value>
                <fullName>Job Completed by LO - Completion Certificate Required</fullName>
                <isActive>false</isActive>
                <label>Job Completed by LO - Completion Certificate Required</label>
            </value>
            <value>
                <fullName>Job Completed by LO - Completion certificate Not Required</fullName>
                <isActive>false</isActive>
                <label>Job Completed by LO - Completion certificate Not Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_ContentDocuments.cls
public class SPEN_ContentDocuments {
	public void beforeDeleteContents(List<ContentDocument> cntList){
               
        Boolean isExternalUser = SPEN_ContentDocuments.isLoggedInAsExternalUser(); 
        //get prefix of Job exception record
        Schema.DescribeSObjectResult job = SPEN_Job__c.sObjectType.getDescribe();
        String jobKeyPrefix = job.getKeyPrefix();    
        List<Id> contentDocId = new List<Id>();
        Map<Id, Id> contDocLinkedMap = new Map<Id, Id>();        
        for(ContentDocument con : cntList){                        
            contentDocId.add(con.Id);
        }
        for(ContentDocumentLink cdl : [SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE ContentDocumentId IN : contentDocId]){
            if(jobKeyPrefix == String.valueOf(cdl.LinkedEntityId).left(3)){
                contDocLinkedMap.put(cdl.ContentDocumentId, cdl.LinkedEntityId);               
            }
        }
        Map<Id, SPEN_Job__c> jobsMap = new Map<ID, SPEN_Job__c>([select Id, SPEN_JobStatus__c from SPEN_Job__c where Id IN : contDocLinkedMap.values()]);
                           
        for(ContentDocument cdoc : cntList){
            //contDocLinkedMap.get(cdoc.Id) will give the LinkedEntityId
            if(isExternalUser && contDocLinkedMap.get(cdoc.id) != null && jobsMap.get(contDocLinkedMap.get(cdoc.id)).SPEN_JobStatus__c != 'Draft' && jobsMap.get(contDocLinkedMap.get(cdoc.id)).SPEN_JobStatus__c != 'Rejected' ){
                cdoc.adderror('Documentation can only be deleted if Job Status is Draft');
            }               
        }
    }
    
    public Static Boolean isLoggedInAsExternalUser(){
        Boolean isExternalUser = false;            
        Id userId = Userinfo.getUserId();
        Boolean hasPermission = FeatureManagement.checkPermission('SPEN_LnPExternalUsers');
        //System.debug('hasPermission==='+hasPermission);
        //User userDetail =[SELECT Id, Name, Email, Profile.Name, UserRole.Name FROM User where Id=:userId ];
        //if(userDetail!= null && (userDetail.UserRole.Name == 'External Distribution' || userDetail.UserRole.Name == 'External Manweb' || userDetail.UserRole.Name == 'External Transmission'))
        if(hasPermission==true)
        {
            isExternalUser=true;                
        } 
        return isExternalUser;
    }
}