force-app/main/default/objects/SPEN_Job__c/SPEN_Job__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store L&amp;P Job records</description>
    <label>Job</label>
    <nameField>
        <label>Job Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Job_Milestone__c/SPEN_Job_Milestone__c.object-meta.xml
<CustomObject>
    <label>Job Milestone</label>
    <nameField>
        <displayFormat>JM-{00000}</displayFormat>
        <label>Job Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Job_Milestone__c/fields/SPEN_Delay_Start_Days__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Delay_Start_Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Delay Start (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_Job_Milestone__c/fields/SPEN_Job__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Job__c</fullName>
    <description>Object created to hold Job Records</description>
    <label>Job</label>
    <referenceTo>SPEN_Job__c</referenceTo>
    <relationshipLabel>Job Milestones</relationshipLabel>
    <relationshipName>Job_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_Job_Milestone__c/fields/SPEN_Milestone__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Milestone__c</fullName>
    <label>Milestone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Job_Milestone__c/fields/SPEN_Milestone_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Milestone_Type__c</fullName>
    <label>Milestone Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Land Interest</fullName>
                <label>Land Right</label>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Planning Task</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Job_Milestone__c/fields/SPEN_Parent_Milestone__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Parent_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Milestone</label>
    <referenceTo>SPEN_WorkCategoryMilestone__c</referenceTo>
    <relationshipLabel>Job Milestones</relationshipLabel>
    <relationshipName>Job_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Job_Milestone__c/fields/SPEN_ParentJobMilestone__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ParentJobMilestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Job Milestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.SPEN_Job__c</field>
            <operation>equals</operation>
            <valueField>SPEN_Job_Milestone__c.SPEN_Job__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SPEN_Job_Milestone__c</referenceTo>
    <relationshipLabel>Job Milestones</relationshipLabel>
    <relationshipName>Job_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Job_Milestone__c/fields/SPEN_Planned_End_Date__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Planned_End_Date__c</fullName>
    <label>Planned End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_Job_Milestone__c/fields/SPEN_Planned_lead_time_Days__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Planned_lead_time_Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Planned Lead Time(Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_Job_Milestone__c/fields/SPEN_Planned_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Planned_Start_Date__c</fullName>
    <label>Planned Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_Job_Milestone__c/fields/SPEN_ReasonforCreation__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ReasonforCreation__c</fullName>
    <description>Created as part of ESC-192.</description>
    <label>Reason for Creation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Predefined</fullName>
            </value>
            <value>
                <fullName>Redesign</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
                <default>true</default>
                <label>Manual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Job_Milestone__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_WorkCategoryMilestone__c/SPEN_WorkCategoryMilestone__c.object-meta.xml
<CustomObject>
    <label>Work Category Milestone</label>
    <nameField>
        <displayFormat>WCM-{00000}</displayFormat>
        <label>Work Category Milestone</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Category Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_WorkCategoryMilestone__c/fields/SPEN_DelayStart__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DelayStart__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Delay Start (Days)</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_WorkCategoryMilestone__c/fields/SPEN_LeadTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LeadTime__c</fullName>
    <label>Lead Time (Days)</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_WorkCategoryMilestone__c/fields/SPEN_Milestone__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Milestone__c</fullName>
    <description>This will hold the milestone value</description>
    <label>Milestone</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_WorkCategoryMilestone__c/fields/SPEN_Milestone_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Milestone_Type__c</fullName>
    <description>ESC-74</description>
    <label>Milestone Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Land Interest</fullName>
                <label>Land Right</label>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Planning Task</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_PlanningTaskCreationInvocable.cls
/* File Name: SPEN_PlanningTaskCreationInvocable 
 * Description: The given code is a global class named SPEN_PlanningTaskCreationInvocable to create job milestone as Planning Task for a job milestone which is marked as in progress.
 * Author: ajay.chandraferi 
 * Version: 1.0
 * History:
 * Date            Author              Comment
 * Oct-10-2023     Ajay Chandraferi      Initial version
 *
 * Additional Information:
 * ESC-179 : Capture and report on field-level information on the planning records. 
 */
global class SPEN_PlanningTaskCreationInvocable {
    
    global static BusinessHours businessHourObj;
    global static SPEN_Job_Milestone__c jobMilestone;
   // global static SPEN_CreatePlanningTaskRequest req;
    
    @InvocableMethod(label = 'Planning Task Creation' description = 'Returns planning task as job milestones record')
    global static list <SPEN_CreatePlanningTaskResult> createPlanningTaskMilestones(list<SPEN_CreatePlanningTaskRequest> milestoneReq) {
        list <SPEN_CreatePlanningTaskResult> oMilestoneResult = new list <SPEN_CreatePlanningTaskResult> ();
        if (!milestoneReq.isEmpty()) {
            list <SPEN_Job_Milestone__c> planningTaskToBeInserted = new list<SPEN_Job_Milestone__c>();
            businessHourObj = [SELECT Id FROM BusinessHours WHERE name = 'Connection Business Hours'];                
            for(SPEN_CreatePlanningTaskRequest req : milestoneReq){                
                jobMilestone = req.jobmilestoneObj;
                SPEN_CreatePlanningTaskResult res = new SPEN_CreatePlanningTaskResult();            
                res.planningTaskResult = new list<SPEN_Job_Milestone__c>(); 
                if(req.wcmPlanningtasks != null){                
                    for(SPEN_WorkCategoryMilestone__c wcmPlanningTask : req.wcmPlanningtasks){
                        SPEN_Job_Milestone__c currPlanningTask = new SPEN_Job_Milestone__c();
                        fieldsAssignment(wcmPlanningTask, currPlanningTask, system.today());
                        res.planningTaskResult.add(currPlanningTask);
                        planningTaskToBeInserted.add(currPlanningTask);
                    }                    
                }
                oMilestoneResult.add(res);   
            }   
            if(planningTaskToBeInserted!= null && planningTaskToBeInserted.size() > 0){
                insert planningTaskToBeInserted;
            }                  
        }
        return oMilestoneResult;
    }
    
    global static void fieldsAssignment(SPEN_WorkCategoryMilestone__c wcmObj, SPEN_Job_Milestone__c newJobMilestone,Date planStartDate){   
        newJobMilestone.SPEN_Job__c =  jobMilestone.SPEN_Job__c;        
        newJobMilestone.SPEN_Milestone_Type__c= wcmObj.SPEN_Milestone_Type__c ;
        newJobMilestone.SPEN_Milestone__c = wcmObj.SPEN_Milestone__c;
        newJobMilestone.SPEN_Parent_Milestone__c = wcmObj.id;
        newJobMilestone.SPEN_ParentJobMilestone__c = jobMilestone.id;
        newJobMilestone.SPEN_ReasonforCreation__c = 'Predefined'; 
        newJobMilestone.SPEN_Delay_Start_Days__c = wcmObj.SPEN_DelayStart__c ;
        newJobMilestone.SPEN_Planned_lead_time_Days__c = wcmobj.SPEN_LeadTime__c ;       
        newJobMilestone.SPEN_Status__c ='New';
        Integer addInitialDays = 0;        
        if(wcmObj.SPEN_DelayStart__c != null){
            addInitialDays += Integer.valueOf(wcmObj.SPEN_DelayStart__c);                      
        }                  
        Integer addEndDateDays = addInitialDays+ Integer.valueOf(wcmObj.SPEN_LeadTime__c);
        if(businessHourObj != null){            
            DateTime startDate = SPEN_BusinessDaysCalculationUtil.addDays((Datetime) planStartDate, addInitialDays,businessHourObj.Id );            
            newJobMilestone.SPEN_Planned_Start_Date__c = Date.newInstance(startDate.year(), startDate.month(), startDate.day());
            DateTime endDate = SPEN_BusinessDaysCalculationUtil.addDays((Datetime) planStartDate, addEndDateDays,businessHourObj.Id );               
            newJobMilestone.SPEN_Planned_End_Date__c = Date.newInstance(endDate.year(), endDate.month(), endDate.day());
        }else{
            newJobMilestone.SPEN_Planned_Start_Date__c = planStartDate.addDays(addInitialDays);
            newJobMilestone.SPEN_Planned_End_Date__c = planStartDate.addDays(addEndDateDays);
        }
    }
    global class SPEN_CreatePlanningTaskRequest {        
        @InvocableVariable(required = true)
        global SPEN_Job_Milestone__c jobmilestoneObj;       
        @InvocableVariable
        global List<SPEN_WorkCategoryMilestone__c> wcmPlanningtasks;
    }
    global class SPEN_CreatePlanningTaskResult {                
        @InvocableVariable
        global list < SPEN_Job_Milestone__c > planningTaskResult;        
    }
    
    
}