force-app/main/default/objects/SPEN_Employee__c/SPEN_Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Employee Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Employee__c/fields/SPEN_EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EmailAddress__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/SPEN_EmployeeSelector.cls
/***************************************************************************
* @Author:      Shubhi
* @Date:        30/08/2023
* @UserStory:   CRMD-7688
* @Description: Selector class for SPEN_Employee object
*****************************************************************************/
public class SPEN_EmployeeSelector {
    
    public static List<SPEN_Employee__c> getEmployeeFromEmail(List<String> requestorEmail){
        List<SPEN_Employee__c> emp=new List<SPEN_Employee__c>();
        try{	
            If(!requestorEmail.isEmpty()){
                emp=[SELECT id,SPEN_EmailAddress__c FROM SPEN_Employee__c 
                 WHERE SPEN_EmailAddress__c IN: requestorEmail ];
            }
        }catch(Exception e){
            SEL_LoggingService.log(e);
        }
        return emp ;  
    }
}