force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/SPEN_TransmissionApplicationFeeRules__c.object-meta.xml
<CustomObject>
    <description>This is an object to store the rules of calculating the Fixed Cumulative Application Fee Values. And provide the admin to edit the rules when necessary.</description>
    <label>Transmission Application Fee Rules</label>
    <nameField>
        <displayFormat>Rule-{0000}</displayFormat>
        <label>Rule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transmission Application Fee Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_ApplicationStage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ApplicationStage__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>Application Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Mod-App</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_ApplicationType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ApplicationType__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>New Onshore Supply Point</fullName>
            </value>
            <value>
                <fullName>SOW</fullName>
            </value>
            <value>
                <fullName>BELLA (Dist)</fullName>
            </value>
            <value>
                <fullName>BELLA (Trans)</fullName>
            </value>
            <value>
                <fullName>BEGA (Dist)</fullName>
            </value>
            <value>
                <fullName>BEGA (Trans)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_ContractArea__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ContractArea__c</fullName>
    <description>This field is for Transmission process.</description>
    <label>Contract Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Area</fullName>
            </value>
            <value>
                <fullName>Affected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_DailyHours__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DailyHours__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>Daily Hours</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_DailyRate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DailyRate__c</fullName>
    <description>This field is for Transmission Process.</description>
    <label>Daily Rate</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_FeeType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_FeeType__c</fullName>
    <description>Formula field for Transmission process.</description>
    <formula>If(RecordType.DeveloperName==&apos;SPEN_FixedApplicationFee&apos;,&apos;Fixed&apos;,If(RecordType.DeveloperName==&apos;SPEN_VariableApplicationFee&apos;,&apos;Variable&apos;,&apos;NA&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fee Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_FixedCumulativeApplicationFee__c.field-meta.xml
<CustomField>
    <fullName>SPEN_FixedCumulativeApplicationFee__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>Fixed Cumulative Application Fee</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_isActive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is for Transmission Process. To check if the rule is active</description>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_LocationType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LocationType__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onshore</fullName>
            </value>
            <value>
                <fullName>Offshore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_MAXDemandCapacityMWs__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MAXDemandCapacityMWs__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>MAX Demand Capacity MWs</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_MAXSizeMWsCECExport__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MAXSizeMWsCECExport__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>MAX Size MWs CEC Export</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_MINDemandCapacityMWs__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MINDemandCapacityMWs__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>MIN Demand Capacity MWs</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_MINSizeMWsCECExport__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MINSizeMWsCECExport__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>MIN Size MWs CEC Export</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_PrimaryTransmissionTechnology__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PrimaryTransmissionTechnology__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>Primary Transmission Technology</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>CCGT</fullName>
            </value>
            <value>
                <fullName>Bio-Fuels</fullName>
            </value>
            <value>
                <fullName>CHP</fullName>
            </value>
            <value>
                <fullName>EFW</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>Power Plant</fullName>
            </value>
            <value>
                <fullName>Interconnector</fullName>
            </value>
            <value>
                <fullName>Tidal</fullName>
            </value>
            <value>
                <fullName>Sync Comp</fullName>
            </value>
            <value>
                <fullName>Demand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_Role__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Role__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Department manager</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Senior Member Of Staff</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Support Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_Team__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Team__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System Design</fullName>
            </value>
            <value>
                <fullName>System Design Manager Approval</fullName>
            </value>
            <value>
                <fullName>Engineering Design</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Development Manager Approval</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Commercial Manager Approval</fullName>
            </value>
            <value>
                <fullName>Delivery Manager Approval</fullName>
            </value>
            <value>
                <fullName>Support Staff</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Offer Questions Time Spent</fullName>
            </value>
            <value>
                <fullName>Engineering Design Manager Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_TransmissionApplicationFeeSelector.cls
/*-----------------------------------------------------------------------------
DESCRIPTION :   Selector class of the TransmissionApplicationFee Queries.
LIBRARY     :   Salesforce Enterprise Library - TransmissionApplicationFee Queries
VERSION     :   1.0

HISTORY     :
Date            Author              Comment
22-Sep-2023     Rohit Sharma        Initial version
-----------------------------------------------------------------------------*/
public inherited sharing class SPEN_TransmissionApplicationFeeSelector {
    /**************************************************
    @Author: Rohit Sharma
    @Date: 22-Sep-2023
    @purpose: Method to get TransmissionApplicationFee details.
    ***************************************************/
        public static List<SPEN_TransmissionApplicationFeeRules__c> getTransmissionApplicationFeeDetails(String feeType){
            List<SPEN_TransmissionApplicationFeeRules__c>	transmissionApplicationFeeList = new List<SPEN_TransmissionApplicationFeeRules__c>();
            if(feeType != null)
            {
                transmissionApplicationFeeList = 	[Select Id,SPEN_isActive__c,SPEN_FeeType__c,SPEN_DailyRate__c,SPEN_Team__c,SPEN_Role__c,SPEN_DailyHours__c             	
                             FROM SPEN_TransmissionApplicationFeeRules__c
                             where SPEN_FeeType__c=: feeType and SPEN_isActive__c=true ORDER BY createdDate DESC];
            }  	                       
            return transmissionApplicationFeeList;     
        }
        public static List<SPEN_TransmissionApplicationFeeRules__c> getTransmissionApplicationFeeDetailsByApplicationType(String feeType,set<String> appType){
            List<SPEN_TransmissionApplicationFeeRules__c>	transmissionApplicationFeeList = new List<SPEN_TransmissionApplicationFeeRules__c>();
            if(feeType != null)
            {
                transmissionApplicationFeeList = 	[select id, SPEN_ApplicationStage__c, SPEN_ApplicationType__c, SPEN_ContractArea__c,SPEN_LocationType__c,
                                                               SPEN_MAXDemandCapacityMWs__c,SPEN_MAXSizeMWsCECExport__c,SPEN_MINDemandCapacityMWs__c,SPEN_MINSizeMWsCECExport__c,
                                                           SPEN_PrimaryTransmissionTechnology__c,SPEN_FixedCumulativeApplicationFee__c
                                                               FROM SPEN_TransmissionApplicationFeeRules__c 
                                                               WHERE SPEN_ApplicationType__c IN: apptype and SPEN_FeeType__c=: feeType and SPEN_isActive__c=true ORDER BY createdDate DESC];
            }  	                       
            return transmissionApplicationFeeList;     
        }
    }