force-app/main/default/objects/SEL_Batch__c/SEL_Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <displayFormat>BAT{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEL_Batch__c/fields/SPEN_AdqmLoadDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AdqmLoadDate__c</fullName>
    <description>This field is used by the ADQM Delta Sync process.</description>
    <inlineHelpText>The created date to process.</inlineHelpText>
    <label>ADQM Load Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/SPEN_ContactNumberEmailStaging__c.object-meta.xml
<CustomObject>
    <description>SPEN_ContactNumberEmailStaging will be staging for contact numbers and Email</description>
    <label>Contact Number Email Staging</label>
    <nameField>
        <displayFormat>CNE-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Number Email Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/fields/SPEN_NumberOrEmail__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NumberOrEmail__c</fullName>
    <label>NumberOrEmail</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/fields/SPEN_SyncStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SyncStatus__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Indicates if the change value is synced to the contact record.</description>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_SyncContactFieldsBatch.cls
/*-------------------------------------------------------------------------------------------------
DESCRIPTION	:	Move contact number and email changes from SPEN_ContactNumberEmailStaging__c to 
				the Contact standard object.
LIBRARY		:	SPEN
VERSION		:	1.0

HISTORY		:
Date			Author				Comment
15/2/2023		Asmita Rajput
-------------------------------------------------------------------------------------------------*/
public with sharing class SPEN_SyncContactFieldsBatch extends SEL_BatchStepBase implements Database.Batchable<sObject>, Database.Stateful, Database.RaisesPlatformEvents
{
	// BATCH FRAMEWORK
	// Do not remove or change.
	public Id batchParentId;
	public Id batchChildId;
	
	// OTHER VARIABLES
	public date adqmLoadDate;
	
	public SPEN_SyncContactFieldsBatch() 
	{
		// BATCH FRAMEWORK
		// Do nothing.
		return;
	}
	
	public SPEN_SyncContactFieldsBatch(Id batch, Id batchStep)
	{
		// BATCH FRAMEWORK
		// Do not remove.
		this.batchParentId = batch;
		this.batchChildId = batchStep;
		
		// Get the ADQM Load Date to process
		List<SEL_Batch__c> results = new SEL_BatchesSelector().selectByIds(new Set<Id> { batch });
		if(!results.isEmpty() && results.size() == 1)
		{
			adqmLoadDate = results[0].SPEN_AdqmLoadDate__c;
		}
	}
	
	public Database.QueryLocator start(Database.BatchableContext bc)
	{
		return new SPEN_ContactStagingSelector().getQueryLocatorForNotStartedAndFailed(adqmLoadDate);
	}
	
	public void execute(Database.BatchableContext bc, List<SPEN_ContactNumberEmailStaging__c> lstContStaging)
	{
		List<Contact> contList = new List<Contact>();
		List<Contact> contUpdateList = new List<Contact>();
		Map<Id,Contact> contactUpdateMap = new Map<Id,Contact>();
		Set<String> setExternalId = new Set<String>();
		Map<String, Contact> mapCustId2Contact = new Map<String,Contact>();
		Map<String, List<SPEN_ContactNumberEmailStaging__c>> mapContId2ListStageRec = new Map<String,List<SPEN_ContactNumberEmailStaging__c>>();
		List<SPEN_ContactNumberEmailStaging__c> tempList;
		List<SPEN_ContactNumberEmailStaging__c> stageRecUpdateList = new List<SPEN_ContactNumberEmailStaging__c>();

		for(SPEN_ContactNumberEmailStaging__c staging : lstContStaging)
		{
			setExternalId.add(staging.SPEN_ExternalId__c);
		}

		if(!setExternalId.isEmpty())
		{
			contList = SPEN_ContactSelector.getContactsByCustomerId(setExternalId);
			if(!contList.isEmpty())
			{
				for(Contact c: contList)
				{
					mapCustId2Contact.put(c.SPEN_CustomerID__c, c);
				}
			}
			
			// RULE
			// Update the record only when there is a change coming from ADQM
			for(SPEN_ContactNumberEmailStaging__c staging : lstContStaging)
			{
				Boolean isChanged = false;
				Contact asIs = mapCustId2Contact.get(staging.SPEN_ExternalId__c);
                Contact toBe = new Contact();
                //Contact toBe = new Contact(Id = asIs.Id);
				if(asIs != null)
				{
					if(!contactUpdateMap.containsKey(asIs.Id))
					{
						toBe.Id = asIs.Id;
					}
					else{
						toBe = contactUpdateMap.get(asIs.Id);
					}
					contactUpdateMap.put(asIs.Id,toBe);
	
					if(staging.SPEN_Type__c.equalsIgnoreCase('Email') &&
					staging.SPEN_NumberOrEmail__c != asIs.Email)
					{
						//isChanged = true;
						toBe.Email = staging.SPEN_NumberOrEmail__c;
					}
					else if(staging.SPEN_Type__c.equalsIgnoreCase('Mobile') &&
					staging.SPEN_NumberOrEmail__c != asIs.MobilePhone)
					{
						//isChanged = true;
						toBe.MobilePhone = staging.SPEN_NumberOrEmail__c;
					}
					else if(staging.SPEN_Type__c.equalsIgnoreCase('Other') &&
					staging.SPEN_NumberOrEmail__c != asIs.OtherPhone)
					{
						//isChanged = true;
						toBe.OtherPhone = staging.SPEN_NumberOrEmail__c;
					}
					else if(staging.SPEN_Type__c.equalsIgnoreCase('Home') &&
					staging.SPEN_NumberOrEmail__c != asIs.Phone)
					{
						//isChanged = true;
						toBe.Phone = staging.SPEN_NumberOrEmail__c;
					}
	
					//if(isChanged)
					//{
						if(mapContId2ListStageRec.containsKey(asIs.Id))
						{
							mapContId2ListStageRec.get(toBe.Id).add(staging);
						}
						else
						{
							mapContId2ListStageRec.put(toBe.Id, new List<SPEN_ContactNumberEmailStaging__c> { staging });
						}
						if(!contUpdateList.contains(toBe))
						{
							contUpdateList.add(toBe);
						}
					//}
				}
				
			}
		}
		//system.debug('***contUpdateList**' +contUpdateList);	
		// COMMIT
		// Changes to both Contact and ContactNumberEmailStaging objects
		if(!contUpdateList.isEmpty())
		{
			Database.SaveResult[] srList = Database.update(contUpdateList, false);
			
			for (Database.SaveResult sr : srList) 
			{
				tempList = mapContId2ListStageRec.get(sr.getId());
				if (sr.isSuccess()) 
				{
					for(SPEN_ContactNumberEmailStaging__c stageRec : tempList)
					{
						stageRec.SPEN_SyncStatus__c = 'Successful';
					}
				}
				else 
				{
					for(SPEN_ContactNumberEmailStaging__c stageRec : tempList)
					{
						stageRec.SPEN_SyncStatus__c = 'Failed';
					}
				}
				stageRecUpdateList.addAll(tempList);
			}
			
			if(!stageRecUpdateList.isEmpty())
			{
				update stageRecUpdateList;
			}
		}
	}

	public void finish(Database.BatchableContext context) 
	{
		// BATCH FRAMEWORK
		// Do not remove or change.
		super.finishBatch(context, this.batchParentId, this.batchChildId);
	}
	
	// BATCH FRAMEWORK METHOD
	// This is a Batch Framework method that must be overridden so the framework
	// can run batches from the sequencing logic. 
	public override void executeBatch()
	{
		if(super.isValid())
		{
			SPEN_SyncContactFieldsBatch runMe = new SPEN_SyncContactFieldsBatch(super.batchId, super.batchStepId);
			Database.executeBatch(runMe, super.batchSize);
		}
		else 
		{
			// TODO: Throw Application Exception
			return;
		}
	}
}