force-app/main/default/objects/SEL_Batch__c/SEL_Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <displayFormat>BAT{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEL_Batch__c/fields/SEL_BatchTemplate__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchTemplate__c</fullName>
    <label>Batch Template</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_Batch__c/fields/SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>SEL_Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SEL_BatchStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEL_Batch__c/fields/SPEN_AdqmLoadDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AdqmLoadDate__c</fullName>
    <description>This field is used by the ADQM Delta Sync process.</description>
    <inlineHelpText>The created date to process.</inlineHelpText>
    <label>ADQM Load Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/SEL_BatchStep__c.object-meta.xml
<CustomObject>
    <label>Batch Step</label>
    <nameField>
        <displayFormat>BAS{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_BatchId__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchId__c</fullName>
    <label>Batch</label>
    <referenceTo>SEL_Batch__c</referenceTo>
    <relationshipLabel>Batch Steps</relationshipLabel>
    <relationshipName>SEL_BatchSteps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchSize__c</fullName>
    <label>Batch Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_Class__c.field-meta.xml
<CustomField>
    <fullName>SEL_Class__c</fullName>
    <description>Batch class or identifier.</description>
    <label>Class</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_Sequence__c.field-meta.xml
<CustomField>
    <fullName>SEL_Sequence__c</fullName>
    <label>Sequence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/SPEN_PSR__c.object-meta.xml
<CustomObject>
    <description>PSR object has been set up to see all the PSR related information</description>
    <label>PSR</label>
    <nameField>
        <displayFormat>PSR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Contact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/SPEN_PSRStaging__c.object-meta.xml
<CustomObject>
    <description>Object for Staging Data</description>
    <label>PSR Staging</label>
    <nameField>
        <displayFormat>PST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSR Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Takes Premise Id.</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_PsrVulnerabilityTypeId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PsrVulnerabilityTypeId__c</fullName>
    <externalId>true</externalId>
    <label>PSR Vulnerability Type ID</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_SyncStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SyncStatus__c</fullName>
    <description>Checks the status of Sync</description>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/SPEN_VoiceAlert__c.object-meta.xml
<CustomObject>
    <label>Voice Alert</label>
    <nameField>
        <label>Voice Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voice Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/SEL_BatchStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Batch Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SPEN_SyncPSRFlagonContact_Test.cls
@isTest
public class SPEN_SyncPSRFlagonContact_Test {
    @IsTest
    private static void testSyncPSRFlagExecute()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user); 
        PermissionSet ps1 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_PSRAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps1.Id);
        PermissionSet ps2 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_ContactAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps2.Id);
        PermissionSet ps3 = [SELECT Id FROM PermissionSet WHERE Name = 'SEL_BatchFrameworkUser'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps3.Id);
        
        System.runAs(user)
        {
            List<Account> accRec = SPEN_TestDataFactory.createAccounts('Test',SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert accRec;
            Contact con= SPEN_TestDataFactory.createContacts(accRec[0].Id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            con.SPEN_CustomerID__c = 'Test123';
            insert con;
            List<SPEN_PSR__c> psralert=SPEN_TestDataFactory.createPSRrecord(SPEN_TestDataFactoryConstants.SINGLE_REC);
            psralert[0].SPEN_Contact__c=con.Id;
            insert psralert;
            
            List<SPEN_VoiceAlert__c> voicealert=SPEN_TestDataFactory.createVoiceAlertrecord(SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert voicealert;
            
            SEL_Batch__c selBatch =new SEL_Batch__c(SPEN_AdqmLoadDate__c = system.today()+1,SEL_BatchTemplate__c = 'ADQM Delta Sync');
            insert selBatch;
            
            SEL_BatchStep__c selBatchStep =new SEL_BatchStep__c(SEL_BatchId__c =selBatch.id,SEL_BatchSize__c=200,SEL_Sequence__c=1,
                                                                SEL_Status__c = SEL_BatchConstants.STATUS_COMPLETED,
                                                                SEL_Class__c = 'SPEN_SyncPSRFlagonContact'
                                                               );
            insert selBatchStep;
            Test.startTest();
            SPEN_PSRStaging__c stage= new SPEN_PSRStaging__c(SPEN_PremiseID__c = 'Test123',SPEN_PsrVulnerabilityTypeId__c = '123',
                                                             SPEN_SyncStatus__c = 'Successful');
            insert stage;
            SPEN_SyncPSRFlagonContact testA = new SPEN_SyncPSRFlagonContact();
            testA.batchId = selBatch.id;
            testA.batchStepId = selBatchStep.id;
            testA.isValid();
            testA.executeBatch();
            Database.QueryLocator ql = testA.start(null);
            testA.execute(null,new List<SPEN_PSRStaging__c>{stage});
            
            
            psralert[0].SPEN_Contact__c=null;    
            update psralert[0];
            Database.QueryLocator ql2 = testA.start(null);
            testA.execute(null,new List<SPEN_PSRStaging__c>{stage});
            //Assert.areEqual('Test123',SPEN_PremiseID__c,'PSRStaging premise id value');
            System.assertEquals('Test123',stage.SPEN_PremiseID__c,'PSRStaging premise id value');
            Test.stopTest();
        }
    }
}