force-app/main/default/objects/SEL_Batch__c/SEL_Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <displayFormat>BAT{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEL_Batch__c/fields/SEL_BatchTemplate__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchTemplate__c</fullName>
    <label>Batch Template</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_Batch__c/fields/SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>SEL_Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SEL_BatchStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEL_Batch__c/fields/SPEN_AdqmLoadDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AdqmLoadDate__c</fullName>
    <description>This field is used by the ADQM Delta Sync process.</description>
    <inlineHelpText>The created date to process.</inlineHelpText>
    <label>ADQM Load Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/SEL_BatchStep__c.object-meta.xml
<CustomObject>
    <label>Batch Step</label>
    <nameField>
        <displayFormat>BAS{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_BatchId__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchId__c</fullName>
    <label>Batch</label>
    <referenceTo>SEL_Batch__c</referenceTo>
    <relationshipLabel>Batch Steps</relationshipLabel>
    <relationshipName>SEL_BatchSteps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchSize__c</fullName>
    <label>Batch Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_Class__c.field-meta.xml
<CustomField>
    <fullName>SEL_Class__c</fullName>
    <description>Batch class or identifier.</description>
    <label>Class</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_Sequence__c.field-meta.xml
<CustomField>
    <fullName>SEL_Sequence__c</fullName>
    <label>Sequence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/fields/SPEN_Value__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/SPEN_ContactNumberEmailStaging__c.object-meta.xml
<CustomObject>
    <description>SPEN_ContactNumberEmailStaging will be staging for contact numbers and Email</description>
    <label>Contact Number Email Staging</label>
    <nameField>
        <displayFormat>CNE-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Number Email Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/fields/SPEN_NumberOrEmail__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NumberOrEmail__c</fullName>
    <label>NumberOrEmail</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/fields/SPEN_SyncStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SyncStatus__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Indicates if the change value is synced to the contact record.</description>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/SPEN_ContactStaging__c.object-meta.xml
<CustomObject>
    <description>Contact Staging</description>
    <label>Contact Staging</label>
    <nameField>
        <displayFormat>CSG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_AdqmAction__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AdqmAction__c</fullName>
    <label>ADQM Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_AdqmLastModifiedDateTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AdqmLastModifiedDateTime__c</fullName>
    <label>ADQM Last Modified Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_AdqmSource__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AdqmSource__c</fullName>
    <label>ADQM Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Other Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_ContactType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ContactType__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>PSR Contact (Primary)</fullName>
            </value>
            <value>
                <fullName>Alternative Contact</fullName>
            </value>
            <value>
                <fullName>Site Contact</fullName>
            </value>
            <value>
                <fullName>Premise Owner</fullName>
            </value>
            <value>
                <fullName>PSR Contact (Alternative)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_FirstName__c.field-meta.xml
<CustomField>
    <fullName>SPEN_FirstName__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_Initials__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Initials__c</fullName>
    <label>Initials</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_LastName__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LastName__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_OtherContactId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_OtherContactId__c</fullName>
    <label>Other Contact ID</label>
    <length>38</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_PremiseId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseId__c</fullName>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_Salutation__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Salutation__c</fullName>
    <label>Salutation</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_SyncStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SyncStatus__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Unique SPEN identifier for a premise</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <description>Select type from dropdown list.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Unmetered Supply</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Generators- HV/LV</fullName>
                <isActive>false</isActive>
                <label>Generators- HV/LV</label>
            </value>
            <value>
                <fullName>Generators- Renewable</fullName>
                <isActive>false</isActive>
                <label>Generators- Renewable</label>
            </value>
            <value>
                <fullName>Generators- Traditional</fullName>
                <isActive>false</isActive>
                <label>Generators- Traditional</label>
            </value>
            <value>
                <fullName>Large Business</fullName>
                <isActive>false</isActive>
                <label>Large Business</label>
            </value>
            <value>
                <fullName>Small Business</fullName>
                <isActive>false</isActive>
                <label>Small Business</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/SEL_BatchStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Batch Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SPEN_SyncContactsBatchTEST.cls
@IsTest
public class SPEN_SyncContactsBatchTEST {
    @IsTest
     private static void testBatchexecute()
    {	
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user); 
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_StagingCRU'];
		insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps.Id); 
        PermissionSet ps1 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_ContactAccessCRU'];
		insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps1.Id); 
        PermissionSet ps3 = [SELECT Id FROM PermissionSet WHERE Name = 'SEL_BatchFrameworkUser'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps3.Id);
        PermissionSet ps9 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_PremiseAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps9.Id);
        System.runAs(user)
        {   
           
            List<Account> accRec = SPEN_TestDataFactory.createAccounts('Test',SPEN_TestDataFactoryConstants.SINGLE_REC);
            //accRec[0].SPEN_ExternalID__c = 'Prem_1';
        	insert accRec;
        	Contact con= SPEN_TestDataFactory.createContacts(accRec[0].Id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            con.SPENAdqmLastSyncDateTime__c=system.now()-1;
            con.SPEN_CustomerID__c = 'Con00002';
        	insert con;
            List<SPEN_Premise__c> lstPremise = SPEN_TestDataFactory.createListOfPremise(1);
            lstPremise[0].SPEN_PremiseID__c = 'Prem_12345';
            insert lstPremise;
            
            List<SPEN_ContactStaging__c> conListInsert=SPEN_TestDataFactory.createContactStagingrecord(SPEN_TestDataFactoryConstants.SINGLE_REC);
            conListInsert[0].SPEN_ExternalId__c='Con00001';
            conListInsert[0].SPEN_AdqmAction__c='New';
            conListInsert[0].SPEN_SyncStatus__c='Not Started';
            conListInsert[0].SPEN_FirstName__c = 'Greg';
            conListInsert[0].SPEN_LastName__c = 'White';
       		conListInsert[0].SPEN_PremiseId__c = 'Prem_12345';
            conListInsert[0].SPEN_Salutation__c ='Mr';
            conListInsert[0].SPEN_Initials__c = 'GW';
            conListInsert[0].SPEN_ContactType__c = 'Customer';
            
            conListInsert[0].SPEN_AdqmLastModifiedDateTime__c = System.now();
            insert conListInsert;
            
                
            List<SPEN_ContactStaging__c> conListUpdate=SPEN_TestDataFactory.createContactStagingrecord(SPEN_TestDataFactoryConstants.SINGLE_REC);
            conListUpdate[0].SPEN_ExternalId__c='Con00003';
            conListUpdate[0].SPEN_AdqmAction__c='Update';
            conListUpdate[0].SPEN_FirstName__c = 'Rob';
            conListUpdate[0].SPEN_LastName__c = 'White';
            conListUpdate[0].SPEN_SyncStatus__c='Not Started';
            conListUpdate[0].SPEN_AdqmLastModifiedDateTime__c = System.now();
            conListUpdate[0].SPEN_Salutation__c = 'Mrs';
             conListUpdate[0].SPEN_Initials__c = 'RW';
            conListInsert[0].SPEN_PremiseId__c = 'Prem_12345';
            
        	insert conListUpdate;
            
            List<SPEN_ContactStaging__c> conListDelete=SPEN_TestDataFactory.createContactStagingrecord(SPEN_TestDataFactoryConstants.SINGLE_REC);
            conListDelete[0].SPEN_AdqmAction__c='Delete';
            conListDelete[0].SPEN_SyncStatus__c='Not Started';
            conListDelete[0].SPEN_FirstName__c = 'Greg';
            conListDelete[0].SPEN_LastName__c = 'White';
            conListDelete[0].SPEN_ExternalId__c='Con00002';
            insert conListDelete;
            
            List<SPEN_ContactNumberEmailStaging__c> contactEmailStageList = new List<SPEN_ContactNumberEmailStaging__c>();
			SPEN_ContactNumberEmailStaging__c emailStage = new SPEN_ContactNumberEmailStaging__c();
            emailStage.SPEN_ExternalId__c = 'Con00002';
            emailStage.SPEN_NumberOrEmail__c = '8888334455';
            emailStage.SPEN_Type__c = 'Mobile';
             emailStage.SPEN_SyncStatus__c = 'Not Started';
            contactEmailStageList.add(emailStage);
            
            SPEN_ContactNumberEmailStaging__c emailStage2 = new SPEN_ContactNumberEmailStaging__c();
            emailStage2.SPEN_ExternalId__c = 'Con00002';
            emailStage2.SPEN_NumberOrEmail__c = 'asm@accenture.com';
            emailStage2.SPEN_Type__c = 'Email';
             emailStage2.SPEN_SyncStatus__c = 'Not Started';
            contactEmailStageList.add(emailStage2);
            
            SPEN_ContactNumberEmailStaging__c emailStage3 = new SPEN_ContactNumberEmailStaging__c();
            emailStage3.SPEN_ExternalId__c = 'Con00002';
            emailStage3.SPEN_NumberOrEmail__c = '8888334455';
            emailStage3.SPEN_Type__c = 'Home';
            emailStage3.SPEN_SyncStatus__c = 'Not Started';
            contactEmailStageList.add(emailStage3);
            
            SPEN_ContactNumberEmailStaging__c emailStage4 = new SPEN_ContactNumberEmailStaging__c();
            emailStage4.SPEN_ExternalId__c = 'Con00002';
            emailStage4.SPEN_NumberOrEmail__c = '8888334455';
            emailStage4.SPEN_Type__c = 'Other';
             emailStage4.SPEN_SyncStatus__c = 'Not Started';
            contactEmailStageList.add(emailStage4);
            
            insert contactEmailStageList;
            
            
           	SPEN_ConfigurableSettings__c setting = SPEN_TestDataFactory.createConfigSetting(1,'RelatedMobileEmailStagingQuery');
            setting.SPEN_Value__c = 'SELECT Id,SPEN_ExternalId__c,SPEN_NumberOrEmail__c,SPEN_Type__c FROM SPEN_ContactNumberEmailStaging__c WHERE Createddate = Today';
            insert setting;
            
            /*List<SPEN_ContactStaging__c> conList3=SPEN_TestDataFactory.createContactStagingrecord(SPEN_TestDataFactoryConstants.SINGLE_REC);
            conList3[0].SPEN_ExternalId__c='1234567';
            insert conList3;
            conList3[0].SPEN_AdqmAction__c='Delete';
        	//conList3[0].SPEN_AdqmSource__c='Other Contact';
        	conList3[0].SPEN_SyncStatus__c='Failed';
            conList3[0].SPEN_OtherContactId__c='SB__001';
            update conList3;*/
            
            SEL_Batch__c selBatch =new SEL_Batch__c(SPEN_AdqmLoadDate__c = system.today()+1,SEL_BatchTemplate__c = 'ADQM Delta Sync');
            insert selBatch;
            
            SEL_BatchStep__c selBatchStep =new SEL_BatchStep__c(SEL_BatchId__c =selBatch.id,SEL_BatchSize__c=200,SEL_Sequence__c=1,
                                                               SEL_Status__c = SEL_BatchConstants.STATUS_COMPLETED,
                                                                SEL_Class__c = 'SPEN_SyncContactsBatch'
                                                               );
            insert selBatchStep;
            Test.startTest();
            
            SPEN_SyncContactsBatch testA = new SPEN_SyncContactsBatch();
            testA.batchId = selBatch.id;
			testA.batchStepId = selBatchStep.id;
            testA.isValid();
            testA.executeBatch();
            Database.QueryLocator ql = testA.start(null);
            testA.execute(null,conListInsert);
            
           //Database.QueryLocator ql2 = testA.start(null);
            //testA.execute(null,conListUpdate);
            
            Database.QueryLocator ql3 = testA.start(null);
            testA.execute(null,conListDelete);
            System.assertEquals('Other',emailStage4.SPEN_Type__c,'type value');
            Test.stopTest();
        }
    }
}