force-app/main/default/objects/SEL_Batch__c/SEL_Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <displayFormat>BAT{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEL_Batch__c/fields/SEL_BatchTemplate__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchTemplate__c</fullName>
    <label>Batch Template</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_Batch__c/fields/SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>SEL_Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SEL_BatchStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEL_Batch__c/fields/SPEN_AdqmLoadDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AdqmLoadDate__c</fullName>
    <description>This field is used by the ADQM Delta Sync process.</description>
    <inlineHelpText>The created date to process.</inlineHelpText>
    <label>ADQM Load Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/SEL_BatchStep__c.object-meta.xml
<CustomObject>
    <label>Batch Step</label>
    <nameField>
        <displayFormat>BAS{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_BatchId__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchId__c</fullName>
    <label>Batch</label>
    <referenceTo>SEL_Batch__c</referenceTo>
    <relationshipLabel>Batch Steps</relationshipLabel>
    <relationshipName>SEL_BatchSteps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchSize__c</fullName>
    <label>Batch Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_Sequence__c.field-meta.xml
<CustomField>
    <fullName>SEL_Sequence__c</fullName>
    <label>Sequence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/SEL_BatchStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Batch Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SEL_BatchesSelector.cls
/*-------------------------------------------------------------------------------------------------
DESCRIPTION	:	Selectore layer of Batch__c custom object.
AUTHOR		:	Macjules Sevilla
LIBRARY		:	Salesforce Enterprise Library - Batch Framework
VERSION		:	1.0

HISTORY		:
Date			Author				Comment
AUG-23-2021		Macjules Sevilla	Initial version
FEB-13-2023		Macjules Sevilla	Added SPEN_AdqmLoadDate__c field to the selectByIds method
-------------------------------------------------------------------------------------------------*/
public inherited sharing class SEL_BatchesSelector 
{
	// DESCRIPTION
	// Returns a list of Batch__c records based on the IDs parameters.
	public List<SEL_Batch__c> selectByIds(Set<Id> ids) 
	{
		List<SEL_Batch__c> result = new List<SEL_Batch__c>();

		if(ids != null && !ids.isEmpty()) 
		{ 
			result = [	
				SELECT	Id, SEL_Status__c, SPEN_AdqmLoadDate__c
				FROM	SEL_Batch__c
				WHERE	Id IN :ids
				WITH	SECURITY_ENFORCED
			];
		}

		return result;
	}

	// DESCRIPTION
	// Returns a list of Batch__c records based on the IDs parameters
	// along with their respective child BatchStep__c records based on status. 
	public List<SEL_Batch__c> selectByIdsByStatuses(Set<Id> ids, Set<String> statuses) 
	{
		List<SEL_Batch__c> result = new List<SEL_Batch__c>();

		if(ids != null && statuses != null && !ids.isEmpty() && !statuses.isEmpty()) 
		{ 
			result = [
				SELECT	Id, (SELECT Id, SEL_BatchId__c, SEL_BatchSize__c, SEL_Sequence__c, SEL_Status__c FROM SEL_BatchSteps__r WHERE SEL_Status__c IN :statuses ORDER BY SEL_Sequence__c)
				FROM	SEL_Batch__c
				WHERE	Id IN :ids 
				WITH	SECURITY_ENFORCED
			];	
		}

		return result;
	}
    public List<SEL_Batch__c> getTodaysBatchRecord()
	{
		List<SEL_Batch__c> ExistingBatch= new List<SEL_Batch__c>();
        ExistingBatch=	[
                    SELECT Id, SEL_Status__c
                    FROM SEL_Batch__c 
                    WHERE  CreatedDate = Today  AND
                    SEL_BatchTemplate__c = 'ADQM Delta Sync'
                    LIMIT 1
                    ];			
		return ExistingBatch;
	}
}