force-app/main/default/objects/SEL_Batch__c/SEL_Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <displayFormat>BAT{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEL_Batch__c/fields/SEL_BatchTemplate__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchTemplate__c</fullName>
    <label>Batch Template</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_Batch__c/fields/SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>SEL_Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SEL_BatchStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEL_Batch__c/fields/SPEN_AdqmLoadDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AdqmLoadDate__c</fullName>
    <description>This field is used by the ADQM Delta Sync process.</description>
    <inlineHelpText>The created date to process.</inlineHelpText>
    <label>ADQM Load Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_AsyncBatch__e/SPEN_AsyncBatch__e.object-meta.xml
<CustomObject>
    <description>Run batch processes asynchronously.</description>
    <label>Async Batch Platform Event</label>
    <pluralLabel>Async Batch Platform Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/SPEN_AsyncBatch__e/fields/SPEN_Action__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Action__c</fullName>
    <description>Informs the platform event which batch process to trigger. Possible values include: [1] Start ADQM Sync Process</description>
    <label>Action</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/SEL_BatchStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Batch Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SPEN_AsyncBatches.cls
/*-----------------------------------------------------------------------------
DESCRIPTION	:	Domain class to trigger Async Batch Processes.
AUTHOR		:	Macjules Sevilla
LIBRARY		:	SPEN
VERSION		:	1.0

HISTORY		:
Date			Author				Comment
FEB-13-2023		Macjules Sevilla	Initial version
-----------------------------------------------------------------------------*/
public with sharing class SPEN_AsyncBatches 
{
	@TestVisible
	private Boolean allowBatchDML = true;

	/**
	 * @description CONSTANTS
	 */
	public final static String ACTION_ADQM = 'Start ADQM Sync Process';

	
	/**
	 * @description BUSINESS LOGIC VARIABLES
	 */
	@TestVisible
	List<SEL_Batch__c> batches = new List<SEL_Batch__c>();

	/**
	 * @description Create Batch records. 
	 * 
	 * IMPORTANT: While this method was written to process bulkified requests; 
	 * 			  it is recommended to keep the batch size low to avoid performance issues.
	 */
    
	public void afterInsert(List<SPEN_AsyncBatch__e> requests)
	{
        List<SEL_Batch__c> lstBatch = new SEL_BatchesSelector().getTodaysBatchRecord();
        SEL_Batch__c existingBatch;
        if(lstBatch != null && !lstBatch.isEmpty())
            existingBatch = lstBatch[0];
        if(requests != null && !requests.isEmpty())
		{
			for(SPEN_AsyncBatch__e r : requests)
			{
				if(r?.SPEN_Action__c.equalsIgnoreCase(SPEN_AsyncBatches.ACTION_ADQM))
				{
                    if(existingBatch == null)
                    {
                        SEL_Batch__c b = new SEL_Batch__c();
                        b.SEL_BatchTemplate__c = SEL_BatchConstants.BATCH_TEMPLATE_ADQM_DELTA_SYNC;
                        b.SEL_Status__c = SEL_BatchConstants.STATUS_NOT_STARTED;
                        b.SPEN_AdqmLoadDate__c = System.today();
                        batches.add(b);
                    }
                    else {
                        existingBatch.SEL_Status__c = SEL_BatchConstants.STATUS_PROCESSING;
                    }
				}
			}
		}

		// RULE
		// Create batch records only if its not empty
		if(!batches.isEmpty() && this.allowBatchDML && Schema.sObjectType.SEL_Batch__c.isCreateable())
		{
			insert batches;
		}
        if(existingBatch != null)
        {
            update existingBatch;
        }
	}
}