force-app/main/default/objects/SEL_Batch__c/SEL_Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <displayFormat>BAT{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEL_Batch__c/fields/SEL_BatchTemplate__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchTemplate__c</fullName>
    <label>Batch Template</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_Batch__c/fields/SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>SEL_Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SEL_BatchStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/SEL_BatchStep__c.object-meta.xml
<CustomObject>
    <label>Batch Step</label>
    <nameField>
        <displayFormat>BAS{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_BatchId__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchId__c</fullName>
    <label>Batch</label>
    <referenceTo>SEL_Batch__c</referenceTo>
    <relationshipLabel>Batch Steps</relationshipLabel>
    <relationshipName>SEL_BatchSteps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>SEL_BatchSize__c</fullName>
    <label>Batch Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_Class__c.field-meta.xml
<CustomField>
    <fullName>SEL_Class__c</fullName>
    <description>Batch class or identifier.</description>
    <label>Class</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEL_BatchStep__c/fields/SEL_Sequence__c.field-meta.xml
<CustomField>
    <fullName>SEL_Sequence__c</fullName>
    <label>Sequence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/SEL_BatchStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Batch Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SEL_BatchStepBase_TEST.cls
/*-----------------------------------------------------------------------------
DESCRIPTION	:	Test class of the BatchStepBase abstract class.
AUTHOR		:	Macjules Sevilla
LIBRARY		:	Salesforce Enterprise Library - Batch Framework
VERSION		:	1.0

Time (MS)		Method
30  			executeBatch
14  			isValid
660 			finishBatch
-----------------------------------------------------------------------------*/
@IsTest
public without sharing class SEL_BatchStepBase_TEST 
{
	// TEST CLASS
	private class SEL_BatchStepTest extends SEL_BatchStepBase {}

	// CONSTANTS
	private static final String BATCH_TEMPLATE_A = 'BatchStepBase_Test_A'; 

	@TestSetup
	static void makeData()
	{
		SEL_Batch__c batch1 = new SEL_Batch__c( SEL_BatchTemplate__c = SEL_BatchStepBase_Test.BATCH_TEMPLATE_A );	
		insert batch1;
		
		List<SEL_BatchStep__c> steps = new List<SEL_BatchStep__c>();

		SEL_BatchStep__c step1 = new SEL_BatchStep__c();
		step1.SEL_BatchId__c = batch1.Id;
		step1.SEL_BatchSize__c = 200;
		step1.SEL_Class__c = 'Class1';
		step1.SEL_Sequence__c = 1;
		step1.SEL_Status__c = SEL_BatchConstants.STATUS_NOT_STARTED;
		steps.add(step1);

		SEL_BatchStep__c step2 = new SEL_BatchStep__c();
		step2.SEL_BatchId__c = batch1.Id;
		step2.SEL_BatchSize__c = 200;
		step2.SEL_Class__c = 'Class2';
		step2.SEL_Sequence__c = 1;
		step2.SEL_Status__c = SEL_BatchConstants.STATUS_NOT_STARTED;
		steps.add(step2);

		insert steps;
	}

	@IsTest
	private static void executeBatch() 
	{
		try 
		{
			// TEST
			new SEL_BatchStepTest().executeBatch();
		} 
		catch (Exception ex) 
		{
			// ASSERT
			System.assert(ex.getMessage().equalsIgnoreCase('Execute batch must be overridden.'), 'Exception must be thrown.');
		}
	}

	@IsTest
	private static void isValid()
	{
		// ERROR SCENARIO
		SEL_BatchStepTest testA = new SEL_BatchStepTest();
		System.assert(testA.isValid() == false, 'Not passing BatchId or BatchStepId will result to invalid state.');

		// NORMAL SCENARIO
		testA.batchId = UserInfo.getUserId();
		testA.batchStepId = UserInfo.getUserId();
		System.assert(testA.isValid() == true, 'Setting both parameters must result to a valid state.');
	}

	@IsTest
	private static void finishBatch()
	{
		Test.startTest();
		Id profileId = [SELECT Id FROM Profile WHERE Name =: 'System Administrator' LIMIT 1].Id;
        User user = new User(	FirstName= 'Macjules', 
								LastName = 'Sevilla', 
								Email = 'msevilla@spenergynetworks.co.uk.test',
								Username = 'Sevilla' + System.currentTimeMillis() + '@spenergynetworks.co.uk.test',
								Alias = 'macj',
								ProfileId =  profileId,
								IsActive = true,
								TimeZoneSidKey = 'America/Los_Angeles',
	                            EmailEncodingKey = 'UTF-8',
                            	LanguageLocaleKey = 'en_US',
								LocaleSidKey = 'en_US');
        Database.insert(user);
        PermissionSet ps1 = [SELECT Id FROM PermissionSet WHERE Name = 'SEL_BatchFrameworkUser'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps1.Id);
       System.runAs(user)
       {
		// DATA
		SEL_BatchStep__c child1 = [SELECT Id, SEL_BatchId__c FROM SEL_BatchStep__c WHERE SEL_BatchId__r.SEL_BatchTemplate__c =: SEL_BatchStepBase_Test.BATCH_TEMPLATE_A LIMIT 1];

		// TEST 1
		// Scenario with successful batch run
		SEL_BatchStepTest stepRun = new SEL_BatchStepTest();
		stepRun.jobCompletedDate = Datetime.now();
		stepRun.jobExtendedStatus = 'Completed'; 
		stepRun.jobFailures = 0;
		stepRun.jobStatus = 'Completed';
		stepRun.finishBatch(null, child1.SEL_BatchId__c, child1.Id);

		// ASSERT 1
		SEL_Batch__c parent1 = [SELECT Id, SEL_Status__c FROM SEL_Batch__c WHERE SEL_BatchTemplate__c =: SEL_BatchStepBase_Test.BATCH_TEMPLATE_A LIMIT 1];
		System.assert(parent1.SEL_Status__c.equalsIgnoreCase(SEL_BatchConstants.STATUS_PROCESSING), 'Parent Batch__c must be set to processing.');

		// TEST 2
		// Scenario with failed batch run
		stepRun.jobExtendedStatus = 'Failed'; 
		stepRun.jobFailures = 1;
		stepRun.jobStatus = 'Failed';
		stepRun.finishBatch(null, child1.SEL_BatchId__c, child1.Id);

		// ASSERT 2
		parent1 = [SELECT Id, SEL_Status__c FROM SEL_Batch__c WHERE SEL_BatchTemplate__c =: SEL_BatchStepBase_Test.BATCH_TEMPLATE_A LIMIT 1];
		System.assert(parent1.SEL_Status__c.equalsIgnoreCase(SEL_BatchConstants.STATUS_FAILED), 'Parent Batch__c must be set to failed.');

		Test.stopTest();
       }
	}
}