force-app/main/default/objects/SPEN_Case_Tracker__c/SPEN_Case_Tracker__c.object-meta.xml
<CustomObject>
    <label>Case Tracker</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Case Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Case_Tracker__c/fields/Case_Tracker_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Tracker_Type__c</fullName>
    <label>Case Tracker Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case Owner Update</fullName>
                <default>true</default>
                <label>Case Owner Update</label>
            </value>
            <value>
                <fullName>Case Status Update</fullName>
            </value>
            <value>
                <fullName>Case SLA Update</fullName>
            </value>
            <value>
                <fullName>Case Routing Outcome Update</fullName>
            </value>
            <value>
                <fullName>3PD Accepted &gt; Closed</fullName>
            </value>
            <value>
                <fullName>Partner Account Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Case_Tracker__c/fields/SPEN_AgentHandlingTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AgentHandlingTime__c</fullName>
    <inlineHelpText>Days : Hours : Minutes : Seconds</inlineHelpText>
    <label>Agent Handling Time</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Case_Tracker__c/fields/SPEN_AgentHandlingTimeInMinutes__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AgentHandlingTimeInMinutes__c</fullName>
    <label>Agent Handling Time (In Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_Case_Tracker__c/fields/SPEN_CaseOwner__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CaseOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Who has made this change</inlineHelpText>
    <label>Updated By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Case_Trackers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Case_Tracker__c/fields/SPEN_EndTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EndTime__c</fullName>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_Case_Tracker__c/fields/SPEN_NewValue__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NewValue__c</fullName>
    <label>New Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Case_Tracker__c/fields/SPEN_OwnerAssignmentType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_OwnerAssignmentType__c</fullName>
    <description>Field to differentiate if the case owner assignment is via manual operation or automated process.</description>
    <label>Owner Assignment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Automated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Case_Tracker__c/fields/SPEN_ParentCase__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ParentCase__c</fullName>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Trackers</relationshipLabel>
    <relationshipName>Case_Trackers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_Case_Tracker__c/fields/SPEN_PreviousValue__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PreviousValue__c</fullName>
    <label>Previous Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Case_Tracker__c/fields/SPEN_StartTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_StartTime__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SPEN_AgentWorkTriggerHandler.cls
/***************************************************************************
* @Author:      Kiranmayi Garimella
* @Date:        19/12/2023
* @UserStory:   
* @Description: To update Case and create CaseTracker Record on AgentWork Record Insertion
*****************************************************************************/

public class SPEN_AgentWorkTriggerHandler {
    Public static Id recordTypeId3PD = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_ThirdPartyDamage').getRecordTypeId();
    Public static Id recordTypeIdQuery = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_Query').getRecordTypeId();
    Public static Id recordTypeIdSW = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_Streetworks').getRecordTypeId();
    Public static Id recordTypeIdNRSWA = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_NRSWA').getRecordTypeId();
    Public static Id recordTypeIdGE = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_GeneralEnquiries').getRecordTypeId();
     public static Set<Id> getCJrecordtypes(){
        Set<Id> setRecordTypeId = new Set<Id>();
        setRecordTypeId.add(recordTypeId3PD);
        setRecordTypeId.add(recordTypeIdQuery);
        setRecordTypeId.add(recordTypeIdSW);
        setRecordTypeId.add(recordTypeIdNRSWA);
        setRecordTypeId.add(recordTypeIdGE);
        return setRecordTypeId;
    }
    public static void createCaseTracker(List<AgentWork> newAgentWorkList)
        
    {
        Set<Id> setRecType = getCJrecordtypes();
        List<Case> casesToUpdate = new List<Case>();
        List<SPEN_Case_Tracker__c> caseTrackersToInsert = new List<SPEN_Case_Tracker__c>();
        Set<Id> setQueueId = new Set<Id>();
        Set<Id> setOwnerID = new Set<Id>();
        Set<Id> setCaseID = new Set<Id>();
        List<Case> listCase = new List<Case>();
        Map<ID, String> mapQueueId2Name = new Map<Id,String>();
        Map<ID, String> mapUserId2Name = new Map<Id,String>();
        Map<ID,Case> mapCaseId2Case = new Map<Id, Case>();
        List<Case> listCaseUpdate = new List<Case>();
        
        for(AgentWork aw : newAgentWorkList){
            setQueueId.add(aw.OriginalQueueId);
            setOwnerID.add(aw.OwnerId);
            setCaseID.add(aw.WorkItemId);
        }
        if(!setCaseID.isEmpty())
        {
            mapCaseId2Case = SPEN_CaseSelector.getCaseForAgentWork(setCaseID,setRecType);
        }
        if(!setQueueId.isEmpty())
        {
            mapQueueId2Name = SPEN_CaseSelector.getQueueName(setQueueId);
        }
        if(!setOwnerID.isEmpty())
        {
            mapUserId2Name = SPEN_CaseSelector.getUserName(setOwnerID);
        }
        try{
             // create Case Tracker
            for(AgentWork aw : newAgentWorkList){
                if(aw.status.equalsIgnoreCase('Opened')){
                    Case parentCase = mapCaseId2Case.get(aw.WorkItemId);
                    SPEN_Case_Tracker__c ctRec = new SPEN_Case_Tracker__c();
                    ctRec.SPEN_StartTime__c = parentCase.SPEN_CaseAssignmentTime__c;
                    ctRec.SPEN_ParentCase__c = aw.WorkItemId;
                    ctRec.SPEN_EndTime__c = system.now();
                    ctRec.Case_Tracker_Type__c = 'Case Owner Update';
                    ctRec.SPEN_NewValue__c = mapUserId2Name.get(aw.OwnerId);
                    ctRec.SPEN_PreviousValue__c = mapQueueId2Name.get(aw.OriginalQueueId);
                    ctRec.SPEN_CaseOwner__c = UserInfo.getUserId();
					ctRec.SPEN_OwnerAssignmentType__c = 'Automated';//CRMD-10516
                   
                    if(ctRec.SPEN_StartTime__c != null && ctRec.SPEN_EndTime__c != null)
                    {
                        ctRec.SPEN_AgentHandlingTimeInMinutes__c = SPEN_BusinessDaysCalculationUtil.getAgentHandlingTimeinMinutes(ctRec.SPEN_StartTime__c, ctRec.SPEN_EndTime__c);
                        ctRec.SPEN_AgentHandlingTime__c = SPEN_BusinessDaysCalculationUtil.calculateTimeDiffinString(ctRec.SPEN_StartTime__c, ctRec.SPEN_EndTime__c);
                    }
                    caseTrackersToInsert.add(ctRec); 
                    parentCase.SPEN_CaseAssignmentTime__c = system.now();
                    listCaseUpdate.add(parentCase);
                }
                
            }
            insert caseTrackersToInsert; 
            if(!listCaseUpdate.isEmpty())
                update listCaseUpdate;
        }catch(exception exc){
            system.debug('Exception occured in SPEN_AgentWorkTriggerHandler '+ exc.getMessage());
        }
       
    }
    public static void beforeInsertDummy(){
        system.debug('Test coverage');
    }
}