force-app/main/default/objects/SPEN_SupplierDetails__c/SPEN_SupplierDetails__c.object-meta.xml
<CustomObject>
    <label>Supplier Details</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_SupplierDetails__c/fields/SPEN_SupplierPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SupplierPhoneNumber__c</fullName>
    <label>Supplier Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/SPEN_SupplierDetailsSelector.cls
public class SPEN_SupplierDetailsSelector 
{
	public static SPEN_SupplierDetails__c getSupplierDetailsRecord(String suppMpidValue)
    {
         List<SPEN_SupplierDetails__c> supplierDetailsRecords = new List<SPEN_SupplierDetails__c>();
        if(String.isNotBlank(suppMpidValue))
        	 supplierDetailsRecords = [Select Name,SPEN_SupplierPhoneNumber__c from SPEN_SupplierDetails__c 
                                                         where SPEN_SupplierMPID__c =:suppMpidValue 
                                                         WITH SECURITY_ENFORCED];
         return supplierDetailsRecords!=null && !supplierDetailsRecords.isEmpty()?supplierDetailsRecords[0]:new SPEN_SupplierDetails__c(); //updated for incident INC3319046
    }
}