force-app/main/default/objects/SPEN_ImpactedPremise__c/SPEN_ImpactedPremise__c.object-meta.xml
<CustomObject>
    <label>Impacted Premise</label>
    <nameField>
        <displayFormat>IP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impacted Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_PremiseId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseId__c</fullName>
    <externalId>true</externalId>
    <label>PremiseId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_RelatedIncident__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelatedIncident__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Impacted Premises</relationshipLabel>
    <relationshipName>Impacted_Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Restored</fullName>
            </value>
            <value>
                <fullName>Not Restored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/SPEN_IntegrationRequest__c.object-meta.xml
<CustomObject>
    <description>Integration Request object has been set up to use for IVR Integration.</description>
    <label>Integration Request</label>
    <nameField>
        <label>Integration Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_IntegrationRequestServiceClass__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IntegrationRequestServiceClass__c</fullName>
    <label>Integration Request Service Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Records__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Records__c</fullName>
    <label>Records</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_RelatedVoiceCall__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelatedVoiceCall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CRMD-8331</description>
    <label>Voice Call</label>
    <referenceTo>VoiceCall</referenceTo>
    <relationshipLabel>Integration Requests</relationshipLabel>
    <relationshipName>Integration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_ActiveIncidentCheck.cls
public class SPEN_ActiveIncidentCheck {
    
    Public static void fetchIncidentRecValue(Set<Id> recId){
        ID IncidentID;
        String voicePrmiseExternalID;
        Map<string,List<VoiceCall>> returnMapRec = new Map<string,List<VoiceCall>>();
        Map<String,VoiceCall> premiseIdVsVoiceCallMap = new Map<String,VoiceCall>();
        Map<id,VoiceCall> vcIdVSVc = new Map<id,VoiceCall>();
        List<VoiceCall> voicecallRec = [Select id,SPEN_RelatedIncident__c,SPEN_VoicecallPremise__c,SPEN_VoicecallPremise__r.SPEN_PremiseID__c from VoiceCall where id IN: recId];
        system.debug('VoicecallRec**' + voicecallRec);
        List<VoiceCall> finalVoicecallRecList =  new List<VoiceCall>();
        List<SPEN_IntegrationRequest__c> intReqList =  new List<SPEN_IntegrationRequest__c>();
        Set<String> premiseExterIdSet = new Set<String>();
        for(VoiceCall vc : voicecallRec){
            if(vc.SPEN_VoicecallPremise__c != NULL){
                voicePrmiseExternalID = vc.SPEN_VoicecallPremise__r.SPEN_PremiseID__c;
                premiseIdVsVoiceCallMap.put(voicePrmiseExternalID,vc);
                premiseExterIdSet.add(voicePrmiseExternalID);
            }
            
        }
        if (premiseExterIdSet != null && premiseExterIdSet.size()>0)
        {
            List<SPEN_ImpactedPremise__c> ImpPremiseRec = [Select Id,SPEN_RelatedIncident__c,SPEN_PremiseId__c,SPEN_RelatedIncident__r.SPEN_IncidentStatus__c from SPEN_ImpactedPremise__c where SPEN_PremiseId__c IN: premiseExterIdSet ORDER BY SPEN_RelatedIncident__r.CreatedDate DESC];
            system.debug('ImpPremiseRec**' + ImpPremiseRec);
            
            for(SPEN_ImpactedPremise__c impPrm : ImpPremiseRec){
                VoiceCall vcRec =  new VoiceCall();
                if(impPrm.SPEN_RelatedIncident__c != NULL)
                {
                   if(!vcIdVSVc.containskey(premiseIdVsVoiceCallMap.get(impPrm.SPEN_PremiseId__c).id) && (impPrm.SPEN_RelatedIncident__r.SPEN_IncidentStatus__c == 'Awaiting' || impPrm.SPEN_RelatedIncident__r.SPEN_IncidentStatus__c == 'In Progress' ||
                     impPrm.SPEN_RelatedIncident__r.SPEN_IncidentStatus__c == 'On Site')){
                        if(premiseIdVsVoiceCallMap != null && premiseIdVsVoiceCallMap.containsKey(impPrm.SPEN_PremiseId__c)){
                            vcRec = premiseIdVsVoiceCallMap.get(impPrm.SPEN_PremiseId__c);
                            vcRec.SPEN_RelatedIncident__c = impPrm.SPEN_RelatedIncident__c;
                        }
                        finalVoicecallRecList.add(vcRec);
                         vcIdVSVc.put(vcRec.id,vcRec);
                    }
                }
                else{
                    if(premiseIdVsVoiceCallMap != null && premiseIdVsVoiceCallMap.containsKey(impPrm.SPEN_PremiseId__c)){
                        vcRec = premiseIdVsVoiceCallMap.get(impPrm.SPEN_PremiseId__c);
                    }
                    
                    SPEN_IntegrationRequest__c IntegrationRequestRecordCreation = new SPEN_IntegrationRequest__c();
                    IntegrationRequestRecordCreation.SPEN_Status__c = 'Processing';
                    IntegrationRequestRecordCreation.SPEN_Records__c = VoicePrmiseExternalID;
                    IntegrationRequestRecordCreation.SPEN_IntegrationRequestServiceClass__c = 'SPEN_ActiveIncidentGetPremiseService';
                    IntegrationRequestRecordCreation.SPEN_RelatedVoiceCall__c = vcRec.id;
                    intReqList.add(IntegrationRequestRecordCreation);
                    system.debug('intReqList**' + intReqList);              
                }
            }
            
        } 
        system.debug('finalVoicecallRecList**' + finalVoicecallRecList);
        if(finalVoicecallRecList != null && finalVoicecallRecList.size()>0){
            update finalVoicecallRecList;// 8331 Enh changes
        }
        if(intReqList != null && intReqList.size()>0){
            insert intReqList;// 8331 Enh changes
        }
    }
    
}