force-app/main/default/objects/SPEN_Condition__c/SPEN_Condition__c.object-meta.xml
<CustomObject>
    <description>This object is created to capture condition information and send it for SAP sync</description>
    <label>Condition</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Condition</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_LandInterest__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LandInterest__c</fullName>
    <label>Land Right</label>
    <referenceTo>SPEN_Land_Interest__c</referenceTo>
    <relationshipLabel>Conditions</relationshipLabel>
    <relationshipName>Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SPEN_L_P_Condition_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Job__c/SPEN_Job__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store L&amp;P Job records</description>
    <label>Job</label>
    <nameField>
        <label>Job Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Job__c/fields/SPEN_BusinessArea__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BusinessArea__c</fullName>
    <label>Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SPEN_LicenseArea__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Land &amp; Planning</fullName>
            </value>
            <value>
                <fullName>Business Transformation</fullName>
            </value>
            <value>
                <fullName>External Customer</fullName>
            </value>
            <value>
                <fullName>Internal Customer</fullName>
            </value>
            <value>
                <fullName>Land Solutions Policy &amp; Performance</fullName>
            </value>
            <value>
                <fullName>Licence Programmes</fullName>
            </value>
            <value>
                <fullName>Processes &amp; Technology</fullName>
            </value>
            <value>
                <fullName>Strategic Transmission Projects</fullName>
            </value>
            <value>
                <fullName>Transmission Operations</fullName>
            </value>
            <value>
                <fullName>Transmission Projects - Customer Connection</fullName>
            </value>
            <value>
                <fullName>Transmission Projects - Infrastructure</fullName>
            </value>
            <value>
                <fullName>Customer Resolution</fullName>
            </value>
            <value>
                <fullName>Customer Connections</fullName>
            </value>
            <value>
                <fullName>Distribution Network Operations</fullName>
            </value>
            <value>
                <fullName>Distribution Network Projects</fullName>
            </value>
            <value>
                <fullName>Estates</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Land Agent</fullName>
            </value>
            <value>
                <fullName>Land Solutions, Policy &amp; Performance</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Tree Department</fullName>
            </value>
            <value>
                <fullName>License Programmes</fullName>
            </value>
            <value>
                <fullName>HS2</fullName>
            </value>
            <value>
                <fullName>SPM 132 Operations</fullName>
            </value>
            <value>
                <fullName>SPM 132 Projects - Infrastructure</fullName>
            </value>
            <value>
                <fullName>SPM 132 Projects - Customer Connection</fullName>
            </value>
            <value>
                <fullName>Interal Customer</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
                <isActive>false</isActive>
                <label>CRM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Job__c/fields/SPEN_District__c.field-meta.xml
<CustomField>
    <fullName>SPEN_District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SPEN_LicenseArea__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Ayrshire &amp; Clyde South</fullName>
            </value>
            <value>
                <fullName>Central &amp; Fife</fullName>
            </value>
            <value>
                <fullName>Dee Valley/ Mid Wales</fullName>
            </value>
            <value>
                <fullName>Dumfries &amp; Galloway</fullName>
            </value>
            <value>
                <fullName>Edinburgh &amp; Borders</fullName>
            </value>
            <value>
                <fullName>Glasgow &amp; Clyde North</fullName>
            </value>
            <value>
                <fullName>Lanarkshire</fullName>
            </value>
            <value>
                <fullName>Merseyside</fullName>
            </value>
            <value>
                <fullName>Mid-Cheshire</fullName>
            </value>
            <value>
                <fullName>North Wales</fullName>
            </value>
            <value>
                <fullName>Wirral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Job__c/fields/SPEN_LicenseArea__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LicenseArea__c</fullName>
    <label>Licence Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Environmental Planning</fullName>
                <isActive>false</isActive>
                <label>Environmental Planning</label>
            </value>
            <value>
                <fullName>Land Assistant North</fullName>
                <isActive>false</isActive>
                <label>Land Assistant North</label>
            </value>
            <value>
                <fullName>Land Assistant South</fullName>
                <isActive>false</isActive>
                <label>Land Assistant South</label>
            </value>
            <value>
                <fullName>SPD</fullName>
            </value>
            <value>
                <fullName>SPM</fullName>
            </value>
            <value>
                <fullName>SPM 132</fullName>
            </value>
            <value>
                <fullName>SPT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Job__c/fields/SPEN_Work_Category__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Work_Category__c</fullName>
    <label>Work Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SPEN_LicenseArea__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CCT Customer Contact Enquiry</fullName>
            </value>
            <value>
                <fullName>Change of Owner</fullName>
            </value>
            <value>
                <fullName>Change of Owner Estate</fullName>
            </value>
            <value>
                <fullName>Change of Owner Farm</fullName>
            </value>
            <value>
                <fullName>Change of Owner Garden</fullName>
            </value>
            <value>
                <fullName>Change Of Vendor Details</fullName>
            </value>
            <value>
                <fullName>Completed Necessary Wayleave</fullName>
            </value>
            <value>
                <fullName>CRM Customer Complaint</fullName>
            </value>
            <value>
                <fullName>Damage Claim</fullName>
            </value>
            <value>
                <fullName>Decomissioning</fullName>
            </value>
            <value>
                <fullName>Decommissioning</fullName>
                <isActive>false</isActive>
                <label>Decommissioning</label>
            </value>
            <value>
                <fullName>District Day to Day</fullName>
            </value>
            <value>
                <fullName>External Land Search Request</fullName>
            </value>
            <value>
                <fullName>Fibre Optic Cable</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Finance Receipting</fullName>
                <isActive>false</isActive>
                <label>Finance Receipting</label>
            </value>
            <value>
                <fullName>Incorporated Rights - All</fullName>
            </value>
            <value>
                <fullName>Injurious Affection</fullName>
            </value>
            <value>
                <fullName>Land Enquiry</fullName>
            </value>
            <value>
                <fullName>Land Rights Enquiry</fullName>
            </value>
            <value>
                <fullName>LVSSA</fullName>
            </value>
            <value>
                <fullName>LVSSA Servitude/Easement ** temp w/l</fullName>
                <isActive>false</isActive>
                <label>LVSSA Servitude/Easement ** temp w/l</label>
            </value>
            <value>
                <fullName>LVSSB</fullName>
            </value>
            <value>
                <fullName>LVSSB Servitude/Easement ** temp w/l</fullName>
                <isActive>false</isActive>
                <label>LVSSB Servitude/Easement ** temp w/l</label>
            </value>
            <value>
                <fullName>Maintenance Works - Non Outage</fullName>
            </value>
            <value>
                <fullName>Maintenance Works - Outage</fullName>
            </value>
            <value>
                <fullName>Major Refurb No planning</fullName>
            </value>
            <value>
                <fullName>Major Refurb Planning</fullName>
            </value>
            <value>
                <fullName>Major Refurb S37</fullName>
            </value>
            <value>
                <fullName>New Marine Cable with Planning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Job__c/fields/SPEN_WorkCategory__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkCategory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Work Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SPEN_WorkCategory__c.SPEN_LicenseArea__c</field>
            <operation>equals</operation>
            <valueField>$Source.SPEN_LicenseArea__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SPEN_WorkCategory__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Land_Interest__c/SPEN_Land_Interest__c.object-meta.xml
<CustomObject>
    <description>Created as part of ESC-122.</description>
    <label>Land Right</label>
    <nameField>
        <label>Land Right Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Land Rights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Land_Interest__c/fields/SPEN_Job__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Job__c</fullName>
    <label>Job</label>
    <referenceTo>SPEN_Job__c</referenceTo>
    <relationshipName>Land_Interests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_Land_Interest__c/fields/SPEN_Land__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Land__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Land</label>
    <referenceTo>SPEN_Land__c</referenceTo>
    <relationshipName>Land_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_WorkCategory__c/SPEN_WorkCategory__c.object-meta.xml
<CustomObject>
    <label>Work Category</label>
    <nameField>
        <label>Work Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_WorkCategory__c/fields/SPEN_LicenseArea__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LicenseArea__c</fullName>
    <description>This field holds license area information</description>
    <label>License Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Environmental Planning</fullName>
                <isActive>false</isActive>
                <label>Environmental Planning</label>
            </value>
            <value>
                <fullName>Land Assistant North</fullName>
                <isActive>false</isActive>
                <label>Land Assistant North</label>
            </value>
            <value>
                <fullName>Land Assistant South</fullName>
                <isActive>false</isActive>
                <label>Land Assistant South</label>
            </value>
            <value>
                <fullName>SPD</fullName>
            </value>
            <value>
                <fullName>SPM</fullName>
            </value>
            <value>
                <fullName>SPM 132</fullName>
            </value>
            <value>
                <fullName>SPT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/SPEN_L_P_Condition_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VCL0</fullName>
        <label>Measure Based Lands</label>
    </customValue>
    <customValue>
        <fullName>VEL0</fullName>
        <label>Compensation Lands</label>
    </customValue>
    <customValue>
        <fullName>VFL0</fullName>
        <label>Fixed Rent Lands</label>
    </customValue>
    <customValue>
        <fullName>VKL0</fullName>
        <label>Damage</label>
    </customValue>
    <customValue>
        <fullName>Lands</fullName>
    </customValue>
    <masterLabel>L&amp;P Condition Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SPEN_SAPContractInvocableTest.cls
/* File Name: SPEN_SAPContractInvocableTest
 * Description: Test class for SPEN_SAPContractInvocable class
 * Author: Rajat mishra
 * Version: 1.0
 * History:
 * Date            Author              Comment
 * Mar-14-2024     Rajat Mishra    Initial version
 *
 */
@isTest
private class SPEN_SAPContractInvocableTest {
    
    public static testMethod void sapContractCreationTest(){
        
        User u = SPEN_TestDataUtility.createuser('System Administrator');
        Database.insert(u);                     
        System.runAs(u){
            SPEN_WorkCategory__c wc = SPEN_TestDataUtility.createWorkCategoryRecord('Test WC','SPD');
            
            List<SPEN_Job__c> job = SPEN_TestDataUtility.createJobRecord('Draft','Yes',wc.Id,'create job through Email',1);
            job[0].SPEN_LicenseArea__c = 'SPD';
            job[0].SPEN_Work_Category__c='CCT Customer Contact Enquiry';
            job[0].SPEN_District__c='Lanarkshire';
            job[0].SPEN_BusinessArea__c='Finance';
            Database.insert(job);
            
            SPEN_Land__c land = SPEN_TestDataUtility.createLandRec();
            
            SPEN_Land_Interest__c lndRight = SPEN_TestDataUtility.createLandIntRec(land.id,job[0].id);
            
            SPEN_Condition__c condRec = new SPEN_Condition__c();
            condRec.SPEN_LandInterest__c = lndRight.id;
            condRec.SPEN_Type__c = 'VEL0';
            condRec.SPEN_Unit__c = '2';
            insert condRec;

            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new SPEN_SAPContractMockResponse());
            List<SPEN_SAPContractInvocable.SPEN_CreateContractRequest> contractReq = new List<SPEN_SAPContractInvocable.SPEN_CreateContractRequest>();
            SPEN_SAPContractInvocable.SPEN_CreateContractRequest req = new SPEN_SAPContractInvocable.SPEN_CreateContractRequest();                    
            SPEN_Land_Interest__c lrObj = [SELECT Id, SPEN_Licence_Area_Code__c,SPEN_Contract_Type__c, SPEN_Contract_Start_Date__c, SPEN_Contract_First_End_Date__c, SPEN_Contract_Valid_From__c, SPEN_ConsentType__c, SPEN_Annual_Wayleave_Payment_Payable__c, SPEN_SAPContract__c
                                           from SPEN_Land_Interest__c where id =: lndRight.id];
            req.landRightObj= lrObj;
            contractReq.add(req);
            List<SPEN_SAPContractInvocable.SPEN_CreateContractResult> contractResult = SPEN_SAPContractInvocable.createSAPContract(contractReq);                      
            Test.stopTest();                
            //Assert
            system.assertEquals(false, contractResult[0].hasContractInitiated);            
        }
        
    }
}