force-app/main/default/objects/SPEN_Condition__c/SPEN_Condition__c.object-meta.xml
<CustomObject>
    <description>This object is created to capture condition information and send it for SAP sync</description>
    <label>Condition</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Condition</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Auto_Invoice__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Auto_Invoice__c</fullName>
    <defaultValue>&apos;X&apos;</defaultValue>
    <label>Auto Invoice</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Bank_Details__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Bank_Details__c</fullName>
    <label>Bank Details</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Condition_Currency__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Condition_Currency__c</fullName>
    <defaultValue>&apos;GBP&apos;</defaultValue>
    <label>Condition Currency</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Frequency__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Frequency__c</fullName>
    <defaultValue>&apos;Months&apos;</defaultValue>
    <label>Frequency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Measurement_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Measurement_Type__c</fullName>
    <label>Measurement Type</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Object__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Object__c</fullName>
    <formula>CASE(TEXT(SPEN_LandInterest__r.SPEN_Job__r.SPEN_LicenseArea__c),
&apos;SPD&apos;, CASE( SPEN_LandInterest__r.SPEN_ConsentType__c , &apos;Wayleave&apos;, &apos;8301/R01/G0000001&apos;, &apos;Servitude&apos;, &apos;8301/R01/G0000001&apos;,&apos;Easement&apos;,&apos;8301/R01/G0000001&apos;,&apos;Lease&apos;,SPEN_LandInterest__r.SPEN_RentalObjectNumber__c,&apos;Closed Couple Lease&apos;,SPEN_LandInterest__r.SPEN_RentalObjectNumber__c,&apos;NWL&apos;,&apos;8301/R01/G0000001&apos;,&apos;&apos;),
&apos;SPT&apos;, CASE( SPEN_LandInterest__r.SPEN_ConsentType__c , &apos;Wayleave&apos;, &apos;8302/R01/G0000001&apos;, &apos;Servitude&apos;, &apos;8302/R01/G0000001&apos;,&apos;Lease&apos;,SPEN_LandInterest__r.SPEN_RentalObjectNumber__c,&apos;Closed Couple Lease&apos;,SPEN_LandInterest__r.SPEN_RentalObjectNumber__c,&apos;NWL&apos;,&apos;8302/R01/G0000001&apos;,&apos;&apos;),
&apos;SPM&apos;, CASE( SPEN_LandInterest__r.SPEN_ConsentType__c , &apos;Wayleave&apos;, &apos;8303/R01/G0000001&apos;,&apos;Easement&apos;,&apos;8303/R01/G0000001&apos;,&apos;Lease&apos;,SPEN_LandInterest__r.SPEN_RentalObjectNumber__c,&apos;Closed Couple Lease&apos;,SPEN_LandInterest__r.SPEN_RentalObjectNumber__c,&apos;NWL&apos;,&apos;8303/R01/G0000001&apos;,&apos;&apos;),
&apos;SPM 132&apos;, CASE( SPEN_LandInterest__r.SPEN_ConsentType__c , &apos;Wayleave&apos;, &apos;8303/R01/G0000001&apos;,&apos;Easement&apos;,&apos;8303/R01/G0000001&apos;,&apos;Lease&apos;,SPEN_LandInterest__r.SPEN_RentalObjectNumber__c,&apos;Closed Couple Lease&apos;,SPEN_LandInterest__r.SPEN_RentalObjectNumber__c,&apos;NWL&apos;,&apos;8303/R01/G0000001&apos;,&apos;&apos;),
&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Object</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Order__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Order__c</fullName>
    <formula>CASE(TEXT(SPEN_LandInterest__r.SPEN_Job__r.SPEN_LicenseArea__c), 
  &apos;SPD&apos;, &apos;5701669718&apos;, 
  &apos;SPT&apos;, &apos;5701678312&apos;,
  &apos;SPM&apos;, &apos;5701669754&apos;,
  &apos;SPM 132&apos;, &apos;5701669754&apos;,
  &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Payment_Form__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Payment_Form__c</fullName>
    <defaultValue>&apos;0 - In Advance&apos;</defaultValue>
    <label>Payment Form</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Payment_Method__c</fullName>
    <defaultValue>&apos;C&apos;</defaultValue>
    <label>Payment Method</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Payment_Term__c</fullName>
    <defaultValue>&apos;0000&apos;</defaultValue>
    <label>Payment Term</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Planner_Group__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Planner_Group__c</fullName>
    <defaultValue>&apos;MPR&apos;</defaultValue>
    <label>Planner Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Posting_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Posting_Type__c</fullName>
    <label>Posting Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SPEN_L_P_Posting_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Tax_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Tax_Type__c</fullName>
    <label>Tax Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SPEN_L_P_Tax_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SPEN_L_P_Condition_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Unit__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Unit__c</fullName>
    <label>Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Condition__c/fields/SPEN_Wind_Farm_Stage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Wind_Farm_Stage__c</fullName>
    <defaultValue>&apos;All Phases&apos;</defaultValue>
    <label>Wind Farm Stage</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Land__c/SPEN_Land__c.object-meta.xml
<CustomObject>
    <label>Land</label>
    <nameField>
        <label>Land Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Land_Interest__c/SPEN_Land_Interest__c.object-meta.xml
<CustomObject>
    <description>Created as part of ESC-122.</description>
    <label>Land Right</label>
    <nameField>
        <label>Land Right Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Land Rights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Land_Interest__c/fields/SPEN_Annual_Wayleave_Payment_Payable__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Annual_Wayleave_Payment_Payable__c</fullName>
    <label>Contract Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_Land_Interest__c/fields/SPEN_ConsentType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ConsentType__c</fullName>
    <label>Consent Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Easement</fullName>
                <color>#A5DD50</color>
                <label>Easement</label>
            </value>
            <value>
                <fullName>Servitude</fullName>
                <color>#5C881A</color>
                <label>Servitude</label>
            </value>
            <value>
                <fullName>Wayleave</fullName>
                <color>#F07B2B</color>
                <label>Wayleave</label>
            </value>
            <value>
                <fullName>Lease</fullName>
                <color>#C3E98A</color>
                <label>Lease</label>
            </value>
            <value>
                <fullName>Freehold</fullName>
                <color>#A6A6A6</color>
                <label>Freehold</label>
            </value>
            <value>
                <fullName>CPO</fullName>
                <color>#B9CDE6</color>
                <label>CPO</label>
            </value>
            <value>
                <fullName>DCO</fullName>
                <color>#8BABD5</color>
                <label>DCO</label>
            </value>
            <value>
                <fullName>NWL</fullName>
                <color>#4A7CBE</color>
                <label>NWL</label>
            </value>
            <value>
                <fullName>Close Coupled Lease</fullName>
                <color>#F6B283</color>
                <label>Close Coupled Lease</label>
            </value>
            <value>
                <fullName>Incorporated Rights</fullName>
                <color>#FFA16D</color>
                <label>Incorporated Rights</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Land_Interest__c/fields/SPEN_Contract_First_End_Date__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contract_First_End_Date__c</fullName>
    <formula>CASE(  SPEN_ConsentType__c , 
      &apos;Lease&apos;,   ADDMONTHS(SPEN_Contract_Start_Date__c,1188) , 
      &apos;Close Coupled Lease&apos;, ADDMONTHS(SPEN_Contract_Start_Date__c,2100),
      &apos;Incorporated Rights&apos;, ADDMONTHS(SPEN_Contract_Start_Date__c,0),
      &apos;Servitude&apos;, ADDMONTHS(SPEN_Contract_Start_Date__c,480),
      &apos;Easement&apos;, ADDMONTHS(SPEN_Contract_Start_Date__c,480),
      &apos;NWL&apos;, ADDMONTHS(SPEN_Contract_Start_Date__c,480),
      &apos;CPO&apos;, ADDMONTHS(SPEN_Contract_Start_Date__c,0),
      &apos;DCO&apos;, ADDMONTHS(SPEN_Contract_Start_Date__c,0),
      ADDMONTHS(SPEN_Contract_Start_Date__c,480)) - 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract First End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_Land_Interest__c/fields/SPEN_Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contract_Start_Date__c</fullName>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_Land_Interest__c/fields/SPEN_Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contract_Type__c</fullName>
    <formula>CASE( SPEN_ConsentType__c , &apos;Lease&apos;, &apos;Lands Contracts&apos;,&apos;UK Wayleave Contracts&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Land_Interest__c/fields/SPEN_Contract_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contract_Valid_From__c</fullName>
    <formula>SPEN_Contract_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_Land_Interest__c/fields/SPEN_Land__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Land__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Land</label>
    <referenceTo>SPEN_Land__c</referenceTo>
    <relationshipName>Land_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Land_Interest__c/fields/SPEN_Licence_Area_Code__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Licence_Area_Code__c</fullName>
    <formula>CASE( TEXT(SPEN_Job__r.SPEN_LicenseArea__c) , 
      &apos;SPD&apos;, &apos;8301&apos;, 
      &apos;SPT&apos;, &apos;8302&apos;,
      &apos;SPM&apos;, &apos;8303&apos;, 
      &apos;SPM 132&apos;, &apos;8303&apos;,
      &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Licence Area Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_LandAssociation__c/SPEN_LandAssociation__c.object-meta.xml
<CustomObject>
    <description>Created as part of ESC-131.</description>
    <label>Land Contact</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Land Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Land Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PartnerAssociation__c/SPEN_PartnerAssociation__c.object-meta.xml
<CustomObject>
    <label>Partner Association</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Partner Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PartnerAssociation__c/fields/SPEN_LandInterest__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LandInterest__c</fullName>
    <label>Land Right</label>
    <referenceTo>SPEN_Land_Interest__c</referenceTo>
    <relationshipLabel>Partner Associations</relationshipLabel>
    <relationshipName>Partner_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_PartnerAssociation__c/fields/SPEN_Partner__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Partner__c</fullName>
    <label>Partner</label>
    <referenceTo>SPEN_LandAssociation__c</referenceTo>
    <relationshipLabel>Partner Associations</relationshipLabel>
    <relationshipName>Partner_Association</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/SPEN_L_P_Condition_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VCL0</fullName>
        <label>Measure Based Lands</label>
    </customValue>
    <customValue>
        <fullName>VEL0</fullName>
        <label>Compensation Lands</label>
    </customValue>
    <customValue>
        <fullName>VFL0</fullName>
        <label>Fixed Rent Lands</label>
    </customValue>
    <customValue>
        <fullName>VKL0</fullName>
        <label>Damage</label>
    </customValue>
    <customValue>
        <fullName>Lands</fullName>
    </customValue>
    <masterLabel>L&amp;P Condition Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SPEN_L_P_Posting_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PR - Periodic Posting</fullName>
        <label>Periodic Posting</label>
    </customValue>
    <customValue>
        <fullName>PE - Statistical Periodic Posting</fullName>
        <label>Statistical Periodic Posting</label>
    </customValue>
    <customValue>
        <fullName>UR - One-Time Posting</fullName>
        <label>One-time Posting</label>
    </customValue>
    <customValue>
        <fullName>UE - Statistical One-Time Posting</fullName>
        <label>Statistical One-time Posting</label>
    </customValue>
    <customValue>
        <fullName>Periodic Posting 1</fullName>
        <isActive>false</isActive>
        <label>Periodic Posting 1</label>
    </customValue>
    <masterLabel>L&amp;P Posting Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SPEN_L_P_Tax_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FT</fullName>
        <label>FT Fleet VAT Shared Use (20%)</label>
    </customValue>
    <customValue>
        <fullName>S9</fullName>
        <label>S9 Standard Rated VAT (20%)</label>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
        <label>SE Exempt (0%)</label>
    </customValue>
    <customValue>
        <fullName>SW</fullName>
        <label>SW Outside of the Scope (0%)</label>
    </customValue>
    <masterLabel>L&amp;P Tax Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SPEN_SAPContract.cls
/* File Name: SPEN_SAPContract
 * Description: This class will be create draft contract payload structure to be send to SAP RE via POST Call
 * Author: ajay.chandraferi
 * Version: 1.0
 * History:
 * Date            Author              Comment
 * Mar-04-2024     Ajay Chandraferi    Initial version
 *
 */
public class SPEN_SAPContract {
    list<SPEN_SAPCondition> ContractSet {get;set;}
    public SPEN_SAPContract(){
        this.ContractSet = new list<SPEN_SAPCondition>();
    }
    public void addSAPCondition(SPEN_Land_Interest__c landRight, SPEN_Condition__c sapCondition, Integer rowNumber){
        SPEN_SAPCondition newCondition = new SPEN_SAPCondition(landRight, sapCondition, false);
        if(rowNumber == 1){
            newCondition.addRenewalParameter();
        	newCondition.addNoticeParameter('1', landRight.SPEN_ConsentType__c);
        }else if(rowNumber == 2){
            newCondition.addNoticeParameter('2', landRight.SPEN_ConsentType__c);
        }
        ContractSet.add(newCondition);
    }
    public void addExtraNoticeRow(SPEN_Land_Interest__c landRight, SPEN_Condition__c sapCondition){
        SPEN_SAPCondition newCondition = new SPEN_SAPCondition(landRight, sapCondition, true);
        newCondition.addNoticeParameter('2', landRight.SPEN_ConsentType__c);
        ContractSet.add(newCondition);
    }
    
    
    public class SPEN_SAPCondition{
        String BukrsDg = '';
        String RecntxtoldDg = '';
        String RecntxtDg = '';
        String RecntypeDg = '';
        String ZzsistemaorigenDg = 'SF';
        String RecncncurrDg = '';
        String ZzautofacturaDg = '';
        String RecnbegDg = '';
        String Recnend1stDg = '';
        String CfpostingfromDg = '';
        String ZzformjurCi = '';
        String ZzgruplaCi = '';
        String ObjnrCd = '';
        String CondvalidfromCd = '';
        String CondvalidtoCd = '';
        String CondtypeCd = '';
        String CondpurposeextCd = '';
        String UnitpriceCd = '';
        String CondcurrCd = '';
        String Calcrulepara1Cd = '';
        String Distrulepara1Cd = '';
        String ZzfaseparCd = '';
        String PartnerPy = '';
        String PymtmethPy = '';
        String PymttermPy = '';
        String BankdetailidPy = '';
        String TaxtypePy = '';
        String FrequencyRh = '';
        String PaymentformrhRh = '';
        String CondvaluereferRh = '';
        String MonthfromRh = '';
        String RhythmbeginRh = '';
        String DuedatecorrruleRh = '';
        String DuedatecorrdayRh = '';
        String AdjmruleAj = '';
        String RhythmAj = '';
        String AdjmfirstdateAj = '';
        String FirstindexdateAj = '';
        String DelaybaseAj = '';
        String GradperiodCd = '';
        String GradmonthCd = '';
        String GradpercentCd = '';
        String NtruletypeNt = '';
        String NtprocprtyNt = '';
        String Ntnotdate1Nt = '';
        String NtrhythmtypeNt = '';
        String NtpermonthsNt = '';
        String RnruletypeRn = '';
        String RnextcountRn = '';
        String RnextyearsRn = '';
        String RnextmonthsRn = '';
        String RnnotmonthsRn = '';
        String ZzsujetoprorrogaRn = '';
        String RnauttypeRn = '';
        String SrrelevantDg = '';
        String TermnoVn = '';
        String RptermnoVnCalc = '';
        String PriceperunitVnCalc = '';
        String FrequencyVnRhytm = '';
        String ZzrentpercentVnCalc = '';
        String SalestypeSr = ''; 
        String ResponsibleDg='';
    
        public SPEN_SAPCondition(SPEN_Land_Interest__c landRightObj, SPEN_Condition__c sapConditionObj, Boolean isExtraNoticeRow){
            //SPEN Land Right record parameter
            if(landRightObj != null){
                if(landRightObj.SPEN_ConsentType__c != null){
                    this.ZzformjurCi = getLegalForm(landRightObj.SPEN_ConsentType__c);
                }
                if(landRightObj.SPEN_Licence_Area_Code__c != null){
                    this.BukrsDg = landRightObj.SPEN_Licence_Area_Code__c;
                }                
                if(landRightObj.Id != null){
                    this.RecntxtoldDg = landRightObj.Id;
                }                
                if(landRightObj.SPEN_Contract_Type__c != null){
                    this.RecntypeDg = landRightObj.SPEN_Contract_Type__c;
                }                
                if(landRightObj.SPEN_Contract_Start_Date__c != null){
                    this.RecnbegDg = convertDate(landRightObj.SPEN_Contract_Start_Date__c);
                }                
                if(landRightObj.SPEN_Contract_First_End_Date__c != null){
                    this.Recnend1stDg = convertDate(landRightObj.SPEN_Contract_First_End_Date__c);
                }                
                if(landRightObj.SPEN_Contract_Valid_From__c != null){
                    this.CfpostingfromDg = convertDate(landRightObj.SPEN_Contract_Valid_From__c);
                    if(!isExtraNoticeRow){
                        this.CondvalidfromCd = convertDate(landRightObj.SPEN_Contract_Valid_From__c);
                    }
                    
                }                
                if(landRightObj.SPEN_Annual_Wayleave_Payment_Payable__c != null && !isExtraNoticeRow){
                    this.RhythmbeginRh  = convertDate(landRightObj.SPEN_Annual_Wayleave_Payment_Payable__c);
                }               
                if(landRightObj.SPEN_Land__r.Name != null){
                    this.RecntxtDg = landRightObj.SPEN_Land__r.Name;   
                }
                if(!isExtraNoticeRow && landRightObj.Partner_Associations__r!=null && landRightObj.Partner_Associations__r.size() > 0){
                    if(landRightObj.Partner_Associations__r[0].SPEN_Partner__c!=null && landRightObj.Partner_Associations__r[0].SPEN_Partner__r.SPEN_BusinessPartnerNumber__c!=null ){
                    	this.PartnerPy = landRightObj.Partner_Associations__r[0].SPEN_Partner__r.SPEN_BusinessPartnerNumber__c;
                    }
                }
            }
            //SPEN Condition record parameter
            if(sapConditionObj != null){                
                
                if(sapConditionObj.SPEN_Auto_Invoice__c != null){  
                    this.ZzautofacturaDg = sapConditionObj.SPEN_Auto_Invoice__c; 
                }
                if(sapConditionObj.SPEN_Planner_Group__c != null){  
                     this.ZzgruplaCi = sapConditionObj.SPEN_Planner_Group__c;
                }
                if(sapConditionObj.SPEN_Condition_Currency__c != null){  
                        this.RecncncurrDg = sapConditionObj.SPEN_Condition_Currency__c;
                    }
                if(!isExtraNoticeRow){
                    this.TaxtypePy = 'SW';
                    this.MonthfromRh = '40';
                    this.CondvaluereferRh = '1';
                    if(sapConditionObj.SPEN_Object__c != null){  
                    	this.ObjnrCd = sapConditionObj.SPEN_Object__c;  
                	}
                    if(sapConditionObj.SPEN_Type__c != null){  
                        this.CondtypeCd = sapConditionObj.SPEN_Type__c;
                    }
                    if(sapConditionObj.SPEN_Posting_Type__c != null){  
                        this.CondpurposeextCd =sapConditionObj.SPEN_Posting_Type__c;
                    }
                    if(sapConditionObj.SPEN_Unit__c != null){  
                        this.UnitpriceCd =String.ValueOf(sapConditionObj.SPEN_Unit__c) ;
                    } 
                    if(sapConditionObj.SPEN_Condition_Currency__c != null){  
                        this.CondcurrCd = sapConditionObj.SPEN_Condition_Currency__c;
                    } 
                    if(sapConditionObj.SPEN_Order__c != null){  
                        this.Distrulepara1Cd = sapConditionObj.SPEN_Order__c;
                    } 
                    if(sapConditionObj.SPEN_Measurement_Type__c != null){
                        this.Calcrulepara1Cd = sapConditionObj.SPEN_Measurement_Type__c;
                    }
                    if(sapConditionObj.SPEN_Wind_Farm_Stage__c != null){  
                        this.ZzfaseparCd = sapConditionObj.SPEN_Wind_Farm_Stage__c;
                    } 
                    if(sapConditionObj.SPEN_Payment_Method__c != null){  
                        this.PymtmethPy = sapConditionObj.SPEN_Payment_Method__c;
                    }
                    if(sapConditionObj.SPEN_Payment_Term__c != null){  
                       this.PymttermPy = sapConditionObj.SPEN_Payment_Term__c;
                    }
                    if(sapConditionObj.SPEN_Bank_Details__c != null){  
                       this.BankdetailidPy = sapConditionObj.SPEN_Bank_Details__c;
                    }
                    
                    if(sapConditionObj.SPEN_Tax_Type__c != null){  
                       this.TaxtypePy = sapConditionObj.SPEN_Tax_Type__c;
                    } 
                    if(sapConditionObj.SPEN_Frequency__c != null){  
                       this.FrequencyRh = sapConditionObj.SPEN_Frequency__c;
                    }
                    if(sapConditionObj.SPEN_Payment_Form__c != null){  
                       this.PaymentformrhRh = sapConditionObj.SPEN_Payment_Form__c;            
                    }                    
                }
        	}
            
            if(SPEN_SAPContractInvocable.currentUser!=null && !String.isBlank(SPEN_SAPContractInvocable.currentUser.SPEN_SAPId__c))
            {
                this.ResponsibleDg=SPEN_SAPContractInvocable.currentUser.SPEN_SAPId__c;
            }
        }
        public void addRenewalParameter(){
            this.RnruletypeRn = 'AUTOMATIC';
            this.RnextcountRn = '2';
            this.RnextyearsRn = '1';
            this.RnextmonthsRn = '1';
            this.RnnotmonthsRn = '1';
            this.ZzsujetoprorrogaRn = '1';
            this.RnauttypeRn = 'R';            
        }
        
        public void addNoticeParameter(String rowNum, String consentType){
            this.NtruletypeNt = 'No restrictions';
            this.NtprocprtyNt = rowNum;
            if(rowNum == '1'){
                if(consentType == 'Lease' || consentType == 'Close Couple Lead'){
                     this.NtpermonthsNt = '6';
                }else{
                    this.NtpermonthsNt = '1';
                }
            }if(rowNum == '2'){                
                this.NtpermonthsNt = '12';
            }              
        }
        
        String convertDate(Date inputDate){ 
            if(inputDate != null){
                Datetime inputDateTime = Date.Valueof(inputDate);                
            	return inputDateTime.format('dd.MM.yyyy');
            }
            return '';
        }
        String getLegalForm(String concentType){
            String sapLegalForm ;
            SWITCH on concentType {
               when 'Easement' {
                   sapLegalForm = '34';
               }
               when 'Servitude' {
                   sapLegalForm = '18';
               }
               when 'Wayleave' {
                  sapLegalForm = '16';
               }
               when 'Lease' {
                   sapLegalForm = '01';
               }
               when 'NWL' {
                   sapLegalForm = '17';
               }
               when 'Close Coupled Lease' {
                   sapLegalForm = '19';
               }
               when else {
                   sapLegalForm = '';
               }
            }
            return sapLegalForm;
        }
        
        
    }
}