force-app/main/default/objects/SPEN_CaseEmployee__c/SPEN_CaseEmployee__c.object-meta.xml
<CustomObject>
    <description>CRMD-6634</description>
    <label>Case Employee</label>
    <nameField>
        <displayFormat>CE-{0000000}</displayFormat>
        <label>Case Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CaseEmployee__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>SPEN_CaseEmployees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseEmployee__c/fields/SPEN_Employee__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>SPEN_Employee__c</referenceTo>
    <relationshipName>SPEN_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseEmployee__c/fields/SPEN_NoticeRequestor__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NoticeRequestor__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>applicable only for Streetworks</inlineHelpText>
    <label>Notice Requestor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseEmployee__c/fields/SPEN_WorkRequestor__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkRequestor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SPEN Originator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/SPEN_CaseInformation__c.object-meta.xml
<CustomObject>
    <label>Case Information</label>
    <nameField>
        <displayFormat>CI-{00000000}</displayFormat>
        <label>Case Information Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CRMD-731</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Information</relationshipLabel>
    <relationshipName>Case_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_Contractor__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contractor__c</fullName>
    <description>CRMD-731</description>
    <label>Contractor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aggreko UK Limited</fullName>
            </value>
            <value>
                <fullName>Balfour Beatty</fullName>
            </value>
            <value>
                <fullName>C. Spratt Multi Utility</fullName>
            </value>
            <value>
                <fullName>Clancy Docwra Ltd</fullName>
            </value>
            <value>
                <fullName>C-Plan Telecommunications Ltd</fullName>
            </value>
            <value>
                <fullName>DT Hughes</fullName>
            </value>
            <value>
                <fullName>O&apos;Connors Overhead</fullName>
            </value>
            <value>
                <fullName>Overlec Ltd</fullName>
            </value>
            <value>
                <fullName>SPIE</fullName>
            </value>
            <value>
                <fullName>Voltcom Group</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Chevron TM</fullName>
            </value>
            <value>
                <fullName>CityFibre</fullName>
            </value>
            <value>
                <fullName>Connors Design and Restoration</fullName>
            </value>
            <value>
                <fullName>D&amp;C Jones</fullName>
            </value>
            <value>
                <fullName>Electricity Asset Services</fullName>
            </value>
            <value>
                <fullName>Emerald Power</fullName>
            </value>
            <value>
                <fullName>Freedom</fullName>
            </value>
            <value>
                <fullName>IQA</fullName>
            </value>
            <value>
                <fullName>Keltbray</fullName>
            </value>
            <value>
                <fullName>Morrisons Energy Services</fullName>
            </value>
            <value>
                <fullName>Optimum Technical Services</fullName>
            </value>
            <value>
                <fullName>OPUS</fullName>
            </value>
            <value>
                <fullName>PLPC</fullName>
            </value>
            <value>
                <fullName>PMK Civil Engineering</fullName>
            </value>
            <value>
                <fullName>Prysmian</fullName>
            </value>
            <value>
                <fullName>Quartzelec</fullName>
            </value>
            <value>
                <fullName>Singleton &amp; Smart</fullName>
            </value>
            <value>
                <fullName>Walker &amp; Watts Ltd</fullName>
            </value>
            <value>
                <fullName>O’Connors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_NoticeRequestorEmail__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NoticeRequestorEmail__c</fullName>
    <description>Notice Requestor Email for webform</description>
    <label>Notice Requestor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_WorkRequestorEmail__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkRequestorEmail__c</fullName>
    <description>Work Requestor Email for Web Form</description>
    <label>SPEN Originator Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/recordTypes/SPEN_NSRWA_Webform.recordType-meta.xml
<RecordType>
    <fullName>SPEN_NSRWA_Webform</fullName>
    <active>true</active>
    <label>NRSWA</label>
</RecordType>

force-app/main/default/objects/SPEN_CaseInformation__c/recordTypes/SPEN_SWWebform.recordType-meta.xml
<RecordType>
    <fullName>SPEN_SWWebform</fullName>
    <active>true</active>
    <label>SW Webform</label>
</RecordType>

force-app/main/default/objects/SPEN_Employee__c/SPEN_Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Employee Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Employee__c/fields/SPEN_EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EmailAddress__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SPEN_ResponsibleParty__c/SPEN_ResponsibleParty__c.object-meta.xml
<CustomObject>
    <label>Responsible Party</label>
    <nameField>
        <displayFormat>RP-{0000000}</displayFormat>
        <label>Responsible Party Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsible Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ResponsibleParty__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>SPEN_CaseResponsibilityParty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_ResponsibleParty__c/fields/SPEN_Company__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3 OR 4)</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>SPEN Account</value>
        </filterItems>
        <filterItems>
            <field>Account.SPEN_3PD_Responsible_Party__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.SPEN_Streetworks_Contractor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.SPEN_NRSWA_Contractor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Responsible Parties</relationshipLabel>
    <relationshipName>SPEN_AccountResponsibilityParty</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_ResponsibleParty__c/fields/SPEN_EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EmailAddress__c</fullName>
    <formula>IF( ISPICKVAL( SPEN_Type__c ,&apos;Company&apos;) ,  SPEN_Company__r.SPEN_PartnerEmailaddress__c ,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ResponsibleParty__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Person</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
                <isActive>false</isActive>
                <label>Employee</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_SyncStreetWorksCaseQueueable.cls
/***************************************************************************
* @Author:      Shubhi
* @Date:        30/08/2023
* @UserStory:   CRMD-7688
* @Description: Queueable class for async processing after SW  and NRSWA case creation
*****************************************************************************/
public with sharing class SPEN_SyncStreetWorksCaseQueueable implements Queueable{
    static final String RESPONSIBLEPARTY_TYPE='Company';
    private static Id recordTypeIdCaseInfoNRSWA = Schema.SObjectType.SPEN_CaseInformation__c.getRecordTypeInfosByDeveloperName().get('SPEN_NSRWA_Webform').getRecordTypeId();
	private static Id recordTypeIdCaseInfoSW = Schema.SObjectType.SPEN_CaseInformation__c.getRecordTypeInfosByDeveloperName().get('SPEN_SWWebform').getRecordTypeId();

    private SPEN_CaseInformation__c caseInfo;
    public SPEN_SyncStreetWorksCaseQueueable(SPEN_CaseInformation__c caseInfo) {
        this.caseInfo = caseInfo;
    }

    public void execute(System.QueueableContext context) {
        if(caseInfo.SPEN_Case__c!=null){
            createCaseEmployee(caseInfo);
        }
        if(String.isNotBlank(caseInfo.SPEN_Contractor__c) && caseinfo.SPEN_Case__c!=null){
            createResponsibleParty(caseInfo);
        }   
    }
    
    public void createCaseEmployee(SPEN_CaseInformation__c caseInfo){
        List<string> emailList=new List<String>();
        if(String.isNotBlank(caseInfo.SPEN_WorkRequestorEmail__c)){
            emailList.add(caseInfo.SPEN_WorkRequestorEmail__c);
        }
        if(String.isNotBlank(caseInfo.SPEN_NoticeRequestorEmail__c)&& caseInfo.SPEN_WorkRequestorEmail__c!=caseInfo.SPEN_NoticeRequestorEmail__c){
            emailList.add(caseInfo.SPEN_NoticeRequestorEmail__c);
        }
        List<SPEN_CaseEmployee__c> csEmpList=new List<SPEN_CaseEmployee__c>();
        try{
            for(SPEN_Employee__c emp:SPEN_EmployeeSelector.getEmployeeFromEmail(emailList)){      
                SPEN_CaseEmployee__c ce=new SPEN_CaseEmployee__c();
                ce.SPEN_Employee__c=emp.id;
                ce.SPEN_Case__c=caseInfo.SPEN_Case__c;
                if(emp.SPEN_EmailAddress__c == caseInfo.SPEN_WorkRequestorEmail__c){
                    ce.SPEN_WorkRequestor__c=true;
                }
                if(emp.SPEN_EmailAddress__c == caseInfo.SPEN_NoticeRequestorEmail__c){
                    ce.SPEN_NoticeRequestor__c=true;
                }
                csEmpList.add(ce);
            }
            insert csEmpList;
        }catch(Exception e){
            SEL_LoggingService.log(e);
        }
     }
    
    public void createResponsibleParty(SPEN_CaseInformation__c caseInfo){
        Account acc=new Account();
        if(caseInfo.RecordTypeId==recordTypeIdCaseInfoNRSWA){//crmd:7898
            acc=SPEN_AccountSelector.getNRSWAContractor(caseInfo.SPEN_Contractor__c);
        }else if(caseInfo.RecordTypeId==recordTypeIdCaseInfoSW){
            acc=SPEN_AccountSelector.getStreetWorkContractor(caseInfo.SPEN_Contractor__c);
        }
        if(acc!=null && Schema.sObjectType.SPEN_ResponsibleParty__c.isCreateable()){
			try{
                SPEN_ResponsibleParty__c responsibleparty=new SPEN_ResponsibleParty__c();
                responsibleparty.SPEN_Type__c=SPEN_SyncStreetWorksCaseQueueable.RESPONSIBLEPARTY_TYPE;
                responsibleparty.SPEN_Company__c=acc.id;
                responsibleparty.SPEN_Case__c=caseInfo.SPEN_Case__c;
                insert responsibleparty;
            }catch(Exception e){
                SEL_LoggingService.log(e);
            }
        }
    }
  
}