force-app/main/default/objects/SPEN_PSRStaging__c/SPEN_PSRStaging__c.object-meta.xml
<CustomObject>
    <description>Object for Staging Data</description>
    <label>PSR Staging</label>
    <nameField>
        <displayFormat>PST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSR Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_ADQMAction__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ADQMAction__c</fullName>
    <description>Choose what will be the ADQM Action.</description>
    <label>ADQM Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_ADQMLastModifiedDateTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ADQMLastModifiedDateTime__c</fullName>
    <description>It holds the ADQM Last Modified Datetime</description>
    <label>ADQM Last Modified DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_Code__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Code__c</fullName>
    <description>Takes Code for PSR Staging</description>
    <label>Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_EffectiveDateFrom__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EffectiveDateFrom__c</fullName>
    <description>Takes the Effective Date From</description>
    <label>Effective Date From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_EffectiveDateTo__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EffectiveDateTo__c</fullName>
    <description>It takes Effective Date To</description>
    <label>Effective Date To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_FirstLanguage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_FirstLanguage__c</fullName>
    <label>First Language</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Takes Premise Id.</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_PsrVulnerabilityTypeId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PsrVulnerabilityTypeId__c</fullName>
    <externalId>true</externalId>
    <label>PSR Vulnerability Type ID</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_SyncStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SyncStatus__c</fullName>
    <description>Checks the status of Sync</description>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_PSRStagingSelector.cls
/*-----------------------------------------------------------------------------
DESCRIPTION	:	Selector Class for SPEN_PSRStaging__c records
LIBRARY		:	SPEN
VERSION		:	1.0
HISTORY		:

Date			Author				Comment
FEB-15-2023		Asmita Rajput		Initial version
MAR-23-2023		Macjules Sevilla	Added ORDER BY to getStageRecSyncPSRBatch
-----------------------------------------------------------------------------*/
public with sharing class SPEN_PSRStagingSelector 
{
	public Database.QueryLocator getQueryLocatorForSuccessful(Date adqmLoadDate)
	{
		Database.QueryLocator q;
		if(adqmLoadDate != null)
		{
			q = Database.getQueryLocator([
				SELECT	Id, 
						SPEN_PremiseID__c
				FROM	SPEN_PSRStaging__c
				WHERE	DAY_ONLY(CreatedDate) = :adqmLoadDate AND 
						SPEN_SyncStatus__c =: 'Successful'
				WITH	SECURITY_ENFORCED
			]);				
		}
		return q;
	}

	public  Database.QueryLocator getStageRecSyncPSRBatch(Date adqmLoadDate)
	{
		Database.QueryLocator q;
		if(adqmLoadDate != null)
		{  
			q = Database.getQueryLocator([
				SELECT		Id, 
							SPEN_PremiseID__c, 
							SPEN_PsrVulnerabilityTypeId__c,
							SPEN_FirstLanguage__c,
							SPEN_ADQMAction__c,
							SPEN_Code__c,
							SPEN_SyncStatus__c,
							SPEN_ADQMLastModifiedDateTime__c,SPEN_EffectiveDateFrom__c,SPEN_EffectiveDateTo__c
				FROM		SPEN_PSRStaging__c
				WHERE		DAY_ONLY(CreatedDate) = :adqmLoadDate AND 
							(SPEN_SyncStatus__c =: 'New' OR SPEN_SyncStatus__c =: 'Failed')
				WITH		SECURITY_ENFORCED
				ORDER BY	SPEN_ADQMAction__c
			]);			
		}
		return q;
	}
}