force-app/main/default/objects/SPEN_CaseInformation__c/SPEN_CaseInformation__c.object-meta.xml
<CustomObject>
    <label>Case Information</label>
    <nameField>
        <displayFormat>CI-{00000000}</displayFormat>
        <label>Case Information Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/Any_additional_completion_criteria__c.field-meta.xml
<CustomField>
    <fullName>Any_additional_completion_criteria__c</fullName>
    <description>CRMD-715</description>
    <label>Any additional completion criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/Interface_with_overhead_line_contractor__c.field-meta.xml
<CustomField>
    <fullName>Interface_with_overhead_line_contractor__c</fullName>
    <description>CRMD-715</description>
    <label>Interface with overhead line contractor</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/Materials_to_be_free_issued_and_Location__c.field-meta.xml
<CustomField>
    <fullName>Materials_to_be_free_issued_and_Location__c</fullName>
    <description>CRMD-715</description>
    <label>Free Issued Material &amp; Collect Location</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/Number_of_landowners_satisfaction_report__c.field-meta.xml
<CustomField>
    <fullName>Number_of_landowners_satisfaction_report__c</fullName>
    <description>CRMD-715</description>
    <label>Number of landowners satisfaction report</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/Reinstatement_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Reinstatement_Contractor__c</fullName>
    <description>CRMD-715</description>
    <label>Reinstatement Contractor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_3rd_Party_Pack_issued_to_Contractor__c.field-meta.xml
<CustomField>
    <fullName>SPEN_3rd_Party_Pack_issued_to_Contractor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CRMD-715</description>
    <label>3rd Party Pack issued to Contractor:</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CRMD-731</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Information</relationshipLabel>
    <relationshipName>Case_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_Contractor__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contractor__c</fullName>
    <description>CRMD-731</description>
    <label>Contractor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aggreko UK Limited</fullName>
            </value>
            <value>
                <fullName>Balfour Beatty</fullName>
            </value>
            <value>
                <fullName>C. Spratt Multi Utility</fullName>
            </value>
            <value>
                <fullName>Clancy Docwra Ltd</fullName>
            </value>
            <value>
                <fullName>C-Plan Telecommunications Ltd</fullName>
            </value>
            <value>
                <fullName>DT Hughes</fullName>
            </value>
            <value>
                <fullName>O&apos;Connors Overhead</fullName>
            </value>
            <value>
                <fullName>Overlec Ltd</fullName>
            </value>
            <value>
                <fullName>SPIE</fullName>
            </value>
            <value>
                <fullName>Voltcom Group</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Chevron TM</fullName>
            </value>
            <value>
                <fullName>CityFibre</fullName>
            </value>
            <value>
                <fullName>Connors Design and Restoration</fullName>
            </value>
            <value>
                <fullName>D&amp;C Jones</fullName>
            </value>
            <value>
                <fullName>Electricity Asset Services</fullName>
            </value>
            <value>
                <fullName>Emerald Power</fullName>
            </value>
            <value>
                <fullName>Freedom</fullName>
            </value>
            <value>
                <fullName>IQA</fullName>
            </value>
            <value>
                <fullName>Keltbray</fullName>
            </value>
            <value>
                <fullName>Morrisons Energy Services</fullName>
            </value>
            <value>
                <fullName>Optimum Technical Services</fullName>
            </value>
            <value>
                <fullName>OPUS</fullName>
            </value>
            <value>
                <fullName>PLPC</fullName>
            </value>
            <value>
                <fullName>PMK Civil Engineering</fullName>
            </value>
            <value>
                <fullName>Prysmian</fullName>
            </value>
            <value>
                <fullName>Quartzelec</fullName>
            </value>
            <value>
                <fullName>Singleton &amp; Smart</fullName>
            </value>
            <value>
                <fullName>Walker &amp; Watts Ltd</fullName>
            </value>
            <value>
                <fullName>O’Connors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_Estimated_Cost__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Estimated_Cost__c</fullName>
    <description>CRMD-715</description>
    <label>Estimated Cost</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_JointingRequired__c.field-meta.xml
<CustomField>
    <fullName>SPEN_JointingRequired__c</fullName>
    <description>Jointing Required for Web Form</description>
    <label>Jointing Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_NCTApproval__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NCTApproval__c</fullName>
    <description>NCT Approval for Web Form</description>
    <label>NCT Approval</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_ProjectId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ProjectId__c</fullName>
    <description>Project Id for Web Form</description>
    <label>Project Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_RoadOpeningNoticeRequired__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RoadOpeningNoticeRequired__c</fullName>
    <description>Road Opening Notice Required for Web Form</description>
    <label>Road Opening Notice Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_ScopeofWork__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ScopeofWork__c</fullName>
    <description>Scope of Work for Web Form</description>
    <label>Scope of Work</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_SharepointURL__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SharepointURL__c</fullName>
    <description>CRMD-7831</description>
    <label>Sharepoint URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_Site_Specific_Rules__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Site_Specific_Rules__c</fullName>
    <description>CRMD-715</description>
    <label>Site Specific Rules</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_WorkLocation__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkLocation__c</fullName>
    <formula>TEXT(SPEN_Case__r.SPEN_WorkLocation__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_WorkRequestorBusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkRequestorBusinessUnit__c</fullName>
    <description>Work Requestor Business Unit for Web Form</description>
    <label>SPEN Originator Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Connections (Fully Customer Funded)</fullName>
            </value>
            <value>
                <fullName>Connections (Partially Customer Funded)</fullName>
            </value>
            <value>
                <fullName>Connections (SPEN Funded)</fullName>
            </value>
            <value>
                <fullName>Reactive Faults (LV - UG &amp; OHL)</fullName>
            </value>
            <value>
                <fullName>Planned Repairs (LV - UG &amp; OHL)</fullName>
            </value>
            <value>
                <fullName>Planned Works (LV - UG &amp; OHL)</fullName>
            </value>
            <value>
                <fullName>Reactive Faults (HV - UG &amp; OHL)</fullName>
            </value>
            <value>
                <fullName>Planned Repairs (HV - UG &amp; OHL)</fullName>
            </value>
            <value>
                <fullName>Planned Works (HV - UG &amp; OHL)</fullName>
            </value>
            <value>
                <fullName>Network Programme (UG &amp; OHL)</fullName>
            </value>
            <value>
                <fullName>Transmission</fullName>
            </value>
            <value>
                <fullName>Street Lighting Faults (SPEN)</fullName>
            </value>
            <value>
                <fullName>Street Lighting Connections (SPEN)</fullName>
            </value>
            <value>
                <fullName>Maintenance (Tea cutting &amp; Link Box Lids)</fullName>
            </value>
            <value>
                <fullName>Jones Lighting</fullName>
            </value>
            <value>
                <fullName>Licence Programmes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_WorkRequestorContact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkRequestorContact__c</fullName>
    <description>Work Requestor Contact for Web Form</description>
    <label>SPEN Originator Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_WorkRequestorEmail__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkRequestorEmail__c</fullName>
    <description>Work Requestor Email for Web Form</description>
    <label>SPEN Originator Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_WorkRequestorName__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkRequestorName__c</fullName>
    <description>Work Requestor Name for Web Form</description>
    <label>SPEN Originator Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/Tests_to_be_carried_out_by_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Tests_to_be_carried_out_by_Contractor__c</fullName>
    <description>CRMD-715</description>
    <label>Tests to be carried out by Contractor</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/Tests_to_be_carried_out_by_employer__c.field-meta.xml
<CustomField>
    <fullName>Tests_to_be_carried_out_by_employer__c</fullName>
    <description>CRMD-715</description>
    <label>Tests to be carried out by employer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/Wayleave_Agreements_and_Grantors_Request__c.field-meta.xml
<CustomField>
    <fullName>Wayleave_Agreements_and_Grantors_Request__c</fullName>
    <description>CRMD-715</description>
    <label>Wayleave Agreements and Grantors Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/Works_to_be_managed_by_named_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Works_to_be_managed_by_named_Contractor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CRMD-715</description>
    <label>Works to be managed by named Contractor?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/recordTypes/SPEN_NSRWA_Webform.recordType-meta.xml
<RecordType>
    <fullName>SPEN_NSRWA_Webform</fullName>
    <active>true</active>
    <label>NRSWA</label>
</RecordType>

force-app/main/default/objects/SPEN_SiteDetails__c/SPEN_SiteDetails__c.object-meta.xml
<CustomObject>
    <label>Site Details</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Site Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_SiteDetails__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Site Details</relationshipLabel>
    <relationshipName>Site_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_SiteDetails__c/recordTypes/NRSWA.recordType-meta.xml
<RecordType>
    <fullName>NRSWA</fullName>
    <active>true</active>
    <label>NRSWA</label>
</RecordType>

force-app/main/default/classes/SPEN_SyncNRSWACaseDetails.cls
/***************************************************************************
* @Author:      Swaathi
* @Date:        07/09/2023
* @UserStory:   CRMD-707
* @Description: Class to create NRSWA case based on the details coming from webform
*****************************************************************************/

@RestResource(urlMapping='/NRSWACase/*')
global with sharing class SPEN_SyncNRSWACaseDetails{
    global with sharing class SuccessResponseWrapper
    {
        public Boolean success;
        public String casenumber;
        public SuccessResponseWrapper(Boolean success,Case cases)
        {
            this.success = success;
            Case cs = [SELECT Id,casenumber from Case where ID=:cases.Id];
            this.casenumber = cs.CaseNumber;
        }
    }
    global with sharing class ErrorResponseWrapper
    { 
        public Boolean success;
        public String error;
        public ErrorResponseWrapper(Boolean success,String error)
        {
            this.success = success;
            this.error = error;
            
        }
    }
    @HttpPost
    global static void createNRSWACaseFromWebform() {
        RestRequest restRqst = RestContext.request;
        RestResponse restResp = RestContext.response;
        Id recordTypeIdNRSWA = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_NRSWA').getRecordTypeId();
        Id recordTypeIdCaseInfo = Schema.SObjectType.SPEN_CaseInformation__c.getRecordTypeInfosByDeveloperName().get('SPEN_NSRWA_Webform').getRecordTypeId();
        Id recordTypeIdSiteDetails = Schema.SObjectType.SPEN_SiteDetails__c.getRecordTypeInfosByDeveloperName().get('NRSWA').getRecordTypeId();
        String recordTypeNameNRSWA = 'SPEN_NRSWA';
        try{
            SPEN_SyncNRSWACaseDetailsWrapper responseWrapper = new SPEN_SyncNRSWACaseDetailsWrapper();
            SPEN_SyncNRSWACaseDetailsWrapper wrapper= (SPEN_SyncNRSWACaseDetailsWrapper)JSON.deserialize(restRqst.requestBody.toString(), 
                                                                                                                     SPEN_SyncNRSWACaseDetailsWrapper.requestBody.class);
            String incidentReference;
            if(wrapper.Cases.IncidentNumber.contains('INCD-'))
            {
                incidentReference = wrapper.Cases.IncidentNumber;
            }
            else
            {
                incidentReference = 'INCD-'+ wrapper.Cases.IncidentNumber;
            }
            Case swCase = new Case();
            swCase.SPEN_NRSWAExternalID__c = recordTypeNameNRSWA+'-'+incidentReference;
            swCase.SPEN_ProjectCommencementDate__c = wrapper.Cases.CommencementDate;
            swCase.SPEN_ProjectCompletionDate__c = wrapper.Cases.completionDate;
            swCase.SPEN_Contractor__c = wrapper.Cases.Contractor;
            swCase.SPEN_WorkLocation__c = wrapper.Cases.WorkLocation;
            swCase.SPEN_NoticeType__c = wrapper.Cases.NoticeType;
            swCase.PlannedJointingDate__c = wrapper.Cases.PlannedJointingDate;
            swCase.RecordTypeId = recordTypeIdNRSWA;
            swCase.Status = SPEN_ConstantData.NRSWACaseStatus;
            swCase.SPEN_Contractor__c = wrapper.Cases.Contractor;
            swCase.SPEN_WorkRequestorName__c = wrapper.Cases.WorkRequestorName;
            swCase.SPEN_ProjectId__c = wrapper.Cases.ProjectId;
            swCase.SPEN_FREPNo__c = wrapper.Cases.FREPNumber;
            swCase.Origin = CasesConstants.originWEB; //CRMD-9451 by Sumit
            if(SPEN_CaseSelector.getIncidentFromIncidentReference(incidentReference) != NULL)
            {
                swCase.SPEN_Incident__c = SPEN_CaseSelector.getIncidentFromIncidentReference(incidentReference).Id;
            }
            swCase.SPEN_Works_Start_Date__c = wrapper.Cases.worksStartDate;
            swCase.SPEN_Works_Completion_Date__c = wrapper.Cases.WorksCompletionDate;
            swCase.SPEN_ConnectionDistrict__c = wrapper.Cases.District;
            insert swCase;
            
            SPEN_CaseInformation__c caseinfo = new SPEN_CaseInformation__c();
            caseinfo.SPEN_Contractor__c = wrapper.caseInfo.Contractor;
            caseinfo.SPEN_Case__c = swCase.Id;
            caseinfo.RecordTypeId = recordTypeIdCaseInfo;  
            caseinfo.SPEN_WorkRequestorName__c = wrapper.caseInfo.WorkRequestorName;
            caseinfo.SPEN_WorkRequestorEmail__c = wrapper.caseInfo.WorkRequestorEmail;
            caseinfo.SPEN_WorkRequestorContact__c = wrapper.caseInfo.WorkRequestorContact;
            caseinfo.SPEN_WorkRequestorBusinessUnit__c = wrapper.caseInfo.WorkRequestorBusinessUnit;
            caseinfo.SPEN_RoadOpeningNoticeRequired__c = wrapper.caseInfo.RoadOpeningNoticeRequired;
            caseinfo.SPEN_ProjectId__c = wrapper.caseInfo.ProjectId;
            caseinfo.SPEN_JointingRequired__c = wrapper.caseInfo.JointingRequired;
            caseinfo.SPEN_NCTApproval__c = wrapper.caseInfo.NCTApproval;
            caseinfo.SPEN_ScopeofWork__c = wrapper.caseInfo.ScopeofWork;
            caseinfo.SPEN_Site_Specific_Rules__c = wrapper.caseInfo.SiteSpecificRules;
            caseinfo.Works_to_be_managed_by_named_Contractor__c = wrapper.caseInfo.WorksToBeManagedByNamedContractor;
            caseinfo.Reinstatement_Contractor__c = wrapper.caseInfo.ReinstatementContractor;
            caseinfo.SPEN_3rd_Party_Pack_issued_to_Contractor__c = wrapper.caseInfo.ThirdPartyPackIssuedToContractor;
            caseinfo.Wayleave_Agreements_and_Grantors_Request__c = wrapper.caseInfo.WayleaveAgreementsAndGrantorsRequest;
            caseinfo.Number_of_landowners_satisfaction_report__c = wrapper.caseInfo.NumberOfLandownersSatisfactionReport;
            caseinfo.Any_additional_completion_criteria__c = wrapper.caseInfo.AnyAdditionalCompletionCriteria;
            caseinfo.Materials_to_be_free_issued_and_Location__c = wrapper.caseInfo.MaterialsToBeFreeIssuedAndLocation;
            caseinfo.Tests_to_be_carried_out_by_Contractor__c = wrapper.caseInfo.TestsToBeCarriedOutByContractor;
            caseinfo.Tests_to_be_carried_out_by_employer__c = wrapper.caseInfo.TestsToBeCarriedOutByEmployer;
            caseinfo.Interface_with_overhead_line_contractor__c = wrapper.caseInfo.InterfaceWithOverheadLineContractor;
            caseinfo.SPEN_Estimated_Cost__c = wrapper.caseInfo.EstimatedCost;
            caseinfo.SPEN_AdditionalComments__c = wrapper.caseInfo.AdditionalComments;
            caseinfo.SPEN_SharepointURL__c = wrapper.caseInfo.SharePointURL;
            insert caseinfo;
            if(caseinfo.id!=null){
                //added by shubhi for CRMD:7898
                Id jobId= System.enqueueJob(new SPEN_SyncStreetWorksCaseQueueable(caseInfo));
            }
            SPEN_SiteDetails__c sitedetail = new SPEN_SiteDetails__c();
            List<SPEN_SiteDetails__c> siteList = new List<SPEN_SiteDetails__c>();
            for(SPEN_SyncNRSWACaseDetailsWrapper.SiteDetailsInput stdetail : wrapper.siteDetails)
            {
                SPEN_SiteDetails__c sd = new SPEN_SiteDetails__c();
                sd.SPEN_Case__c = swCase.Id;
                sd.SPEN_LocationOfWorks__c = stdetail.LocationofWorks;
                sd.SPEN_Coords__c = stdetail.Coordinates;
                sd.RecordTypeId = recordTypeIdSiteDetails;
                sd.SPEN_SurfaceType__c = stdetail.Surfacetype;
                if(stdetail.TrafficLights == 'None')
                {
                    sd.SPEN_TrafficLights__c = '';
                }
                else
                {
                    sd.SPEN_TrafficLights__c = stdetail.TrafficLights;  
                }
                sd.SPEN_TrafficManagement__c = stdetail.TrafficManagement;
                sd.SPEN_ApplicationDate__c = stdetail.ApplicationDate;
                siteList.add(sd);
            }
            insert siteList;
            if(swCase != NULL)
            {
                restResp.addHeader('Content-Type', 'application/json');
                restResp.responseBody = Blob.valueOf(JSON.serialize(new SuccessResponseWrapper(true,swCase))); 
                
                SPEN_IntegrationRequest__c integrationRequestRecordCreation = new SPEN_IntegrationRequest__c();
                integrationRequestRecordCreation.SPEN_Status__c = SPEN_ConstantData.Completed;
                integrationRequestRecordCreation.SPEN_IntegrationRequestServiceClass__c = SPEN_ConstantData.NRSWAIntegrationRequestServiceClass;
                integrationRequestRecordCreation.SPEN_Records__c = swCase.Id;
                integrationRequestRecordCreation.SPEN_Response__c = restResp.responseBody.toString();
                integrationRequestRecordCreation.SPEN_Request__c = restRqst.requestBody.toString();
                insert integrationRequestRecordCreation;
            }
        }
        catch(Exception e)
        {
            restResp.addHeader('Content-Type', 'application/json');
            restResp.responseBody = Blob.valueOf(JSON.serialize(new ErrorResponseWrapper(false,e.getMessage())));
            
            SPEN_IntegrationRequest__c integrationRequestRecordCreation = new SPEN_IntegrationRequest__c();
            integrationRequestRecordCreation.SPEN_Status__c = SPEN_ConstantData.Failed;
            integrationRequestRecordCreation.SPEN_IntegrationRequestServiceClass__c = SPEN_ConstantData.NRSWAIntegrationRequestServiceClass;
            integrationRequestRecordCreation.SPEN_Request__c = restRqst.requestBody.toString();
            integrationRequestRecordCreation.SPEN_Response__c = restResp.responseBody.toString();
            insert integrationRequestRecordCreation;
        }
      
    }	
    
}