force-app/main/default/objects/SPEN_CaseInformation__c/SPEN_CaseInformation__c.object-meta.xml
<CustomObject>
    <label>Case Information</label>
    <nameField>
        <displayFormat>CI-{00000000}</displayFormat>
        <label>Case Information Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_AssetConditionCode__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AssetConditionCode__c</fullName>
    <label>Asset Condition Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A01</fullName>
            </value>
            <value>
                <fullName>A03</fullName>
            </value>
            <value>
                <fullName>A04</fullName>
            </value>
            <value>
                <fullName>A05</fullName>
            </value>
            <value>
                <fullName>A07</fullName>
            </value>
            <value>
                <fullName>A10</fullName>
            </value>
            <value>
                <fullName>A12</fullName>
            </value>
            <value>
                <fullName>A14</fullName>
            </value>
            <value>
                <fullName>A15</fullName>
            </value>
            <value>
                <fullName>A17</fullName>
            </value>
            <value>
                <fullName>A19</fullName>
            </value>
            <value>
                <fullName>B01</fullName>
            </value>
            <value>
                <fullName>B02</fullName>
            </value>
            <value>
                <fullName>B03</fullName>
            </value>
            <value>
                <fullName>B04</fullName>
            </value>
            <value>
                <fullName>B05</fullName>
            </value>
            <value>
                <fullName>B07</fullName>
            </value>
            <value>
                <fullName>B08</fullName>
            </value>
            <value>
                <fullName>B10</fullName>
            </value>
            <value>
                <fullName>B11</fullName>
            </value>
            <value>
                <fullName>B12</fullName>
            </value>
            <value>
                <fullName>C02</fullName>
            </value>
            <value>
                <fullName>C03</fullName>
            </value>
            <value>
                <fullName>C06</fullName>
            </value>
            <value>
                <fullName>C07</fullName>
            </value>
            <value>
                <fullName>C11</fullName>
            </value>
            <value>
                <fullName>C14</fullName>
            </value>
            <value>
                <fullName>C15</fullName>
            </value>
            <value>
                <fullName>C16</fullName>
            </value>
            <value>
                <fullName>C17</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_DateLetter1__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DateLetter1__c</fullName>
    <description>Created as part of CRMD-10581</description>
    <label>Date Letter 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_Flowreceiveddate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Flowreceiveddate__c</fullName>
    <description>Created as part of CRMD-10581</description>
    <label>Flow received date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_JobStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_JobStatus__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reject: Incomplete contact details</fullName>
            </value>
            <value>
                <fullName>Reject: Out of Area / unknown postcode</fullName>
            </value>
            <value>
                <fullName>Reject: Duplicate</fullName>
            </value>
            <value>
                <fullName>In flight job (CAT-A or CAT-B)</fullName>
            </value>
            <value>
                <fullName>MEX completed</fullName>
            </value>
            <value>
                <fullName>Issued To LP - pending delivery instruction</fullName>
            </value>
            <value>
                <fullName>Awaiting Appointment Call 1 Made</fullName>
            </value>
            <value>
                <fullName>Awaiting Appointment Call 2 Made</fullName>
            </value>
            <value>
                <fullName>Awaiting Appointment Call 3 Made</fullName>
            </value>
            <value>
                <fullName>Awaiting Appointment Letter 1 Sent</fullName>
            </value>
            <value>
                <fullName>Awaiting Appointment 10 WD response</fullName>
            </value>
            <value>
                <fullName>Land Registry</fullName>
            </value>
            <value>
                <fullName>Awaiting Appointment Letter 2 Sent</fullName>
            </value>
            <value>
                <fullName>Escalation L2 Manager/Legal</fullName>
            </value>
            <value>
                <fullName>Reject: Unable to Contact Customer Reasonable Endeavours Made</fullName>
            </value>
            <value>
                <fullName>Appointment Booked 1</fullName>
            </value>
            <value>
                <fullName>No Access on 1st Appointment Date</fullName>
            </value>
            <value>
                <fullName>Appointment Booked 2</fullName>
            </value>
            <value>
                <fullName>Reject: No further appointment made</fullName>
            </value>
            <value>
                <fullName>Reject: No Access on 2nd Appointment Date</fullName>
            </value>
            <value>
                <fullName>Reject: Access Refused Safety</fullName>
            </value>
            <value>
                <fullName>Reject: Access Refused Non Safety</fullName>
            </value>
            <value>
                <fullName>Reject: Unable to Access Equipment Safety</fullName>
            </value>
            <value>
                <fullName>Reject: Unable to Access Equipment Non Safety</fullName>
            </value>
            <value>
                <fullName>Further SPEN Works Req</fullName>
            </value>
            <value>
                <fullName>Reject: no works required</fullName>
            </value>
            <value>
                <fullName>Reject: works already completed</fullName>
            </value>
            <value>
                <fullName>Works Completed</fullName>
            </value>
            <value>
                <fullName>Final Contact Attempt</fullName>
            </value>
            <value>
                <fullName>Disconnection Letter Issued</fullName>
            </value>
            <value>
                <fullName>Cat C Job - On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_MPANCore__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MPANCore__c</fullName>
    <label>MPAN Core</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_SubStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SubStatus__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Contact Attempt – Day 1</fullName>
            </value>
            <value>
                <fullName>Customer Contact Attempt – Day 2 (AM)</fullName>
            </value>
            <value>
                <fullName>Customer Contact Attempt – Day 3 (PM)</fullName>
            </value>
            <value>
                <fullName>Customer Contact Attempt – Day 4 (OOH)</fullName>
            </value>
            <value>
                <fullName>28 day - letter 1 issued</fullName>
            </value>
            <value>
                <fullName>28 day - letter 2 issued</fullName>
            </value>
            <value>
                <fullName>28 day - letter 3 issued</fullName>
            </value>
            <value>
                <fullName>Missing Information Received</fullName>
            </value>
            <value>
                <fullName>Missing Information Requested</fullName>
            </value>
            <value>
                <fullName>Survey/Quote Review</fullName>
            </value>
            <value>
                <fullName>Quote Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/recordTypes/SPEN_LCTRecordType.recordType-meta.xml
<RecordType>
    <fullName>SPEN_LCTRecordType</fullName>
    <active>true</active>
    <label>LCT</label>
</RecordType>

force-app/main/default/objects/SPEN_CaseInformation__c/recordTypes/SPEN_SmartIntervention.recordType-meta.xml
<RecordType>
    <fullName>SPEN_SmartIntervention</fullName>
    <active>true</active>
    <label>Smart Intervention</label>
</RecordType>

force-app/main/default/objects/SPEN_MPAN__c/SPEN_MPAN__c.object-meta.xml
<CustomObject>
    <description>MPAN object is used to see MPAN related data.</description>
    <label>MPAN/Meter</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MPAN Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPAN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_AccountNumberMPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AccountNumberMPAN__c</fullName>
    <description>The account number associated with a call - PO map this to the MPAN. Question - what if there are multiple MPANS associated? Can this be cross checked</description>
    <externalId>true</externalId>
    <label>MPAN</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SPEN_CaseInformationInterface.cls
@SuppressWarnings('PMD.EmptyStatementBlock')
public class SPEN_CaseInformationInterface implements TriggerHandlerInterface{
    Public Static ID LCTRecordTypeId =  Schema.SObjectType.SPEN_CaseInformation__c.getRecordTypeInfosByDeveloperName().get('SPEN_LCTRecordType').getRecordTypeId();
    Public Static ID SIRecordTypeId =  Schema.SObjectType.SPEN_CaseInformation__c.getRecordTypeInfosByDeveloperName().get('SPEN_SmartIntervention').getRecordTypeId();
    public void beforeInsert(SObject[] newItems){
        SPEN_CaseInformationTriggerHandler.beforeInsert(newItems);
		List<SPEN_CaseInformation__c> caseInfos = new List<SPEN_CaseInformation__c>();
        for (SObject newItem : newItems) {
            SPEN_CaseInformation__c newCaseInfo = (SPEN_CaseInformation__c)newItem;
            if (newCaseInfo.SPEN_FlowReceivedDate__c != null || (newCaseInfo.SPEN_DateLetter1__c != null 
                                                                 && 'Reject: Unable to Contact Customer Reasonable Endeavours Made'.equalsIgnorecase(newCaseInfo.SPEN_JobStatus__c))){
                                                                     caseInfos.add((SPEN_CaseInformation__c)newItem);
                                                                 }
        }
        if(!caseInfos.isEmpty() && caseInfos.size() > 0 ){
        SPEN_CaseInformationTriggerHandler.calculateAndSetDates(caseInfos);           
        }
    }
    public void beforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems){
	List<SPEN_CaseInformation__c> caseInfosToUpdate = new List<SPEN_CaseInformation__c>();
        for (Id caseInfoId : newItems.keySet()){
            SPEN_CaseInformation__c newCaseInfo = (SPEN_CaseInformation__c)newItems.get(caseInfoId);
            SPEN_CaseInformation__c oldCaseInfo = (SPEN_CaseInformation__c)oldItems.get(caseInfoId);
            if ((newCaseInfo.SPEN_FlowReceivedDate__c != oldCaseInfo.SPEN_FlowReceivedDate__c) ||
                (newCaseInfo.SPEN_DateLetter1__c != oldCaseInfo.SPEN_DateLetter1__c 
                 && 'Reject: Unable to Contact Customer Reasonable Endeavours Made'.equalsIgnorecase(newCaseInfo.SPEN_JobStatus__c))){
                     caseInfosToUpdate.add(newCaseInfo);
                     if (!caseInfosToUpdate.isEmpty() && caseInfosToUpdate.size()>0){
                         SPEN_CaseInformationTriggerHandler.calculateAndSetDates(caseInfosToUpdate);
                     }
                 }
            
        }
        
    }
    public void afterInsert(Map<Id, SObject> newItems)
    {
		/*List<Id> caseInfoIds = new List<Id>();
		//CRMD-11219 starts here
        Map<String,Id> mapMpan = new Map<String,Id>();
        List<String> mpanCoreList = new List<String>();
        Set<Id> mpanIds = new Set<Id>();
        for(SPEN_CaseInformation__c cseInfo : (List<SPEN_CaseInformation__c>)newItems.values())
        {
            mpanCoreList.add(cseInfo.SPEN_MPANCore__c);
        }
        if (!mpanCoreList.isEmpty())
        {
            for(SPEN_MPAN__c mpan : SPEN_MPANSelector.getRecordForMpanAccountNumber(mpanCoreList))
            {
                mapMpan.put(mpan.SPEN_AccountNumberMPAN__c, mpan.Id);
            }
        }
        //CRMD-11219 ends here
			
			for (SPEN_CaseInformation__c newItem : (List<SPEN_CaseInformation__c>)newItems.values()) {
				if (//newItem.SPEN_JobStatus__c != null &&
					newItem.SPEN_JobStatus__c != 'Reject: Duplicate' &&
					newItem.SPEN_JobStatus__c != 'Reject: Incomplete contact details' &&
					newItem.SPEN_JobStatus__c != 'Reject: Out of Area / unknown postcode' &&
					newItem.SPEN_JobStatus__c != 'In flight job (CAT-A or CAT-B)' &&
					newItem.SPEN_JobStatus__c != 'MEX completed' &&
					newItem.SPEN_JobStatus__c != 'Cat C Job - On Hold'/*&&
					newItem.Owner.Name.contains('SPEN Azure User')) {
					//caseInfoIds.add(newItem.Id);
				}
			//CRMD-11219 starts here
             if (newItem.SPEN_MPANCore__c!= NULL && 
                newItem.SPEN_IsMigrated__c == FALSE && 
                newItem.recordtypeid == SIRecordTypeId &&
		        newItem.SPEN_AssetConditionCode__c!=null &&
                newItem.SPEN_AssetConditionCode__c.startswith ('B') == TRUE
                && mapMpan.containsKey(newItem.SPEN_MPANCore__c))
            {
                mpanIds.add(mapMpan.get(newItem.SPEN_MPANCore__c));
                //system.debug('mpanIds-->'+mpanIds);
                
            }
               
        }
        if(!mpanIds.isEmpty())
        {
            SPEN_CaseInformationTriggerHandler.fetchMpanDetails(mpanIds);
        }
              //CRMD-11219 ends here   
			
			
			if (!caseInfoIds.isEmpty()) {
				Database.executeBatch(new SPEN_CaseInfoJobStatusBatchUpdate(caseInfoIds));
			}*/
        
    }

    public void afterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems){
        //List<SPEN_CaseInformation__c> caseInfosToUpdateEntitlement = new List<SPEN_CaseInformation__c>();
        
        /*for (Id caseInfoId : newItems.keySet())
        {
            SPEN_CaseInformation__c newCaseInfo = (SPEN_CaseInformation__c)newItems.get(caseInfoId);
            SPEN_CaseInformation__c oldCaseInfo = (SPEN_CaseInformation__c)oldItems.get(caseInfoId);
            if (newCaseInfo.recordtypeid == LCTRecordTypeId && newCaseInfo.SPEN_SubStatus__c != null && newCaseInfo.SPEN_SubStatus__c != oldCaseInfo.SPEN_SubStatus__c && 
                (newCaseInfo.SPEN_SubStatus__c.equalsIgnoreCase(System.label.SPEN_CaseInfo28DaysLetterSubStatus) || 
                 newCaseInfo.SPEN_SubStatus__c.equalsIgnoreCase(System.label.SPEN_CaseInfoMissingInfoRequestedSubStaus))){
                     caseInfosToUpdateEntitlement.add(newCaseInfo);
                     SPEN_CaseInformationTriggerHandler.updateParentCaseEntitlement(caseInfosToUpdateEntitlement);
                 }
        }*/
        SPEN_CaseInformationTriggerHandler.updateParentCaseEntitlement(newItems,oldItems);
		/*List<Id> caseInfoIds = new List<Id>();
        
        for (SPEN_CaseInformation__c newItem : (List<SPEN_CaseInformation__c>)newItems.values()) {
            SPEN_CaseInformation__c oldItem = (SPEN_CaseInformation__c)oldItems.get(newItem.Id);
            
            // Check if SPEN_JobStatus__c has changed and meets the criteria
            if (newItem.SPEN_JobStatus__c != oldItem.SPEN_JobStatus__c &&
                newItem.SPEN_JobStatus__c != null &&
                newItem.SPEN_JobStatus__c != 'Reject: Duplicate' &&
				newItem.SPEN_JobStatus__c != 'Reject: Incomplete contact details' &&
				newItem.SPEN_JobStatus__c != 'Reject: Out of Area / unknown postcode' &&
				newItem.SPEN_JobStatus__c != 'In flight job (CAT-A or CAT-B)' &&
				newItem.SPEN_JobStatus__c != 'MEX completed' &&
                UserInfo.getUserName() == 'SPEN Azure User') {
                caseInfoIds.add(newItem.Id);
            }
        }
        
        if (!caseInfoIds.isEmpty()) {
            Database.executeBatch(new SPEN_CaseInfoJobStatusBatchUpdate(caseInfoIds));
        }*/
        //CRMD-10762
        SPEN_CaseInformationTriggerHandler.afterUpdate(newItems,oldItems);
        //END
    }
    
     public void afterDelete(Map<Id, SObject> oldItems){
        
    }
	 public void beforeDelete(Map<Id, SObject> oldItems){
        
    }
    public void afterUndelete(Map<Id, SObject> oldItems){
        
    }
}