force-app/main/default/objects/SPEN_CaseInformation__c/SPEN_CaseInformation__c.object-meta.xml
<CustomObject>
    <label>Case Information</label>
    <nameField>
        <displayFormat>CI-{00000000}</displayFormat>
        <label>Case Information Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CRMD-731</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Information</relationshipLabel>
    <relationshipName>Case_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_Contractor__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contractor__c</fullName>
    <description>CRMD-731</description>
    <label>Contractor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aggreko UK Limited</fullName>
            </value>
            <value>
                <fullName>Balfour Beatty</fullName>
            </value>
            <value>
                <fullName>C. Spratt Multi Utility</fullName>
            </value>
            <value>
                <fullName>Clancy Docwra Ltd</fullName>
            </value>
            <value>
                <fullName>C-Plan Telecommunications Ltd</fullName>
            </value>
            <value>
                <fullName>DT Hughes</fullName>
            </value>
            <value>
                <fullName>O&apos;Connors Overhead</fullName>
            </value>
            <value>
                <fullName>Overlec Ltd</fullName>
            </value>
            <value>
                <fullName>SPIE</fullName>
            </value>
            <value>
                <fullName>Voltcom Group</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Chevron TM</fullName>
            </value>
            <value>
                <fullName>CityFibre</fullName>
            </value>
            <value>
                <fullName>Connors Design and Restoration</fullName>
            </value>
            <value>
                <fullName>D&amp;C Jones</fullName>
            </value>
            <value>
                <fullName>Electricity Asset Services</fullName>
            </value>
            <value>
                <fullName>Emerald Power</fullName>
            </value>
            <value>
                <fullName>Freedom</fullName>
            </value>
            <value>
                <fullName>IQA</fullName>
            </value>
            <value>
                <fullName>Keltbray</fullName>
            </value>
            <value>
                <fullName>Morrisons Energy Services</fullName>
            </value>
            <value>
                <fullName>Optimum Technical Services</fullName>
            </value>
            <value>
                <fullName>OPUS</fullName>
            </value>
            <value>
                <fullName>PLPC</fullName>
            </value>
            <value>
                <fullName>PMK Civil Engineering</fullName>
            </value>
            <value>
                <fullName>Prysmian</fullName>
            </value>
            <value>
                <fullName>Quartzelec</fullName>
            </value>
            <value>
                <fullName>Singleton &amp; Smart</fullName>
            </value>
            <value>
                <fullName>Walker &amp; Watts Ltd</fullName>
            </value>
            <value>
                <fullName>O’Connors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_NoticeRequestorEmail__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NoticeRequestorEmail__c</fullName>
    <description>Notice Requestor Email for webform</description>
    <label>Notice Requestor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_WorkRequestorEmail__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkRequestorEmail__c</fullName>
    <description>Work Requestor Email for Web Form</description>
    <label>SPEN Originator Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/recordTypes/SPEN_NSRWA_Webform.recordType-meta.xml
<RecordType>
    <fullName>SPEN_NSRWA_Webform</fullName>
    <active>true</active>
    <label>NRSWA</label>
</RecordType>

force-app/main/default/classes/SPEN_SyncNRSWACaseDetails_Test.cls
/***************************************************************************
* @Author:      Swaathi
* @Date:        24/08/2023
* @UserStory:   CRMD-724
* @Description: Method to handle test class coverage for SPEN_SyncStreetworksCaseDetails class
*****************************************************************************/

@isTest
@suppresswarnings('PMD.SOQLSelectorPattern,PMD.CodeBestPracticesAvoidEmptyQueries')
public class SPEN_SyncNRSWACaseDetails_Test  {
    public static SPEN_SyncNRSWACaseDetailsWrapper setupTestData()
    {
        SPEN_SyncNRSWACaseDetailsWrapper wrapper = new SPEN_SyncNRSWACaseDetailsWrapper();
        
        SPEN_SyncNRSWACaseDetailsWrapper.CaseInput caseWrapper = new SPEN_SyncNRSWACaseDetailsWrapper.CaseInput();
        casewrapper.Contractor = 'Aggreko UK Limited';
        casewrapper.WorkRequestorName = 'Test Name';
        casewrapper.ProjectId = '1235465'; 
        caseWrapper.CommencementDate = Date.today();
        caseWrapper.completionDate = Date.today();
        caseWrapper.WorkLocation = 'England';
        casewrapper.NoticeType = 'Emergency';
        casewrapper.District = 'North Wales';
        casewrapper.PlannedJointingDate = Date.Today();
        casewrapper.FREPNumber = '1235465'; 
        casewrapper.IncidentNumber = '1235465'; 
        casewrapper.worksStartDate = Date.Today();
        casewrapper.WorksCompletionDate = Date.Today();
       
        wrapper.Cases = caseWrapper;
        
        SPEN_SyncNRSWACaseDetailsWrapper.CaseInformationInput  caseInfoWrapper = new SPEN_SyncNRSWACaseDetailsWrapper.CaseInformationInput();
        caseInfoWrapper.Contractor = 'Aggreko UK Limited';
        casewrapper.WorkRequestorName = 'Test Name';
        caseInfoWrapper.WorkRequestorEmail = 'test@gmail.com';
        caseInfoWrapper.WorkRequestorContact = '+447404885092';
        caseInfoWrapper.WorkRequestorBusinessUnit = 'Transmission';
        caseInfoWrapper.RoadOpeningNoticeRequired = 'Yes';
        caseInfoWrapper.ProjectId = '1235465'; 
        caseInfoWrapper.JointingRequired = 'Yes'; 
        caseInfoWrapper.NCTApproval = 'Yes'; 
        caseInfoWrapper.ScopeofWork = 'Test Scope'; 
        caseInfoWrapper.SiteSpecificRules = 'Test Rule';
        caseInfoWrapper.WorksToBeManagedByNamedContractor = false;
        caseInfoWrapper.ReinstatementContractor = 'Test Reinstatement';
        caseInfoWrapper.ThirdPartyPackIssuedToContractor = false;
        caseInfoWrapper.WayleaveAgreementsAndGrantorsRequest = 'Test';
        caseInfoWrapper.NumberOfLandownersSatisfactionReport = 'Test';
        caseInfoWrapper.AnyAdditionalCompletionCriteria = 'Test';
        caseInfoWrapper.MaterialsToBeFreeIssuedAndLocation = 'Test';
        caseInfoWrapper.TestsToBeCarriedOutByContractor = 'Test';
        caseInfoWrapper.TestsToBeCarriedOutByEmployer = 'Test';
        caseInfoWrapper.InterfaceWithOverheadLineContractor = 'Test';
        caseInfoWrapper.EstimatedCost = 'Test';
        caseInfoWrapper.AdditionalComments = 'Test';
        wrapper.caseInfo = caseInfoWrapper;
        
        List<SPEN_SyncNRSWACaseDetailsWrapper.SiteDetailsInput> siteDetailsList = new List<SPEN_SyncNRSWACaseDetailsWrapper.SiteDetailsInput>();
        SPEN_SyncNRSWACaseDetailsWrapper.SiteDetailsInput sitewrapper = new SPEN_SyncNRSWACaseDetailsWrapper.SiteDetailsInput();
        sitewrapper.LocationofWorks = '23 Merseyside AB1 1AB';
        sitewrapper.Coordinates = '0001234,0007890';
        sitewrapper.Surfacetype = 'Footpath';
        sitewrapper.TrafficManagement = 'Contraflow';
        sitewrapper.TrafficLights = '2-Way';
        sitewrapper.ApplicationDate = Date.today();
        siteDetailsList.add(sitewrapper);
        wrapper.siteDetails = siteDetailsList;
        return wrapper;
    }    
    
    @isTest
    public static void testcreateStreetWorkCaseOnSuccess()
    {
        SPEN_SyncNRSWACaseDetailsWrapper wrapper = setupTestData();
        
        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/NRSWACase/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serialize(wrapper));
        RestContext.request = req;
        
        RestResponse resp = new RestResponse();
        resp.responseBody=Blob.valueOf('{"success":true,"casenumber":"00036645"}');
        RestContext.response = resp;
        
        test.startTest();
        SPEN_SyncNRSWACaseDetails.createNRSWACaseFromWebform();
        Id recordTypeIdCaseInfo = Schema.SObjectType.SPEN_CaseInformation__c.getRecordTypeInfosByDeveloperName().get('SPEN_NSRWA_Webform').getRecordTypeId();
        SPEN_CaseInformation__c caseinfo=[Select id,SPEN_Case__c,SPEN_Contractor__c,SPEN_WorkRequestorEmail__c,SPEN_NoticeRequestorEmail__c,recordTypeId from SPEN_CaseInformation__c where recordTypeId=:recordTypeIdCaseInfo limit 1];
        Id jobId= System.enqueueJob(new SPEN_SyncStreetWorksCaseQueueable(caseInfo));
        test.stopTest();
        Assert.isNotNull(req.requestBody);
    }
    
    @isTest
    public static void testcreateStreetWorkCaseOnError()
    {
        SPEN_SyncNRSWACaseDetailsWrapper wrapper = setupTestData();
        
        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/NRSWACase/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serialize(wrapper.Cases));
        RestContext.request = req;
        
        RestResponse resp = new RestResponse();
        resp.responseBody=Blob.valueOf('{"success":false,"error":"Null Pointer Exception"}');
        RestContext.response = resp;
        
        test.startTest();
        SPEN_SyncNRSWACaseDetails.createNRSWACaseFromWebform();
        test.stopTest();
        Assert.isNotNull(req.requestBody);
        
    }
}