force-app/main/default/objects/SPEN_CaseInformation__c/SPEN_CaseInformation__c.object-meta.xml
<CustomObject>
    <label>Case Information</label>
    <nameField>
        <displayFormat>CI-{00000000}</displayFormat>
        <label>Case Information Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_AssetConditionCode__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AssetConditionCode__c</fullName>
    <label>Asset Condition Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A01</fullName>
            </value>
            <value>
                <fullName>A03</fullName>
            </value>
            <value>
                <fullName>A04</fullName>
            </value>
            <value>
                <fullName>A05</fullName>
            </value>
            <value>
                <fullName>A07</fullName>
            </value>
            <value>
                <fullName>A10</fullName>
            </value>
            <value>
                <fullName>A12</fullName>
            </value>
            <value>
                <fullName>A14</fullName>
            </value>
            <value>
                <fullName>A15</fullName>
            </value>
            <value>
                <fullName>A17</fullName>
            </value>
            <value>
                <fullName>A19</fullName>
            </value>
            <value>
                <fullName>B01</fullName>
            </value>
            <value>
                <fullName>B02</fullName>
            </value>
            <value>
                <fullName>B03</fullName>
            </value>
            <value>
                <fullName>B04</fullName>
            </value>
            <value>
                <fullName>B05</fullName>
            </value>
            <value>
                <fullName>B07</fullName>
            </value>
            <value>
                <fullName>B08</fullName>
            </value>
            <value>
                <fullName>B10</fullName>
            </value>
            <value>
                <fullName>B11</fullName>
            </value>
            <value>
                <fullName>B12</fullName>
            </value>
            <value>
                <fullName>C02</fullName>
            </value>
            <value>
                <fullName>C03</fullName>
            </value>
            <value>
                <fullName>C06</fullName>
            </value>
            <value>
                <fullName>C07</fullName>
            </value>
            <value>
                <fullName>C11</fullName>
            </value>
            <value>
                <fullName>C14</fullName>
            </value>
            <value>
                <fullName>C15</fullName>
            </value>
            <value>
                <fullName>C16</fullName>
            </value>
            <value>
                <fullName>C17</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CRMD-731</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Information</relationshipLabel>
    <relationshipName>Case_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_Flowreceiveddate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Flowreceiveddate__c</fullName>
    <description>Created as part of CRMD-10581</description>
    <label>Flow received date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_LocationofDamage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LocationofDamage__c</fullName>
    <description>CRMD-7691</description>
    <label>Location of Damage</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_MPANCore__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MPANCore__c</fullName>
    <label>MPAN Core</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_SubStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SubStatus__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Contact Attempt – Day 1</fullName>
            </value>
            <value>
                <fullName>Customer Contact Attempt – Day 2 (AM)</fullName>
            </value>
            <value>
                <fullName>Customer Contact Attempt – Day 3 (PM)</fullName>
            </value>
            <value>
                <fullName>Customer Contact Attempt – Day 4 (OOH)</fullName>
            </value>
            <value>
                <fullName>28 day - letter 1 issued</fullName>
            </value>
            <value>
                <fullName>28 day - letter 2 issued</fullName>
            </value>
            <value>
                <fullName>28 day - letter 3 issued</fullName>
            </value>
            <value>
                <fullName>Missing Information Received</fullName>
            </value>
            <value>
                <fullName>Missing Information Requested</fullName>
            </value>
            <value>
                <fullName>Survey/Quote Review</fullName>
            </value>
            <value>
                <fullName>Quote Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/fields/SPEN_Town__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Town__c</fullName>
    <label>Town</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_CaseInformation__c/recordTypes/SPEN_3PDDamageForm.recordType-meta.xml
<RecordType>
    <fullName>SPEN_3PDDamageForm</fullName>
    <active>true</active>
    <label>3PD Damage Form</label>
</RecordType>

force-app/main/default/objects/SPEN_CaseInformation__c/recordTypes/SPEN_LCTRecordType.recordType-meta.xml
<RecordType>
    <fullName>SPEN_LCTRecordType</fullName>
    <active>true</active>
    <label>LCT</label>
</RecordType>

force-app/main/default/objects/SPEN_CaseInformation__c/recordTypes/SPEN_SmartIntervention.recordType-meta.xml
<RecordType>
    <fullName>SPEN_SmartIntervention</fullName>
    <active>true</active>
    <label>Smart Intervention</label>
</RecordType>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/fields/SPEN_Description__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/fields/SPEN_Value__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/recordTypes/Zone.recordType-meta.xml
<RecordType>
    <fullName>Zone</fullName>
    <active>true</active>
    <label>Zone</label>
</RecordType>

force-app/main/default/objects/SPEN_Zone__c/SPEN_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <label>IVR Message Temporary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_Parent__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Zone</relationshipLabel>
    <relationshipName>Zone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>District</fullName>
            </value>
            <value>
                <fullName>Zone</fullName>
            </value>
            <value>
                <fullName>Town</fullName>
            </value>
            <value>
                <fullName>Blanket</fullName>
                <isActive>false</isActive>
                <label>Blanket</label>
            </value>
            <value>
                <fullName>World</fullName>
                <isActive>false</isActive>
                <label>World</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_CaseInformationTriggerHandler_Test.cls
@isTest
public class SPEN_CaseInformationTriggerHandler_Test {
    Public static Id faultRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_UnplannedFault').getRecordTypeId();
    Public static Id bypassRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_UnplannedBypass').getRecordTypeId();
    Public static Id recordTypeIdIncident = Schema.SObjectType.Incident.getRecordTypeInfosByDeveloperName().get('SPEN_SPENIncident').getRecordTypeId();
    Public static Id recordTypeId3PD = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_ThirdPartyDamage').getRecordTypeId();
    Public static Id caseInfoRecordTypeId = Schema.SObjectType.SPEN_CaseInformation__c.getRecordTypeInfosByDeveloperName().get('SPEN_3PDDamageForm').getRecordTypeId();
    Public Static ID LCTRecordTypeId =  Schema.SObjectType.SPEN_CaseInformation__c.getRecordTypeInfosByDeveloperName().get('SPEN_LCTRecordType').getRecordTypeId();
	Public Static ID SIRecordTypeId =  Schema.SObjectType.SPEN_CaseInformation__c.getRecordTypeInfosByDeveloperName().get('SPEN_SmartIntervention').getRecordTypeId();

    
    @isTest 
    public static void creat3PDCaseTest4()
    {
       Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user);
        
        if (devOpsPSGroup.Status != 'Updated') 
        {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);	
        }  
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.Id;
        insert devOpsAssign; 
        PermissionSet ps3 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_CaseInformationCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps3.Id);
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_CaseThirdPartyDamageCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps.Id);
        System.runAs(user){
            Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
            Test.startTest();
             List<SPEN_ConfigurableSettings__c> csList=new List<SPEN_ConfigurableSettings__c>();
            SPEN_ConfigurableSettings__c cS =SPEN_TestDataFactory.createConfigSetting(1,'Incident broadcast message updated last one hour');
            csList.add(cS);
            SPEN_ConfigurableSettings__c cS1 =SPEN_TestDataFactory.createConfigSetting(1,'MessagingTaskType');
            csList.add(cS1);
            SPEN_ConfigurableSettings__c cS2 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelay');
            csList.add(cS2);
            SPEN_ConfigurableSettings__c cS3 =SPEN_TestDataFactory.createConfigSetting(1,'HV Incident Message');
            csList.add(cS3);
            SPEN_ConfigurableSettings__c cS4 =SPEN_TestDataFactory.createConfigSetting(1,'GetAffectedPremiseINCType');
            cS4.SPEN_Value__c = 'HV_N,HV_S,LV';
            cS4.SPEN_Description__c ='config setting description';
            csList.add(cS4);
            insert csList;
             SPEN_IVRMessage__c IVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
            Insert IVRMessage;
			
             Incident inc = new Incident();
            inc.Subject='Test Subject';
            inc.SPEN_IncidentReference__c='INCD-434014-r';
            inc.RecordTypeId=recordTypeIdIncident;
            insert inc;
            
            Case ThreePDCase =new Case();
            ThreePDCase.SPEN_Incident__c = inc.id;
            //ThreePDCase.SPEN_IncidentRefFormula__c = inc.SPEN_IncidentReference__c;
            ThreePDCase.Status ='Created';
            ThreePDCase.Priority='Medium';
            ThreePDCase.RecordTypeId = recordTypeId3PD;
            insert ThreePDCase;
            
          	
    		List<Account> testAccount = SPEN_TestDataFactory.createAccounts(SPEN_TestDataFactoryConstants.ACCNAME,SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert testAccount;
            Contact ct = SPEN_TestDataFactory.createContacts(testAccount[0].id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert ct;
            
            Case faultCase = new Case();
            faultCase.ContactId = ct.Id;
            faultCase.SPEN_CallerInitials__c = ct.Salutation;
            faultCase.SPEN_CallerMobileTelephone__c = ct.MobilePhone;
            faultCase.SPEN_CallerName__c = ct.Name;
            faultCase.SPEN_CallerTelephone__c = ct.Phone;
            faultCase.SPEN_CallerTitle__c = ct.Suffix;
            faultCase.status='Restored';
            faultCase.RecordTypeId = faultRecordTypeId;
            faultCase.Subject = 'Damaged Equipment Wizard Case';
            faultCase.SPEN_Incident__c = inc.id;
           	insert faultCase;
            
             SPEN_CaseInformation__c caseInfo = new SPEN_CaseInformation__c();
            caseInfo.recordtypeid = caseInfoRecordTypeId;
            caseInfo.SPEN_Case__c = ThreePDCase.id;
            insert caseInfo;
            
             SPEN_Zone__c SPDZoneParent = SPEN_TestDataFActory.createZoneRecords(IVRMessage.id);
            SPDZoneParent.name = 'Ayrshire';
            SPDZoneParent.SPEN_Type__c = 'Zone';
            insert SPDZoneParent;
            
            SPEN_Zone__c SPDZone = SPEN_TestDataFActory.createZoneRecords(IVRMessage.id);
            SPDZone.name = 'CLYDE SOUTH';
            SPDZone.SPEN_Type__c = 'Zone';
            SPDZone.SPEN_Parent__c = SPDZoneParent.Id;
            insert SPDZone;
            
            SPEN_Zone__c townRecord = SPEN_TestDataFActory.createZoneRecords(IVRMessage.id);
            townRecord.SPEN_Type__c = 'Town';
            townRecord.name = 'Test Town';
            townRecord.SPEN_Parent__c = SPDZone.Id;
            insert townRecord;
            
            faultCase.SPEN_Incident__c = null;
            update faultCase;
            Case bypassCase = new Case();
            bypassCase.ContactId = ct.Id;
            bypassCase.SPEN_CallerInitials__c = ct.Salutation;
            bypassCase.SPEN_CallerMobileTelephone__c = ct.MobilePhone;
            bypassCase.SPEN_CallerName__c = ct.Name;
            bypassCase.SPEN_CallerTelephone__c = ct.Phone;
            bypassCase.SPEN_CallerTitle__c = ct.Suffix;
            bypassCase.status='Restored';
            bypassCase.SPEN_Town__c = townRecord.id;
            bypassCase.RecordTypeId = bypassRecordTypeId;
            bypassCase.Subject = 'Damaged Equipment Wizard Case';
            bypassCase.SPEN_Incident__c = inc.id;
           	insert bypassCase;
            
            SPEN_CaseInformation__c caseInfo1 = new SPEN_CaseInformation__c();
            caseInfo1.recordtypeid = caseInfoRecordTypeId;
            caseInfo1.SPEN_Case__c = ThreePDCase.id;
            insert caseInfo1;

//Added to cover blocks in interface class
            caseInfo1.SPEN_LocationofDamage__c = 'test';
            update caseInfo1;
            
            SPEN_CaseInformation__c caseInfo2 = new SPEN_CaseInformation__c();
            caseInfo2.recordtypeid = LCTRecordTypeId;
            caseInfo2.SPEN_Case__c = ThreePDCase.id;
            insert caseInfo2;
			caseInfo2.SPEN_SubStatus__c = 'Missing Information Requested';
            update caseInfo2;
            //Added to cover blocks in interface class
            caseInfo1.SPEN_LocationofDamage__c = 'test';
            update caseInfo1;
            SPEN_CaseInformationInterface obj = new SPEN_CaseInformationInterface(); 
            Map<Id, sObject> deleteMap = new Map<Id,sObject>();
            deleteMap.put(caseInfo1.id,caseInfo1);
            obj.beforeDelete(deleteMap);
            obj.afterDelete(deleteMap);
            obj.afterUndelete(deleteMap);
            Test.stopTest();
            
        }
    }

    
    @isTest
    static void calculateAndSetDatesTest() {
        // Create test data
        BusinessHours bh = [SELECT Id FROM BusinessHours WHERE Name = 'Connection Business Hours' LIMIT 1];
        //SPEN_CaseInformation__c caseInfo = new SPEN_CaseInformation__c(SPEN_FlowReceivedDate__c = Datetime.now());
        SPEN_CaseInformation__c caseInfo = new SPEN_CaseInformation__c();
        caseInfo.RecordTypeId = SIRecordTypeId;
        caseInfo.SPEN_MPANCore__c = '1800000000';
        caseInfo.SPEN_AssetConditionCode__c = 'B06';
        caseInfo.SPEN_FlowReceivedDate__c = Datetime.now();
        insert caseInfo;
        //insert caseInfo;
        // Call the helper method
        Test.startTest();
        List<SPEN_CaseInformation__c> caseInfosToUpdate = new List<SPEN_CaseInformation__c>{caseInfo};
            if(!caseInfosToUpdate.isEmpty() && caseInfosToUpdate.size() > 0 ){
                SPEN_CaseInformationTriggerHandler.calculateAndSetDates(caseInfosToUpdate);
            }
        SPEN_CaseInformationInterface handler = new SPEN_CaseInformationInterface();
        handler.beforeInsert(new List<SObject>{caseInfo});
        Test.stopTest();
    }
    @isTest
    static void calculateAndSetDatesTestNull() {
        // Create test data
        BusinessHours bh = [SELECT Id FROM BusinessHours WHERE Name = 'SPEN GE SPD Business Hours' LIMIT 1];
        SPEN_CaseInformation__c caseInfo = new SPEN_CaseInformation__c(SPEN_FlowReceivedDate__c = null);
        insert caseInfo;
        // Call the helper method
        Test.startTest();
        List<SPEN_CaseInformation__c> caseInfosToUpdate = new List<SPEN_CaseInformation__c>{caseInfo};
            if(!caseInfosToUpdate.isEmpty() && caseInfosToUpdate.size() > 0 ){
                SPEN_CaseInformationTriggerHandler.calculateAndSetDates(caseInfosToUpdate);
        SPEN_CaseInformationInterface handler = new SPEN_CaseInformationInterface();
        handler.beforeInsert(new List<SObject>{caseInfo});
            }
        Test.stopTest();
    }
}