force-app/main/default/objects/SPEN_ResourceDetail__c/SPEN_ResourceDetail__c.object-meta.xml
<CustomObject>
    <description>Resource Detail object has been set up to use for resource Incident case API</description>
    <label>Resource Detail</label>
    <nameField>
        <label>Resource Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ResourceDetail__c/fields/SPEN_Comment__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Comment__c</fullName>
    <label>Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_ResourceDetail__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ResourceDetail__c/fields/SPEN_EventDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EventDate__c</fullName>
    <label>Event Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_ResourceDetail__c/fields/SPEN_Incident__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Incident__c</fullName>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Resource Details</relationshipLabel>
    <relationshipName>Resource_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_ResourceDetail__c/fields/SPEN_ResourceName__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ResourceName__c</fullName>
    <label>Resource Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SPEN_createNRSWAQueryCase.cls
/***************************************************************************
* @Author:      Shubhi 
* @Date:        25/09/2023
* @UserStory:   CRMD-7413	
* @Description: class for creating NRSWA query case for resource detail arrival on site 
*****************************************************************************/
public with sharing class SPEN_createNRSWAQueryCase {
    
   	@InvocableMethod(category='SPEN' label='SPEN NRSWA query case' description='Create NRSWA query case for resource detail')
    public static void createNRSWAQueryCase(List<SPEN_ResourceDetail__c> resourceDetail){
        if(resourceDetail!=null && resourceDetail[0]!=null){
			Incident inc=IncidentSelector.getIncRecordById(resourceDetail[0].SPEN_Incident__c);
            insertQueryCase(resourceDetail[0],inc);
        }
    }
    private static void insertQueryCase(SPEN_ResourceDetail__c resdetail,Incident inc){
        Case nRSWAcase=new Case();
        Id recordTypeIdQuery = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_Query').getRecordTypeId();
        nRSWAcase.recordTypeId=recordTypeIdQuery;
        nRSWACase.SPEN_Type__c=CasesConstants.nrswaType;
        nRSWACase.status=CasesConstants.openStatus;//'Open';
        nRSWACase.Origin=CasesConstants.poweronOrigin;
        nrswaCase.Description ='Resource Name: '+ resdetail.SPEN_ResourceName__c +'\n'+ 'Event Date: '+  resdetail.SPEN_EventDate__c + '\n'+'Log Comment: '+resdetail.SPEN_Comment__c;
        //nRSWACase.Description=resdetail.SPEN_ResourceName__c+' '+resdetail.SPEN_Comment__c;
        nRSWACase.SPEN_QueryReason__c='Resource - '+resdetail.SPEN_Event__c;
        if(inc!=null){
          nRSWACase.SPEN_Incident__c=inc.id;
          nRSWACase.SPEN_SPDSPMIndicator__c=inc.SPEN_SPDSPM__c; 
          nRSWACase.SPEN_IncidentReference__c=inc.SPEN_IncidentReference__c; 
        }
        if(inc.SPEN_SPDSPM__c == 'SPM' && nrswaCase.SPEN_Email_WI_Queue_Routing_Outcome__c == NULL){//9376
            nrswaCase.SPEN_Email_WI_Queue_Routing_Outcome__c='2 Hr SLA South';
            
        }
         if(inc.SPEN_SPDSPM__c == 'SPM' && !nrswaCase.SPEN_Email_WI_Queue_Routing_Outcome__c.containsIgnoreCase('High')){//9376
            nrswaCase.SPEN_Email_WI_Queue_Routing_Outcome__c='2 Hr SLA South';
            
        }else if(inc.SPEN_SPDSPM__c == 'SPD' && nrswaCase.SPEN_Email_WI_Queue_Routing_Outcome__c == NULL){//9376
            nrswaCase.SPEN_Email_WI_Queue_Routing_Outcome__c='2 Hr SLA North';
            
        }
        else if(inc.SPEN_SPDSPM__c == 'SPD' && !nrswaCase.SPEN_Email_WI_Queue_Routing_Outcome__c.containsIgnoreCase('High')){//9376
            nrswaCase.SPEN_Email_WI_Queue_Routing_Outcome__c='2 Hr SLA North';
            
        }
        /*if(nRSWACase.SPEN_SPDSPMIndicator__c=='SPD'){
           //Group queueTobeAssigned = new SPEN_GroupsSelector().selectByQueueName('NRSWA_SPD');
           //nRSWACase.ownerId = queueTobeAssigned.id;
           /*BusinessHours bsHr=SPEN_BusinessHourSelector.getBusinessHrsByName(CasesConstants.NRSWA_SPD_BUSINESSHOUR);
           if(bsHr!=null){
              nRSWACase.BusinessHoursId=bsHr.id;
           }
        }else if(nRSWACase.SPEN_SPDSPMIndicator__c=='SPM'){
           //Group queueTobeAssigned = new SPEN_GroupsSelector().selectByQueueName('NRSWA_SPM');
           //nRSWACase.ownerId = queueTobeAssigned.id;
           /*BusinessHours bsHr=SPEN_BusinessHourSelector.getBusinessHrsByName(CasesConstants.NRSWA_SPM_BUSINESSHOUR);
           if(bsHr!=null){
               nRSWACase.BusinessHoursId=bsHr.id;
           }
        }*/
        insert nRSWACase;
        Set<Id> setCaseId = new Set<Id>();
        setCaseId.add(nrswaCase.id);
        System.enqueueJob(new SPEN_JourneySLAQueueable(setCaseId));
    }
}