force-app/main/default/objects/SPEN_ResourceDetail__c/SPEN_ResourceDetail__c.object-meta.xml
<CustomObject>
    <description>Resource Detail object has been set up to use for resource Incident case API</description>
    <label>Resource Detail</label>
    <nameField>
        <label>Resource Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ResourceDetail__c/fields/SPEN_Comment__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Comment__c</fullName>
    <label>Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_ResourceDetail__c/fields/SPEN_Company__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Company__c</fullName>
    <label>Company</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_ResourceDetail__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ResourceDetail__c/fields/SPEN_EventDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EventDate__c</fullName>
    <label>Event Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_ResourceDetail__c/fields/SPEN_Incident__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Incident__c</fullName>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Resource Details</relationshipLabel>
    <relationshipName>Resource_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_ResourceDetail__c/fields/SPEN_ResourceName__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ResourceName__c</fullName>
    <label>Resource Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SPEN_createNRSWAQueryCaseTest.cls
@isTest
@SuppressWarnings('PMD.SOQLSelectorPattern')
public class SPEN_createNRSWAQueryCaseTest {
    @testSetup static void setup(){
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user);
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        if (devOpsPSGroup.Status != 'Updated') {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);
        }
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.Id;
        insert devOpsAssign;
        System.runAS(user){
            List<Incident> lstInct = SPEN_TestDataFactory.createListofIncidents(1);
            lstInct[0].SPEN_IncidentCategory__c = 'SP';
            lstInct[0].SPEN_IncidentID__c = '123';
            lstInct[0].SPEN_IncidentReference__c = 'INCD-588323-k';
            insert lstInct;
            
            SPEN_ResourceDetail__c redRecord = new SPEN_ResourceDetail__c();
            redRecord.SPEN_Company__c = 'MORRISON';
            redRecord.SPEN_Comment__c = 'test';
            redRecord.SPEN_ResourceName__c = 'sfdc';
            //redRecord.SPEN_EventDate__c = '2023-07-27T12:45:35.000+01:00';
            redRecord.SPEN_EventDate__c = System.now();
            redRecord.SPEN_Incident__c = lstInct[0].Id;
            redRecord.SPEN_Event__c = 'Arrival On Site';
            insert redRecord;
        }
    }
    @isTest
    public static void createNRSWAQueryCaseTestPositive(){
        Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
       List<SPEN_ResourceDetail__c> resourceDetail=[Select id,SPEN_ResourceName__c,SPEN_Comment__c,SPEN_Event__c,SPEN_EventDate__c,SPEN_Incident__c from SPEN_ResourceDetail__c where id!=null];
       SPEN_createNRSWAQueryCase.createNRSWAQueryCase(resourceDetail);
      Case nrswacase=[Select id from case where recordType.developername='SPEN_Query' and SPEN_type__c='NRSWA'];
      Assert.isTrue(nrswacase!=null);
    }
    @isTest
    public static void createNRSWAQueryCaseTestNegative(){
        Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
       List<SPEN_ResourceDetail__c> resourceDetail;//[Select id,SPEN_ResourceName__c,SPEN_Comment__c,SPEN_Event__c,SPEN_Incident__c from SPEN_ResourceDetail__c];
       SPEN_createNRSWAQueryCase.createNRSWAQueryCase(resourceDetail);
        try{
            Case nrswacase=[Select id from case where recordType.developername='SPEN_Query' and SPEN_type__c='NRSWA'];
        }catch(Exception e){
             Assert.isTrue(e!=null);
        }
    }
}