force-app/main/default/objects/SFBG_Answer__c/SFBG_Answer__c.object-meta.xml
<CustomObject>
    <description>Represents an Answer record. Part of the Dynamic Questionnaire asset created by Macjules Sevilla.</description>
    <label>Answer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SFBG_Answer__c/fields/SFBG_Answer__c.field-meta.xml
<CustomField>
    <fullName>SFBG_Answer__c</fullName>
    <description>The label to display in the custom rendering engine.</description>
    <label>Answer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SFBG_Answer__c/fields/SFBG_Order__c.field-meta.xml
<CustomField>
    <fullName>SFBG_Order__c</fullName>
    <description>The order by which the answers are displayed in the rendering engine. Use 100 as intervals.</description>
    <label>Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SFBG_Answer__c/fields/SFBG_QuestionId__c.field-meta.xml
<CustomField>
    <fullName>SFBG_QuestionId__c</fullName>
    <description>The question record where this answer record is related.</description>
    <label>Question</label>
    <referenceTo>SFBG_Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>SFBG_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SFBG_Answer__c/fields/SFBG_QuestionToDisplayId__c.field-meta.xml
<CustomField>
    <fullName>SFBG_QuestionToDisplayId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use this to open the next question.</description>
    <label>Question to Display</label>
    <referenceTo>SFBG_Question__c</referenceTo>
    <relationshipLabel>Answers (Question to Display)</relationshipLabel>
    <relationshipName>SFBG_QuestionsToDisplay</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFBG_Answer__c/fields/SFBG_Value__c.field-meta.xml
<CustomField>
    <fullName>SFBG_Value__c</fullName>
    <description>The value of the answer. In most cases, this value will be equal to the Answer however this can be replaced with some code value.</description>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/SFBG_Question__c.object-meta.xml
<CustomObject>
    <description>Represents a Question record. Part of the Dynamic Questionnaire asset created by Macjules Sevilla.</description>
    <label>Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_HelpText__c.field-meta.xml
<CustomField>
    <fullName>SFBG_HelpText__c</fullName>
    <description>Help text to display in the custom rendering engine.</description>
    <inlineHelpText>Fill this out only if you want a help text to show up in the questionnaire form.</inlineHelpText>
    <label>Help Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_InformationCategory__c.field-meta.xml
<CustomField>
    <fullName>SFBG_InformationCategory__c</fullName>
    <description>Information to be displayed is of the following category</description>
    <label>Information Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_Question__c.field-meta.xml
<CustomField>
    <fullName>SFBG_Question__c</fullName>
    <description>The question to display in the custom rendering engine.</description>
    <label>Question</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_QuestionnaireId__c.field-meta.xml
<CustomField>
    <fullName>SFBG_QuestionnaireId__c</fullName>
    <description>The questionnaire record where this question record is related.</description>
    <label>Questionnaire</label>
    <referenceTo>SFBG_Questionnaire__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>SFBG_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/fields/SFBG_QuestionToDisplayId__c.field-meta.xml
<CustomField>
    <fullName>SFBG_QuestionToDisplayId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use this to open the next question if the Question Type is Textbox.</description>
    <label>Question To Display</label>
    <referenceTo>SFBG_Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>QuestionsToDisplayFromQuestion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/fields/SPEN_CallOutcome__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CallOutcome__c</fullName>
    <label>Call Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SPEN_CategoryOutcome</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFBG_Question__c/recordTypes/Information.recordType-meta.xml
<RecordType>
    <fullName>Information</fullName>
    <active>true</active>
    <label>Information</label>
</RecordType>

force-app/main/default/objects/SFBG_Question__c/recordTypes/Textbox.recordType-meta.xml
<RecordType>
    <fullName>Textbox</fullName>
    <active>true</active>
    <label>Textbox</label>
</RecordType>

force-app/main/default/objects/SFBG_Questionnaire__c/SFBG_Questionnaire__c.object-meta.xml
<CustomObject>
    <description>Represents a Questionnaire record. Part of the Dynamic Questionnaire asset created by Macjules Sevilla.</description>
    <label>Questionnaire</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SFBG_Questionnaire__c/fields/SFBG_StartingQuestionId__c.field-meta.xml
<CustomField>
    <fullName>SFBG_StartingQuestionId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The starting question of the questionnaire.</description>
    <label>Starting Question</label>
    <referenceTo>SFBG_Question__c</referenceTo>
    <relationshipLabel>Questionnaires with Starting Question Record</relationshipLabel>
    <relationshipName>QuestionnairesWithStartingQuestionId</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFBG_Questionnaire__c/fields/SPEN_CategoryCriticalInfo__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CategoryCriticalInfo__c</fullName>
    <label>Category Critical Information</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SFBG_Questionnaire__c/fields/SPEN_CategoryRemarks__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CategoryRemarks__c</fullName>
    <label>Category Remarks</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SFBG_DynamicCallWizardService.cls
/*-----------------------------------------------------------------------------
DESCRIPTION	:	Service class of the Dynamic Call Wizard. Currently contains Selector Code also. Refinement In Progress.
LIBRARY		:	Salesforce Enterprise Library - Dynamic Call Wizard Framework
VERSION		:	1.0

HISTORY		:
Date			Author				    Comment
SEP-21-2022		Bhagyashree Mandlik     Initial version
-----------------------------------------------------------------------------*/
public inherited sharing class SFBG_DynamicCallWizardService {
  @AuraEnabled
  public static List<SFBG_DynamicCallWizardController.WizardTriageQuestionnaireWrapper> getQuestionnaire(
    String launchVal
  ) {
    try {
      List<SFBG_DynamicCallWizardController.WizardTriageQuestionnaireWrapper> questionnaireData = new List<SFBG_DynamicCallWizardController.WizardTriageQuestionnaireWrapper>();
      List<SFBG_Questionnaire__c> questionnaireList = SFBG_DynamicCallWizardSelector.getQuestionnaireList(
        launchVal
      );
      SFBG_DynamicCallWizardController.WizardTriageQuestionnaireWrapper questionnaireDataToSend = new SFBG_DynamicCallWizardController.WizardTriageQuestionnaireWrapper();

      if (!questionnaireList.isEmpty()) {
        for (SFBG_Questionnaire__c quest : questionnaireList) {
          questionnaireDataToSend.questionnaireId = quest.Id;
          questionnaireDataToSend.questionnaireName = quest.Name;
          questionnaireDataToSend.questionnaireCriticalInfo = quest.SPEN_CategoryCriticalInfo__c;
          questionnaireDataToSend.questionnaireRemarks = quest.SPEN_CategoryRemarks__c;
          questionnaireDataToSend.firstquestion = getQuesAndAnsToDisplay(
            quest.Id,
            quest.SFBG_StartingQuestionId__c
          );
          questionnaireData.add(questionnaireDataToSend);
        }
      }
      return questionnaireData;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static SFBG_DynamicCallWizardController.WizardTriageQuestionWrapper getQuesAndAnsToDisplay(
    Id questionnaireId,
    Id quesId
  ) {
    try {
      SFBG_DynamicCallWizardController.WizardTriageQuestionWrapper questionData = new SFBG_DynamicCallWizardController.WizardTriageQuestionWrapper();
      SFBG_Question__c question = SFBG_DynamicCallWizardSelector.getQuesToDisplayList(
        questionnaireId,
        quesId
      );
      List<SFBG_DynamicCallWizardController.WizardTriageAnswerWrapper> answerListToSend = new List<SFBG_DynamicCallWizardController.WizardTriageAnswerWrapper>();
      Map<SFBG_Question__c, List<SFBG_Answer__c>> quesAnsMap = new Map<SFBG_Question__c, List<SFBG_Answer__c>>();
      List<SFBG_Answer__c> answerList = SFBG_DynamicCallWizardSelector.getAnswerToDisplayList(
        quesId
      );
      Boolean nextQfromA = false;
      if (question != null) {
        questionData.questionnaireId = question.SFBG_QuestionnaireId__c;
        questionData.questionId = question.Id;
        questionData.questionLabelToDisplay = question.SFBG_Question__c;
        questionData.questionRecType = question.RecordType.DeveloperName;
        if (question.SFBG_QuestionToDisplayId__c != null) {
          questionData.nextQuestionfromQuesId = question.SFBG_QuestionToDisplayId__c;
        }
        questionData.informationQuestionType = question.SFBG_InformationCategory__c;
        questionData.questionHelpText = question.SFBG_HelpText__c;
        questionData.questionOutcome = question.SPEN_CallOutcome__c;
      }
      if (!answerList.isEmpty()) {
        for (SFBG_Answer__c answer : answerList) {
          SFBG_DynamicCallWizardController.WizardTriageAnswerWrapper currAnswer = new SFBG_DynamicCallWizardController.WizardTriageAnswerWrapper();

          currAnswer.answerId = answer.Id;
          currAnswer.answerValueToDisplay = answer.SFBG_Answer__c;
          currAnswer.answerValue = answer.SFBG_Value__c;
          currAnswer.answerOrder = answer.SFBG_Order__c;
          currAnswer.currentQuestionId = answer.SFBG_QuestionId__c;
          if (answer.SFBG_QuestionToDisplayId__c != null) {
            currAnswer.nextQuestionId = answer.SFBG_QuestionToDisplayId__c;
            nextQfromA = true;
          } else{            
            questionData.isLastQuestion = true;
          }
          answerListToSend.add(currAnswer);
        }
      }
      if (questionData.nextQuestionfromQuesId == null && nextQfromA == false) {
        questionData.isLastQuestion = true;
      }

      questionData.answers = answerListToSend;
      return questionData;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static SFBG_DynamicCallWizardController.WizardTriageQuestionWrapper getNextQuesFromAns(
    Id answerId,
    Id quesId
  ) {
    try {
      SFBG_DynamicCallWizardController.WizardTriageQuestionWrapper wrapperToReturn = new SFBG_DynamicCallWizardController.WizardTriageQuestionWrapper();
      List<SFBG_Answer__c> ansList = SFBG_DynamicCallWizardSelector.getNextQuesFromAns(
        answerId,
        quesId
      );
      SFBG_Question__c currentQuestion = SFBG_DynamicCallWizardSelector.checkIfQuestionTypeText(
        quesId
      );

      if (
        ansList.size() > 0 &&
        ansList[0].SFBG_QuestionToDisplayId__c != null
      ) {
        wrapperToReturn = getQuesAndAnsToDisplay(
          ansList[0].SFBG_QuestionId__r.SFBG_QuestionnaireId__c,
          ansList[0].SFBG_QuestionToDisplayId__c
        );
      }

      if (
        currentQuestion.RecordType.Name == 'Textbox' ||
        currentQuestion.RecordType.Name == 'Information'
      ) {
        wrapperToReturn = getQuesAndAnsToDisplay(
          currentQuestion.SFBG_QuestionnaireId__c,
          currentQuestion.SFBG_QuestionToDisplayId__c
        );
      }
      wrapperToReturn.previousQuestionId = quesId;
      return wrapperToReturn;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static Case createCasefromCallWizard(
    String caseData,
    Boolean isBypassCase
  ) {
    try {
      String result;
      Id insertedRecord;
      SFBG_DynamicCallWizardController.WizardTriageNewCaseWrapper caseDataWrapper = (SFBG_DynamicCallWizardController.WizardTriageNewCaseWrapper) System.JSON.deserializeStrict(
        caseData,
        SFBG_DynamicCallWizardController.WizardTriageNewCaseWrapper.class
      );
      Case wizardCase = new Case();
      wizardCase.Status = caseDataWrapper.caseStatus;
      wizardCase.Subject = caseDataWrapper.caseSubject;
      wizardCase.Origin = caseDataWrapper.caseOrigin;
      wizardCase.SPEN_CaseCategoryOutcome__c = caseDataWrapper.caseCategoryOutcome;
      wizardCase.SPEN_CaseProblemCategory__c = caseDataWrapper.caseProblemCategory;
      wizardCase.SPEN_WizardHistory__c = caseDataWrapper.caseHistory;
      wizardCase.SPEN_Incident__c = caseDataWrapper.caseRelatedIncident;

      if (
        caseDataWrapper.caseCategoryOutcome ==
        SFBG_DynamicCallWizardConstant.Case_KeyMeter
      ) {
        if (caseDataWrapper.keyMeterRemarks == 'faulty') {
          caseDataWrapper.caseRemarks = addAutoPopulationFields(
            'Meter Faulty',
            caseDataWrapper.caseRemarks
          );
        } else if (caseDataWrapper.keyMeterRemarks == 'lost') {
          caseDataWrapper.caseRemarks = addAutoPopulationFields(
            'Lost or Faulty Key',
            caseDataWrapper.caseRemarks
          );
        }
      }
      wizardCase.SPEN_Remarks__c = caseDataWrapper.caseRemarks;
      wizardCase.SPEN_CriticalInformation__c = caseDataWrapper.caseCriticalInformation;
      if (isBypassCase == true) {
        wizardCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
          .get(CasesConstants.Case_UnplannedBypass)
          .getRecordTypeId();
      }
      else
      {
          wizardCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
          .get(CasesConstants.Case_UnplannedFault)
          .getRecordTypeId();
      }
      //Written by Ayush
      if (caseDataWrapper.casePremiseId != null) {
        wizardCase.SPEN_AddressPremise__c = caseDataWrapper.casePremiseId;
      }
      //Written by Ayush
      if (caseDataWrapper.caseContactId != null) {
        Contact callerData = SFBG_CommonDynamicWizardService.getPreferredContactMethod(
          caseDataWrapper.caseContactId
        );
        wizardCase.ContactId = caseDataWrapper.caseContactId;
        wizardCase.SPEN_PreferredMethodofContact__c = caseDataWrapper.contPrefMethod;
        wizardCase.SPEN_CallerName__c = callerData.Name;
        wizardCase.SPEN_CallerTitle__c = callerData.Title;
      }
      Database.SaveResult dataSaveRes = Database.insert(wizardCase);
      if (dataSaveRes.isSuccess()) {
        insertedRecord = dataSaveRes.getId();
      }
      List<Case> caseToReturn = SPEN_CaseSelector.getCaseNumber(insertedRecord);
      return caseToReturn[0];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static SFBG_DynamicCallWizardController.WizardTriageQuestionWrapper getPrevQuestion(
    Id questionnaireId,
    Id quesId
  ) {
    try {
      SFBG_DynamicCallWizardController.WizardTriageQuestionWrapper wrapperToReturn = getQuesAndAnsToDisplay(
        questionnaireId,
        quesId
      );
      Map<List<Id>, Boolean> prevQId = SFBG_DynamicCallWizardSelector.getPrevQuesId(
        questionnaireId,
        quesId
      );
      Boolean isfirstQuestion = false;
      for (List<Id> idValue : prevQId.keyset()) {
        isfirstQuestion = prevQId.get(idValue);
        if (!isfirstQuestion) {
          wrapperToReturn.previousQuestionId = idValue[0];
        }
      }
      return wrapperToReturn;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  public static String addAutoPopulationFields(
    String infoToAdd,
    String destField
  ) {
    try {
      if (
        destField != '' ||
        destField != null ||
        destField != 'undefined' ||
        destField != 'null'
      ) {
        destField = infoToAdd + ': ' + destField;
      } else {
        destField = infoToAdd;
      }
      return destField;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled(cacheable=true)
  public static CasesConstants getAllConstants() {
      return new CasesConstants();
  }

  @AuraEnabled
  public static SPEN_Premise__c getPremiseDetails(Id premiseId){
    try {
     
      SPEN_Premise__c premise = new SPEN_Premise__c();
      premise = SPEN_DynamicWizardServiceHelper.getPremiseData(premise,premiseId); 
      return premise;
      
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static void updateVoiceCall(Id voiceCallId, Id caseId) {
    if(voiceCallId != NULL && caseId != NULL){
      SFBG_DynamicCallWizardSelector.updateVoiceCallRec(voiceCallId);
      VoiceCall vcToUpdate = new VoiceCall();
      vcToUpdate.Id = voiceCallId;
      vcToUpdate.SPEN_VCCase__c = caseId;
      SPEN_DynamicWizardServiceHelper.updateVoiceCall(vcToUpdate);
    }
  }
  
}