force-app/main/default/objects/SPEN_IncidentAutomaticRefresh__mdt/SPEN_IncidentAutomaticRefresh__mdt.object-meta.xml
<CustomObject>
    <description>The incident record page will automatically refresh</description>
    <label>Incident Automatic Refresh</label>
    <pluralLabel>Incident Automatic Refresh</pluralLabel>
</CustomObject>

force-app/main/default/objects/SPEN_IncidentAutomaticRefresh__mdt/fields/SPEN_Channel__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Channel__c</fullName>
    <label>Channel</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IncidentAutomaticRefresh__mdt/fields/SPEN_IsActive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SPEN_IncidentInsertUpdateMetadata_TEST.cls
/*-------------------------------------------------------------------------------------------------------------------
DESCRIPTION: UNIT TEST CLASS FOR SPEN_IncidentInsertUpdateMetadata.apxc and SPEN_PushTopicController.apxc classes
AUTHOR                      VERSION       	 DATE       		Details
Sheker Kulkacherla            1            23/11/2022         CRMD-440 View Current Reactive Incidents
----------------------------------------------------------------------------------------------------------------*/
@isTest
global class SPEN_IncidentInsertUpdateMetadata_TEST {
	@isTest
     public static void getIncidentData(){
         
         SPEN_IncidentAutomaticRefresh__mdt incRecord = [SELECT SPEN_Channel__c,SPEN_IsActive__c from SPEN_IncidentAutomaticRefresh__mdt LIMIT 1];     
          Test.startTest();
          SPEN_IncidentInsertUpdateMetadata.getChannel();
          System.assertEquals('IncidentInsertAndUpdates', incRecord.SPEN_Channel__c);
          System.assertEquals(true, incRecord.SPEN_IsActive__c);
          Test.stopTest();
    }
}