force-app/main/default/objects/SPEN_IncidentAutomaticRefresh__mdt/SPEN_IncidentAutomaticRefresh__mdt.object-meta.xml
<CustomObject>
    <description>The incident record page will automatically refresh</description>
    <label>Incident Automatic Refresh</label>
    <pluralLabel>Incident Automatic Refresh</pluralLabel>
</CustomObject>

force-app/main/default/objects/SPEN_IncidentAutomaticRefresh__mdt/fields/SPEN_Channel__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Channel__c</fullName>
    <label>Channel</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SPEN_IncidentInsertUpdateMetadata.cls
/*-------------------------------------------------------------------------------------------------------------------
DESCRIPTION: Apex CLASS SPEN_IncidentInsertUpdateMetadata.apxc for Incident Record Auto Refresh
AUTHOR                      VERSION       	 DATE       		Details
Sheker Kulkacherla            1            23/11/2022         CRMD-440 View Current Reactive Incidents
----------------------------------------------------------------------------------------------------------------*/
global with sharing class SPEN_IncidentInsertUpdateMetadata {
    @AuraEnabled
    public static String getChannel(){
        SPEN_IncidentAutomaticRefresh__mdt incidentRecord = SPEN_IncidentAutomaticRefresh__mdt.getInstance(SPEN_ConstantData.INCIDENTINSERTANDUPDATES);
        return string.valueOf(incidentRecord.SPEN_Channel__c);
    }
}