force-app/main/default/objects/SPEN_CallDetails__c/SPEN_CallDetails__c.object-meta.xml
<CustomObject>
    <description>This custom object will be used as an extension of the Voice Call object</description>
    <label>Call Details</label>
    <nameField>
        <displayFormat>CD-{00000000}</displayFormat>
        <label>Call Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CallDetails__c/fields/SPEN_MPAN_Number__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MPAN_Number__c</fullName>
    <label>MPAN Number</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IVR__c/SPEN_IVR__c.object-meta.xml
<CustomObject>
    <description>This object will hold IVR flow details.</description>
    <label>IVR</label>
    <nameField>
        <label>IVR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVR__c/fields/SPEN_CallGroup__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CallGroup__c</fullName>
    <label>Call Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SPEN_CallGroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/SPEN_MPAN__c.object-meta.xml
<CustomObject>
    <description>MPAN object is used to see MPAN related data.</description>
    <label>MPAN/Meter</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MPAN Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPAN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_AccountNumberMPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AccountNumberMPAN__c</fullName>
    <description>The account number associated with a call - PO map this to the MPAN. Question - what if there are multiple MPANS associated? Can this be cross checked</description>
    <externalId>true</externalId>
    <label>MPAN</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_ConnectionStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ConnectionStatus__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <label>Connection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disconnected</fullName>
            </value>
            <value>
                <fullName>Unmetered Supply</fullName>
            </value>
            <value>
                <fullName>Energised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>MPAN</relationshipLabel>
    <relationshipName>MPAN</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Status of the smart meter - energised, de-energised</description>
    <label>Smart Meter Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_AccountNumberMPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AccountNumberMPAN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account number is look up with Account Number (MPAN) field of MPAN object</description>
    <label>Account Number (MPAN)</label>
    <referenceTo>SPEN_MPAN__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_MPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MPAN__c</fullName>
    <description>A text box to capture MPAN number to be sent to ADQM.</description>
    <label>MPAN</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <description>Select type from dropdown list.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Unmetered Supply</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Generators- HV/LV</fullName>
                <isActive>false</isActive>
                <label>Generators- HV/LV</label>
            </value>
            <value>
                <fullName>Generators- Renewable</fullName>
                <isActive>false</isActive>
                <label>Generators- Renewable</label>
            </value>
            <value>
                <fullName>Generators- Traditional</fullName>
                <isActive>false</isActive>
                <label>Generators- Traditional</label>
            </value>
            <value>
                <fullName>Large Business</fullName>
                <isActive>false</isActive>
                <label>Large Business</label>
            </value>
            <value>
                <fullName>Small Business</fullName>
                <isActive>false</isActive>
                <label>Small Business</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Voicemail__c/SPEN_Voicemail__c.object-meta.xml
<CustomObject>
    <description>Omni-channel work item to distribute voicemail assignments to agents.</description>
    <label>Voicemail</label>
    <nameField>
        <displayFormat>VCM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voicemails</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Voicemail__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Voicemail__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <description>Indicates what type of call the voicemail is.</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Voicemail__c/fields/SPEN_VoiceCallId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_VoiceCallId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The voice call record where an Agent can find the recording and transcription.</description>
    <label>Voice Call</label>
    <referenceTo>VoiceCall</referenceTo>
    <relationshipLabel>Voicemails</relationshipLabel>
    <relationshipName>SPEN_Voicemails</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/SPEN_CallGroup.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General Enquiries</fullName>
    </customValue>
    <customValue>
        <fullName>MPAS</fullName>
    </customValue>
    <customValue>
        <fullName>PSR</fullName>
    </customValue>
    <customValue>
        <fullName>SPD</fullName>
    </customValue>
    <customValue>
        <fullName>SPM</fullName>
    </customValue>
    <customValue>
        <fullName>Unclassified</fullName>
    </customValue>
    <customValue>
        <fullName>Streetworks_South</fullName>
    </customValue>
    <customValue>
        <fullName>Streetworks_North</fullName>
    </customValue>
    <customValue>
        <fullName>Debt</fullName>
    </customValue>
    <customValue>
        <fullName>DefaultVoiceChannel</fullName>
    </customValue>
    <customValue>
        <fullName>Faults</fullName>
    </customValue>
    <customValue>
        <fullName>CSAT</fullName>
    </customValue>
    <customValue>
        <fullName>Storm Bureau</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints-SPD</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints-SPM</fullName>
    </customValue>
    <customValue>
        <fullName>Social Obs</fullName>
    </customValue>
    <customValue>
        <fullName>SPD SEN</fullName>
    </customValue>
    <customValue>
        <fullName>SPM SEN</fullName>
    </customValue>
    <customValue>
        <fullName>NRSWA-North</fullName>
    </customValue>
    <customValue>
        <fullName>NRSWA-South</fullName>
    </customValue>
    <customValue>
        <fullName>3PD</fullName>
    </customValue>
    <customValue>
        <fullName>SPD Old</fullName>
    </customValue>
    <customValue>
        <fullName>SPM Old</fullName>
    </customValue>
    <customValue>
        <fullName>Connections</fullName>
    </customValue>
    <customValue>
        <fullName>MOP</fullName>
    </customValue>
    <customValue>
        <fullName>Voice Alerts</fullName>
    </customValue>
    <customValue>
        <fullName>GE Surveys</fullName>
    </customValue>
    <customValue>
        <fullName>LCT Surveys</fullName>
    </customValue>
    <customValue>
        <fullName>Faults Surveys</fullName>
    </customValue>
    <customValue>
        <fullName>Planned Works Surveys</fullName>
    </customValue>
    <description>Group related IVR numbers together based on purpose.</description>
    <masterLabel>Call Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VoiceCalls.cls
/*-----------------------------------------------------------------------------
DESCRIPTION	:	Domain class of the VoiceCall object
LIBRARY		:	SPEN
VERSION		:	1.0
HISTORY		:
Date			Author				Comment
NOV-11-2022		Ayush Mittal		Initial version
FEB-02-2023		Macjules Sevilla	Added after update
-----------------------------------------------------------------------------*/
@SuppressWarnings('PMD.CyclomaticComplexity')
public with sharing class VoiceCalls 
{
	@TestVisible
	private Boolean allowVoicemailDML = true;
	public static Boolean premiseUpdateFlag = false;
    
	/**
	 * @description CONSTANTS
	 */ 
	public final static String CALL_ORIGIN_VOICEMAIL = 'Voicemail';

	/**
	 * @description BUSINESS LOGIC VARIABLES
	 */
	@TestVisible
	List<SPEN_Voicemail__c> voicemails = new List<SPEN_Voicemail__c>();

	static Map<String,String> mapPlatKeyMasterLabel= new Map<String,String>();


	/**
	 * @description Handles the BEFORE UPDATE trigger event
	 */
	public void onBeforeUpdate(Map<Id, VoiceCall> oldVoiceCallMap, List<VoiceCall> newVoiceCall){
		//CRMD-4874, Premise will be puplated from IVR and uncommented 33 line for outbound calls
		new SPEN_VoiceCallService().isUpdatingPremiseOnVoiceCall(oldVoiceCallMap, newVoiceCall);	
         try{
		for(VoiceCall voice : newVoiceCall)
		{
			VoiceCall  voicecallOldData = oldVoiceCallMap.get(voice.Id);
			// BUSINESS RULE 1 - WALLBOARD FUNCTIONALITY
			// Update the Accepted Date Time immediately when the voice call is assigned to an agent.
			// This metric is important to the wallboard functionality.
			if(voice.SPEN_CallAcceptedDateTime__c == null && voice.UserId != oldVoiceCallMap.get(voice.Id).UserId)
			{
				voice.SPEN_CallAcceptedDateTime__c = Datetime.now();
			}
			//New field was created as it should be populated only for the Callback 
			if(voice.CallType == 'Callback' && voice.SPEN_CallbackAcceptDateTime__c == null && voice.UserId != oldVoiceCallMap.get(voice.Id).UserId)
			{
				voice.SPEN_CallbackAcceptDateTime__c = Datetime.now();
			}
			// to poulating the SPEN_nextCallId__c field value
			if(voicecallOldData.NextCallId == null && voicecallOldData.NextCallId != voice.NextCallId){
				voice.SPEN_NextCallId__c = voice.NextCallId;
			}
		}      
        }catch(exception ex){
		   SEL_LoggingService.log(ex);
	    }
	}

	/* Added Under [CRMD]: 1322 */
	public void onBeforeInsert(List<VoiceCall> currentList){ 
		Map<String,String> mapExtId2CallGrp = new Map<String,String>();
		Map<String,List<VoiceCall>> mapPhone2ListOfVoiceCall = new Map<String,List<VoiceCall>>();
	    try{
			mapPhone2ListOfVoiceCall=VoiceCalls.getVoiceCallMap(currentList);
			if(mapPhone2ListOfVoiceCall != null && !mapPhone2ListOfVoiceCall.keySet().isEmpty()){
				mapExtId2CallGrp=VoiceCalls.getCallGroupMap(mapPhone2ListOfVoiceCall);
				if(mapExtId2CallGrp != null){
					VoiceCalls.updateCallGroup(mapExtId2CallGrp,currentList);
				}
			}
	    }catch(exception ex){
		   SEL_LoggingService.log(ex);
	    }
	}
	private static Map<String,List<VoiceCall>> getVoiceCallMap(List<VoiceCall> currentList){
		Map<String,List<VoiceCall>> mapPhone2ListOfVoiceCall = new Map<String,List<VoiceCall>>();
		for(VoiceCall objVoice : currentList){
			if(mapPhone2ListOfVoiceCall.containsKey(String.valueOf(objVoice.ToPhoneNumber))){
				mapPhone2ListOfVoiceCall.get(String.valueOf(objVoice.ToPhoneNumber)).add(objVoice);
			}else{
				mapPhone2ListOfVoiceCall.put(String.valueOf(objVoice.ToPhoneNumber),new List<VoiceCall>{objVoice});
			}
		}
		return mapPhone2ListOfVoiceCall;
	}
	@SuppressWarnings('PMD.SOQLSelectorPattern,PMD.ApexCRUDViolation')
	private static Map<String,String> getCallGroupMap(Map<String,List<VoiceCall>> mapPhone2ListOfVoiceCall){
		Map<String,String> mapExtId2CallGrp = new Map<String,String>();
		List<MessagingChannel> lstMsgChannel = new List<MessagingChannel>();
		List<SPEN_IVR__c > lstIVR = new List<SPEN_IVR__c >();
		if(mapPhone2ListOfVoiceCall != null && !mapPhone2ListOfVoiceCall.keySet().isEmpty()){
			lstMsgChannel= [SELECT MasterLabel,MessagingPlatformKey FROM MessagingChannel WHERE MessageType = 'Voice' AND 
			MessagingPlatformKey IN: mapPhone2ListOfVoiceCall.keySet()];
			for(MessagingChannel msgCh : lstMsgChannel)
			{
				mapPlatKeyMasterLabel.put(msgCh.MessagingPlatformKey,msgCh.MasterLabel);
			}
			if(mapPlatKeyMasterLabel != null && !mapPlatKeyMasterLabel.keySet().isEmpty()){
					lstIVR = SPEN_IVRSelector.getIvrSelector(mapPlatKeyMasterLabel.values());
					//[SELECT SPEN_CallGroup__c,SPEN_ExternalId__c FROM SPEN_IVR__c	WHERE SPEN_ExternalId__c IN:mapPlatKeyMasterLabel.values()];
			}
			if(lstIVR != null && !lstIVR.isEmpty()){
				for(SPEN_IVR__c ivr : lstIVR){
					mapExtId2CallGrp.put(ivr.SPEN_ExternalId__c,ivr.SPEN_CallGroup__c);
				}
			}
		}
		return mapExtId2CallGrp;
	}
	private static void updateCallGroup(Map<String,String> mapExtId2CallGrp ,List<VoiceCall> currentList){
		String callGroup;
		for(VoiceCall vc: currentList){
			callGroup = mapExtId2CallGrp.get(mapPlatKeyMasterLabel.get(String.valueOf(vc.ToPhoneNumber)));
			if(String.isNotBlank(callGroup)){
				vc.SPEN_CallGroup__c = callGroup;
			}else {
				vc.SPEN_CallGroup__c = 'Unclassified';
			}
		}
	}

	
	/**
	 * @description Handles the AFTER UPDATE trigger event
	 */
	public void onAfterUpdate(Map<Id, VoiceCall> prior, Map<Id, VoiceCall> current){
		List<VoiceCall> priorList = new List<VoiceCall>();
		List<VoiceCall> currentList = new List<VoiceCall>();
		 system.debug('after update Come here***');
		Set<Id> voiceCallIdSet = new Set<Id>();	
        
		if(!prior.isEmpty()) { 
			priorList = prior.values(); 
		}
		if(!current.isEmpty()) { 
			currentList = current.values(); 
		}
		voicemails=VoiceCalls.voiceMailList(currentList,prior);
		//CRMD-7689 
		voicecalls.setMPANNumberOnCallDetails(currentList, prior);
		// BUSINESS RULE 1
		// Insert voicemails for prioritisation
		if(voicemails.isEmpty() == false && this.allowVoicemailDML == true && Schema.sObjectType.SPEN_Voicemail__c.isCreateable())
		{
			insert voicemails;
		}
        for(VoiceCall voice : currentList)	{
         VoiceCall voicecallOldData = prior.get(voice.Id);
        if(voice.SPEN_VoicecallPremise__c != null && voicecallOldData.SPEN_VoicecallPremise__c != voice.SPEN_VoicecallPremise__c){
                voiceCallIdSet.add(voice.id);// 8331 Enh changes
            }
        }
        system.debug('voiceCallIdSet**' + voiceCallIdSet);
             if(voiceCallIdSet != null && voiceCallIdSet.size()>0){
                 premiseUpdateFlag = true;
                 system.debug('come here**');
               SPEN_ActiveIncidentCheck.fetchIncidentRecValue(voiceCallIdSet);// 8331 Enh changes
             }
	}
	private static List<SPEN_Voicemail__c> voiceMailList(List<VoiceCall> currentList,Map<Id, VoiceCall> prior){
        List<SPEN_Voicemail__c> voicemailList = new List<SPEN_Voicemail__c>();
		for(VoiceCall c : currentList)	{
			// BUSINESS RULE 1
			// IF the Call Origin is changed to Voicemail
			// THEN create the corresponding SPEN_Voicemail__c records
			String callOrigin=c?.CallOrigin != null?c?.CallOrigin:'';
			if(callOrigin.equalsIgnoreCase(VoiceCalls.CALL_ORIGIN_VOICEMAIL) && callOrigin!= prior.get(c.Id)?.CallOrigin){
				SPEN_Voicemail__c voicemail = new SPEN_Voicemail__c();
				voicemail.SPEN_Status__c = SPEN_Voicemails.STATUS_NOT_STARTED;
				voicemail.SPEN_Type__c = SPEN_Voicemails.TYPE_MPAS; // TODO: At some point, the type must be adjusted based on the call type
				voicemail.SPEN_VoiceCallId__c = c.Id;
				voicemailList.add(voicemail);
			}
		}
        return voicemailList;
	}
	// CRMD-7689: Voice call premise MPAN to be added to VC record
	public static void setMPANNumberOnCallDetails(List<VoiceCall> currentList,Map<Id, VoiceCall> prior){
        Map<Id,Id> callDetailsId = new Map<Id,ID>();
        Set<Id> callDetailsIds = new Set<Id>();
        Set<Id> voiceCallPremiseId = new Set<Id>();
        List<SPEN_CallDetails__c> callDetailsList = new List<SPEN_CallDetails__c>();
        Map<Id, SPEN_MPAN__c> mpanDeails = new Map<Id, SPEN_MPAN__c>();
        for(VoiceCall vc :  currentList){
            if(vc.SPEN_RelatedCallDetails__c != Null && vc.SPEN_VoicecallPremise__c != Null){
                callDetailsIds.add(vc.SPEN_RelatedCallDetails__c);
                voiceCallPremiseId.add(vc.SPEN_VoicecallPremise__c);
                callDetailsId.put(vc.SPEN_VoicecallPremise__c,vc.SPEN_RelatedCallDetails__c);
            }
        }
        if(voiceCallPremiseId.size() >0 && callDetailsIds.size() >0){
            for(SPEN_MPAN__c mp : [Select Id,SPEN_AccountNumberMPAN__c,SPEN_Premise__c from SPEN_MPAN__c where SPEN_Premise__c =:voiceCallPremiseId and SPEN_ConnectionStatus__c = 'Energised']){
                mpanDeails.put(mp.SPEN_Premise__c, mp);
            }
        }
        if(mpanDeails.size() >0){
            for(VoiceCall vc :  currentList){
                if(vc.SPEN_VoicecallPremise__c != prior.get(vc.Id).SPEN_VoicecallPremise__c && callDetailsId.get(vc.SPEN_VoicecallPremise__c) != null){
                    SPEN_CallDetails__c cDetails = new SPEN_CallDetails__c(Id = callDetailsId.get(vc.SPEN_VoicecallPremise__c), SPEN_MPAN_Number__c = mpanDeails.get(vc.SPEN_VoicecallPremise__c).SPEN_AccountNumberMPAN__c  );
                    callDetailsList.add(cDetails);
                }
            } 
        }
        
        if(!callDetailsList.isEmpty()){
            update callDetailsList; 
        }
    }
	
}