force-app/main/default/objects/SPEN_CustomerUpdate__c/SPEN_CustomerUpdate__c.object-meta.xml
<CustomObject>
    <description>Various update activities to inform customers.</description>
    <label>Outbound Dialler Task</label>
    <nameField>
        <displayFormat>OD-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Dialler Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CustomerUpdate__c/fields/SPEN_ContactId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ContactId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Outbound Dialler Tasks</relationshipLabel>
    <relationshipName>Outbound_Dialler_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_CustomerUpdate__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipName>Customer_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SPEN_CustomerUpdatesSelector.cls
/*-----------------------------------------------------------------------------
DESCRIPTION :   Selector class of the SPEN_CustomerUpdate__c Queries.
HISTORY     :
Date            Author              Comment
Jan-19-2023     Deepraj Bhushan        Initial version
-----------------------------------------------------------------------------*/
public inherited sharing class SPEN_CustomerUpdatesSelector {
		/**************************************************
	   	@Author: Smita Raikar
	   	@Date: 31/10/22
	   	@purpose: Method to get contact premise details.
	   	***************************************************/
		public static Map<Id,SPEN_CustomerUpdate__c> getCustomerUpdateForVoiceCall(VoiceCall voiceCallObj)
	   	{
            Map<Id,SPEN_CustomerUpdate__c> voiceCustomerUpdateMap = new Map<Id,SPEN_CustomerUpdate__c>();
            	string contactIdPrefix = Schema.SObjectType.Contact.getKeyPrefix();
            	if(voiceCallObj.RelatedRecordId !=null && String.valueOf(voiceCallObj.RelatedRecordId).startsWith(contactIdPrefix) && voiceCallObj.CallType == 'Outbound'){
                	List<SPEN_CustomerUpdate__c> odObjList = [SELECT Id,SPEN_IncidentId__c 
                                                              	FROM SPEN_CustomerUpdate__c 
                                                              	WHERE OwnerId =: voiceCallObj.OwnerId 
                                                              	AND SPEN_ContactId__c =: voiceCallObj.RelatedRecordId
                                                              	AND LastModifiedDate=today Limit 1];
                	if(!odObjList.isEmpty()){
                    	voiceCustomerUpdateMap.put(voiceCallObj.Id,odObjList[0]);
                	}
            	}
		   return voiceCustomerUpdateMap;
	   	}
}