force-app/main/default/objects/SPEN_CustomerUpdate__c/SPEN_CustomerUpdate__c.object-meta.xml
<CustomObject>
    <description>Various update activities to inform customers.</description>
    <label>Outbound Dialler Task</label>
    <nameField>
        <displayFormat>OD-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Dialler Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CustomerUpdate__c/fields/SPEN_Info__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Info__c</fullName>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_CustomerUpdate__c/fields/SPEN_Priority__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A11</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>A21</fullName>
            </value>
            <value>
                <fullName>A3</fullName>
            </value>
            <value>
                <fullName>A31</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
            <value>
                <fullName>A41</fullName>
            </value>
            <value>
                <fullName>A5</fullName>
            </value>
            <value>
                <fullName>A51</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B11</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>B21</fullName>
            </value>
            <value>
                <fullName>B3</fullName>
            </value>
            <value>
                <fullName>B31</fullName>
            </value>
            <value>
                <fullName>B4</fullName>
            </value>
            <value>
                <fullName>B41</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>D1</fullName>
            </value>
            <value>
                <fullName>D2</fullName>
            </value>
            <value>
                <fullName>D3</fullName>
            </value>
            <value>
                <fullName>D4</fullName>
            </value>
            <value>
                <fullName>E1</fullName>
            </value>
            <value>
                <fullName>E11</fullName>
            </value>
            <value>
                <fullName>E2</fullName>
            </value>
            <value>
                <fullName>E21</fullName>
            </value>
            <value>
                <fullName>E3</fullName>
            </value>
            <value>
                <fullName>E4</fullName>
            </value>
            <value>
                <fullName>F1</fullName>
            </value>
            <value>
                <fullName>F2</fullName>
            </value>
            <value>
                <fullName>F3</fullName>
            </value>
            <value>
                <fullName>F4</fullName>
            </value>
            <value>
                <fullName>G1</fullName>
            </value>
            <value>
                <fullName>G2</fullName>
            </value>
            <value>
                <fullName>G3</fullName>
            </value>
            <value>
                <fullName>G4</fullName>
            </value>
            <value>
                <fullName>H1</fullName>
            </value>
            <value>
                <fullName>H2</fullName>
            </value>
            <value>
                <fullName>H3</fullName>
            </value>
            <value>
                <fullName>H4</fullName>
            </value>
            <value>
                <fullName>I1</fullName>
            </value>
            <value>
                <fullName>I2</fullName>
            </value>
            <value>
                <fullName>I3</fullName>
            </value>
            <value>
                <fullName>I4</fullName>
            </value>
            <value>
                <fullName>I5</fullName>
            </value>
            <value>
                <fullName>J1</fullName>
            </value>
            <value>
                <fullName>J2</fullName>
            </value>
            <value>
                <fullName>J3</fullName>
            </value>
            <value>
                <fullName>J4</fullName>
            </value>
            <value>
                <fullName>J5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CustomerUpdate__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
                <isActive>false</isActive>
                <label>Dropped</label>
            </value>
            <value>
                <fullName>RetryCustomer</fullName>
                <isActive>false</isActive>
                <label>RetryCustomer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/SPEN_ImpactedPremise__c.object-meta.xml
<CustomObject>
    <label>Impacted Premise</label>
    <nameField>
        <displayFormat>IP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impacted Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_Dispatched_Date__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Dispatched_Date__c</fullName>
    <label>Dispatched Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_DroppedSupplyWithNoticeFormula__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DroppedSupplyWithNoticeFormula__c</fullName>
    <formula>SPEN_RelatedIncident__r.SPEN_droppedsupply__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dropped Supply With Notice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_DroppedSupplyWithoutNoticeFormula__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DroppedSupplyWithoutNoticeFormula__c</fullName>
    <formula>SPEN_RelatedIncident__r.SPEN_DroppedSupplyWithoutNotice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dropped Supply Without Notice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_ETRChangeTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ETRChangeTime__c</fullName>
    <label>ETRChangeTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_INCETRChangeTimeFormula__c.field-meta.xml
<CustomField>
    <fullName>SPEN_INCETRChangeTimeFormula__c</fullName>
    <formula>SPEN_RelatedIncident__r.SPEN_ETRChangeTime__c</formula>
    <label>INC ETRChangeTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_IncidentType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentType__c</fullName>
    <label>Incident Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SP</fullName>
                <label>Single Premise Incident</label>
            </value>
            <value>
                <fullName>LV</fullName>
                <label>Low Voltage Incident</label>
            </value>
            <value>
                <fullName>HV_S</fullName>
                <label>High Voltage Incident</label>
            </value>
            <value>
                <fullName>HV_N</fullName>
                <label>High Voltage Network Incident</label>
            </value>
            <value>
                <fullName>CG</fullName>
                <label>Call Group Incident</label>
            </value>
            <value>
                <fullName>AREA</fullName>
                <label>Area Incident</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_INCStatusFormula__c.field-meta.xml
<CustomField>
    <fullName>SPEN_INCStatusFormula__c</fullName>
    <formula>TEXT(SPEN_RelatedIncident__r.SPEN_IncidentStatus__c)</formula>
    <label>INC Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_isCalledIn__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isCalledIn__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Are there any cases under this INC for the mentioned premise</description>
    <label>isCalledIn</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_IsETRChange__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IsETRChange__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsETRChange</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_isMerged__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isMerged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isMerged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_MergeDateTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MergeDateTime__c</fullName>
    <label>MergeDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_OutComfortHoursFormula__c.field-meta.xml
<CustomField>
    <fullName>SPEN_OutComfortHoursFormula__c</fullName>
    <formula>If(((NOW() - SPEN_RelatedIncident__r.SPEN_LastCommunicationTime__c)*24)&gt;3,true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OutComfortHours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_PSRType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PSRType__c</fullName>
    <label>PSR Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PSR</fullName>
            </value>
            <value>
                <fullName>Other PSR</fullName>
            </value>
            <value>
                <fullName>No PSR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_RelatedContact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelatedContact__c</fullName>
    <formula>SPEN_ContactPremise__r.SPEN_RelatedContact__c</formula>
    <label>RelatedContact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_ResourceArrivalDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ResourceArrivalDate__c</fullName>
    <label>Resource Arrival Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Restored</fullName>
            </value>
            <value>
                <fullName>Not Restored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_OutboundDiallerConfig__mdt/SPEN_OutboundDiallerConfig__mdt.object-meta.xml
<CustomObject>
    <label>Outbound Dialler Config</label>
    <pluralLabel>Outbound Dialler Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/SPEN_OutboundDiallerConfig__mdt/fields/ApplicableCalledInINCType__c.field-meta.xml
<CustomField>
    <fullName>ApplicableCalledInINCType__c</fullName>
    <description>For Orphan Call logs or Cases, which outcomes are to be considered for A3 or D3</description>
    <inlineHelpText>No Supply (Single Premise)
ENS1
No Supply (Online) SP
NSOS
No Supply (SP) auto call IVR
NOS4
No Supply (IVR) Single Premise
NOS2</inlineHelpText>
    <label>ApplicableCalledInINCType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_OutboundDiallerConfig__mdt/fields/ApplicableINCStatus__c.field-meta.xml
<CustomField>
    <fullName>ApplicableINCStatus__c</fullName>
    <description>It will tell for which INC Status OD to be created</description>
    <label>Applicable INC Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_OutboundDiallerConfig__mdt/fields/ApplicableINCType__c.field-meta.xml
<CustomField>
    <fullName>ApplicableINCType__c</fullName>
    <description>It will have the Applicable INC type separated by ,</description>
    <label>Applicable INC Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_OutboundDiallerConfig__mdt/fields/RuleName__c.field-meta.xml
<CustomField>
    <fullName>RuleName__c</fullName>
    <label>RuleName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_OutboundDiallerConfig__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PSR</fullName>
                <default>true</default>
                <label>PSR</label>
            </value>
            <value>
                <fullName>Other PSR</fullName>
            </value>
            <value>
                <fullName>Non PSR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_OutboundDiallersServiceImpl.cls
public with sharing class SPEN_OutboundDiallersServiceImpl {
	public void updateOutboundDiallerPriority(List<SPEN_ImpactedPremise__c> impactedPremiseList, Map<Id,SPEN_ImpactedPremise__c> impactedPremiseMap){
		
		Map<String, SPEN_OutboundDiallerConfig__mdt> priorityDetailMap = SPEN_OutboundDiallerConfig__mdt.getAll();
        group grp = [Select id from group where DeveloperName = 'Outbound_Dialer'];
		Boolean isInsert = impactedPremiseMap==null?true:false;
		List<SPEN_CustomerUpdate__c> outboundDiallerList = new List<SPEN_CustomerUpdate__c>();
		
		for(SPEN_ImpactedPremise__c impactedPremiseObj : impactedPremiseList){
			if(impactedPremiseObj.SPEN_PSRType__c!= null && impactedPremiseObj.SPEN_RelatedContact__c!= null && impactedPremiseObj.SPEN_Status__c!=null && impactedPremiseObj.SPEN_IncidentType__c!='' && (impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR') || impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('Other PSR'))){
				SPEN_CustomerUpdate__c odRec = new SPEN_CustomerUpdate__c();
				if(isInsert && (impactedPremiseObj.SPEN_Status__c).equalsIgnoreCase('Not Restored') && impactedPremiseObj.SPEN_INCETRChangeTimeFormula__c ==null && !impactedPremiseObj.SPEN_OutComfortHoursFormula__c){
					if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR')){
						if(impactedPremiseObj.SPEN_isMerged__c && priorityDetailMap.get('A3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('A3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('A3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='A3';
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('A4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='A4';
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('A2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='A2';
						}
						else if(priorityDetailMap.get('A1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('A1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('A1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='A1'; 
						}
					}
					else {
						if(impactedPremiseObj.SPEN_isMerged__c && priorityDetailMap.get('D3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('D3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('D3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='D3';
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('D4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='D4';
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('D2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='D2';
						}
						else if(priorityDetailMap.get('D1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('D1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('D1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='D1'; 
						} 
					}
				}
				else if(isInsert && (impactedPremiseObj.SPEN_Status__c).equalsIgnoreCase('Not Restored') && impactedPremiseObj.SPEN_INCETRChangeTimeFormula__c !=null && !impactedPremiseObj.SPEN_OutComfortHoursFormula__c){
					if(!(impactedPremiseObj.SPEN_isMerged__c && impactedPremiseObj.SPEN_MergeDateTime__c > impactedPremiseObj.SPEN_INCETRChangeTimeFormula__c) && !(impactedPremiseObj.SPEN_isMerged__c && impactedPremiseObj.SPEN_MergeDateTime__c ==null)){
						if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR')){
							if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('B4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='B4';
							}
							else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('B2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='B2';
							}
							else if(priorityDetailMap.get('B1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('B1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('B1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
								odRec.SPEN_Priority__c='B1'; 
							}
						}
						else {
							if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('C4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='C4';
							}
							else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('C2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='C2';
							}
							else if(priorityDetailMap.get('C1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('C1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('C1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
								odRec.SPEN_Priority__c='C1'; 
							}
						}
					}
					else {
						if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR') && priorityDetailMap.get('B3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('B3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('B3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='B3';
						}
						else if(priorityDetailMap.get('C3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('C3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('C3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='C3'; 
						}
					}
				}
				else if(isInsert && (impactedPremiseObj.SPEN_Status__c).equalsIgnoreCase('Not Restored') && impactedPremiseObj.SPEN_OutComfortHoursFormula__c){
					if(!(impactedPremiseObj.SPEN_isMerged__c)){
						if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR')){
							if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('E4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='E4';
							}
							else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('E2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='E2';
							}
							else if(priorityDetailMap.get('E1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('E1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('E1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
								odRec.SPEN_Priority__c='E1'; 
							}
						}
						else {
							if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('G4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='G4';
							}
							else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('G2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='G2';
							}
							else if(priorityDetailMap.get('G1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('G1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('G1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
								odRec.SPEN_Priority__c='G1'; 
							}
						}
					}
					else {
						if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR') && priorityDetailMap.get('E3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('E3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('E3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='E3';
						}
						else if(priorityDetailMap.get('G3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('G3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('G3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='G3'; 
						}
					}
				}
				else if(!isInsert && (impactedPremiseObj.SPEN_Status__c).equalsIgnoreCase('Restored')){
					if(impactedPremiseObj.SPEN_IncidentType__c == ((SPEN_ImpactedPremise__c)impactedPremiseMap.get(impactedPremiseObj.Id)).SPEN_IncidentType__c){
						if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR')){
							if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('F4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && priorityDetailMap.get('F4').ApplicableINCStatus__c.contains(String.ValueOf(impactedPremiseObj.SPEN_INCStatusFormula__c))){
								odRec.SPEN_Priority__c='F4';
							}
							else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('F2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && priorityDetailMap.get('F2').ApplicableINCStatus__c.contains(String.ValueOf(impactedPremiseObj.SPEN_INCStatusFormula__c))){
								odRec.SPEN_Priority__c='F2';
							}
							else if(priorityDetailMap.get('F1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && priorityDetailMap.get('F1').ApplicableINCStatus__c.contains(String.ValueOf(impactedPremiseObj.SPEN_INCStatusFormula__c)) && ((priorityDetailMap.get('F1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('F1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
								odRec.SPEN_Priority__c='F1'; 
							}
						}
						else {
							if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('H4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && priorityDetailMap.get('H4').ApplicableINCStatus__c.contains(String.ValueOf(impactedPremiseObj.SPEN_INCStatusFormula__c))){
								odRec.SPEN_Priority__c='H4';
							}
							else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('H2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && priorityDetailMap.get('H2').ApplicableINCStatus__c.contains(String.ValueOf(impactedPremiseObj.SPEN_INCStatusFormula__c))){
								odRec.SPEN_Priority__c='H2';
							}
							else if(priorityDetailMap.get('H1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && priorityDetailMap.get('H1').ApplicableINCStatus__c.contains(String.ValueOf(impactedPremiseObj.SPEN_INCStatusFormula__c)) && ((priorityDetailMap.get('H1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('H1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
								odRec.SPEN_Priority__c='H1'; 
							}
						}
					}
					else {
						if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR') && priorityDetailMap.get('F3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && priorityDetailMap.get('F3').ApplicableINCStatus__c.contains(String.ValueOf(impactedPremiseObj.SPEN_INCStatusFormula__c)) && ((priorityDetailMap.get('F3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('F3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='F3';
						}
						else if(priorityDetailMap.get('H3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && priorityDetailMap.get('H3').ApplicableINCStatus__c.contains(String.ValueOf(impactedPremiseObj.SPEN_INCStatusFormula__c)) && ((priorityDetailMap.get('H3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('H3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='H3'; 
						}
					}
				}
				else if(!isInsert && (impactedPremiseObj.SPEN_Status__c).equalsIgnoreCase('Not Restored') && impactedPremiseObj.SPEN_INCETRChangeTimeFormula__c !=null && !impactedPremiseObj.SPEN_OutComfortHoursFormula__c){
					if(!(impactedPremiseObj.SPEN_isMerged__c && impactedPremiseObj.SPEN_MergeDateTime__c > impactedPremiseObj.SPEN_INCETRChangeTimeFormula__c) && !(impactedPremiseObj.SPEN_isMerged__c && impactedPremiseObj.SPEN_MergeDateTime__c ==null)){
						if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR')){
							if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('B4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='B4';
							}
							else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('B2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='B2';
							}
							else if(priorityDetailMap.get('B1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('B1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('B1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
								odRec.SPEN_Priority__c='B1'; 
							}
						}
						else {
							if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('C4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='C4';
							}
							else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('C2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='C2';
							}
							else if(priorityDetailMap.get('C1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('C1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('C1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
								odRec.SPEN_Priority__c='C1'; 
							}
						}
					}
					else {
						if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR') && priorityDetailMap.get('B3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('B3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('B3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='B3';
						}
						else if(priorityDetailMap.get('C3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('C3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('C3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='C3'; 
						}
					}
				}
				else if(!isInsert && (impactedPremiseObj.SPEN_Status__c).equalsIgnoreCase('Not Restored') && impactedPremiseObj.SPEN_OutComfortHoursFormula__c){
					if(impactedPremiseObj.SPEN_IncidentType__c== ((SPEN_ImpactedPremise__c)impactedPremiseMap.get(impactedPremiseObj.Id)).SPEN_IncidentType__c && !(impactedPremiseObj.SPEN_isMerged__c && impactedPremiseObj.SPEN_MergeDateTime__c >= impactedPremiseObj.SPEN_ETRChangeTime__c)){
						if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR')){
							if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('E4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='E4';
							}
							else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('E2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='E2';
							}
							else if(priorityDetailMap.get('E1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('E1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('E1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
								odRec.SPEN_Priority__c='E1'; 
							}
						}
						else {
							if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('G4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='G4';
							}
							else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('G2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
								odRec.SPEN_Priority__c='G2';
							}
							else if(priorityDetailMap.get('G1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('G1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('G1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
								odRec.SPEN_Priority__c='G1'; 
							}
						}
					}
					else {
						if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR') && priorityDetailMap.get('E3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('E3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('E3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='E3';
						}
						else if(priorityDetailMap.get('G3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('G3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('G3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='G3'; 
						}
					}
				}
				else if(!isInsert && (impactedPremiseObj.SPEN_Status__c).equalsIgnoreCase('Not Restored') && impactedPremiseObj.SPEN_INCETRChangeTimeFormula__c ==null && !impactedPremiseObj.SPEN_OutComfortHoursFormula__c){
					if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR')){
						
						if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('A4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='A4';
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('A2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='A2';
						}
						else if(priorityDetailMap.get('A1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('A1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('A1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='A1'; 
						}
						else if(impactedPremiseObj.SPEN_isMerged__c && priorityDetailMap.get('A3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('A3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('A3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='A3';
						}
					}
					else {
						
						if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('D4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='D4';
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('D2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='D2';
						}
						else if(priorityDetailMap.get('D1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('D1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('D1').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='D1'; 
						} 
						else if(impactedPremiseObj.SPEN_isMerged__c && priorityDetailMap.get('D3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && ((priorityDetailMap.get('D3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)) && impactedPremiseObj.SPEN_isCalledIn__c) || !priorityDetailMap.get('D3').ApplicableCalledInINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c)))){
							odRec.SPEN_Priority__c='D3';
						}
					}
				}
				else if(!isInsert && (impactedPremiseObj.SPEN_Status__c).equalsIgnoreCase('Not Restored') && impactedPremiseObj.SPEN_IncidentType__c != ((SPEN_ImpactedPremise__c)impactedPremiseMap.get(impactedPremiseObj.Id)).SPEN_IncidentType__c && !impactedPremiseObj.SPEN_IsETRChange__c){
					if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR')){
						if(priorityDetailMap.get('A3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='A3';
						}
					}
					else {
						if(priorityDetailMap.get('D3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='D3';
						}
					}
				}
				else if(!isInsert && (impactedPremiseObj.SPEN_Status__c).equalsIgnoreCase('Not Restored') && impactedPremiseObj.SPEN_isMerged__c != ((SPEN_ImpactedPremise__c)impactedPremiseMap.get(impactedPremiseObj.Id)).SPEN_isMerged__c && !impactedPremiseObj.SPEN_IsETRChange__c){
					if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR')){
						if(priorityDetailMap.get('A3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='A3';
						}
					}
					else {
						if(priorityDetailMap.get('D3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='D3';
						}
					}
				}
				else if(!isInsert && (impactedPremiseObj.SPEN_Status__c).equalsIgnoreCase('Not Restored') && !impactedPremiseObj.SPEN_IsETRChange__c){
					if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR')){
						if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('A4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='A4';
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('A2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='A2';
						}
						else if(priorityDetailMap.get('A1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='A1'; 
						}
					}
					else {
						if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('D4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='D4';
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('D2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='D2';
						}
						else if(priorityDetailMap.get('D1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='D1'; 
						}
					}
				}
				else if(!isInsert && (impactedPremiseObj.SPEN_Status__c).equalsIgnoreCase('Not Restored') && impactedPremiseObj.SPEN_ResourceArrivalDate__c!= ((SPEN_ImpactedPremise__c)impactedPremiseMap.get(impactedPremiseObj.Id)).SPEN_ResourceArrivalDate__c){
					if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR')){
						if(priorityDetailMap.get('I1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='I1'; 
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('I2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='I2';
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('I3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='I3';
						}
					}
					else {
						if(priorityDetailMap.get('J1').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='J1'; 
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('J2').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='J2';
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('J3').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='J3';
						}
					}
				}
				else if(!isInsert && (impactedPremiseObj.SPEN_Status__c).equalsIgnoreCase('Not Restored') && impactedPremiseObj.SPEN_Dispatched_Date__c!= ((SPEN_ImpactedPremise__c)impactedPremiseMap.get(impactedPremiseObj.Id)).SPEN_Dispatched_Date__c){
					if(impactedPremiseObj.SPEN_PSRType__c.equalsIgnoreCase('PSR')){
						if(priorityDetailMap.get('I4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='I4'; 
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('I5').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='I5';
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('I6').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='I6';
						}
					}
					else {
						if(priorityDetailMap.get('J4').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='J4'; 
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithNoticeFormula__c && priorityDetailMap.get('J5').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='J5';
						}
						else if(impactedPremiseObj.SPEN_DroppedSupplyWithoutNoticeFormula__c && priorityDetailMap.get('J6').ApplicableINCType__c.contains(String.ValueOf(impactedPremiseObj.SPEN_IncidentType__c))){
							odRec.SPEN_Priority__c='J6';
						}
					}
				}
				else{
					continue;
				}

				if(priorityDetailMap.containsKey(odRec.SPEN_Priority__c) && priorityDetailMap.get(odRec.SPEN_Priority__c).IsActive__c){
					odRec.SPEN_Info__c = priorityDetailMap.get(odRec.SPEN_Priority__c).RuleName__c;
					odRec.SPEN_Type__c = priorityDetailMap.get(odRec.SPEN_Priority__c).Type__c;
					odRec.SPEN_Campaign__c = priorityDetailMap.get(odRec.SPEN_Priority__c).Campaign__c;
					odRec.SPEN_ContactId__c = impactedPremiseObj.SPEN_RelatedContact__c;
					odRec.SPEN_IncidentId__c = impactedPremiseObj.SPEN_RelatedIncident__c;
					odRec.SPEN_Impacted_Premise__c = impactedPremiseObj.Id;
					odRec.OwnerId=grp.Id;
					odRec.SPEN_ExternalId__c = String.valueOf(impactedPremiseObj.SPEN_RelatedIncident__c)+String.valueOf(odRec.SPEN_ContactId__c)+String.valueOf(odRec.SPEN_Campaign__c);
					outboundDiallerList.add(odRec);
				}
			}
		}
		if(!outboundDiallerList.isEmpty()){
			Upsert outboundDiallerList SPEN_ExternalId__c;
		}
	}
}