force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/SPEN_ContactNumberEmailStaging__c.object-meta.xml
<CustomObject>
    <description>SPEN_ContactNumberEmailStaging will be staging for contact numbers and Email</description>
    <label>Contact Number Email Staging</label>
    <nameField>
        <displayFormat>CNE-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Number Email Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/fields/SPEN_NumberOrEmail__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NumberOrEmail__c</fullName>
    <label>NumberOrEmail</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/fields/SPEN_SyncStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SyncStatus__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Indicates if the change value is synced to the contact record.</description>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ContactNumberEmailStaging__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/SPEN_ContactStaging__c.object-meta.xml
<CustomObject>
    <description>Contact Staging</description>
    <label>Contact Staging</label>
    <nameField>
        <displayFormat>CSG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_AdqmAction__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AdqmAction__c</fullName>
    <label>ADQM Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_AdqmLastModifiedDateTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AdqmLastModifiedDateTime__c</fullName>
    <label>ADQM Last Modified Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_AdqmSource__c.field-meta.xml
<CustomField>
    <fullName>SPEN_AdqmSource__c</fullName>
    <label>ADQM Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Other Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_ContactType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ContactType__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>PSR Contact (Primary)</fullName>
            </value>
            <value>
                <fullName>Alternative Contact</fullName>
            </value>
            <value>
                <fullName>Site Contact</fullName>
            </value>
            <value>
                <fullName>Premise Owner</fullName>
            </value>
            <value>
                <fullName>PSR Contact (Alternative)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_Email__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_FirstName__c.field-meta.xml
<CustomField>
    <fullName>SPEN_FirstName__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_Initials__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Initials__c</fullName>
    <label>Initials</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_LastName__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LastName__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_Mobile__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_Other__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Other__c</fullName>
    <label>Other</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_OtherContactId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_OtherContactId__c</fullName>
    <label>Other Contact ID</label>
    <length>38</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_PremiseId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseId__c</fullName>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_Salutation__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Salutation__c</fullName>
    <label>Salutation</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_SyncComment__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SyncComment__c</fullName>
    <label>Sync Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_SyncStatus__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SyncStatus__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ContactStaging__c/fields/SPEN_Telephone__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Telephone__c</fullName>
    <label>Telephone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/SPEN_ContactStagingSelector.cls
/*-----------------------------------------------------------------------------
DESCRIPTION	:	Selector Class for SPEN_ContactNumberEmailStaging__c object.
LIBRARY		:	SPEN
VERSION		:	1.0
HISTORY		:
Date			Author		    Comment
TODO
-----------------------------------------------------------------------------*/
public inherited sharing class SPEN_ContactStagingSelector 
{
	public Database.QueryLocator getQueryLocatorForNotStartedAndFailed(Date adqmLoadDate)
	{
		Database.QueryLocator q;

		if(adqmLoadDate != null)
		{
			q = Database.getQueryLocator([
				SELECT	Id, SPEN_ExternalId__c, SPEN_NumberOrEmail__c, SPEN_Type__c
				FROM	SPEN_ContactNumberEmailStaging__c
				WHERE	DAY_ONLY(CreatedDate) = :adqmLoadDate AND 
                (SPEN_SyncStatus__c =: 'Not Started' OR SPEN_SyncStatus__c =: 'Failed') AND
                SPEN_Type__c != null
			]);				
		}
	   
		return q;
	}

	public Database.QueryLocator getStageRecForContSync(Date adqmLoadDate)
	{
		Database.QueryLocator q;

		if(adqmLoadDate != null)
		{
			q = Database.getQueryLocator([
				SELECT  ID,SPEN_ContactType__c,SPEN_ExternalId__c,SPEN_AdqmAction__c,SPEN_AdqmLastModifiedDateTime__c,SPEN_AdqmSource__c,
                        SPEN_Email__c,SPEN_FirstName__c,SPEN_Initials__c, SPEN_LastName__c,SPEN_Mobile__c,
                        SPEN_Other__c,SPEN_OtherContactId__c, SPEN_PremiseId__c,SPEN_Salutation__c,
                        SPEN_SyncComment__c,SPEN_SyncStatus__c,SPEN_Telephone__c 
                FROM    SPEN_ContactStaging__c 
                WHERE   DAY_ONLY(CreatedDate) = :adqmLoadDate 
				AND (SPEN_AdqmAction__c =: 'New' OR SPEN_AdqmAction__c =: 'Update') 
				AND (SPEN_SyncStatus__c =: 'Not Started' OR SPEN_SyncStatus__c =: 'Failed')
			]);
		}

		return q;
	}
	public List<SPEN_ContactNumberEmailStaging__c> getStageRecordForContactUpdate(Date adqmLoadDate,Set<String> contactExtIdSet)
	{
		List<SPEN_ContactNumberEmailStaging__c> lstStage= new List<SPEN_ContactNumberEmailStaging__c>();
        if(adqmLoadDate != null && !contactExtIdSet.isEmpty())
		{
			lstStage=	[
						SELECT Id,SPEN_ExternalId__c,SPEN_NumberOrEmail__c,SPEN_Type__c 
						FROM SPEN_ContactNumberEmailStaging__c 
						WHERE  DAY_ONLY(CreatedDate) =: adqmLoadDate  
						AND SPEN_SyncStatus__c ='Not Started' and SPEN_ExternalId__c =:contactExtIdSet
						];			
		}
		
		return lstStage;
	}
}