force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Unique SPEN identifier for a premise</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/SPEN_PSR__c.object-meta.xml
<CustomObject>
    <description>PSR object has been set up to see all the PSR related information</description>
    <label>PSR</label>
    <nameField>
        <displayFormat>PSR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_ADQMLastSync__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ADQMLastSync__c</fullName>
    <description>Represents the last time the record is synchronized with ADQM.</description>
    <label>ADQM Last Sync</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Contact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_FirstLanguage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_FirstLanguage__c</fullName>
    <description>For code 17 this field will be selected</description>
    <label>First Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALBANIAN</fullName>
            </value>
            <value>
                <fullName>AMHARIC</fullName>
            </value>
            <value>
                <fullName>ARABIC</fullName>
            </value>
            <value>
                <fullName>BENGALI</fullName>
            </value>
            <value>
                <fullName>BULGARIAN</fullName>
            </value>
            <value>
                <fullName>CANTONESE</fullName>
            </value>
            <value>
                <fullName>CHINESE</fullName>
            </value>
            <value>
                <fullName>CROATIAN</fullName>
            </value>
            <value>
                <fullName>CZECH</fullName>
            </value>
            <value>
                <fullName>DANISH</fullName>
            </value>
            <value>
                <fullName>DUTCH</fullName>
            </value>
            <value>
                <fullName>ESTONIAN</fullName>
            </value>
            <value>
                <fullName>FINNISH</fullName>
            </value>
            <value>
                <fullName>FRENCH</fullName>
            </value>
            <value>
                <fullName>GERMAN</fullName>
            </value>
            <value>
                <fullName>GREEK</fullName>
            </value>
            <value>
                <fullName>HINDI</fullName>
            </value>
            <value>
                <fullName>HUNGARIAN</fullName>
            </value>
            <value>
                <fullName>INDONESIAN</fullName>
            </value>
            <value>
                <fullName>ITALIAN</fullName>
            </value>
            <value>
                <fullName>JAPANESE</fullName>
            </value>
            <value>
                <fullName>KOREAN</fullName>
            </value>
            <value>
                <fullName>KURDISH</fullName>
            </value>
            <value>
                <fullName>LATVIAN</fullName>
            </value>
            <value>
                <fullName>LITHUANIAN</fullName>
            </value>
            <value>
                <fullName>LYBIAN</fullName>
            </value>
            <value>
                <fullName>MALTESE</fullName>
            </value>
            <value>
                <fullName>MANDARIN</fullName>
            </value>
            <value>
                <fullName>NEPALI</fullName>
            </value>
            <value>
                <fullName>PASHTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_PSREffectiveFromDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PSREffectiveFromDate__c</fullName>
    <description>Date that the PSR category is effective from</description>
    <label>PSR Effective From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_PSREffectiveToDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PSREffectiveToDate__c</fullName>
    <description>Date that the PSR category is effective until</description>
    <label>PSR Effective To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_PSRId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PSRId__c</fullName>
    <externalId>true</externalId>
    <label>SPEN PSR Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_PSRVulnerabilityType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PSRVulnerabilityType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PSR and Vulnerability Type</label>
    <referenceTo>SPEN_PSRVulnerabilityType__c</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/recordTypes/SPEN_PSR.recordType-meta.xml
<RecordType>
    <fullName>SPEN_PSR</fullName>
    <active>true</active>
    <label>SPEN PSR</label>
</RecordType>

force-app/main/default/objects/SPEN_PSRStaging__c/SPEN_PSRStaging__c.object-meta.xml
<CustomObject>
    <description>Object for Staging Data</description>
    <label>PSR Staging</label>
    <nameField>
        <displayFormat>PST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSR Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_ADQMLastModifiedDateTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ADQMLastModifiedDateTime__c</fullName>
    <description>It holds the ADQM Last Modified Datetime</description>
    <label>ADQM Last Modified DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_Code__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Code__c</fullName>
    <description>Takes Code for PSR Staging</description>
    <label>Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_EffectiveDateFrom__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EffectiveDateFrom__c</fullName>
    <description>Takes the Effective Date From</description>
    <label>Effective Date From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_EffectiveDateTo__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EffectiveDateTo__c</fullName>
    <description>It takes Effective Date To</description>
    <label>Effective Date To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_FirstLanguage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_FirstLanguage__c</fullName>
    <label>First Language</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Takes Premise Id.</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRStaging__c/fields/SPEN_PsrVulnerabilityTypeId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PsrVulnerabilityTypeId__c</fullName>
    <externalId>true</externalId>
    <label>PSR Vulnerability Type ID</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRVulnerabilityType__c/SPEN_PSRVulnerabilityType__c.object-meta.xml
<CustomObject>
    <description>PSR Type/Vulnerability Type object has been set up to store master data</description>
    <label>PSR and Vulnerability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSR and Vulnerability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSRVulnerabilityType__c/fields/SPEN_Code__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SPEN_SyncPSRBatchService.cls
public with sharing class SPEN_SyncPSRBatchService 
{
	// New PSR
	public static Map<String, SPEN_PSR__c> createSFPSR(List<SPEN_PSRStaging__c> psrStagingRecords, Set<String> premiseExtIdSet)
	{
		Id psrRecordTypeID = Schema.SObjectType.SPEN_PSR__c.getRecordTypeInfosByDeveloperName().get('SPEN_PSR').getRecordTypeId();
		Map<String, SPEN_PSR__c> psrByExternalId = new Map<String, SPEN_PSR__c>();

		for(SPEN_PSRStaging__c psrStaging : psrStagingRecords)
		{
			SPEN_PSR__c psrRecord;
			String externalId = psrStaging.SPEN_PremiseId__c + '-' + psrStaging.SPEN_PsrVulnerabilityTypeId__c;

			// Create PSR placeholder or update if there is an existing one
			if(psrByExternalId.containsKey(externalId))
			{
				psrRecord = psrByExternalId.get(externalId);
			}
			else
			{
				psrRecord = new SPEN_PSR__c(SPEN_PSRId__c = externalId);
				psrByExternalId.put(externalId, psrRecord);
			}
			
			// References
			Contact cont = new Contact(SPEN_CustomerID__c = psrStaging.SPEN_PremiseId__c);
			SPEN_Premise__c premise = new SPEN_Premise__c(SPEN_PremiseId__c = psrStaging.SPEN_PremiseId__c);
			SPEN_PSRVulnerabilityType__c code = new SPEN_PSRVulnerabilityType__c(SPEN_Code__c = psrStaging.SPEN_PsrVulnerabilityTypeId__c);

			// Populate data
			psrRecord.RecordTypeId = psrRecordTypeID;
			psrRecord.SPEN_ADQMLastSync__c = psrStaging.SPEN_ADQMLastModifiedDateTime__c;
			psrRecord.SPEN_Premise__r = premise;
			psrRecord.SPEN_Contact__r = cont;
			psrRecord.SPEN_PSRVulnerabilityType__r = code;

			// Special handling of 17s
			if(psrStaging.SPEN_PsrVulnerabilityTypeId__c.equalsIgnoreCase('17'))
			{
				if(psrStaging.SPEN_EffectiveDateFrom__c != null) { psrRecord.SPEN_PSREffectiveFromDate__c = psrStaging.SPEN_EffectiveDateFrom__c; }
				if(psrStaging.SPEN_EffectiveDateTo__c != null) { psrRecord.SPEN_PSREffectiveToDate__c = psrStaging.SPEN_EffectiveDateTo__c; }
				if(psrStaging.SPEN_FirstLanguage__c != null) { psrRecord.SPEN_FirstLanguage__c = psrStaging.SPEN_FirstLanguage__c; }
			}   
			else 
			{
				psrRecord.SPEN_PSREffectiveFromDate__c = psrStaging.SPEN_EffectiveDateFrom__c;
				psrRecord.SPEN_PSREffectiveToDate__c = psrStaging.SPEN_EffectiveDateTo__c;
			}
		}
		
		return psrByExternalId;
	}
}