force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_FullAddress__c.field-meta.xml
<CustomField>
    <fullName>SPEN_FullAddress__c</fullName>
    <description>Flat Number + Building + Street + Area + Town + Post Code
(Combination of all other Premise Fields)</description>
    <formula>IF( NOT(ISBLANK(SPEN_PlotNumber__c)), SPEN_PlotNumber__c &amp;&quot; &quot;&amp; SPEN_FlatNumber__c &amp;&quot; &quot;&amp; SPEN_BuildingNameNumber__c &amp;&quot; &quot;&amp; SPEN_Street__c &amp;&quot; &quot; &amp;SPEN_Area__c &amp;&quot; &quot;&amp; SPEN_Town__c &amp;&quot; &quot;&amp; SPEN_PostCode__c, SPEN_FlatNumber__c &amp;&quot; &quot;&amp; SPEN_BuildingNameNumber__c &amp;&quot; &quot;&amp; SPEN_Street__c &amp;&quot; &quot; &amp;SPEN_Area__c &amp;&quot; &quot;&amp; SPEN_Town__c &amp;&quot; &quot;&amp; SPEN_PostCode__c)</formula>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Unique SPEN identifier for a premise</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_SubstationName__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SubstationName__c</fullName>
    <externalId>true</externalId>
    <label>Substation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_Zone__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SPEN_Zone__c.SPEN_Type__c</field>
            <operation>equals</operation>
            <value>Zone</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/SPEN_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SPEN_PremiseCommFlowHandlerHTTPMock.cls
@isTest
global class SPEN_PremiseCommFlowHandlerHTTPMock implements HttpCalloutMock{
    global HttpResponse respond(HTTPRequest req){
        HttpResponse res = new HttpResponse();
    	res.setStatus('OK');
    	res.setStatusCode(200);
        Map<String,String> mapResp = new Map <String,String>();
        mapResp.put('query','SELECT Name, SPEN_PremiseID__c, SPEN_FullAddress__c, SPEN_SubstationName__c, SPEN_Zone__r.Name, Id, RecordTypeId, CreatedDate, LastModifiedDate, SystemModstamp, SPEN_Zone__c FROM SPEN_Premise__c WHERE SPEN_PremiseID__c =:'+ 'test'+' ORDER BY SPEN_PremiseID__c');
        res.setBody(JSON.serialize(mapResp));
    return res;
    }

}