force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Unique SPEN identifier for a premise</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/SPEN_PSR__c.object-meta.xml
<CustomObject>
    <description>PSR object has been set up to see all the PSR related information</description>
    <label>PSR</label>
    <nameField>
        <displayFormat>PSR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Contact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_PSRId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PSRId__c</fullName>
    <externalId>true</externalId>
    <label>SPEN PSR Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_PSRVulnerabilityType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PSRVulnerabilityType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PSR and Vulnerability Type</label>
    <referenceTo>SPEN_PSRVulnerabilityType__c</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_SpecificVulnerability__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SpecificVulnerability__c</fullName>
    <formula>If(AND(NOT(SPEN_PSREffectiveToDate__c  &lt;  TODAY()),NOT(ISBLANK(SPEN_PSREffectiveToDate__c  )), SPEN_PSRVulnerabilityType__r.SPEN_SpecificVulnerability__c) , true, if(AND(ISBLANK(SPEN_PSREffectiveToDate__c  ), SPEN_PSRVulnerabilityType__r.SPEN_SpecificVulnerability__c),true,false))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Specific Vulnerability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRVulnerabilityType__c/SPEN_PSRVulnerabilityType__c.object-meta.xml
<CustomObject>
    <description>PSR Type/Vulnerability Type object has been set up to store master data</description>
    <label>PSR and Vulnerability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSR and Vulnerability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSRVulnerabilityType__c/fields/SPEN_Code__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_PSRVulnerabilityType__c/fields/SPEN_SpecificVulnerability__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SpecificVulnerability__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Specific Vulnerability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PSRs.cls
public with sharing class PSRs 
{
    public static Set<Id> contactIds = new Set<Id>();
	public static void afterPSRInsert(List<SPEN_PSR__c> newPSRList)
    {
        for(SPEN_PSR__c psrRec : newPSRList){
            //system.debug('---InsideInsertLoop---');
            contactIds.add(psrRec.SPEN_Contact__c);
        }
        if(!contactIds.isEmpty() && !System.isBatch()){
            setSpecificVulOnContact(contactIds);
        }
    }
    public static void afterPSRUpdate(Map<Id, sObject> psrNewMap, Map<Id, sObject> psrOldMap)
    {
        List<SPEN_PSR__c> pasrnewList = (List<SPEN_PSR__c>)psrNewMap.values();
        Map<Id,SPEN_PSR__c> psrMapOldVal = (Map<Id,SPEN_PSR__c>)psrOldMap;
        for(SPEN_PSR__c psrRec: pasrnewList){
            if(psrRec.SPEN_PSRVulnerabilityType__c != psrMapOldVal.get(psrRec.Id).SPEN_PSRVulnerabilityType__c)
            {
                contactIds.add(psrRec.SPEN_Contact__c);
            }
        }
        
        if(!contactIds.isEmpty() && !System.isBatch()){
            setSpecificVulOnContact(contactIds);
        }
    }    
    
    public static void PSRUpdateSyncADQMValue(List<SPEN_PSR__c> newPSRList){
        List<Contact> conUpd=new List<Contact>();
        Set<Id> contactIds = new Set<Id> ();
        for(SPEN_PSR__c psrRec : newPSRList){
            contactIds.add(psrRec.SPEN_Contact__c);
        }
        
        if(!contactIds.isEmpty() && !contactIds.contains(null))
        {
            for(Id conId : contactIds)
            {
                Contact psrContact = new Contact(Id = conId);
                psrContact.SPEN_RequireSynctoADQM__c = true;
                psrContact.SPEN_PSRSynctoADQM__c = true;
                conUpd.add(psrContact);
            }
            update conUpd;
        }
    }
	public static void beforePSRInsert(List<SPEN_PSR__c> newPSRList){
        Set<String> setVulnerabilityId = new Set<String>();
        Set<String> setPremiseId = new Set<String>();
        Map<Id, SPEN_Premise__c> mapId2Premise = new Map<Id,SPEN_Premise__c>();
        Map<Id, SPEN_PSRVulnerabilityType__c> mapId2Vulnerability = new Map<Id,SPEN_PSRVulnerabilityType__c>();
        for(SPEN_PSR__c psrRec : newPSRList)
        {
            setPremiseId.add(psrRec.SPEN_Premise__c);
            setVulnerabilityId.add(psrRec.SPEN_PSRVulnerabilityType__c);
        }
        for(SPEN_Premise__c prem: new SPEN_PremisesSelector().getPremiseForBeforeTrigger(setPremiseId))
        {
            mapId2Premise.put(prem.id,prem);
        }
        for(SPEN_PSRVulnerabilityType__c vul: new SPEN_PSRVulnerabilitySelector().getCodeForBeforeTrigger(setVulnerabilityId))
        {
            mapId2Vulnerability.put(vul.id,vul);
        }
        if(!mapId2Premise.isEmpty() && !mapId2Vulnerability.isEmpty())
        {
            for(SPEN_PSR__c psrRec : newPSRList)
            {
                if(mapId2Premise.containsKey(psrRec.SPEN_Premise__c) && mapId2Vulnerability.containsKey(psrRec.SPEN_PSRVulnerabilityType__c))
                {
                    String extId = mapId2Premise.get(psrRec.SPEN_Premise__c).SPEN_PremiseId__c + '-' + 
                                mapId2Vulnerability.get(psrRec.SPEN_PSRVulnerabilityType__c).SPEN_Code__c;
                    psrRec.SPEN_PSRId__c = extId;
                }
            }
        }
    }
    
    @future
    public static void setSpecificVulOnContact(Set<Id> conIds){
        List<Contact> contactsToBeUpdated = new List<Contact>();
        List<Contact> contactSet = SPEN_ContactSelector.setVulCon(conIds);
        for(Contact conRec : contactSet)
        {
            if(conRec.PSRs__r.size() > 0){
                conRec.SPEN_SpecificVulnerability__c = true;
                
            }
            else{
                conRec.SPEN_SpecificVulnerability__c = false;
            }
            contactsToBeUpdated.add(conRec);
        }
        
        if(!contactsToBeUpdated.isEmpty()){
            update contactsToBeUpdated;
        }
    }
}