force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Unique SPEN identifier for a premise</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/SPEN_PSR__c.object-meta.xml
<CustomObject>
    <description>PSR object has been set up to see all the PSR related information</description>
    <label>PSR</label>
    <nameField>
        <displayFormat>PSR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_ADQMLastSync__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ADQMLastSync__c</fullName>
    <description>Represents the last time the record is synchronized with ADQM.</description>
    <label>ADQM Last Sync</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Contact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_PSREffectiveFromDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PSREffectiveFromDate__c</fullName>
    <description>Date that the PSR category is effective from</description>
    <label>PSR Effective From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_PSREffectiveToDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PSREffectiveToDate__c</fullName>
    <description>Date that the PSR category is effective until</description>
    <label>PSR Effective To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_PSRVulnerabilityType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PSRVulnerabilityType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PSR and Vulnerability Type</label>
    <referenceTo>SPEN_PSRVulnerabilityType__c</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRVulnerabilityType__c/SPEN_PSRVulnerabilityType__c.object-meta.xml
<CustomObject>
    <description>PSR Type/Vulnerability Type object has been set up to store master data</description>
    <label>PSR and Vulnerability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSR and Vulnerability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PSRs_Test.cls
@isTest
public class PSRs_Test { 
    @testSetup static void setup(){
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user);
        PermissionSet ps1 = SPEN_TestdataSelector.getPermissionSet('SPEN_ContactAccessCRU');
        //[SELECT Id FROM PermissionSet WHERE Name = 'SPEN_ContactAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps1.Id);
        PermissionSet ps2 = SPEN_TestdataSelector.getPermissionSet('SPEN_PremiseAccessCRU');
        //[SELECT Id FROM PermissionSet WHERE Name = 'SPEN_PremiseAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps2.Id);
        PermissionSet ps3 = SPEN_TestdataSelector.getPermissionSet('SPEN_ContactPremiseAccessCRU');
        //[SELECT Id FROM PermissionSet WHERE Name = 'SPEN_ContactPremiseAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps3.Id);

    }

    @isTest
    private static void testPSRInsert()
    {
       
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);
		System.runAs(user)
        {
            Test.startTest();
            List<Account> accRec = SPEN_TestDataFactory.createAccounts('Test',SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert accRec;
            Contact con= SPEN_TestDataFactory.createContacts(accRec[0].Id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            con.SPEN_CustomerID__c = 'TEST1234';
            insert con;
            
            List<SPEN_PSRVulnerabilityType__c> vulList = SPEN_TestDataFactory.createPSRVulnerabilityRecords();
            insert vulList;
            
            List<SPEN_Premise__c> premiseList = SPEN_TestDataFactory.createListOfPremise(1);
            premiseList[0].SPEN_PremiseID__c = 'TEST1234';
            insert premiseList;
            
            List<SPEN_PSR__c> psrList = SPEN_TestDataFactory.createPSRrecord(1);
            psrList[0].SPEN_PSREffectiveFromDate__c = System.today()-10;
            psrList[0].SPEN_PSREffectiveToDate__c = System.today()+15;
            psrList[0].SPEN_ADQMLastSync__c = System.today()-1;
            psrList[0].SPEN_Premise__c = premiseList[0].id;
            psrList[0].SPEN_Contact__c = con.id;
            psrList[0].SPEN_PSRVulnerabilityType__c = vulList[0].id;
            insert psrList;
            Assert.AreEqual(psrList[0].SPEN_Premise__c,premiseList[0].id);
            psrList[0].SPEN_PSRVulnerabilityType__c = vulList[1].id;
            update psrList;
            Assert.AreEqual(psrList[0].SPEN_PSRVulnerabilityType__c,vulList[1].id);
            Test.stopTest();
        }
    }

    @isTest
    private static void testPSRInsertNegative()
    {
       
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);
		System.runAs(user)
        {
            Test.startTest();
            List<Account> accRec = SPEN_TestDataFactory.createAccounts('Test',SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert accRec;
            Contact con= SPEN_TestDataFactory.createContacts(accRec[0].Id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            con.SPEN_CustomerID__c = 'TEST1234';
            insert con;
            
            List<SPEN_PSRVulnerabilityType__c> vulList = SPEN_TestDataFactory.createPSRVulnerabilityRecords();
            insert vulList;
            
            List<SPEN_Premise__c> premiseList = SPEN_TestDataFactory.createListOfPremise(1);
            premiseList[0].SPEN_PremiseID__c = 'TEST1234';
            insert premiseList;
            
            List<SPEN_PSR__c> psrList = SPEN_TestDataFactory.createPSRrecord(1);
            psrList[0].SPEN_PSREffectiveFromDate__c = System.today()-10;
            psrList[0].SPEN_PSREffectiveToDate__c = System.today()+15;
            psrList[0].SPEN_ADQMLastSync__c = System.today()-1;
            psrList[0].SPEN_Premise__c = //premiseList[0].id;
            psrList[0].SPEN_Contact__c = //con.id;
            psrList[0].SPEN_PSRVulnerabilityType__c = vulList[0].id;
            try{
                insert psrList;
                Assert.AreEqual(psrList[0].SPEN_Premise__c,null);
            }catch(Exception e){
                Assert.isTrue(e!=null);
            }
            Test.stopTest();
        }
    }
}