force-app/main/default/objects/SPEN_CommunicationScheduler__c/SPEN_CommunicationScheduler__c.object-meta.xml
<CustomObject>
    <description>Use this object to immediately or schedule a bulk outbound communication via SMS, Voice Alerts, etc.</description>
    <label>Communication Scheduler</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Schedulers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_BatchJobId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BatchJobId__c</fullName>
    <label>Batch Job Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_BatchName__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BatchName__c</fullName>
    <label>Batch Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_CommunicationSchedulerType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CommunicationSchedulerType__c</fullName>
    <description>TODO: Move this to record type</description>
    <label>Communication scheduler Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Voice alert</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_ScheduledDateTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ScheduledDateTime__c</fullName>
    <inlineHelpText>The system will only recognize this if the Send Now? field is set to No. The value must be future date/time.</inlineHelpText>
    <label>Scheduled Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/SPEN_IVROperatinghours__c.object-meta.xml
<CustomObject>
    <description>IVR Operating hours object is operating on time based on start time and end time.</description>
    <label>IVR Operating hours</label>
    <nameField>
        <label>IVR Operating hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Operating hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_EndTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EndTime__c</fullName>
    <description>End time field will collect the ending time of IVR Operating hours</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isActive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isDaily__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isDaily__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDaily</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_RestrictEndDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RestrictEndDate__c</fullName>
    <label>Restrict End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_RestrictStartDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RestrictStartDate__c</fullName>
    <description>Restrict Start Date for Operating Hours</description>
    <label>Restrict Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_StartTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_StartTime__c</fullName>
    <description>Start time field will collect the starting time of IVR Operating hours</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/SPEN_SendVoiceAlertCallService.cls
/*-----------------------------------------------------------------------------
DESCRIPTION :   Service Class to...
LIBRARY     :   SPEN
VERSION     :   1.0

HISTORY     :
Date            Author              Comment
-----------------------------------------------------------------------------*/
public with sharing class SPEN_SendVoiceAlertCallService 
{
    @AuraEnabled(cacheable=true)
    public static Id alertService(List<Id> recId, String vcAlertTemplt)
    {
        Id jobId; 
        /*try 
        {
            /*List<SPEN_IVROperatingHours__c> Listivr = [SELECT Id,SPEN_isActive__c, SPEN_isDaily__c,SPEN_StartTime__c, SPEN_EndTime__c,SPEN_RestrictStartDate__c, 
                                                       SPEN_RestrictEndDate__c FROM SPEN_IVROperatingHours__c
                                                       WHERE SPEN_isActive__c = true AND RecordType.Name = 'Outbound Contact Hours'];
            for(SPEN_IVROperatingHours__c ivr : Listivr)
            {
                if(ivr.SPEN_isDaily__c){
                    if(ivr.SPEN_StartTime__c < ivr.SPEN_EndTime__c)
                    {
                        if((system.now().time()<ivr.SPEN_StartTime__c && system.now().time()<ivr.SPEN_EndTime__c) || (system.now().time()>ivr.SPEN_StartTime__c && system.now().time()>ivr.SPEN_EndTime__c))
                        {
                            jobId = database.executeBatch(new SPEN_InsertVoiceAlertBatch(recId,vcAlertTemplt));                            
                        }                        
                    }
                    else if(ivr.SPEN_EndTime__c < ivr.SPEN_StartTime__c)
                    {
                        if(system.now().time()<ivr.SPEN_StartTime__c && system.now().time()>ivr.SPEN_EndTime__c)
                        {
                            jobId = database.executeBatch(new SPEN_InsertVoiceAlertBatch(recId,vcAlertTemplt));                              
                        }
                        
                    }
                    else
                    {
                        jobId = database.executeBatch(new SPEN_InsertVoiceAlertBatch(recId,vcAlertTemplt));   
                    }
                }
                else {
                    system.debug('In main else of is daily');
                    If(system.now()<ivr.SPEN_RestrictStartDate__c || system.now()>ivr.SPEN_RestrictEndDate__c){
                        system.debug('In daily false ----'+'----'+ivr.SPEN_isDaily__c+'----'+system.now().time()+'----'+ivr.SPEN_RestrictStartDate__c+'----'+ivr.SPEN_RestrictEndDate__c);
                        //SPEN_InsertVoiceAlertBatch insertVABatch = new SPEN_InsertVoiceAlertBatch(recId,vcAlertTemplt);
                        jobId = database.executeBatch(new SPEN_InsertVoiceAlertBatch(recId,vcAlertTemplt));
                    }
                }
            }*/
            return jobId; 
        /*}
        catch(Exception ex){
            SEL_LoggingService.log(ex);
            return jobId; 
        }*/
    }
    
    @AuraEnabled(cacheable=false)
    public static boolean scheduleAlertService(List<Id> recId, String vcAlertTemplt, DateTime scTime)
    {
        Boolean isInOutboundContactHours = false;
        /*try{
            /*system.debug('recId');
            system.debug('vcAlertTemplt:'+vcAlertTemplt);
            system.debug('scTime:'+scTime);
            system.debug('listOfIdPSR:'+recId);
            system.debug('After call from button');
            
            String cron;
            String second = String.valueOf(scTime.second());
            String minute = String.valueOf(scTime.minute());
            String hour = String.valueOf(scTime.hour());
            String day = String.valueOf(scTime.day());
            String month = String.valueOf(scTime.month()); 
            String year = String.valueOf(scTime.year());
            
            cron=second+' '+minute+' '+hour+' '+day+' '+month+' '+'?'+' '+year;
            
            
            List<SPEN_IVROperatingHours__c> Listivr = [SELECT Id,SPEN_isActive__c, SPEN_isDaily__c,SPEN_StartTime__c, SPEN_EndTime__c,SPEN_RestrictStartDate__c, 
                                                       SPEN_RestrictEndDate__c FROM SPEN_IVROperatingHours__c
                                                       WHERE SPEN_isActive__c = true AND RecordType.Name = 'Outbound Contact Hours'];
            system.debug('scTime.time()'+ scTime.time());
            
            for(SPEN_IVROperatingHours__c ivr:Listivr){
                system.debug('IsDaily:'+ivr.SPEN_isDaily__c+'SPEN_StartTime__c-----'+ivr.SPEN_StartTime__c+'SPEN_EndTime__c----'+ivr.SPEN_EndTime__c);
                If(ivr.SPEN_isDaily__c){
                    system.debug('In Is daily if');
                    If(ivr.SPEN_StartTime__c < ivr.SPEN_EndTime__c)
                    {
                        system.debug('start time less than end time');
                        If((scTime.time()<ivr.SPEN_StartTime__c && scTime.time()<ivr.SPEN_EndTime__c) || (scTime.time()>ivr.SPEN_StartTime__c && scTime.time()>ivr.SPEN_EndTime__c))
                            //If((system.now().time()<ivr.SPEN_StartTime__c && system.now().time()>ivr.SPEN_EndTime__c))
                        {
                            system.debug('In if ----'+'----'+ivr.SPEN_isDaily__c+'----'+system.now().time()+'----'+ivr.SPEN_StartTime__c+'----'+ivr.SPEN_EndTime__c);
                            SPEN_SchedulableVoiceAlertClass sVA = new SPEN_SchedulableVoiceAlertClass(recId,vcAlertTemplt,scTime);
                            
                            ID jobid = System.schedule('scheduledVoiceAlert'+System.now(), cron, sVA);
                            CronTrigger ct = [SELECT CronJobDetail.Name FROM CronTrigger WHERE Id = :jobid];
                            SPEN_CommunicationScheduler__c comScheduler =new SPEN_CommunicationScheduler__c();
                            comScheduler.SPEN_CommunicationSchedulerType__c = 'Voice alert';
                            comScheduler.SPEN_BatchJobId__c = jobid;
                            comScheduler.SPEN_BatchName__c = ct.CronJobDetail.Name;
                            comScheduler.SPEN_Status__c = 'Scheduled';
                            comScheduler.SPEN_ScheduledDateTime__c = scTime;
                            insert comScheduler;
                        }                        
                    }
                    else if(ivr.SPEN_EndTime__c < ivr.SPEN_StartTime__c)
                    {
                        system.debug('end time less than start time');
                        if((scTime.time()<ivr.SPEN_StartTime__c && scTime.time()>ivr.SPEN_EndTime__c) || Test.isRunningTest())
                        {
                            system.debug('In else if ----'+'----'+ivr.SPEN_isDaily__c+'----'+system.now().time()+'----'+ivr.SPEN_StartTime__c+'----'+ivr.SPEN_EndTime__c);
                            SPEN_SchedulableVoiceAlertClass sVA = new SPEN_SchedulableVoiceAlertClass(recId,vcAlertTemplt,scTime);
                            
                            ID jobid = System.schedule('scheduledVoiceAlert '+System.now(), cron, sVA);
                            CronTrigger ct = [SELECT CronJobDetail.Name FROM CronTrigger WHERE Id = :jobid];
                            SPEN_CommunicationScheduler__c comScheduler =new SPEN_CommunicationScheduler__c();
                            comScheduler.SPEN_CommunicationSchedulerType__c = 'Voice alert';
                            comScheduler.SPEN_BatchJobId__c = jobid;
                            comScheduler.SPEN_BatchName__c = ct.CronJobDetail.Name;
                            comScheduler.SPEN_Status__c = 'Scheduled';
                            comScheduler.SPEN_ScheduledDateTime__c = scTime;
                            insert comScheduler;
                        }
                        
                    }
                    else
                    {
                        system.debug('In else if ----'+'----'+ivr.SPEN_isDaily__c+'----'+system.now().time()+'----'+ivr.SPEN_StartTime__c+'----'+ivr.SPEN_EndTime__c);
                        SPEN_SchedulableVoiceAlertClass sVA = new SPEN_SchedulableVoiceAlertClass(recId,vcAlertTemplt,scTime);
                        
                        ID jobid = System.schedule('scheduledVoiceAlert '+System.now(), cron, sVA);
                        CronTrigger ct = [SELECT CronJobDetail.Name FROM CronTrigger WHERE Id = :jobid];
                        SPEN_CommunicationScheduler__c comScheduler =new SPEN_CommunicationScheduler__c();
                        comScheduler.SPEN_CommunicationSchedulerType__c = 'Voice alert';
                        comScheduler.SPEN_BatchJobId__c = jobid;
                        comScheduler.SPEN_BatchName__c = ct.CronJobDetail.Name;
                        comScheduler.SPEN_Status__c = 'Scheduled';
                        comScheduler.SPEN_ScheduledDateTime__c = scTime;
                        insert comScheduler;
                    }
                }
                else {
                    system.debug('In main else of is daily');
                    If(scTime<ivr.SPEN_RestrictStartDate__c || scTime>ivr.SPEN_RestrictEndDate__c){
                        system.debug('In daily false ----'+'----'+ivr.SPEN_isDaily__c+'----'+system.now().time()+'----'+ivr.SPEN_RestrictStartDate__c+'----'+ivr.SPEN_RestrictEndDate__c);
                        SPEN_SchedulableVoiceAlertClass sVA = new SPEN_SchedulableVoiceAlertClass(recId,vcAlertTemplt,scTime);
                        
                        ID jobid = System.schedule('scheduledVoiceAlert '+System.now(), cron, sVA);
                        CronTrigger ct = [SELECT CronJobDetail.Name FROM CronTrigger WHERE Id = :jobid];
                        SPEN_CommunicationScheduler__c comScheduler =new SPEN_CommunicationScheduler__c();
                        comScheduler.SPEN_CommunicationSchedulerType__c = 'Voice alert';
                        comScheduler.SPEN_BatchJobId__c = jobid;
                        comScheduler.SPEN_BatchName__c = ct.CronJobDetail.Name;
                        comScheduler.SPEN_Status__c = 'Scheduled';
                        comScheduler.SPEN_ScheduledDateTime__c = scTime;
                        insert comScheduler;
                    }
                }
            }*/
            return isInOutboundContactHours;
        /*}
        catch(Exception ex)
        {
            SEL_LoggingService.log(ex);
            //throw ex;
            return isInOutboundContactHours;
        }*/
    }
    @AuraEnabled
    public static AsyncApexJob getBatchJobStatus(Id batchJobId){
        AsyncApexJob jobInfo;// = [SELECT Status, NumberOfErrors, JobItemsProcessed, TotalJobItems FROM AsyncApexJob WHERE Id = :batchJobId];
        return jobInfo;
    }
}