force-app/main/default/objects/SPEN_CommunicationScheduler__c/SPEN_CommunicationScheduler__c.object-meta.xml
<CustomObject>
    <description>Use this object to immediately or schedule a bulk outbound communication via SMS, Voice Alerts, etc.</description>
    <label>Communication Scheduler</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Schedulers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CRMD-1333</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Communication Schedulers</relationshipLabel>
    <relationshipName>Communication_Schedulers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <description>The event that initiated the creation of Communication Scheduler.</description>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3-Hour Comfort Call</fullName>
            </value>
            <value>
                <fullName>3rd Call Received</fullName>
            </value>
            <value>
                <fullName>Dropped Supply with Notice</fullName>
            </value>
            <value>
                <fullName>Dropped Supply without Notice</fullName>
            </value>
            <value>
                <fullName>Estimated Restoration Time Extended</fullName>
            </value>
            <value>
                <fullName>Incident Created</fullName>
            </value>
            <value>
                <fullName>Incident Restored</fullName>
            </value>
            <value>
                <fullName>Resource Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Resource Dispatched</fullName>
            </value>
            <value>
                <fullName>Medically Dependent by District</fullName>
            </value>
            <value>
                <fullName>Planned Outage Communication</fullName>
            </value>
            <value>
                <fullName>On Demand</fullName>
            </value>
            <value>
                <fullName>HV proactive contact</fullName>
            </value>
            <value>
                <fullName>15days Task Creation non LVHV</fullName>
            </value>
            <value>
                <fullName>5 Days System Email LVHV</fullName>
            </value>
            <value>
                <fullName>15 Days System Email LVHV</fullName>
            </value>
            <value>
                <fullName>10 Days Task Creation LVHV</fullName>
            </value>
            <value>
                <fullName>20 Days Task Creation LVHV</fullName>
            </value>
            <value>
                <fullName>10 Days System Email Non LVHV</fullName>
            </value>
            <value>
                <fullName>45 Days System email Non LVHV</fullName>
            </value>
            <value>
                <fullName>60 Days task Create Non LVHV</fullName>
            </value>
            <value>
                <fullName>Customer Engagement Task PUM/PDM</fullName>
            </value>
            <value>
                <fullName>Customer Engagement Task HOD</fullName>
            </value>
            <value>
                <fullName>Customer Engagement Task PM</fullName>
            </value>
            <value>
                <fullName>Annual Meeting Prior 14 Days</fullName>
            </value>
            <value>
                <fullName>ITT Issued Due Date Prior 1 day</fullName>
            </value>
            <value>
                <fullName>Energisation Date Prior 14 days</fullName>
            </value>
            <value>
                <fullName>Stage 1 Energisation Date to PM</fullName>
            </value>
            <value>
                <fullName>MTM 2 Offer Expire To NGESO CCM 14 Days</fullName>
            </value>
            <value>
                <fullName>BiAnnual Meeting Prior 14 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Communication Schedulers</relationshipLabel>
    <relationshipName>SPEN_CommunicationSchedulers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/SPEN_VoiceAlert__c.object-meta.xml
<CustomObject>
    <label>Voice Alert</label>
    <nameField>
        <label>Voice Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voice Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_BroadcastMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BroadcastMessage__c</fullName>
    <label>Broadcast Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CRMD-5392</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Voice Alerts</relationshipLabel>
    <relationshipName>Voice_Alerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_CommunicationScheduler__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CommunicationScheduler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Communication scheduler</label>
    <referenceTo>SPEN_CommunicationScheduler__c</referenceTo>
    <relationshipLabel>Voice Alerts</relationshipLabel>
    <relationshipName>Voice_Alerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_ContactId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Voice Alerts</relationshipLabel>
    <relationshipName>SPEN_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <label>Event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Voice Alerts</relationshipLabel>
    <relationshipName>SPEN_VoiceAlertIncident</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_IsProactive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IsProactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Proactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Various status for voice alert</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_GESurveyQueueable.cls
public class SPEN_GESurveyQueueable implements Queueable {
    public Set<Id> smsVAIDs ; 
    public String surveyType;
    public String channel;
    Map<Id,Id> mapCseIdConId;
    Map<Id,String> mapCseIdEmailId;
    public SPEN_GESurveyQueueable(Set<Id> smsVAIDs, String surveyType, String channel)
    {
        this.smsVAIDs = smsVAIDs ;  
        this.surveyType = surveyType;
        this.channel = channel;
    }
    public SPEN_GESurveyQueueable(Map<Id,Id> mapCseIdConId,Map<Id,String> mapCseIdEmailId,String surveyType, String channel)
    {
        this.mapCseIdConId = mapCseIdConId;
        this.mapCseIdEmailId = mapCseIdEmailId;
        this.surveyType = surveyType;
        this.channel = channel;
    }
    public void execute(QueueableContext context) {
        if(channel.equalsIgnoreCase('SMS') && surveyType.equalsIgnoreCase('General Enquiries'))
        {
            SPEN_SurveyUtility.updateSMSWithInvitation(smsVAIDs, surveyType);
        }
        else if(channel.equalsIgnoreCase('Voice Alert') && surveyType.equalsIgnoreCase('General Enquiries'))
        {
            List<SPEN_VoiceAlert__c> lstVoiceAlert = new List<SPEN_VoiceAlert__c>();
            system.debug('SPEN_SurveyUtility>>> before');
            SPEN_SurveyUtility.updateVoiceAlertWithInvitation(smsVAIDs, surveyType);
            system.debug('SPEN_SurveyUtility>>> after');
            for(SPEN_VoiceAlert__c va : [select id,SPEN_ContactId__c,SPEN_IncidentId__c,SPEN_Event__c,SPEN_CommunicationScheduler__c,SPEN_BroadcastMessage__c,SPEN_IsProactive__c,SPEN_Case__c,RecordTypeId,SPEN_Status__c  from SPEN_VoiceAlert__c where id in :smsVAIDs])
            {
                lstVoiceAlert.add(va);
            }
            if(!Test.isRunningTest())
            {
                SPEN_VoiceAlertService.isServiceCall(lstVoiceAlert);
            }
        }
        else if(channel.equalsIgnoreCase('Email') && surveyType.equalsIgnoreCase('General Enquiries'))
        {
            SPEN_SurveyUtility.sendSurveyEmails(mapCseIdConId, mapCseIdEmailId, surveyType);
        }
    }
}