force-app/main/default/objects/SPEN_CommunicationScheduler__c/SPEN_CommunicationScheduler__c.object-meta.xml
<CustomObject>
    <description>Use this object to immediately or schedule a bulk outbound communication via SMS, Voice Alerts, etc.</description>
    <label>Communication Scheduler</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Schedulers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_Action__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Action__c</fullName>
    <description>The action that the agent selected.</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Send SMS to All Customers</fullName>
            </value>
            <value>
                <fullName>Send SMS to Called In</fullName>
            </value>
            <value>
                <fullName>Send SMS to PSR</fullName>
            </value>
            <value>
                <fullName>Send Voice Alert to All Customers</fullName>
            </value>
            <value>
                <fullName>Send Voice Alert to Called In</fullName>
            </value>
            <value>
                <fullName>Send Voice Alert to PSR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_BatchJobId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BatchJobId__c</fullName>
    <label>Batch Job Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Communication Schedulers</relationshipLabel>
    <relationshipName>SPEN_CommunicationSchedulers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_Message__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Message__c</fullName>
    <description>The template or customised message to be broadcasted.</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_MessagingTaskId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MessagingTaskId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Message Task that created the Communication Scheduler.</description>
    <label>Messaging Task</label>
    <referenceTo>SPEN_MessagingTask__c</referenceTo>
    <relationshipLabel>Communication Schedulers</relationshipLabel>
    <relationshipName>SPEN_CommunicationSchedulers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_ScheduledDateTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ScheduledDateTime__c</fullName>
    <inlineHelpText>The system will only recognize this if the Send Now? field is set to No. The value must be future date/time.</inlineHelpText>
    <label>Scheduled Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MessagingTask__c/SPEN_MessagingTask__c.object-meta.xml
<CustomObject>
    <description>This object allows agents to set up and configure broadcast messaging via SMS, Voice Alerts, etc.</description>
    <label>Messaging Task</label>
    <nameField>
        <displayFormat>MST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messaging Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The incident record that created the Messaging Task</description>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Messaging Tasks</relationshipLabel>
    <relationshipName>SPEN_MessagingTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Shows the progress of the Message Task</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/recordTypes/Incident.recordType-meta.xml
<RecordType>
    <fullName>Incident</fullName>
    <active>true</active>
    <description>When the Messaging Task record is driven from an Incident event</description>
    <label>Incident</label>
</RecordType>

force-app/main/default/objects/SPEN_PSR__c/SPEN_PSR__c.object-meta.xml
<CustomObject>
    <description>PSR object has been set up to see all the PSR related information</description>
    <label>PSR</label>
    <nameField>
        <displayFormat>PSR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Contact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SPEN_AbortBatch_TEST.cls
@IsTest
public class SPEN_AbortBatch_TEST 
{
    @testSetup static void setup(){
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user);
        PermissionSet ps1 = SPEN_TestdataSelector.getPermissionSet('SPEN_CommunicationSchedulerAccessCRU');
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps1.Id);
        PermissionSet ps2 = SPEN_TestdataSelector.getPermissionSet('SPEN_ContactAccessCRU');
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps2.Id);
        PermissionSet ps3 = SPEN_TestdataSelector.getPermissionSet('SPEN_Zone_CRU');
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps3.Id);
        System.runAs(user)
        {
            Test.startTest();
            SPEN_ConfigurableSettings__c cs2 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelay');
            insert cs2;
            SPEN_ConfigurableSettings__c cs1 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelayForMessagingTask');
            insert cs1;
            SPEN_ConfigurableSettings__c cs3 =SPEN_TestDataFactory.createConfigSetting(1,'OnDemandMessageDelayForMessagingTask');
            insert cs3;
            Test.stopTest();
        
        }
    }
    @IsTest
    @SuppressWarnings('PMD.SOQLSelectorPattern')
    private static void testAbortBatchexecute()
    {
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);
        System.runAs(user)
        {
            Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
            Test.startTest();
            List<Account> accRec = SPEN_TestDataFactory.createAccounts('Test',SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert accRec;
            Contact con= SPEN_TestDataFactory.createContacts(accRec[0].Id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert con;
            List<SPEN_PSR__c> psralert=SPEN_TestDataFactory.createPSRrecord(SPEN_TestDataFactoryConstants.SINGLE_REC);
            psralert[0].SPEN_Contact__c=con.Id;
            insert psralert;
            List<Id> psrList=new List<Id>();
            
            psrList.add(psralert[0].Id);
            List<SPEN_CommunicationScheduler__c> comList=new List<SPEN_CommunicationScheduler__c>();
            
            Datetime scTime=System.now().addDays(1);
            
            String cron;
            String second = String.valueOf(scTime.second());
            String minute = String.valueOf(scTime.minute());
            String hour = String.valueOf(scTime.hour());
            String day = String.valueOf(scTime.day());
            String month = String.valueOf(scTime.month()); 
            String year = String.valueOf(scTime.year());
            
            cron=second+' '+minute+' '+hour+' '+day+' '+month+' '+'?'+' '+year;
            SPEN_SchedulableVoiceAlertClass sVA = new SPEN_SchedulableVoiceAlertClass(psrList,'Voice Alert',scTime);
            
            ID jobid = System.schedule('scheduledVoiceAlert '+System.now(), cron, sVA);
            //Create messaging task
            List<SPEN_MessagingTask__c> sMsgtask = new List<SPEN_MessagingTask__c>();
            SPEN_MessagingTask__c sMsgtask1 = new SPEN_MessagingTask__c();
            sMsgtask1.SPEN_Status__c='New';   
            insert sMsgtask1;
            sMsgtask.add(sMsgtask1);
            
            List<Incident> inci = new List<Incident>();
            Incident inci1 = new Incident();
            Inci1.Subject='Test new subject real time';   
            insert inci1;
            Inci.add(inci1);
            
            SPEN_CommunicationScheduler__c c1=new SPEN_CommunicationScheduler__c();
            //c1.Name='Sample com';
            c1.SPEN_BatchJobId__c=jobid; 
            c1.SPEN_MessagingTaskId__c=sMsgtask1.id;
            c1.SPEN_Action__c='Send SMS to PSR';
            c1.SPEN_IncidentId__c=Inci1.id;
            c1.SPEN_Message__c='Test';
            c1.SPEN_ScheduledDateTime__c=DateTime.newInstance(1997, 1, 31, 10, 8, 16);
            c1.SPEN_Status__c='Not Started';
            comList.add(c1);
            insert comList;
            
            SPEN_AbortBatch.inputVariables inp=new SPEN_AbortBatch.inputVariables();
            inp.comSchedule=comList;
            SPEN_AbortBatch.abortJob(new List<SPEN_AbortBatch.inputVariables>{inp});
            if(sMsgtask1!=null && sMsgtask1.id!=null){
                SPEN_CommunicationScheduler__c comSch=[Select id,SPEN_Status__c from SPEN_CommunicationScheduler__c where SPEN_MessagingTaskId__c=:sMsgtask1.id limit 1];
                Assert.areEqual(comSch.SPEN_Status__c,'Cancelled'); 
            }
            Test.stopTest();
        }
    }
    @IsTest
    @SuppressWarnings('PMD.SOQLSelectorPattern')
    private static void testAbortBatchexecuteNeg()
    {
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);
        System.runAs(user)
        {
            Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
            Test.startTest();
            List<Account> accRec = SPEN_TestDataFactory.createAccounts('Test',SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert accRec;
            Contact con= SPEN_TestDataFactory.createContacts(accRec[0].Id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert con;
            List<SPEN_PSR__c> psralert=SPEN_TestDataFactory.createPSRrecord(SPEN_TestDataFactoryConstants.SINGLE_REC);
            psralert[0].SPEN_Contact__c=con.Id;
            insert psralert;
            List<Id> psrList=new List<Id>();
            
            psrList.add(psralert[0].Id);
            List<SPEN_CommunicationScheduler__c> comList=new List<SPEN_CommunicationScheduler__c>();
            
            Datetime scTime=System.now().addDays(1);
            
            String cron;
            String second = String.valueOf(scTime.second());
            String minute = String.valueOf(scTime.minute());
            String hour = String.valueOf(scTime.hour());
            String day = String.valueOf(scTime.day());
            String month = String.valueOf(scTime.month()); 
            String year = String.valueOf(scTime.year());
            
            cron=second+' '+minute+' '+hour+' '+day+' '+month+' '+'?'+' '+year;
            SPEN_SchedulableVoiceAlertClass sVA = new SPEN_SchedulableVoiceAlertClass(psrList,'Voice Alert',scTime);
            
            ID jobid = System.schedule('scheduledVoiceAlert '+System.now(), cron, sVA);
            //Create messaging task
            List<SPEN_MessagingTask__c> sMsgtask = new List<SPEN_MessagingTask__c>();
            SPEN_MessagingTask__c sMsgtask1 = new SPEN_MessagingTask__c();
            sMsgtask1.SPEN_Status__c='New';   
            insert sMsgtask1;
            sMsgtask.add(sMsgtask1);
            
            List<Incident> inci = new List<Incident>();
            Incident inci1 = new Incident();
            Inci1.Subject='Test new subject real time';   
            insert inci1;
            Inci.add(inci1);
            
            SPEN_CommunicationScheduler__c c1=new SPEN_CommunicationScheduler__c();
            //c1.Name='Sample com';
            c1.SPEN_BatchJobId__c=jobid; 
            c1.SPEN_MessagingTaskId__c=sMsgtask1.id;
            c1.SPEN_Action__c='Send SMS to PSR';
            c1.SPEN_IncidentId__c=Inci1.id;
            c1.SPEN_Message__c='Test';
            c1.SPEN_ScheduledDateTime__c=DateTime.newInstance(1997, 1, 31, 10, 8, 16);
            c1.SPEN_Status__c='Not Started';
            comList.add(c1);
            insert comList;
            
            SPEN_AbortBatch.inputVariables inp=new SPEN_AbortBatch.inputVariables();
            inp.comSchedule=comList;
            try{
                SPEN_AbortBatch.abortJob(new List<SPEN_AbortBatch.inputVariables>());
            }catch(Exception e){
                 Assert.isTrue(e!=null);
            }
            if(sMsgtask1!=null && sMsgtask1.id!=null){
                SPEN_CommunicationScheduler__c comSch=[Select id,SPEN_Status__c from SPEN_CommunicationScheduler__c where SPEN_MessagingTaskId__c=:sMsgtask1.id limit 1];
                Assert.isTrue(comSch.SPEN_Status__c!='Cancelled');
            }
            Test.stopTest();
        }
    }
}