force-app/main/default/objects/SPEN_CommunicationScheduler__c/SPEN_CommunicationScheduler__c.object-meta.xml
<CustomObject>
    <description>Use this object to immediately or schedule a bulk outbound communication via SMS, Voice Alerts, etc.</description>
    <label>Communication Scheduler</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Schedulers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_Creation_Batch_Delay__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Creation_Batch_Delay__c</fullName>
    <label>Creation Batch Delay</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_CommunicationScheduler__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <description>The event that initiated the creation of Communication Scheduler.</description>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3-Hour Comfort Call</fullName>
            </value>
            <value>
                <fullName>3rd Call Received</fullName>
            </value>
            <value>
                <fullName>Dropped Supply with Notice</fullName>
            </value>
            <value>
                <fullName>Dropped Supply without Notice</fullName>
            </value>
            <value>
                <fullName>Estimated Restoration Time Extended</fullName>
            </value>
            <value>
                <fullName>Incident Created</fullName>
            </value>
            <value>
                <fullName>Incident Restored</fullName>
            </value>
            <value>
                <fullName>Resource Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Resource Dispatched</fullName>
            </value>
            <value>
                <fullName>Medically Dependent by District</fullName>
            </value>
            <value>
                <fullName>Planned Outage Communication</fullName>
            </value>
            <value>
                <fullName>On Demand</fullName>
            </value>
            <value>
                <fullName>HV proactive contact</fullName>
            </value>
            <value>
                <fullName>15days Task Creation non LVHV</fullName>
            </value>
            <value>
                <fullName>5 Days System Email LVHV</fullName>
            </value>
            <value>
                <fullName>15 Days System Email LVHV</fullName>
            </value>
            <value>
                <fullName>10 Days Task Creation LVHV</fullName>
            </value>
            <value>
                <fullName>20 Days Task Creation LVHV</fullName>
            </value>
            <value>
                <fullName>10 Days System Email Non LVHV</fullName>
            </value>
            <value>
                <fullName>45 Days System email Non LVHV</fullName>
            </value>
            <value>
                <fullName>60 Days task Create Non LVHV</fullName>
            </value>
            <value>
                <fullName>Customer Engagement Task PUM/PDM</fullName>
            </value>
            <value>
                <fullName>Customer Engagement Task HOD</fullName>
            </value>
            <value>
                <fullName>Customer Engagement Task PM</fullName>
            </value>
            <value>
                <fullName>Annual Meeting Prior 14 Days</fullName>
            </value>
            <value>
                <fullName>ITT Issued Due Date Prior 1 day</fullName>
            </value>
            <value>
                <fullName>Energisation Date Prior 14 days</fullName>
            </value>
            <value>
                <fullName>Stage 1 Energisation Date to PM</fullName>
            </value>
            <value>
                <fullName>MTM 2 Offer Expire To NGESO CCM 14 Days</fullName>
            </value>
            <value>
                <fullName>BiAnnual Meeting Prior 14 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/fields/SPEN_Value__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SPEN_CommunicationSchedulers.cls
/**
 * @description       : Service class for SPEN_CommunicationSchedulerTrigger 
 * @author            : rahul.dd.kumar@accenture.com
 * @last modified on  : 03-06-2023
 * @last modified by  : 
**/
public class SPEN_CommunicationSchedulers {
     public void beforeCommunicationSchInsert(List<sObject> commSchNewList){
         SPEN_ConfigurableSettings__c batchDelayInMinutes = [SELECT Id, SPEN_Value__c FROM SPEN_ConfigurableSettings__c WHERE Name='CreationBatchDelayForMessagingTask' Limit 1];
         Integer delayMinutes = Integer.valueOf(batchDelayInMinutes.SPEN_Value__c);
         SPEN_ConfigurableSettings__c onDemandDelayInMinutes = [SELECT Id, SPEN_Value__c FROM SPEN_ConfigurableSettings__c WHERE Name='OnDemandMessageDelayForMessagingTask' Limit 1];
         Integer delayMinutesForOnDemandMessage = Integer.valueOf(onDemandDelayInMinutes.SPEN_Value__c);
         List<SPEN_CommunicationScheduler__c> commSchList = (List<SPEN_CommunicationScheduler__c>)commSchNewList;
         for(SPEN_CommunicationScheduler__c commSch : commSchList){
           if(commSch.SPEN_Event__c=='On Demand')
           {
               commSch.SPEN_Creation_Batch_Delay__c = System.now().addMinutes(delayMinutesForOnDemandMessage);
           }
           else
           {
               commSch.SPEN_Creation_Batch_Delay__c = System.now().addMinutes(delayMinutes);
           }
             
        }
     }
}