force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/fields/SPEN_Value__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/SPEN_IntegrationRequest__c.object-meta.xml
<CustomObject>
    <description>Integration Request object has been set up to use for IVR Integration.</description>
    <label>Integration Request</label>
    <nameField>
        <label>Integration Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_RelatedRecord__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelatedRecord__c</fullName>
    <description>Should be updated with zone id when we are updating the message details in integration request record</description>
    <label>Related Record</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Response__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Response__c</fullName>
    <label>Response</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SPEN_IncidentIntegrationRequestUpdate.cls
public without sharing class SPEN_IncidentIntegrationRequestUpdate {
    public static void afterIncidentIVRMessageAPIUpdate(Map<Id,Incident> selectedIncidentIds,String Incident_ConfigSetting)
    {
        
        Map<String,SPEN_ConfigurableSettings__c> configSetMap = new Map<String,SPEN_ConfigurableSettings__c>();
        configSetMap = SPEN_CaseSelector.configSettingsMap;
        
        Integer threshold = Integer.valueOf(configSetMap.get(Incident_ConfigSetting).SPEN_Value__c);
        Datetime dateThreshold = system.now().addHours(-threshold);
        List<SPEN_IntegrationRequest__c> intReqList = new List<SPEN_IntegrationRequest__c>();
        if(!selectedIncidentIds.isEmpty())
        {
            for(SPEN_IntegrationRequest__c intRequest : geIntegrationRequestIncident(selectedIncidentIds.keySet(), dateThreshold))
            {
                intRequest.SPEN_Response__c = selectedIncidentIds.get(intRequest.SPEN_RelatedRecord__c).SPEN_IVRMessage__c;
                intReqList.add(intRequest);
            }
        }
        
        if(!intReqList.isEmpty())
        {
            update intReqList;
        }
    }
    public static List<SPEN_IntegrationRequest__c> geIntegrationRequestIncident(set<Id> relatedRecordsId, Datetime threshHold){
        List<SPEN_IntegrationRequest__c> intRequestZone;
        if(relatedRecordsId != null && threshHold != null)
        	intRequestZone =[SELECT Id,SPEN_Response__c,SPEN_RelatedRecord__c
                                                        FROM SPEN_IntegrationRequest__c
                                                        WHERE SPEN_RelatedRecord__c =: relatedRecordsId
                                                        AND CreatedDate >=: threshHold
                                                   ];
        /*System.debug('=====intRequestZone'+intRequestZone);
        System.debug('=====zoneId'+relatedRecordsId);
        System.debug('=====threshHold'+threshHold);*/
        return intRequestZone;
    }
}