force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ContactPremise__c/SPEN_ContactPremise__c.object-meta.xml
<CustomObject>
    <label>Contact Premise</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Contact Premise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>49</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>Contact Premises</relationshipLabel>
    <relationshipName>Contact_Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_Role__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>PSR Contact</fullName>
                <label>PSR Contact (Primary)</label>
            </value>
            <value>
                <fullName>Alternative Contact</fullName>
            </value>
            <value>
                <fullName>Premise Owner</fullName>
            </value>
            <value>
                <fullName>PSR Contact (Alternative)</fullName>
            </value>
            <value>
                <fullName>Site Contact</fullName>
                <isActive>false</isActive>
                <label>Site Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CustomerUpdate__c/SPEN_CustomerUpdate__c.object-meta.xml
<CustomObject>
    <description>Various update activities to inform customers.</description>
    <label>Outbound Dialler Task</label>
    <nameField>
        <displayFormat>OD-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Dialler Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CustomerUpdate__c/fields/SPEN_Campaign__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Campaign__c</fullName>
    <label>Campaign</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stage 1</fullName>
            </value>
            <value>
                <fullName>Stage 2</fullName>
            </value>
            <value>
                <fullName>Stage 3</fullName>
            </value>
            <value>
                <fullName>Stage 4</fullName>
            </value>
            <value>
                <fullName>Stage 2 Reply</fullName>
            </value>
            <value>
                <fullName>Stage 1 Reply</fullName>
            </value>
            <value>
                <fullName>Stage 3 Reply</fullName>
            </value>
            <value>
                <fullName>Stage 4 Reply</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_CustomerUpdate__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_CustomerUpdate__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipName>Customer_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_CustomerUpdate__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
                <isActive>false</isActive>
                <label>Dropped</label>
            </value>
            <value>
                <fullName>RetryCustomer</fullName>
                <isActive>false</isActive>
                <label>RetryCustomer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/SPEN_ImpactedPremise__c.object-meta.xml
<CustomObject>
    <label>Impacted Premise</label>
    <nameField>
        <displayFormat>IP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impacted Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_ContactPremise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ContactPremise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Premise</label>
    <referenceTo>SPEN_ContactPremise__c</referenceTo>
    <relationshipLabel>Impacted Premises</relationshipLabel>
    <relationshipName>Impacted_Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>It should be Combination of Incident and Premise</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <label>IncidentId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_IncidentType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentType__c</fullName>
    <label>Incident Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SP</fullName>
                <label>Single Premise Incident</label>
            </value>
            <value>
                <fullName>LV</fullName>
                <label>Low Voltage Incident</label>
            </value>
            <value>
                <fullName>HV_S</fullName>
                <label>High Voltage Incident</label>
            </value>
            <value>
                <fullName>HV_N</fullName>
                <label>High Voltage Network Incident</label>
            </value>
            <value>
                <fullName>CG</fullName>
                <label>Call Group Incident</label>
            </value>
            <value>
                <fullName>AREA</fullName>
                <label>Area Incident</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_PremiseId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseId__c</fullName>
    <externalId>true</externalId>
    <label>PremiseId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_RelatedIncident__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelatedIncident__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Impacted Premises</relationshipLabel>
    <relationshipName>Impacted_Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Restored</fullName>
            </value>
            <value>
                <fullName>Not Restored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Unique SPEN identifier for a premise</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/SPEN_PSR__c.object-meta.xml
<CustomObject>
    <description>PSR object has been set up to see all the PSR related information</description>
    <label>PSR</label>
    <nameField>
        <displayFormat>PSR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Contact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_PSRVulnerabilityType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PSRVulnerabilityType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PSR and Vulnerability Type</label>
    <referenceTo>SPEN_PSRVulnerabilityType__c</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRVulnerabilityType__c/SPEN_PSRVulnerabilityType__c.object-meta.xml
<CustomObject>
    <description>PSR Type/Vulnerability Type object has been set up to store master data</description>
    <label>PSR and Vulnerability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSR and Vulnerability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSRVulnerabilityType__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <label>[TO BE DELETED] External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SPEN_OutboundDialerServiceTEST.cls
@IsTest
@SuppressWarnings('PMD.SOQLSelectorPattern')
public class SPEN_OutboundDialerServiceTEST {
    
    @IsTest
    private static void testIdentificationMethod()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user); 
        if (devOpsPSGroup.Status != 'Updated') {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);
        }
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.Id;
        insert devOpsAssign;
        System.runAs(user){
            Test.startTest();
            SPEN_ConfigurableSettings__c cS2 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelay');
            insert cS2;
            List<Account> accRec = SPEN_TestDataFactory.createAccounts('Test',SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert accRec;
            
            List<SPEN_Premise__c> premiseList = SPEN_TestDataFactory.createListOfPremise(2);
            insert premiseList; 
            
            Contact con= SPEN_TestDataFactory.createContacts(accRec[0].Id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            //con.MobilePhone='1234567892';
            con.SPEN_PSR__c=true;
            con.SPEN_IsPrimaryContact__c = true;
            con.SPEN_CustomerID__c = String.valueOf(premiseList[0].Id);
            insert con;
            
            /*Contact con1= SPEN_TestDataFactory.createContacts(accRec[0].Id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            //con.MobilePhone='1234567892';
            con1.SPEN_PSR__c=true;
            con1.SPEN_IsPrimaryContact__c = true;
            con1.SPEN_CustomerID__c = String.valueOf(premiseList[1].Id);
            insert con1;*/
            
            Contact con1= SPEN_TestDataFactory.createContacts(accRec[0].Id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            con1.MobilePhone = '07123456799';
            con1.FirstName = 'John';
            con1.LastName = 'Doe';
            con1.Phone = '01234567891';
            con1.SPEN_PSR__c=false;
            con1.SPEN_IsPrimaryContact__c = false;
            con1.SPEN_CustomerID__c = String.valueOf(premiseList[1].Id);
            insert con1;
            
            List<Case> testCase = SPEN_TestDataFactory.createListOfCases(SPEN_TestDataFactoryConstants.SINGLE_REC);
            testCase[0].Origin = 'Web';
            testCase[0].ContactId=con.Id;
            insert testCase;
            
            list<SPEN_PSRVulnerabilityType__c> psrv=SPEN_TestDataFactory.createPSRVulnerabilityRecords();
            insert psrv;
            
            List<SPEN_PSR__c> psralert1=SPEN_TestDataFactory.createPSRrecord(SPEN_TestDataFactoryConstants.SINGLE_REC);
            psralert1[0].SPEN_Contact__c=con.Id;
            psralert1[0].SPEN_PSRVulnerabilityType__c=psrv[0].Id;
            insert psralert1;
            
            SPEN_ContactPremise__c conpremise = SPEN_TestDataFactory.createContactPremises(SPEN_TestDataFactoryConstants.SINGLE_REC,con.Id,premiseList[0].Id);
            conpremise.SPEN_ExternalId__c='1244';
            conpremise.SPEN_Role__c = 'Customer';
            insert conpremise;
            
            SPEN_ContactPremise__c conpremise2 = SPEN_TestDataFactory.createContactPremises(SPEN_TestDataFactoryConstants.SINGLE_REC,con1.Id,premiseList[0].Id);
            conpremise2.SPEN_ExternalId__c='1245';
            conpremise2.SPEN_Role__c = 'Alternative Contact';
            insert conpremise2;
            
            Incident inc = SPEN_TestDataFactory.createIncidents(testCase[0].id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            inc.SPEN_IncidentType__c='SP';
            inc.SPEN_IncidentID__c = '1111';
            insert inc;
            
            Incident inc1 = SPEN_TestDataFactory.createIncidents(testCase[0].id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            inc1.SPEN_IncidentType__c='SP';
            inc1.SPEN_IncidentID__c = '111456789';
            insert inc1;
            List<String> inclist=new List<String>();
            inclist.add(inc.Id);
            inclist.add(inc1.Id);
            
            
            SPEN_ConfigurableSettings__c cSeting= SPEN_TestDataFactory.createConfigSetting(1,'OutboundIncidentType');
            insert cSeting;
            
            List<SPEN_ImpactedPremise__c> impList=SPEN_TestDataFactory.createImpactedPremiserecord(2);
            impList[0].SPEN_Status__c='Not Restored';
            impList[0].SPEN_RelatedIncident__c=inc.Id;
            impList[0].SPEN_ContactPremise__c=conpremise.Id;
            impList[0].SPEN_PremiseId__c = String.valueOf(premiseList[0].Id);
            impList[0].SPEN_IncidentId__c = '1111';
            
            impList[1].SPEN_Status__c='Not Restored';
            impList[1].SPEN_RelatedIncident__c=inc.Id;
            impList[1].SPEN_ContactPremise__c=conpremise.Id;
            impList[1].SPEN_PremiseId__c = String.valueOf(premiseList[0].Id);
            impList[1].SPEN_IncidentId__c = '1112';
            insert impList;
            
            Group odQue=new Group();
            odQue.DeveloperName='Outbound_Dialer2';
            odQue.Name='Outbound Dialer';
            insert odQue;
            
            User user1 = SPEN_TestDataFactory.settestUser('Minimum Access - Salesforce');
            Database.insert(user1);
            
            SPEN_CustomerUpdate__c cus=new SPEN_CustomerUpdate__c();
            cus.SPEN_IncidentId__c=inc.Id;
            cus.OwnerId=user1.Id;
            cus.SPEN_Campaign__c='Stage 3';
            insert cus;
            
            map<id,SPEN_ImpactedPremise__c> impMap = new map<id,SPEN_ImpactedPremise__c>();
            impMap.put(impList[0].id, impList[0]);
            impMap.put(impList[1].id, impList[1]);
            
            SPEN_OutboundDialerService ods = new SPEN_OutboundDialerService();
            //ods.IdentificationMethod(impList, impMap);
            //ods.IdentificationMethod(impList, null);
            SPEN_OutboundDialerService.dropOlderODTasksOnMerge(inclist);
            SPEN_OutboundDialerService.dropOlderODTasksOnDelog(inclist);
            SPEN_OutboundDialerService.dropComfortODTasksOnERTChange(inclist);
            Assert.isNotNull(inclist, 'Assertion Passed');
            Test.stopTest();
        }
    }
}