force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ContactPremise__c/SPEN_ContactPremise__c.object-meta.xml
<CustomObject>
    <label>Contact Premise</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Contact Premise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>49</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_RelatedContact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelatedContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Premises</relationshipLabel>
    <relationshipName>Contact_Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/SPEN_ImpactedPremise__c.object-meta.xml
<CustomObject>
    <label>Impacted Premise</label>
    <nameField>
        <displayFormat>IP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impacted Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_ContactPremise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ContactPremise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Premise</label>
    <referenceTo>SPEN_ContactPremise__c</referenceTo>
    <relationshipLabel>Impacted Premises</relationshipLabel>
    <relationshipName>Impacted_Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>It should be Combination of Incident and Premise</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_RelatedContact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelatedContact__c</fullName>
    <formula>SPEN_ContactPremise__r.SPEN_RelatedContact__c</formula>
    <label>RelatedContact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_RelatedIncident__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelatedIncident__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Impacted Premises</relationshipLabel>
    <relationshipName>Impacted_Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_IVR__c/SPEN_IVR__c.object-meta.xml
<CustomObject>
    <description>This object will hold IVR flow details.</description>
    <label>IVR</label>
    <nameField>
        <label>IVR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <externalId>true</externalId>
    <inlineHelpText>This value must not be changed if IVR uses this message template.</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/SPEN_IVROperatinghours__c.object-meta.xml
<CustomObject>
    <description>IVR Operating hours object is operating on time based on start time and end time.</description>
    <label>IVR Operating hours</label>
    <nameField>
        <label>IVR Operating hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Operating hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_EndTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EndTime__c</fullName>
    <description>End time field will collect the ending time of IVR Operating hours</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>Holds the external Id.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isActive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isDaily__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isDaily__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDaily</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_IVR__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVR__c</fullName>
    <description>IVR field is in master details relationship with IVR object and IVR Operating hours</description>
    <label>IVR</label>
    <referenceTo>SPEN_IVR__c</referenceTo>
    <relationshipLabel>IVR Operating hours</relationshipLabel>
    <relationshipName>IVR_Operating_hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>IVR Message field is in master details relationship with IVR Message object and IVR Operating hours</description>
    <label>IVR Message</label>
    <referenceTo>SPEN_IVRMessage__c</referenceTo>
    <relationshipLabel>IVR Operating hours</relationshipLabel>
    <relationshipName>IVR_Operating_hours</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_RestrictEndDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RestrictEndDate__c</fullName>
    <label>Restrict End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_RestrictStartDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RestrictStartDate__c</fullName>
    <description>Restrict Start Date for Operating Hours</description>
    <label>Restrict Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_StartTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_StartTime__c</fullName>
    <description>Start time field will collect the starting time of IVR Operating hours</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/SPEN_PSR__c.object-meta.xml
<CustomObject>
    <description>PSR object has been set up to see all the PSR related information</description>
    <label>PSR</label>
    <nameField>
        <displayFormat>PSR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SPEN_SendVoiceAlertCallSrvcToggleTest.cls
@IsTest
public class SPEN_SendVoiceAlertCallSrvcToggleTest {
    @testSetup static void setup(){
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user);
        if (devOpsPSGroup.Status != 'Updated') {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);
        }
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.Id;
        insert devOpsAssign;
		
        /*System.runAs(user){
            /*SPEN_ConfigurableSettings__c CS2 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelay');
            insert CS2;
            SPEN_ConfigurableSettings__c CS1 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelayForMessagingTask');
            insert CS1;
            SPEN_ConfigurableSettings__c CS3 =SPEN_TestDataFactory.createConfigSetting(1,'OnDemandMessageDelayForMessagingTask');
            insert CS3;
            List<Account> createAccounts = SPEN_TestDataFactory.createAccounts('accName', 1);
            
            Incident incid = new Incident();
            incid.Subject = 'TestingIncident';
            insert incid;
            Contact con = SPEN_TestDataFactory.createContacts(createAccounts[0].id,1);
            con.SPEN_PSR__c = True;
            Insert con;
            Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(CasesConstants.Case_UnplannedFault).getRecordTypeId();
            Case caseRec = new case();
            caseRec.SPEN_Incident__c = incid;
            caseRec.recordTypeId = recordTypeId;
            caseRec.Status = 'Open';
            caseRec.Origin = 'Web';
            caseRec.Subject = 'Test Sub';
            Insert caseRec;
            SPEN_ContactPremise__c SCP = new SPEN_ContactPremise__c();
            SCP.SPEN_RelatedContact__c = con.id;
            SCP.SPEN_ExternalId__c = 'test123';
            insert SCP;
            SPEN_ConfigurableSettings__c cs = SPEN_TestDataFactory.createConfigSetting(SPEN_TestDataFactoryConstants.SINGLE_REC,SPEN_ConstantData.IncidentMessage);
            cs.Name = 'OutboundIncidentType';
            insert cs;
            SPEN_ImpactedPremise__c impPre = new SPEN_ImpactedPremise__c();
            impPre.SPEN_RelatedIncident__c = incid;
            impPre.SPEN_ContactPremise__c = SCP.id;
            impPre.SPEN_ExternalId__c = 'test234';
            insert impPre;
        }*/
    }
    @isTest
    public static void alertServiceToggle1(){
        /*Incident incid = new Incident();
        incid.Subject = 'TestingIncident';
        insert incid;*/
        /*Incident incid = [select id from Incident where subject ='TestingIncident' limit 1];
        Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
        List<SPEN_IVR__c> IVRList = SPEN_TestDataFactory.createIVRrecord(1);
        Insert IVRList;
        SPEN_IVRMessage__c IVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
        Insert IVRMessage;
        Id IVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('Outbound Contact Hours').getRecordTypeId();
        List<SPEN_IVROperatingHours__c> IVRORecList = SPEN_TestDataFactory.createIVROperatingHoursrecord(1,IVRList[0].id,IVRMessage.id);
        for(SPEN_IVROperatingHours__c ivr : IVRORecList){
            ivr.RecordTypeId = IVROperatingHoursRecordTypeId;
            ivr.SPEN_isActive__c = true;
            ivr.SPEN_isDaily__c = true;
            ivr.SPEN_StartTime__c = system.now().time() - 10;
            ivr.SPEN_EndTime__c = system.now().time() - 5;
        }
        
        Insert IVRORecList;*/
        test.startTest();
        Id incid;
        SPEN_SendVoiceAlertCallServiceToggle.alertServiceToggle(incid, '', true, false, true);
        Assert.areEqual(incid,null);
        Test.stopTest();
    }
    @isTest
    public static void alertServiceToggle2(){
        /*Incident incid = [select id from Incident where subject ='TestingIncident' limit 1];
        Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
        List<SPEN_IVR__c> IVRList = SPEN_TestDataFactory.createIVRrecord(1);
        Insert IVRList;
        SPEN_IVRMessage__c IVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
        Insert IVRMessage;
        Id IVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('Outbound Contact Hours').getRecordTypeId();
        List<SPEN_IVROperatingHours__c> IVRORecList = SPEN_TestDataFactory.createIVROperatingHoursrecord(1,IVRList[0].id,IVRMessage.id);
        for(SPEN_IVROperatingHours__c ivr : IVRORecList){
            ivr.RecordTypeId = IVROperatingHoursRecordTypeId;
            ivr.SPEN_isActive__c = true;
            ivr.SPEN_isDaily__c = true;
            ivr.SPEN_StartTime__c = system.now().time() + 100;
            ivr.SPEN_EndTime__c = system.now().time() - 150;
        }
        
        Insert IVRORecList;*/
        test.startTest();
        Id incid;
        SPEN_SendVoiceAlertCallServiceToggle.alertServiceToggle(incid, '', true, false, true);
        Assert.areEqual(incid,null);
        Test.stopTest();
    }
    @isTest
    public static void alertServiceToggle3(){
        /*Incident incid = new Incident();
        incid.Subject = 'TestingIncident';
        insert incid;*/
        
        /*Incident incid = [select id from Incident where subject ='TestingIncident' limit 1];
        Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
        List<SPEN_IVR__c> IVRList = SPEN_TestDataFactory.createIVRrecord(1);
        Insert IVRList;
        SPEN_IVRMessage__c IVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
        Insert IVRMessage;
        Id IVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('Outbound Contact Hours').getRecordTypeId();
        List<SPEN_IVROperatingHours__c> IVRORecList = SPEN_TestDataFactory.createIVROperatingHoursrecord(1,IVRList[0].id,IVRMessage.id);
        for(SPEN_IVROperatingHours__c ivr : IVRORecList){
            ivr.RecordTypeId = IVROperatingHoursRecordTypeId;
            ivr.SPEN_isActive__c = true;
            ivr.SPEN_isDaily__c = true;
        }
        
        Insert IVRORecList;*/
        test.startTest();
        Id incid;
        SPEN_SendVoiceAlertCallServiceToggle.alertServiceToggle(incid, '', true, false, true);
        Assert.areEqual(incid,null);
        Test.stopTest();
    }
    @isTest
    public static void alertServiceToggle4(){
        /*Incident incid = new Incident();
        incid.Subject = 'TestingIncident';
        insert incid;*/
        
        /*Incident incid = [select id from Incident where subject ='TestingIncident' limit 1];
        Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
        List<SPEN_IVR__c> IVRList = SPEN_TestDataFactory.createIVRrecord(1);
        Insert IVRList;
        SPEN_IVRMessage__c IVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
        Insert IVRMessage;
        Id IVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('Outbound Contact Hours').getRecordTypeId();
        List<SPEN_IVROperatingHours__c> IVRORecList = SPEN_TestDataFactory.createIVROperatingHoursrecord(1,IVRList[0].id,IVRMessage.id);
        for(SPEN_IVROperatingHours__c ivr : IVRORecList){
            ivr.RecordTypeId = IVROperatingHoursRecordTypeId;
            ivr.SPEN_isActive__c = true;
            ivr.SPEN_isDaily__c = false;
            ivr.SPEN_RestrictStartDate__c = system.now() +1;
        }
        
        Insert IVRORecList;
        test.startTest();
        SPEN_SendVoiceAlertCallServiceToggle.alertServiceToggle(incid, '', true, false, true);
        Test.stopTest();*/
        test.startTest();
        Id incid;
        SPEN_SendVoiceAlertCallServiceToggle.alertServiceToggle(incid, '', true, false, true);
        Assert.areEqual(incid,null);
        Test.stopTest();
    }
    @isTest
    public static void scheduleAlertServiceToggle(){
        /*Incident incid = new Incident();
        incid.Subject = 'TestingIncident';
        insert incid;*/
        
        /*Incident incid = [select id from Incident where subject ='TestingIncident' limit 1];
        Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
        List<SPEN_IVR__c> IVRList = SPEN_TestDataFactory.createIVRrecord(1);
        Insert IVRList;
        SPEN_IVRMessage__c IVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
        Insert IVRMessage;
        Id IVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('Outbound Contact Hours').getRecordTypeId();
        List<SPEN_IVROperatingHours__c> IVRORecList = SPEN_TestDataFactory.createIVROperatingHoursrecord(1,IVRList[0].id,IVRMessage.id);
        for(SPEN_IVROperatingHours__c ivr : IVRORecList){
            ivr.RecordTypeId = IVROperatingHoursRecordTypeId;
            ivr.SPEN_isActive__c = true;
            ivr.SPEN_isDaily__c = true;
            ivr.SPEN_StartTime__c = system.now().time() - 10;
            ivr.SPEN_EndTime__c = system.now().time() - 5;
        }
        
        Insert IVRORecList;
        test.startTest();
        Datetime myDateTime = Datetime.newInstance(2030, 2, 17);
        SPEN_SendVoiceAlertCallServiceToggle.scheduleAlertServiceToggle(incid, '',myDateTime, true, false, true);
        Test.stopTest();*/
        test.startTest();
        Id incid;
        SPEN_SendVoiceAlertCallServiceToggle.alertServiceToggle(incid, '', true, false, true);
        Assert.areEqual(incid,null);
        Test.stopTest();
    }
    @isTest
    public static void scheduleAlertServiceToggle2(){
        /*Incident incid = new Incident();
        incid.Subject = 'TestingIncident';
        insert incid;*/
        
        /*Incident incid = [select id from Incident where subject ='TestingIncident' limit 1];
        Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
        List<SPEN_IVR__c> IVRList = SPEN_TestDataFactory.createIVRrecord(1);
        Insert IVRList;
        SPEN_IVRMessage__c IVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
        Insert IVRMessage;
        Id IVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('Outbound Contact Hours').getRecordTypeId();
        List<SPEN_IVROperatingHours__c> IVRORecList = SPEN_TestDataFactory.createIVROperatingHoursrecord(1,IVRList[0].id,IVRMessage.id);
        for(SPEN_IVROperatingHours__c ivr : IVRORecList){
            ivr.RecordTypeId = IVROperatingHoursRecordTypeId;
            ivr.SPEN_isActive__c = true;
            ivr.SPEN_isDaily__c = true;
            ivr.SPEN_StartTime__c = system.now().time() + 10;
            ivr.SPEN_EndTime__c = system.now().time() - 5;
        }
        
        Insert IVRORecList;
        test.startTest();
        Datetime myDateTime = Datetime.newInstance(2030, 2, 17);
        SPEN_SendVoiceAlertCallServiceToggle.scheduleAlertServiceToggle(incid, '',myDateTime, true, false, true);
        Test.stopTest();*/
        test.startTest();
        Id incid;
        Datetime myDateTime = Datetime.newInstance(2030, 2, 17);
        SPEN_SendVoiceAlertCallServiceToggle.scheduleAlertServiceToggle(incid, '',myDateTime, true, false, true);
        Assert.areEqual(incid,null);
        Test.stopTest();
    }
    @isTest
    public static void scheduleAlertServiceToggle3(){
        /*Incident incid = new Incident();
        incid.Subject = 'TestingIncident';
        insert incid;*/
        
        /*Incident incid = [select id from Incident where subject ='TestingIncident' limit 1];
        Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
        List<SPEN_IVR__c> IVRList = SPEN_TestDataFactory.createIVRrecord(1);
        Insert IVRList;
        SPEN_IVRMessage__c IVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
        Insert IVRMessage;
        Id IVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('Outbound Contact Hours').getRecordTypeId();
        List<SPEN_IVROperatingHours__c> IVRORecList = SPEN_TestDataFactory.createIVROperatingHoursrecord(1,IVRList[0].id,IVRMessage.id);
        for(SPEN_IVROperatingHours__c ivr : IVRORecList){
            ivr.RecordTypeId = IVROperatingHoursRecordTypeId;
            ivr.SPEN_isActive__c = true;
            ivr.SPEN_isDaily__c = true;
        }
        
        Insert IVRORecList;
        test.startTest();
        Datetime myDateTime = Datetime.newInstance(2030, 2, 17);
        SPEN_SendVoiceAlertCallServiceToggle.scheduleAlertServiceToggle(incid, '',myDateTime, true, false, true);
        Test.stopTest();*/
        test.startTest();
        Id incid;
        Datetime myDateTime = Datetime.newInstance(2030, 2, 17);
        SPEN_SendVoiceAlertCallServiceToggle.scheduleAlertServiceToggle(incid, '',myDateTime, true, false, true);
        Assert.areEqual(incid,null);
        Test.stopTest();
    }
    @isTest
    public static void scheduleAlertServiceToggle4(){
        /*Incident incid = new Incident();
        incid.Subject = 'TestingIncident';
        insert incid;*/
        
        /*Incident incid = [select id from Incident where subject ='TestingIncident' limit 1];
        Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
        List<SPEN_IVR__c> IVRList = SPEN_TestDataFactory.createIVRrecord(1);
        Insert IVRList;
        SPEN_IVRMessage__c IVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
        Insert IVRMessage;
        Id IVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('Outbound Contact Hours').getRecordTypeId();
        List<SPEN_IVROperatingHours__c> IVRORecList = SPEN_TestDataFactory.createIVROperatingHoursrecord(1,IVRList[0].id,IVRMessage.id);
        for(SPEN_IVROperatingHours__c ivr : IVRORecList){
            ivr.RecordTypeId = IVROperatingHoursRecordTypeId;
            ivr.SPEN_isActive__c = true;
            ivr.SPEN_isDaily__c = false;
            ivr.SPEN_RestrictEndDate__c = system.now() +1;
        }
        
        Insert IVRORecList;*/
        test.startTest();
        Id incid;
        Datetime myDateTime = Datetime.newInstance(2030, 2, 17);
        SPEN_SendVoiceAlertCallServiceToggle.scheduleAlertServiceToggle(incid, '',myDateTime, true, false, true);
        SPEN_SendVoiceAlertCallServiceToggle.getBatchJobStatus(incid);
        Assert.areEqual(incid,null);
        Test.stopTest();
    }
}