force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/fields/SPEN_Description__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/fields/SPEN_Value__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <externalId>true</externalId>
    <inlineHelpText>This value must not be changed if IVR uses this message template.</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_Purpose__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Storm</fullName>
            </value>
            <value>
                <fullName>LV</fullName>
            </value>
            <value>
                <fullName>HV</fullName>
            </value>
            <value>
                <fullName>Flickering</fullName>
            </value>
            <value>
                <fullName>XRT</fullName>
            </value>
            <value>
                <fullName>XRT - Some On</fullName>
            </value>
            <value>
                <fullName>ETR Unknown</fullName>
            </value>
            <value>
                <fullName>HV Shutdown for Safety</fullName>
            </value>
            <value>
                <fullName>Dropped Supply</fullName>
            </value>
            <value>
                <fullName>Dropped Supply Within a Fault</fullName>
            </value>
            <value>
                <fullName>Multiple Fuse Replacements</fullName>
            </value>
            <value>
                <fullName>Extended Awaiting Emergency Services to provide access</fullName>
            </value>
            <value>
                <fullName>Some on Some off</fullName>
            </value>
            <value>
                <fullName>Cancelled Pre Arranged</fullName>
            </value>
            <value>
                <fullName>Extended Pre-Arranged</fullName>
            </value>
            <value>
                <fullName>Generators</fullName>
            </value>
            <value>
                <fullName>Unconfirmed reports of Fire, Vandalism, 3rd Party damage</fullName>
            </value>
            <value>
                <fullName>Comfort</fullName>
            </value>
            <value>
                <fullName>3-Hour Comfort Call</fullName>
            </value>
            <value>
                <fullName>3rd Call Received</fullName>
            </value>
            <value>
                <fullName>Dropped Supply with Notice</fullName>
            </value>
            <value>
                <fullName>Dropped Supply without Notice</fullName>
            </value>
            <value>
                <fullName>Estimated Restoration Time Extended</fullName>
            </value>
            <value>
                <fullName>Incident Created</fullName>
            </value>
            <value>
                <fullName>Incident Restored</fullName>
            </value>
            <value>
                <fullName>Resource Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Resource Dispatched</fullName>
            </value>
            <value>
                <fullName>Restore Confirmation</fullName>
            </value>
            <value>
                <fullName>MPAS Inquiry</fullName>
            </value>
            <value>
                <fullName>MPAS Out-Of-Area Inquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/recordTypes/SMS.recordType-meta.xml
<RecordType>
    <fullName>SMS</fullName>
    <active>true</active>
    <label>SMS</label>
</RecordType>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseDistrict__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseDistrict__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>21.6.23: as aligned with Lauren in context of CRMD-430: this field is not in use at all in PROD (populated for 5 records only) --&gt; NO LONGER RELEVANT &amp; candidate for deletion.</description>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SPEN_Zone__c.SPEN_Type__c</field>
            <operation>equals</operation>
            <value>District</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Premises (District)</relationshipLabel>
    <relationshipName>Premises1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_Zone__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SPEN_Zone__c.SPEN_Type__c</field>
            <operation>equals</operation>
            <value>Zone</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/SPEN_PSR__c.object-meta.xml
<CustomObject>
    <description>PSR object has been set up to see all the PSR related information</description>
    <label>PSR</label>
    <nameField>
        <displayFormat>PSR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_SpecificVulnerability__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SpecificVulnerability__c</fullName>
    <formula>If(AND(NOT(SPEN_PSREffectiveToDate__c  &lt;  TODAY()),NOT(ISBLANK(SPEN_PSREffectiveToDate__c  )), SPEN_PSRVulnerabilityType__r.SPEN_SpecificVulnerability__c) , true, if(AND(ISBLANK(SPEN_PSREffectiveToDate__c  ), SPEN_PSRVulnerabilityType__r.SPEN_SpecificVulnerability__c),true,false))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Specific Vulnerability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/SPEN_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <label>IVR Message Temporary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_Parent__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Zone</relationshipLabel>
    <relationshipName>Zone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SPEN_IncidentScopeChangeProcessBatchTest.cls
/**
* @description       : Test class for SPEN_IncidentScopeChangedProcessingBatch
* @author            : Rahul Kumar
* @group             : 
* @last modified on  : 21-11-2023
* @last modified by  : rahul.dd.kumar@accenture.com
**/
@IsTest(SeeAllData=false)
public class SPEN_IncidentScopeChangeProcessBatchTest{
   
    @testSetup 
    static void dataSetup(){
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user);
        if (devOpsPSGroup.Status != 'Updated'){
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);
        }
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.Id;
        insert devOpsAssign;
        List<PermissionSetAssignment> psaList=new list<PermissionSetAssignment>();
        PermissionSet ps9 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_Zone_CRU'];
        psaList.add(new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps9.Id));
        PermissionSet ps3 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_ConfigurableSettingsRU'];
        psaList.add(new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps3.Id));
        insert psaList;
        System.runAs(user){
            List<SPEN_ConfigurableSettings__c> csList=new List<SPEN_ConfigurableSettings__c>();
            SPEN_ConfigurableSettings__c cS =SPEN_TestDataFactory.createConfigSetting(1,'Incident broadcast message updated last one hour');
            csList.add(cS);
            SPEN_ConfigurableSettings__c cS1 =SPEN_TestDataFactory.createConfigSetting(1,'MessagingTaskType');
            csList.add(cS1);
            SPEN_ConfigurableSettings__c cS2 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelay');
            csList.add(cS2);
            SPEN_ConfigurableSettings__c cS3 =SPEN_TestDataFactory.createConfigSetting(1,'HV Incident Message');
            csList.add(cS3);
            SPEN_ConfigurableSettings__c cS4 =SPEN_TestDataFactory.createConfigSetting(1,'GetAffectedPremiseINCType');
            cS4.SPEN_Value__c = 'HV_N,HV_S,LV';
            cS4.SPEN_Description__c ='config setting description';
            csList.add(cS4);
            insert csList;
            Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
            Integer threshold = Integer.valueOf(cS.SPEN_Value__c);
            Datetime dateThreshHold = system.now().addHours(-threshold);            
            Id msgRecordTypeId = Schema.SObjectType.SPEN_IVRMessage__c.getRecordTypeInfosByName().get('SMS').getRecordTypeId();
            SPEN_IVRMessage__c message = new SPEN_IVRMessage__c();
            message=new SPEN_IVRMessage__c();
            message.Name='SMS – Single Premise – Network Fault';
            message.SPEN_IVRMessage__c='The following information is only for the customers';
            message.RecordTypeId=msgRecordTypeId;
            message.SPEN_Purpose__c='Incident Created';
            message.SPEN_ExternalId__c = 'SMS – Single Premise – Network Fault';
            insert message;
    
            SPEN_Zone__c zoneRegionRecord = SPEN_TestDataFactory.createZoneRegionRecords(message.Id);
            insert zoneRegionRecord;
    
            SPEN_Zone__c zoneDistrictRecord = SPEN_TestDataFactory.createZoneDistrictRecords(message.Id);
            zoneDistrictRecord.SPEN_Parent__c=zoneRegionRecord.Id;
            zoneDistrictRecord.Name = 'districtzone';
            insert zoneDistrictRecord;
            
            List<SPEN_Premise__c> lstPremise =  SPEN_TestDataFactory.createListOfPremise(1);
            lstPremise[0].SPEN_PremiseDistrict__c = zoneDistrictRecord.id;
            insert lstPremise;
            
        

            Contact contactObj = SPEN_TestDataFactory.createContacts(null,1);
            contactObj.SPEN_PSR__c = true;
            contactObj.SPEN_SpecificVulnerability__c =true;
            insert contactObj;

            List<Incident> incList=new List<Incident>();
            Incident inc1 = SPEN_TestDataFactory.createListofIncidents(1)[0];        
            inc1.Status = 'New';
            inc1.SPEN_IncidentCategory__c = 'HV';
            inc1.SPEN_IncidentType__c = 'SP';
            inc1.Subject = 'Testing1';
            incList.add(inc1);
            
            Incident inc2 = SPEN_TestDataFactory.createListofIncidents(1)[0];        
            inc2.Status = 'New';
            inc2.SPEN_IncidentCategory__c = 'HV';
            inc2.Subject = 'Testing2';
            inc2.SPEN_IncidentType__c = 'HV_N';
            inc2.SPEN_IncidentID__c = inc2.SPEN_IncidentID__c + Integer.valueof((Math.random()*10));
            incList.add(inc2); 
            
            insert incList;
            
            Id unplannedFaultRecId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Unplanned - Fault').getRecordTypeId();
            Integer count = 0;
            List<Case> lstCases = new List<Case>();
            for(Case cse : SPEN_TestDataFactory.createListOfCases(1)){
            
                cse.contactId = contactObj.id;
                cse.recordTypeId = unplannedFaultRecId;
                cse.SPEN_Incident__c = inc1.id;
                cse.SPEN_AddressPremise__c = lstPremise[0].Id;
                cse.SPEN_PreferredMethodofContact__c ='T'; 
                cse.SPEN_CallerMobileTelephone__c = '07111111111'; //Mobile number update
                lstCases.add(cse);
            }
            for(Case cse : SPEN_TestDataFactory.createListOfCases(1)){
            
                cse.contactId = contactObj.id;
                cse.recordTypeId = unplannedFaultRecId;
                cse.SPEN_Incident__c = inc1.id;
                cse.SPEN_AddressPremise__c = lstPremise[0].Id;
                cse.SPEN_PreferredMethodofContact__c ='H'; 
                cse.SPEN_CallerTelephone__c = '0111111111'; //Mobile number update
                lstCases.add(cse);
            }
            for(Case cse : SPEN_TestDataFactory.createListOfCases(1)){
            
                cse.contactId = contactObj.id;
                cse.recordTypeId = unplannedFaultRecId;
            // cse.SPEN_Incident__c = inc1.id;
                cse.SPEN_AddressPremise__c = lstPremise[0].Id;
                cse.SPEN_PreferredMethodofContact__c ='H'; 
                cse.SPEN_CallerTelephone__c = '0111111111'; //Mobile number update
                lstCases.add(cse);
            }
			Test.startTest();
            if(!lstCases.isEmpty()){
                insert lstCases;
            }
            Test.stopTest();
        }
    }
    @isTest 
    private static void testInsertScopeChnageProcessing(){
        User u= [Select id FROM User where IsActive=true LIMIT 1];
        System.runAs(u){
            Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
            Test.startTest();
            Incident inc2  = [select id, ParentIncidentId, SPEN_IncidentStatus__c,SPEN_IncidentType__c from Incident where Subject='Testing2' LIMIT 1];
            List<Id> lstOfCaseRef = new List<Id>();

            for(Case cc: [Select Id,Status,SPEN_IsMerge__c,SPEN_Incident__c,SPEN_Incident__r.ParentIncidentId,SPEN_Incident__r.SPEN_IncidentStatus__c,SPEN_Incident__r.SPEN_IncidentType__c from CASE where SPEN_Incident__c!=null LIMIT 1]){
                lstOfCaseRef.add(cc.Id);
            }
            
            Database.executeBatch(new SPEN_IncidentScopeChangedProcessingBatch(inc2,lstOfCaseRef));
            Test.stopTest();
        	Case cc = [Select Id,Status,SPEN_IsMerge__c,SPEN_Incident__c,SPEN_Incident__r.ParentIncidentId,SPEN_Incident__r.SPEN_IncidentStatus__c,SPEN_Incident__r.SPEN_IncidentType__c from CASE where SPEN_Incident__c!=null LIMIT 1]; 
               
        	Assert.areEqual(cc.SPEN_IsMerge__c, true, 'Case field updated by merged true flag');
        }
    }

}