force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/fields/SPEN_Value__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/recordTypes/Zone.recordType-meta.xml
<RecordType>
    <fullName>Zone</fullName>
    <active>true</active>
    <label>Zone</label>
</RecordType>

force-app/main/default/objects/SPEN_Zone__c/SPEN_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_BroadcastMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BroadcastMessage__c</fullName>
    <label>IVR  Message Assigned</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <label>IVR Message Temporary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_IVRMessageTemplate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessageTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IVR Message Template</label>
    <referenceTo>SPEN_IVRMessage__c</referenceTo>
    <relationshipLabel>Zone</relationshipLabel>
    <relationshipName>Zone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_IVRTemplateBody__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRTemplateBody__c</fullName>
    <label>IVR Template Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SPEN_ZoneConfigurationServiceHelper.cls
/*-----------------------------------------------------------------------------
DESCRIPTION :   Helper for Zone Trigger
AUTHOR      :   Shubhi Vijayvergia
LIBRARY     :   Salesforce Enterprise Library (SEL) - Core
VERSION     :   1.0
TEST CLASS	:	SPEN_ZoneConfigurationServiceHelperTest
HISTORY     :
Date            Author              Comment
Jun-27-2023     Shubhi Vijayvergia         Initial version
-----------------------------------------------------------------------------*/
public with sharing class SPEN_ZoneConfigurationServiceHelper {
    static final String ZONE_TYPE_DISTRICT='District';
    static final String ZONE_TYPE_ZONE='Zone';
    static final String ZONE_TYPE_REGION='Region';
    public static final String ZONE_CONFIGSETTING = 'Zone broadcast message updated last one hour';
    static List<Id> ivrMsgIdList=new List<Id>();
    static Map<Id,SPEN_IVRMessage__c> zoneIVRMesgMap=new Map<Id,SPEN_IVRMessage__c>();
      
    //method invoking from before insert to update message fields from template message
    public static void updateMessageOnInsert(List<SPEN_Zone__c> newZoneList){
        SPEN_ZoneConfigurationServiceHelper.getTemplateIdsForMessageUpdate(newZoneList);
        if(ivrMsgIdList!=null && !ivrMsgIdList.isEmpty()){
            SPEN_ZoneConfigurationServiceHelper.zoneIVRMesgMap=SPEN_IVRMessageSelector.getIVRMessageMap(ivrMsgIdList);
        }
        for(SPEN_Zone__c z: newZoneList){
            if(z.SPEN_IVRMessageTemplate__c!=null && SPEN_ZoneConfigurationServiceHelper.zoneIVRMesgMap!=null && SPEN_ZoneConfigurationServiceHelper.zoneIVRMesgMap.containsKey(z.SPEN_IVRMessageTemplate__c)){
                z.SPEN_IVRTemplateBody__c=SPEN_ZoneConfigurationServiceHelper.zoneIVRMesgMap.get(z.SPEN_IVRMessageTemplate__c).SPEN_IVRMessage__c; //CRMD-5177
            }
        }
    }
    public static void updateMessageOnUpdate(Map<Id, SPEN_Zone__c> zoneOldMap,List<SPEN_Zone__c> newZoneList){
        SPEN_ZoneConfigurationServiceHelper.getTemplateIdsForMessageUpdate(newZoneList);
        if(ivrMsgIdList!=null && !ivrMsgIdList.isEmpty()){
            SPEN_ZoneConfigurationServiceHelper.zoneIVRMesgMap=SPEN_IVRMessageSelector.getIVRMessageMap(ivrMsgIdList);
            for(SPEN_Zone__c z: newZoneList){
                if(z.SPEN_IVRMessageTemplate__c!=null && zoneOldMap.containsKey(z.id) && zoneOldMap.get(z.id).SPEN_IVRMessageTemplate__c!=z.SPEN_IVRMessageTemplate__c && SPEN_ZoneConfigurationServiceHelper.zoneIVRMesgMap!=null && SPEN_ZoneConfigurationServiceHelper.zoneIVRMesgMap.containsKey(z.SPEN_IVRMessageTemplate__c)){
                    z.SPEN_IVRTemplateBody__c=SPEN_ZoneConfigurationServiceHelper.zoneIVRMesgMap.get(z.SPEN_IVRMessageTemplate__c).SPEN_IVRMessage__c; //CRMD-5177
                }
            }
        }
        
    }
    private static void getTemplateIdsForMessageUpdate(List<SPEN_Zone__c> zoneNewList){
        for(SPEN_Zone__c z: zoneNewList){
            ivrMsgIdList.add(z.SPEN_IVRMessageTemplate__c);
        }
    }
    /// method invoking from after update to update IR on change of broadcast message
    public static void updateIROnUpdate(Map<Id, SPEN_Zone__c> zoneOldMap,List<SPEN_Zone__c> zoneNewList){
        Map<Id,SPEN_Zone__c> zoneMap = new Map<Id,SPEN_Zone__c>();
        if(!zoneOldMap.isEmpty() && !zoneNewList.isEmpty()){
            for(SPEN_Zone__c zoneValue: zoneNewList){
                if(zoneOldMap.containsKey(zoneValue.Id) && zoneOldMap.get(zoneValue.Id) != Null && zoneValue.SPEN_BroadcastMessage__c !=null && zoneOldMap.get(zoneValue.Id).SPEN_BroadcastMessage__c !=zoneValue.SPEN_BroadcastMessage__c)
                {
                    zoneMap.put(zoneValue.Id,zoneValue);
                }
            }
            if(!zoneMap.isEmpty()){
                SPEN_ZoneConfigurationServiceHelper.updateIRO(zoneMap);
            }
            
        }
    }
    public static void updateIRO(Map<Id,SPEN_Zone__c> zoneMap){
        if(zoneMap!=null && !zoneMap.isEmpty()){
            Map<String,SPEN_ConfigurableSettings__c> configSetMap = new Map<String,SPEN_ConfigurableSettings__c>();
            configSetMap = SPEN_CaseSelector.configSettingsMap;//map to hold COnfig settings value
            Integer threshold = Integer.valueOf(configSetMap.get(ZONE_CONFIGSETTING).SPEN_Value__c);
            Datetime dateThreshold = system.now().addHours(-threshold);
            SPEN_IntegrationRequestSelector.geIntegrationRequestZoneRecord(zoneMap,dateThreshold);
        }
    }
}