force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/fields/SPEN_Description__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/fields/SPEN_Value__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <externalId>true</externalId>
    <inlineHelpText>This value must not be changed if IVR uses this message template.</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_Purpose__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Storm</fullName>
            </value>
            <value>
                <fullName>LV</fullName>
            </value>
            <value>
                <fullName>HV</fullName>
            </value>
            <value>
                <fullName>Flickering</fullName>
            </value>
            <value>
                <fullName>XRT</fullName>
            </value>
            <value>
                <fullName>XRT - Some On</fullName>
            </value>
            <value>
                <fullName>ETR Unknown</fullName>
            </value>
            <value>
                <fullName>HV Shutdown for Safety</fullName>
            </value>
            <value>
                <fullName>Dropped Supply</fullName>
            </value>
            <value>
                <fullName>Dropped Supply Within a Fault</fullName>
            </value>
            <value>
                <fullName>Multiple Fuse Replacements</fullName>
            </value>
            <value>
                <fullName>Extended Awaiting Emergency Services to provide access</fullName>
            </value>
            <value>
                <fullName>Some on Some off</fullName>
            </value>
            <value>
                <fullName>Cancelled Pre Arranged</fullName>
            </value>
            <value>
                <fullName>Extended Pre-Arranged</fullName>
            </value>
            <value>
                <fullName>Generators</fullName>
            </value>
            <value>
                <fullName>Unconfirmed reports of Fire, Vandalism, 3rd Party damage</fullName>
            </value>
            <value>
                <fullName>Comfort</fullName>
            </value>
            <value>
                <fullName>3-Hour Comfort Call</fullName>
            </value>
            <value>
                <fullName>3rd Call Received</fullName>
            </value>
            <value>
                <fullName>Dropped Supply with Notice</fullName>
            </value>
            <value>
                <fullName>Dropped Supply without Notice</fullName>
            </value>
            <value>
                <fullName>Estimated Restoration Time Extended</fullName>
            </value>
            <value>
                <fullName>Incident Created</fullName>
            </value>
            <value>
                <fullName>Incident Restored</fullName>
            </value>
            <value>
                <fullName>Resource Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Resource Dispatched</fullName>
            </value>
            <value>
                <fullName>Restore Confirmation</fullName>
            </value>
            <value>
                <fullName>MPAS Inquiry</fullName>
            </value>
            <value>
                <fullName>MPAS Out-Of-Area Inquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/recordTypes/SMS.recordType-meta.xml
<RecordType>
    <fullName>SMS</fullName>
    <active>true</active>
    <label>SMS</label>
</RecordType>

force-app/main/default/objects/SPEN_SiteDetails__c/SPEN_SiteDetails__c.object-meta.xml
<CustomObject>
    <label>Site Details</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Site Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_SiteDetails__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Site Details</relationshipLabel>
    <relationshipName>Site_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_SiteDetails__c/fields/SPEN_LAReference__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LAReference__c</fullName>
    <label>LA Reference</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_SiteDetails__c/fields/SPEN_WorksReference__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorksReference__c</fullName>
    <description>Works Reference for SW case</description>
    <label>Works Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_SiteDetails__c/recordTypes/NRSWA.recordType-meta.xml
<RecordType>
    <fullName>NRSWA</fullName>
    <active>true</active>
    <label>NRSWA</label>
</RecordType>

force-app/main/default/objects/SPEN_SiteDetails__c/recordTypes/Streetworks.recordType-meta.xml
<RecordType>
    <fullName>Streetworks</fullName>
    <active>true</active>
    <label>Streetworks</label>
</RecordType>

force-app/main/default/classes/SPEN_CasesUtil_Test.cls
@IsTest
public class SPEN_CasesUtil_Test {
    
    @testSetup static void setup(){
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user);
        PermissionSet ps1 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_CaseAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps1.Id);
        PermissionSet ps2 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_IncidentAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps2.Id);
        PermissionSet ps3 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_ConfigurableSettingsRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps3.Id);
        PermissionSet ps4 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_CaseThirdPartyDamageCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps4.Id);
        PermissionSet ps5 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_StreetworkCaseAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps5.Id);
        
        System.runAs(user)
        {
            Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
            List<SPEN_ConfigurableSettings__c> csList=new List<SPEN_ConfigurableSettings__c>();
            SPEN_ConfigurableSettings__c cS =SPEN_TestDataFactory.createConfigSetting(1,'Incident broadcast message updated last one hour');
            csList.add(cS);
            SPEN_ConfigurableSettings__c cS1 =SPEN_TestDataFactory.createConfigSetting(1,'MessagingTaskType');
            csList.add(cS1);
            SPEN_ConfigurableSettings__c cS2 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelay');
            csList.add(cS2);
            SPEN_ConfigurableSettings__c cS3 =SPEN_TestDataFactory.createConfigSetting(1,'HV Incident Message');
            csList.add(cS3);
            SPEN_ConfigurableSettings__c cS4 =SPEN_TestDataFactory.createConfigSetting(1,'GetAffectedPremiseINCType');
            cS4.SPEN_Value__c = 'HV_N,HV_S,LV';
            cS4.SPEN_Description__c ='config setting description';
            csList.add(cS4);
            insert csList;
            
            Integer threshold = Integer.valueOf(cS.SPEN_Value__c);
            Datetime dateThreshHold = system.now().addHours(-threshold);            
            Id msgRecordTypeId = Schema.SObjectType.SPEN_IVRMessage__c.getRecordTypeInfosByName().get('SMS').getRecordTypeId();
            SPEN_IVRMessage__c message = new SPEN_IVRMessage__c();
            message=new SPEN_IVRMessage__c();
            message.Name='SMS – Single Premise – Network Fault';
            message.SPEN_IVRMessage__c='The following information is only for the customers';
            message.RecordTypeId=msgRecordTypeId;
            message.SPEN_Purpose__c='Incident Created';
            message.SPEN_ExternalId__c = 'SMS – Single Premise – Network Fault';
            insert message;
            
            Id recordTypeIdIncident = Schema.SObjectType.Incident.getRecordTypeInfosByDeveloperName().get('SPEN_SPENIncident').getRecordTypeId();
            Incident inc = new Incident();
            inc.Subject='Test Subject';
            inc.SPEN_IncidentReference__c='INCD-434014-r';
            inc.RecordTypeId=recordTypeIdIncident;
            insert inc;
            
            Id recordTypeId3PD = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_NRSWA').getRecordTypeId();
            Case ThreePDCase =new Case();
            ThreePDCase.SPEN_IncidentReference__c=inc.SPEN_IncidentReference__c;
            ThreePDCase.Status ='Created';
            ThreePDCase.Priority='Medium';
            ThreePDCase.SPEN_IncidentRefFormula__c='INCD-434014-r';
            ThreePDCase.RecordTypeId = recordTypeId3PD;
            insert ThreePDCase;
            
            Id recordTypeIdSW = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_Streetworks').getRecordTypeId();
            Case SWCases =new Case();
            SWCases.Status ='Created';
            SWCases.Priority='Medium';
            SWCases.RecordTypeId = recordTypeIdSW;
            insert SWCases;
            
            Id recordTypeIdSiteDetails = Schema.SObjectType.SPEN_SiteDetails__c.getRecordTypeInfosByDeveloperName().get('Streetworks').getRecordTypeId();
            SPEN_SiteDetails__c siteDetails =new SPEN_SiteDetails__c();
            siteDetails.SPEN_LAReference__c='123456';
            siteDetails.SPEN_WorksReference__c='SP051DTHJT3764';
            siteDetails.SPEN_Case__c=SWCases.Id;
            siteDetails.RecordTypeId=recordTypeIdSiteDetails;
            insert siteDetails;
            
            case swCase=[select id,CaseNumber from case where RecordTypeId=:recordTypeId3PD];
            String caseNumber=swCase.CaseNumber;
            Id recordTypeIdQuery = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_Query').getRecordTypeId();
            Case queryCaseSW1=new Case();
            queryCaseSW1.Status='Open';
            queryCaseSW1.Origin='Email';
            queryCaseSW1.SPEN_Type__c='Streetworks';
            queryCaseSW1.SPEN_QueryType__c='Internal';
            queryCaseSW1.Subject='Test';
            queryCaseSW1.Description='123456';
            queryCaseSW1.RecordTypeId=recordTypeIdQuery;
            insert queryCaseSW1;
            
            Case queryCase2=new Case();
            queryCase2.Status='Open';
            queryCase2.Origin='Email';
            queryCase2.SPEN_Type__c='Streetworks';
            queryCase2.SPEN_QueryType__c='Internal';
            queryCase2.Subject='SP051DTHJT3764';
            queryCase2.Description='Test';
            queryCase2.RecordTypeId=recordTypeIdQuery;
            insert queryCase2;
            
            Case queryCase=new Case();
            queryCase.Status='Open';
            queryCase.Origin='Email';
            queryCase.SPEN_Type__c='NRSWA';
            queryCase.SPEN_QueryType__c='Internal';
            queryCase.Subject='IND-434014-r';
            queryCase.Description='Test Desc';
            querycase.RecordTypeId=recordTypeIdQuery;
            insert queryCase;
            
            Case queryCase1=new Case();
            queryCase1.Status='Open';
            queryCase1.Origin='Email';
            queryCase.SPEN_Type__c='NRSWA';
            queryCase1.SPEN_QueryType__c='Internal';
            queryCase1.Subject='Test'+'{'+caseNumber+'}';
            queryCase1.Description='Test Desc 1';
            queryCase1.RecordTypeId=recordTypeIdQuery;
            insert queryCase1;
            
        }
    }
    
    @isTest
    public static void QueryCaseBeforeInsertTest() 
    {
        User user = [select id from user WHERE isActive = true limit 1];
        System.runAs(user)
        {
            Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
            Test.startTest();
            try{
                Id recordTypeIdQuery = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_Query').getRecordTypeId();
                List<Case> cases=[select id,RecordTypeId,Origin,Subject,Description,SPEN_IncidentRefFormula__c,CaseNumber,SPEN_Type__c,SPEN_SPDSPMIndicator__c,SPEN_SPD_SPM__c from case where RecordTypeId=:recordTypeIdQuery  and subject like '%IND%'];
                List<Case> modifiedCases=SPEN_CasesUtil.populateParentCaseOnQueryCase(cases);
                system.assert(modifiedCases!= null);
            }
            catch(exception e)
            {
                System.assert(e != NULL);
            }
            Test.stopTest();
        }
    }
    
    @isTest
    public static void QueryCaseBeforeInsertTest1() 
    {
        User user = [select id from user WHERE isActive = true limit 1];
        System.runAs(user)
        {
            Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
            Test.startTest();
            try{
                Id recordTypeIdQuery = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_Query').getRecordTypeId();
                List<Case> cases=[select id,RecordTypeId,Origin,Subject,Description,SPEN_IncidentRefFormula__c,CaseNumber,SPEN_Type__c,SPEN_SPDSPMIndicator__c,SPEN_SPD_SPM__c from case where RecordTypeId=:recordTypeIdQuery and subject like '%{%'];
                List<Case> modifiedCases=SPEN_CasesUtil.populateParentCaseOnQueryCase(cases);
                system.assert(modifiedCases!= null);
            }
            catch(exception e)
            {
                System.assert(e != NULL);
            }
            Test.stopTest();
        }
    }
    
        @isTest
    public static void QueryCaseSWTest1() 
    {
        User user = [select id from user WHERE isActive = true limit 1];
        System.runAs(user)
        {
            Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
            Test.startTest();
            try{
                Id recordTypeIdQuery = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_Query').getRecordTypeId();
                List<Case> cases=[select id,RecordTypeId,Origin,Subject,Description,SPEN_IncidentRefFormula__c,CaseNumber,SPEN_Type__c,SPEN_SPDSPMIndicator__c,SPEN_SPD_SPM__c from case where RecordTypeId=:recordTypeIdQuery and subject like '%123%'];
                List<Case> modifiedCases=SPEN_CasesUtil.populateParentCaseOnQueryCase(cases);
                system.assert(modifiedCases!= null);
            }
            catch(exception e)
            {
                System.assert(e != NULL);
            }
            Test.stopTest();
        }
    }
    
        @isTest
    public static void QueryCaseSWTest2() 
    {
        User user = [select id from user WHERE isActive = true limit 1];
        System.runAs(user)
        {
            Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
            Test.startTest();
            try{
                Id recordTypeIdQuery = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SPEN_Query').getRecordTypeId();
                List<Case> cases=[select id,RecordTypeId,Origin,Subject,Description,SPEN_IncidentRefFormula__c,CaseNumber,SPEN_Type__c,SPEN_SPDSPMIndicator__c,SPEN_SPD_SPM__c from case where RecordTypeId=:recordTypeIdQuery and subject like '%SP%'];
                List<Case> modifiedCases=SPEN_CasesUtil.populateParentCaseOnQueryCase(cases);
                system.assert(modifiedCases!= null);
            }
            catch(exception e)
            {
                System.assert(e != NULL);
            }
            Test.stopTest();
        }
    }
}