force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ImpactedPremise__c/SPEN_ImpactedPremise__c.object-meta.xml
<CustomObject>
    <label>Impacted Premise</label>
    <nameField>
        <displayFormat>IP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impacted Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_IncidentType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentType__c</fullName>
    <label>Incident Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SP</fullName>
                <label>Single Premise Incident</label>
            </value>
            <value>
                <fullName>LV</fullName>
                <label>Low Voltage Incident</label>
            </value>
            <value>
                <fullName>HV_S</fullName>
                <label>High Voltage Incident</label>
            </value>
            <value>
                <fullName>HV_N</fullName>
                <label>High Voltage Network Incident</label>
            </value>
            <value>
                <fullName>CG</fullName>
                <label>Call Group Incident</label>
            </value>
            <value>
                <fullName>AREA</fullName>
                <label>Area Incident</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_PremiseId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseId__c</fullName>
    <externalId>true</externalId>
    <label>PremiseId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_RelatedIncident__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelatedIncident__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Impacted Premises</relationshipLabel>
    <relationshipName>Impacted_Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_ImpactedPremise__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Restored</fullName>
            </value>
            <value>
                <fullName>Not Restored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/SPEN_IntegrationRequest__c.object-meta.xml
<CustomObject>
    <description>Integration Request object has been set up to use for IVR Integration.</description>
    <label>Integration Request</label>
    <nameField>
        <label>Integration Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_IntegrationRequestServiceClass__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IntegrationRequestServiceClass__c</fullName>
    <label>Integration Request Service Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_MessageType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MessageType__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incident</fullName>
            </value>
            <value>
                <fullName>Zone</fullName>
            </value>
            <value>
                <fullName>District</fullName>
            </value>
            <value>
                <fullName>Region</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Records__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Records__c</fullName>
    <label>Records</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_RelatedRecord__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelatedRecord__c</fullName>
    <description>Should be updated with zone id when we are updating the message details in integration request record</description>
    <label>Related Record</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IntegrationRequest__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Unique SPEN identifier for a premise</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SPEN_ActiveIncidentCheck_Test.cls
@IsTest
public class SPEN_ActiveIncidentCheck_Test 
{
    @IsTest
    private static void testfetchIncident()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user); 
        if (devOpsPSGroup.Status != 'Updated') {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);
        }
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.Id;
        insert devOpsAssign;
        System.runAs(user)
        {
            Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
            Test.startTest();
            SPEN_ConfigurableSettings__c cs7 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelay');
            insert cs7;
            CallCenter center=[select Id from CallCenter limit 1];
            List<Case> testCase = SPEN_TestDataFactory.createListOfCases(SPEN_TestDataFactoryConstants.SINGLE_REC);
            testCase[0].Origin = 'Web';
            //testCase[0].ContactId=con.Id;
            insert testCase;
            Incident inc = SPEN_TestDataFactory.createIncidents(testCase[0].id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            inc.SPEN_IncidentType__c='LV';
            insert inc;
            List<SPEN_Premise__c> premiseRec = SPEN_TestDataFactory.createListOfPremise(SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert premiseRec;
            //List<SPEN_ImpactedPremise__c> implist=SPEN_TestDataFactory.createImpactedPremiserecord(SPEN_TestDataFactoryConstants.SINGLE_REC);
            List<SPEN_ImpactedPremise__c> implist=SPEN_TestDataFactory.createImpactedPremiserecord(2);
            implist[0].SPEN_RelatedIncident__c=inc.Id;
            implist[0].SPEN_PremiseId__c= premiseRec[0].SPEN_PremiseID__c;
            insert implist;
            VoiceCall vc=SPEN_TestDataFactory.createVoiceCall(SPEN_TestDataFactoryConstants.SINGLE_REC);
            vc.VendorCallKey='Test vendor';
            vc.CallCenterId =center.Id;
            vc.SPEN_VoicecallPremise__c = premiseRec[0].Id;
            insert vc;
            List <VoiceCall> vclist=new List<VoiceCall>();
            vclist.add(vc);
            List<SPEN_IntegrationRequest__c> intereq=SPEN_TestDataFactory.createIntegrationReq(SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert intereq;
            List<Case> testCase1 = SPEN_TestDataFactory.createListOfCases(SPEN_TestDataFactoryConstants.SINGLE_REC);
            testCase1[0].Origin = 'Web';
            //testCase[0].ContactId=con.Id;
            insert testCase1;
            Incident inc1 = SPEN_TestDataFactory.createIncidents(testCase1[0].id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            //inc1.Id=implist[0].SPEN_RelatedIncident__c;
            inc1.SPEN_IncidentType__c='LV';
            insert inc1;
            //List<SPEN_ImpactedPremise__c> implist1=SPEN_TestDataFactory.createImpactedPremiserecord(SPEN_TestDataFactoryConstants.SINGLE_REC);
            implist[1].SPEN_RelatedIncident__c=inc1.Id;
            update implist;
            Set<Id> recId = new Set<Id>();
            recId.add(vc.Id);
            SPEN_ActiveIncidentCheck.fetchIncidentRecValue(recId);
            //SPEN_ActiveIncidentCheck.UpdateVoiceCallRecord(inc.id, vclist);
            //SPEN_ActiveIncidentCheck.GetIntegrationRequestRecord(intereq[0].Id, vclist);
            //fetchIncident.put('Test VoiceCall',vclist);
            //Assert.isNotNull(fetchIncident);
            Test.stopTest();
        }
    }
    
	@IsTest
    private static void testIntegrationRequest()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user); 
        if (devOpsPSGroup.Status != 'Updated') {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);
        }
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.Id;
        insert devOpsAssign;
        System.runAs(user)
        {
            Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
            Test.startTest();
            
            SPEN_ConfigurableSettings__c cs1 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelay');
            insert cs1;
            
            CallCenter center=[select Id from CallCenter limit 1];
            List<Case> testCase = SPEN_TestDataFactory.createListOfCases(SPEN_TestDataFactoryConstants.SINGLE_REC);
			testCase[0].Origin = 'Web';
			insert testCase;
            
			Incident inc = SPEN_TestDataFactory.createIncidents(testCase[0].id,SPEN_TestDataFactoryConstants.SINGLE_REC);
			inc.SPEN_IncidentType__c='LV';
			inc.SPEN_IncidentStatus__c='Emergency';
			insert inc;
            
            List<SPEN_Premise__c> premiseRec = SPEN_TestDataFactory.createListOfPremise(SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert premiseRec;
            
            List<SPEN_ImpactedPremise__c> implist=SPEN_TestDataFactory.createImpactedPremiserecord(2);
            implist[0].SPEN_RelatedIncident__c=inc.Id;
            implist[0].SPEN_PremiseId__c= premiseRec[0].SPEN_PremiseID__c;
            insert implist;
            
            VoiceCall vc=SPEN_TestDataFactory.createVoiceCall(SPEN_TestDataFactoryConstants.SINGLE_REC);
            vc.VendorCallKey='Test vendor';
            vc.CallCenterId =center.Id;
            vc.SPEN_VoicecallPremise__c = premiseRec[0].Id;
            insert vc;
            List <VoiceCall> vclist=new List<VoiceCall>();
            vclist.add(vc);
            
            List<SPEN_IntegrationRequest__c> intereq=SPEN_TestDataFactory.createIntegrationReq(SPEN_TestDataFactoryConstants.SINGLE_REC);
            intereq[0].SPEN_Records__c=vc.SPEN_VoicecallPremise__r.SPEN_PremiseID__c;
            intereq[0].SPEN_Status__c = 'Completed';
            intereq[0].SPEN_MessageType__c = 'Incident';
            intereq[0].SPEN_RelatedRecord__c = inc.Id;
            intereq[0].SPEN_IntegrationRequestServiceClass__c='SPEN_ActiveIncidentGetPremiseService';
            insert intereq;
            Set<Id> recId = new Set<Id>();
            recId.add(vc.Id);
            
            SPEN_ActiveIncidentCheck.fetchIncidentRecValue(recId);
            //SPEN_ActiveIncidentCheck.GetIntegrationRequestRecord(intereq[0].Id, vclist);
            Assert.isNotNull(inc);
            Test.stopTest();
        }
    }
}