force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVR__c/SPEN_IVR__c.object-meta.xml
<CustomObject>
    <description>This object will hold IVR flow details.</description>
    <label>IVR</label>
    <nameField>
        <label>IVR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <externalId>true</externalId>
    <inlineHelpText>This value must not be changed if IVR uses this message template.</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_Purpose__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Storm</fullName>
            </value>
            <value>
                <fullName>LV</fullName>
            </value>
            <value>
                <fullName>HV</fullName>
            </value>
            <value>
                <fullName>Flickering</fullName>
            </value>
            <value>
                <fullName>XRT</fullName>
            </value>
            <value>
                <fullName>XRT - Some On</fullName>
            </value>
            <value>
                <fullName>ETR Unknown</fullName>
            </value>
            <value>
                <fullName>HV Shutdown for Safety</fullName>
            </value>
            <value>
                <fullName>Dropped Supply</fullName>
            </value>
            <value>
                <fullName>Dropped Supply Within a Fault</fullName>
            </value>
            <value>
                <fullName>Multiple Fuse Replacements</fullName>
            </value>
            <value>
                <fullName>Extended Awaiting Emergency Services to provide access</fullName>
            </value>
            <value>
                <fullName>Some on Some off</fullName>
            </value>
            <value>
                <fullName>Cancelled Pre Arranged</fullName>
            </value>
            <value>
                <fullName>Extended Pre-Arranged</fullName>
            </value>
            <value>
                <fullName>Generators</fullName>
            </value>
            <value>
                <fullName>Unconfirmed reports of Fire, Vandalism, 3rd Party damage</fullName>
            </value>
            <value>
                <fullName>Comfort</fullName>
            </value>
            <value>
                <fullName>3-Hour Comfort Call</fullName>
            </value>
            <value>
                <fullName>3rd Call Received</fullName>
            </value>
            <value>
                <fullName>Dropped Supply with Notice</fullName>
            </value>
            <value>
                <fullName>Dropped Supply without Notice</fullName>
            </value>
            <value>
                <fullName>Estimated Restoration Time Extended</fullName>
            </value>
            <value>
                <fullName>Incident Created</fullName>
            </value>
            <value>
                <fullName>Incident Restored</fullName>
            </value>
            <value>
                <fullName>Resource Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Resource Dispatched</fullName>
            </value>
            <value>
                <fullName>Restore Confirmation</fullName>
            </value>
            <value>
                <fullName>MPAS Inquiry</fullName>
            </value>
            <value>
                <fullName>MPAS Out-Of-Area Inquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/recordTypes/SMS.recordType-meta.xml
<RecordType>
    <fullName>SMS</fullName>
    <active>true</active>
    <label>SMS</label>
</RecordType>

force-app/main/default/objects/SPEN_IVROperatinghours__c/SPEN_IVROperatinghours__c.object-meta.xml
<CustomObject>
    <description>IVR Operating hours object is operating on time based on start time and end time.</description>
    <label>IVR Operating hours</label>
    <nameField>
        <label>IVR Operating hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Operating hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_EndTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EndTime__c</fullName>
    <description>End time field will collect the ending time of IVR Operating hours</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>Holds the external Id.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isActive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isDaily__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isDaily__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDaily</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_IVR__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVR__c</fullName>
    <description>IVR field is in master details relationship with IVR object and IVR Operating hours</description>
    <label>IVR</label>
    <referenceTo>SPEN_IVR__c</referenceTo>
    <relationshipLabel>IVR Operating hours</relationshipLabel>
    <relationshipName>IVR_Operating_hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>IVR Message field is in master details relationship with IVR Message object and IVR Operating hours</description>
    <label>IVR Message</label>
    <referenceTo>SPEN_IVRMessage__c</referenceTo>
    <relationshipLabel>IVR Operating hours</relationshipLabel>
    <relationshipName>IVR_Operating_hours</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_StartTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_StartTime__c</fullName>
    <description>Start time field will collect the starting time of IVR Operating hours</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/SPEN_IncidentReparentBatch_Test.cls
@isTest
public class SPEN_IncidentReparentBatch_Test 
{
    @isTest
    private static void testme()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user);
        
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        if (devOpsPSGroup.Status != 'Updated') 
        {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);
        }
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetGroupId = devOpsPSGroup.Id);
        
        User u = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        u.FirstName = 'Dropped ';
        u.LastName = 'Outbound Task User';
        insert u;
        /*
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_CaseAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps.Id); 
        PermissionSet ps1 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_IncidentAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps1.Id);
        PermissionSet ps10 = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_IVROperatinghoursAccessCRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps10.Id);
        PermissionSet zoneAccess = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_Zone_CRU'];
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = zoneAccess.Id);     
		*/        
		System.runAs(user)
        {
            Test.startTest();
            SPEN_ConfigurableSettings__c cSeting= SPEN_TestDataFactory.createConfigSetting(1,'Incident broadcast message updated last one hour');
            insert cSeting;
            SPEN_ConfigurableSettings__c cSeting1= SPEN_TestDataFactory.createConfigSetting(1,'MessagingTaskType');
            insert cSeting1;
            SPEN_ConfigurableSettings__c cs2 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelay');
            insert cs2;
            
             
            Id msgRecordTypeId = Schema.SObjectType.SPEN_IVRMessage__c.getRecordTypeInfosByName().get('SMS').getRecordTypeId();
            SPEN_IVRMessage__c message = new SPEN_IVRMessage__c();
            message=new SPEN_IVRMessage__c();
            message.Name='SMS – Single Premise – Network Fault';
            message.SPEN_IVRMessage__c='The following information is only for the //////customers';
            message.RecordTypeId=msgRecordTypeId;
            message.SPEN_Purpose__c='Incident Created';
            message.SPEN_ExternalId__c = 'SMS – Single Premise – Network Fault';
            insert message;
            
            List<SPEN_IVR__c> iVRList = SPEN_TestDataFactory.createIVRrecord(1);
            Insert iVRList;
            Id iVROperatingHoursRecordTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('SMS Blackout Window').getRecordTypeId();
            Id iVRVARecTypeId = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('VA Blackout Window').getRecordTypeId();
            
            List<SPEN_IVROperatingHours__c> iVRORecList = SPEN_TestDataFactory.createIVROperatingHoursrecord(1,iVRList[0].id,message.id);
            iVRORecList[0].RecordTypeId = iVROperatingHoursRecordTypeId;
            iVRORecList[0].SPEN_isActive__c = true;
            iVRORecList[0].SPEN_isDaily__c = true;
            iVRORecList[0].SPEN_StartTime__c = system.now().time() - 10;
            iVRORecList[0].SPEN_EndTime__c = system.now().time() - 5;
            Insert iVRORecList;
            
            List<SPEN_IVROperatingHours__c> vAOprHrList = SPEN_TestDataFactory.createIVROperatingHoursrecord(1,iVRList[0].id,message.id);
            vAOprHrList[0].RecordTypeId = iVRVARecTypeId;
            vAOprHrList[0].SPEN_isActive__c = true;
            vAOprHrList[0].SPEN_isDaily__c = true;
            vAOprHrList[0].SPEN_StartTime__c = system.now().time() - 10;
            vAOprHrList[0].SPEN_EndTime__c = system.now().time() - 5;
            Insert vAOprHrList;
            
            List<Case> cs = SPEN_TestDataFactory.createListOfCases(3); 
            cs[0].Origin = 'Web';
            cs[0].Status = 'Restored';
            cs[1].Origin = 'Web';
            cs[1].Status = 'Restored';
            cs[2].Origin = 'Web';
            cs[2].Status = 'Restored';
            insert cs;
            
            Incident inc = SPEN_TestDataFactory.createIncidents(cs[0].id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            inc.SPEN_IncidentType__c='HV_S';
            inc.SPEN_IncidentStatus__c = 'Awaiting';
            insert inc;
            
            Incident inc1 = SPEN_TestDataFactory.createIncidents(cs[0].id,SPEN_TestDataFactoryConstants.SINGLE_REC);
            inc1.subject = 'Test Incident1';
            inc1.ParentIncidentId = inc.Id;
            inc1.SPEN_IncidentType__c='SP';
            //inc1.SPEN_IncidentType__c='HV_S';
            inc.SPEN_IncidentStatus__c = 'Awaiting';
            insert inc1;
            
            cs[2].SPEN_Incident__c = inc.Id;
            cs[0].SPEN_Incident__c = inc1.Id;
            
            cs[0].SPEN_PreferredMethodofContact__c = 'T';
            cs[0].SPEN_CallerMobileTelephone__c = '+448888334455';
            cs[0].SPEN_AdditionalCaller__c = true;
            update cs;

            List<String> cRef = new List<String>();
            cRef.add(cs[0].id);
            cRef.add(cs[1].id);
            cRef.add(cs[2].id);
            
            SPEN_IncidentReparentBatch obj= new SPEN_IncidentReparentBatch(inc,cRef);
            Database.executeBatch(obj);
            Assert.isNotNull(obj);
            Test.stopTest();
        }
    }
}