force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ConfigurableSettings__c/fields/SPEN_Value__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <externalId>true</externalId>
    <inlineHelpText>This value must not be changed if IVR uses this message template.</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/recordTypes/Zone.recordType-meta.xml
<RecordType>
    <fullName>Zone</fullName>
    <active>true</active>
    <label>Zone</label>
</RecordType>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseDistrict__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseDistrict__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>21.6.23: as aligned with Lauren in context of CRMD-430: this field is not in use at all in PROD (populated for 5 records only) --&gt; NO LONGER RELEVANT &amp; candidate for deletion.</description>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SPEN_Zone__c.SPEN_Type__c</field>
            <operation>equals</operation>
            <value>District</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Premises (District)</relationshipLabel>
    <relationshipName>Premises1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_Zone__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SPEN_Zone__c.SPEN_Type__c</field>
            <operation>equals</operation>
            <value>Zone</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/SPEN_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <label>IVR Message Temporary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_OverwriteToChild__c.field-meta.xml
<CustomField>
    <fullName>SPEN_OverwriteToChild__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overwrite To Child</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_Parent__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Zone</relationshipLabel>
    <relationshipName>Zone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SPEN_ZoneSelectorTEST.cls
@IsTest
public class SPEN_ZoneSelectorTEST 
{
    @testSetup static void setup(){
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user); 
        PermissionSet ps1=SPEN_TestdataSelector.getPermissionSet('SPEN_PremiseAccessCRU');
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps1.Id);
        PermissionSet ps2=SPEN_TestdataSelector.getPermissionSet('SPEN_Zone_CRU');
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps2.Id);
        PermissionSet ps3=SPEN_TestdataSelector.getPermissionSet('SPEN_IncidentAccessCRU');
        insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps3.Id);
        if (devOpsPSGroup.Status != 'Updated') 
        {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);	
        }  
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.Id;
        insert devOpsAssign;
        System.runAs(user){
            Test.startTest();
            SPEN_ConfigurableSettings__c cs = SPEN_TestDataFactory.createConfigSetting(SPEN_TestDataFactoryConstants.SINGLE_REC,SPEN_ConstantData.IncidentMessage);
            cs.Name = 'Zone broadcast message updated last one hour';
            cs.SPEN_Value__c = '10';
            insert cs;
            SPEN_ConfigurableSettings__c cS2 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelay');
            insert cS2;
            List<SPEN_iVRmessage__c> iVRmessageList=new List<SPEN_iVRmessage__c>();
            SPEN_iVRmessage__c iVRmessage = SPEN_TestDataFactory.createiVRmessage(1);
            iVRmessageList.add(iVRmessage);
            insert iVRmessageList;
            List<SPEN_Zone__c> zoneList=new List<SPEN_Zone__c>();
            SPEN_Zone__c zoneRegionRecord = SPEN_TestDataFactory.createZoneRegionRecords(iVRmessage.Id);
            zoneRegionRecord.SPEN_OverwriteToChild__c=true;
            zoneList.add(zoneRegionRecord);
            SPEN_Zone__c zoneDistrictRecord = SPEN_TestDataFactory.createZoneDistrictRecords(iVRmessage.Id);
            zoneList.add(zoneDistrictRecord);
            SPEN_Zone__c zoneRecord = SPEN_TestDataFactory.createZoneRecords(iVRmessage.Id);
            zoneRecord.SPEN_ExternalId__c = 'XOXO';
            zoneList.add(zoneRecord);
            insert zoneList;
            List<SPEN_Zone__c> updatezoneList=new List<SPEN_Zone__c>();
            zoneDistrictRecord.SPEN_Parent__c=zoneRegionRecord.Id;
            zoneDistrictRecord.SPEN_OverwriteToChild__c=true;
            updatezoneList.add(zoneDistrictRecord);
            zoneRecord.SPEN_Parent__c=zoneDistrictRecord.Id;
            updatezoneList.add(zoneRecord);
			update updatezoneList;
            Incident inc = SPEN_TestDataFactory.createIncidents(NULL,SPEN_TestDataFactoryConstants.SINGLE_REC);
            inc.SPEN_OperatingZoneId__c = 'XOXO';
            insert inc;
            Test.stopTest();
        }
    }
    @IsTest
    private static void testgetZoneRecords()
    {
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);
        System.runAs(user)
        {   
            Test.startTest();
            
            Set<Id> emptySet = new Set<Id>();
            Set<Id> zoneIds = new Set<Id>();
            
            set<string> zoneSet = new set<string>();
            zoneset.add('XOXO');
            SPEN_Zone__c district=SPEN_TestdataSelector.getZone('District');
            SPEN_Zone__c zone=SPEN_TestdataSelector.getZone('Zone');
            SPEN_Zone__c region=SPEN_TestdataSelector.getZone('Region');
			zoneIds.add(region.Id);
            zoneIds.add(district.Id);
            zoneIds.add(zone.Id);
            List<SPEN_Premise__c> premiselist=SPEN_TestDataFactory.createListOfPremise(2); 
            premiselist[0].SPEN_Zone__c=zone.Id;
            premiselist[1].SPEN_PremiseDistrict__c=district.Id;
            insert premiselist;
            SPEN_ZoneSelector.getZoneRecords(premiselist[0]);
            SPEN_ZoneSelector.getDistrictRecords(premiselist[1]);
            SPEN_ZoneSelector.getRegionRecords(premiselist[0]);
            SPEN_ZoneSelector.getRegionRecord();
            SPEN_ZoneSelector.getDistrictDetails(district.Id);
            SPEN_ZoneSelector.getZoneDetails(zone.Id);
            SPEN_ZoneSelector.getZoneRecordsByIds(zoneIds);
            SPEN_ZoneSelector.getZoneRecordsByIds(emptySet);
            SPEN_ZoneSelector.getZoneTownRecord(zone.Id);
            SPEN_ZoneSelector.getZoneRecordforInc(zoneSet);
            
            Assert.IsNotNull(premiselist[0].Id);      
            Test.stopTest();
        }
    }
    @IsTest
    private static void getChildrenZoneTest()
    {
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);
        System.runAs(user)
        {   
            Test.startTest();
            SPEN_Zone__c region=SPEN_TestdataSelector.getZone('Region');
            List<SPEN_Zone__c> childZones=SPEN_ZoneSelector.getChildrenZone(new List<Id>{region.Id},'District');
            SPEN_Zone__c district=SPEN_TestdataSelector.getZone('District');
            List<SPEN_Zone__c> childZones2=SPEN_ZoneSelector.getChildrenZone(new List<Id>{region.Id},'Zone');
            Assert.IsNotNull(childZones);  
            Assert.IsNotNull(childZones2);      
            Test.stopTest();
        }
    }
}