force-app/main/default/objects/SPEN_ConfigurableSettings__c/SPEN_ConfigurableSettings__c.object-meta.xml
<CustomObject>
    <label>Configurable Settings</label>
    <nameField>
        <label>Configurable Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurable Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVR__c/SPEN_IVR__c.object-meta.xml
<CustomObject>
    <description>This object will hold IVR flow details.</description>
    <label>IVR</label>
    <nameField>
        <label>IVR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/SPEN_IVROperatinghours__c.object-meta.xml
<CustomObject>
    <description>IVR Operating hours object is operating on time based on start time and end time.</description>
    <label>IVR Operating hours</label>
    <nameField>
        <label>IVR Operating hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Operating hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_EndTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EndTime__c</fullName>
    <description>End time field will collect the ending time of IVR Operating hours</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isActive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isDaily__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isDaily__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDaily</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_IVR__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVR__c</fullName>
    <description>IVR field is in master details relationship with IVR object and IVR Operating hours</description>
    <label>IVR</label>
    <referenceTo>SPEN_IVR__c</referenceTo>
    <relationshipLabel>IVR Operating hours</relationshipLabel>
    <relationshipName>IVR_Operating_hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>IVR Message field is in master details relationship with IVR Message object and IVR Operating hours</description>
    <label>IVR Message</label>
    <referenceTo>SPEN_IVRMessage__c</referenceTo>
    <relationshipLabel>IVR Operating hours</relationshipLabel>
    <relationshipName>IVR_Operating_hours</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_RestrictEndDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RestrictEndDate__c</fullName>
    <label>Restrict End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_RestrictStartDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RestrictStartDate__c</fullName>
    <description>Restrict Start Date for Operating Hours</description>
    <label>Restrict Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_StartTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_StartTime__c</fullName>
    <description>Start time field will collect the starting time of IVR Operating hours</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PostCode__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PostCode__c</fullName>
    <description>It takes the premise postal code</description>
    <externalId>true</externalId>
    <label>Post Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Unique SPEN identifier for a premise</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseNumber__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseNumber__c</fullName>
    <description>The identifying number (if known) for the property affected. If empty the new call will have 0 as it&apos;s property number</description>
    <label>Premise Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/SPEN_PSR__c.object-meta.xml
<CustomObject>
    <description>PSR object has been set up to see all the PSR related information</description>
    <label>PSR</label>
    <nameField>
        <displayFormat>PSR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Contact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SPEN_SendVoiceAlertCallServiceTest.cls
@IsTest
public class SPEN_SendVoiceAlertCallServiceTest
{
    @IsTest
    public static void alertVoiceService()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user); 
        if (devOpsPSGroup.Status != 'Updated') {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);
        }
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.Id;
        insert devOpsAssign;
        System.runAs(user){
            /*SPEN_ConfigurableSettings__c CS1 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelayForMessagingTask');
            insert CS1;
            SPEN_ConfigurableSettings__c CS2 =SPEN_TestDataFactory.createConfigSetting(1,'OnDemandMessageDelayForMessagingTask');
            insert CS2;
            Test.setMock(HttpCalloutMock.class, new SPEN_UtilityClass());
            List<Id> ids = new List<Id>();
            String vAlertMessage = 'Thanks for contacting';
            datetime dt = system.now()+4;
            
            List<Account> accReclist = SPEN_TestDataFactory.createAccounts('Acc Name',SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert accReclist;
            Contact conRec = SPEN_TestDataFactory.createContacts(accReclist[0].Id, SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert conRec;
            
            List<SPEN_PSR__c> psrRecList = SPEN_TestDataFactory.createPSRrecord(SPEN_TestDataFactoryConstants.SINGLE_REC);
            psrRecList[0].SPEN_Contact__c = conRec.Id;
            insert psrRecList;
            
            for(SPEN_PSR__c s : psrRecList)
            {
                ids.add(s.Id);
            }
            
            
            Id recTypeIdOfSchedule = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('Outbound Contact Hours').getRecordTypeId();
            
            //SPEN_IVRMessage__c ivrMsg = new SPEN_IVRMessage__c();
            SPEN_IVRMessage__c ivrMsg = SPEN_TestDataFactory.createIVRMessage(SPEN_TestDataFactoryConstants.SINGLE_REC);
            //ivrMsg.Name = 'TESTMessageRecord';
            ivrMsg.SPEN_IVRMessage__c = 'Thanks for Contacting SPEN';
            insert ivrMsg;
            
            SPEN_IVR__c ivr = new SPEN_IVR__c();
            ivr.Name = 'IVRTEST';
            insert ivr;
            
            List<SPEN_IVROperatingHours__c> ivrList = new List<SPEN_IVROperatingHours__c>();
            
            SPEN_IVROperatingHours__c ivrRec1 = new SPEN_IVROperatingHours__c();
            ivrRec1.SPEN_isActive__c = true;
            ivrRec1.SPEN_isDaily__c = true;
            ivrRec1.SPEN_StartTime__c = system.now().time();
            ivrRec1.SPEN_EndTime__c = system.now().time()+5;
            ivrRec1.RecordTypeId = recTypeIdOfSchedule;
            ivrRec1.SPEN_IVR__c = ivr.Id;
            ivrRec1.SPEN_IVRMessage__c = ivrMsg.Id;
            
            SPEN_IVROperatingHours__c ivrRec2 = new SPEN_IVROperatingHours__c();
            ivrRec2.SPEN_isActive__c = true;
            ivrRec2.SPEN_isDaily__c = true;
            ivrRec2.SPEN_StartTime__c = system.now().time()+10;
            ivrRec2.SPEN_EndTime__c = system.now().time()-1;
            ivrRec2.RecordTypeId = recTypeIdOfSchedule;
            ivrRec2.SPEN_IVR__c = ivr.Id;
            ivrRec2.SPEN_IVRMessage__c = ivrMsg.Id;
            
            ivrList.add(ivrRec2);
            ivrList.add(ivrRec1);
            insert ivrList;*/
            String vAlertMessage = 'Thanks for contacting';
            List<Id> ids = new List<Id>();
            datetime dt = system.now()+4;
            Test.StartTest();
            SPEN_SendVoiceAlertCallService.alertService(ids,vAlertMessage);
            SPEN_SendVoiceAlertCallService.scheduleAlertService(ids,vAlertMessage,dt);
            Assert.isNotNull(vAlertMessage);
            Test.StopTest();
        }
    }
    
    @IsTest
    public static void exceptionCoverage()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user); 
        if (devOpsPSGroup.Status != 'Updated') {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);
        }
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.Id;
        insert devOpsAssign;
        System.runAs(user){
            /*SPEN_ConfigurableSettings__c CS1 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelayForMessagingTask');
            insert CS1;
            SPEN_ConfigurableSettings__c CS2 =SPEN_TestDataFactory.createConfigSetting(1,'OnDemandMessageDelayForMessagingTask');
            insert CS2;
            List<SPEN_IVROperatingHours__c> ivrList = new List<SPEN_IVROperatingHours__c>();
            insert ivrList;
            List<Id> ids = new List<Id>();
            
            for(SPEN_IVROperatingHours__c ivr : ivrList)
            {
                ids.add(ivr.Id);
            }*/
            String vAlertMessage = 'Thanks for contacting';
            List<Id> ids = new List<Id>();
            Test.StartTest();
            SPEN_SendVoiceAlertCallService.alertService(ids,null);
            Assert.isNotNull(vAlertMessage);
        }
    }
    
    @IsTest
    public static void operationHourscodeCoverage()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user); 
        if (devOpsPSGroup.Status != 'Updated') {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);
        }
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.Id;
        insert devOpsAssign;
        System.runAs(user){ 
            /*SPEN_ConfigurableSettings__c CS1 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelayForMessagingTask');
            insert CS1;
            SPEN_ConfigurableSettings__c CS2 =SPEN_TestDataFactory.createConfigSetting(1,'OnDemandMessageDelayForMessagingTask');
            insert CS2;
            List<Id> psrIds = new List<Id>();
            List<Sobject> sobjectList;
            String vAlertMessage = 'Thanks for contacting';
            datetime dt = system.now()+4;
            
            Contact con = new Contact(LastName = 'Contact', FirstName ='Sheker', email= 'sheker.kulkacherla@accenture.com');
            //insert con;
            SPEN_Premise__c  pri = new SPEN_Premise__c(SPEN_PremiseID__c = 'TEST', SPEN_PremiseNumber__c ='Prem1', SPEN_PostCode__c ='AK28');
            sobjectList = new List<Sobject>{con,pri};
                insert sobjectList;
            Id recTypeIdOfSchedule = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('Outbound Contact Hours').getRecordTypeId();
            SPEN_PSR__c psr = new SPEN_PSR__c();
            psr.SPEN_Contact__c = con.Id;
            psr.SPEN_Premise__c = pri.Id;
            insert psr;
            
            psrIds.add(psr.Id);
            
            SPEN_IVRMessage__c ivrMsg = new SPEN_IVRMessage__c();
            ivrMsg.Name = 'TESTMessageRecord';
            ivrMsg.SPEN_IVRMessage__c = 'Thanks for Contacting SPEN';
            insert ivrMsg;
            
            SPEN_IVR__c ivr = new SPEN_IVR__c();
            ivr.Name = 'IVRTEST';
            insert ivr;
            
            SPEN_IVROperatingHours__c ivrRec1 = new SPEN_IVROperatingHours__c();
            ivrRec1.SPEN_isActive__c = true;
            ivrRec1.SPEN_isDaily__c = false;
            
            Time expected = Time.newInstance(12, 1, 2, 0);
            ivrRec1.SPEN_RestrictStartDate__c =  System.today().addDays(7);
            ivrRec1.SPEN_RestrictEndDate__c =  System.today().addDays(9);
            ivrRec1.RecordTypeId = recTypeIdOfSchedule;
            ivrRec1.SPEN_IVR__c = ivr.Id;
            ivrRec1.SPEN_IVRMessage__c = ivrMsg.Id;
            System.debug( ivrRec1.SPEN_StartTime__c +'<'+ivrRec1.SPEN_EndTime__c);
            System.debug( ivrRec1.SPEN_EndTime__c +'<'+ivrRec1.SPEN_StartTime__c);
            insert ivrRec1;*/
            Test.startTest();
            List<Id> psrIds = new List<Id>();
            datetime dt = system.now()+4;
            String vAlertMessage = 'Thanks for contacting';
            SPEN_SendVoiceAlertCallService.scheduleAlertService(psrIds, vAlertMessage, dt);
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
            Assert.isNotNull(vAlertMessage);
            Test.stopTest();
        }
    }
    @IsTest
    public static void operationHourscodeCoverage1()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user); 
        if (devOpsPSGroup.Status != 'Updated') {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);
        }
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.id;
        insert devOpsAssign;
        System.runAs(user){   
            /*SPEN_ConfigurableSettings__c CS1 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelayForMessagingTask');
            insert CS1;
            SPEN_ConfigurableSettings__c CS2 =SPEN_TestDataFactory.createConfigSetting(1,'OnDemandMessageDelayForMessagingTask');
            insert CS2;
            List<Id> psrIds = new List<Id>();
            Id jobId;
            List<Sobject> sobjectList;
            String vAlertMessage = 'Thanks for contacting';
            datetime dt = system.now()+4;
            
            Contact con = new Contact(LastName = 'Contact', FirstName ='Sheker', email= 'sheker.kulkacherla@accenture.com');
            //insert con;
            SPEN_Premise__c  pri = new SPEN_Premise__c(SPEN_PremiseID__c = 'TEST', SPEN_PremiseNumber__c ='Prem1', SPEN_PostCode__c ='AK28');
            sobjectList = new List<Sobject>{con,pri};
                insert sobjectList;
            Id recTypeIdOfSchedule = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('Outbound Contact Hours').getRecordTypeId();
            SPEN_PSR__c psr = new SPEN_PSR__c();
            psr.SPEN_Contact__c = con.Id;
            psr.SPEN_Premise__c = pri.Id;
            insert psr;
            
            psrIds.add(psr.Id);
            
            SPEN_IVRMessage__c ivrMsg = new SPEN_IVRMessage__c();
            ivrMsg.Name = 'TESTMessageRecord';
            ivrMsg.SPEN_IVRMessage__c = 'Thanks for Contacting SPEN';
            insert ivrMsg;
            
            SPEN_IVR__c ivr = new SPEN_IVR__c();
            ivr.Name = 'IVRTEST';
            insert ivr;
            
            SPEN_IVROperatingHours__c ivrRec1 = new SPEN_IVROperatingHours__c();
            ivrRec1.SPEN_isActive__c = true;
            ivrRec1.SPEN_isDaily__c = true;
            Time expected = Time.newInstance(12, 1, 2, 0);
            ivrRec1.SPEN_StartTime__c = system.now().time()+10;
            ivrRec1.SPEN_EndTime__c = system.now().time()-1;
            ivrRec1.RecordTypeId = recTypeIdOfSchedule;
            ivrRec1.SPEN_IVR__c = ivr.Id;
            ivrRec1.SPEN_IVRMessage__c = ivrMsg.Id;
            System.debug( ivrRec1.SPEN_StartTime__c +'<'+ivrRec1.SPEN_EndTime__c);
            System.debug( ivrRec1.SPEN_EndTime__c +'<'+ivrRec1.SPEN_StartTime__c);
            insert ivrRec1;*/
            Test.startTest();
            List<Id> psrIds = new List<Id>();
            datetime dt = system.now()+4;
            String vAlertMessage = 'Thanks for contacting';
            SPEN_SendVoiceAlertCallService.scheduleAlertService(psrIds, vAlertMessage, dt);
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
            SPEN_SendVoiceAlertCallService.getBatchJobStatus(database.executeBatch(new SPEN_InsertVoiceAlertBatch(psrIds, vAlertMessage, System.now())));
            Assert.isNotNull(vAlertMessage);
            Test.stopTest();
            //SPEN_SendVoiceAlertCallService.getBatchJobStatus(database.executeBatch(new SPEN_InsertVoiceAlertBatch(psrIds, vAlertMessage)));
        }
    }
    @IsTest
    public static void operationHourscodeCoverage2()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user); 
        if (devOpsPSGroup.Status != 'Updated') {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);
        }
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.id;
        insert devOpsAssign;
        System.runAs(user){   
            /*SPEN_ConfigurableSettings__c CS1 =SPEN_TestDataFactory.createConfigSetting(1,'CreationBatchDelayForMessagingTask');
            insert CS1;
            SPEN_ConfigurableSettings__c CS2 =SPEN_TestDataFactory.createConfigSetting(1,'OnDemandMessageDelayForMessagingTask');
            insert CS2;
            List<Id> psrIds = new List<Id>();
            Id jobId;
            List<Sobject> sobjectList;
            String vAlertMessage = 'Thanks for contacting';
            datetime dt = system.now()+4;
            
            Contact con = new Contact(LastName = 'Contact', FirstName ='Sheker', email= 'sheker.kulkacherla@accenture.com');
            //insert con;
            SPEN_Premise__c  pri = new SPEN_Premise__c(SPEN_PremiseID__c = 'TEST', SPEN_PremiseNumber__c ='Prem1', SPEN_PostCode__c ='AK28');
            sobjectList = new List<Sobject>{con,pri};
                insert sobjectList;
            Id recTypeIdOfSchedule = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get('Outbound Contact Hours').getRecordTypeId();
            SPEN_PSR__c psr = new SPEN_PSR__c();
            psr.SPEN_Contact__c = con.Id;
            psr.SPEN_Premise__c = pri.Id;
            insert psr;
            
            psrIds.add(psr.Id);
            
            SPEN_IVRMessage__c ivrMsg = new SPEN_IVRMessage__c();
            ivrMsg.Name = 'TESTMessageRecord';
            ivrMsg.SPEN_IVRMessage__c = 'Thanks for Contacting SPEN';
            insert ivrMsg;
            
            SPEN_IVR__c ivr = new SPEN_IVR__c();
            ivr.Name = 'IVRTEST';
            insert ivr;
            
            SPEN_IVROperatingHours__c ivrRec1 = new SPEN_IVROperatingHours__c();
            ivrRec1.SPEN_isActive__c = true;
            ivrRec1.SPEN_isDaily__c = true;
            Time expected = Time.newInstance(12, 1, 2, 0);
            ivrRec1.SPEN_StartTime__c = system.now().time();
            ivrRec1.SPEN_EndTime__c = system.now().time();
            ivrRec1.RecordTypeId = recTypeIdOfSchedule;
            ivrRec1.SPEN_IVR__c = ivr.Id;
            ivrRec1.SPEN_IVRMessage__c = ivrMsg.Id;
            System.debug( ivrRec1.SPEN_StartTime__c +'<'+ivrRec1.SPEN_EndTime__c);
            System.debug( ivrRec1.SPEN_EndTime__c +'<'+ivrRec1.SPEN_StartTime__c);
            insert ivrRec1;*/
            List<Id> psrIds = new List<Id>();
            datetime dt = system.now()+4;
            String vAlertMessage = 'Thanks for contacting';
            Test.startTest();
            SPEN_SendVoiceAlertCallService.scheduleAlertService(psrIds, vAlertMessage, dt);
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
            SPEN_SendVoiceAlertCallService.getBatchJobStatus(database.executeBatch(new SPEN_InsertVoiceAlertBatch(psrIds, vAlertMessage)));
            Test.stopTest();
            Assert.isNotNull(vAlertMessage);
        }
    }
}