force-app/main/default/objects/SPEN_PhysicalInformation__c/SPEN_PhysicalInformation__c.object-meta.xml
<CustomObject>
    <description>This custom object is for connections process.</description>
    <label>Physical Information</label>
    <nameField>
        <displayFormat>PHYI-{00000}</displayFormat>
        <label>Physical Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physical Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PhysicalInformation__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Physical Information</relationshipLabel>
    <relationshipName>Physical_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SPEN_PhysicalInformationService.cls
public with sharing class SPEN_PhysicalInformationService {
    @InvocableMethod(label='SAP Callout for Physical Information' description='SAP Callout for Physical Information when case is Competent')
    public static void callSAPCallout(List<Id> phyInfoIds)
    {
        try
        {
            String phyInfoId;
            List<Id> lstCaseId = new List<Id>();
            SPEN_PhysicalInformation__c phyInfo = SPEN_PhysicalInformationSelector.getPhysicalInfoFromPhyInfoIds(phyInfoIds);
            phyInfoId= phyInfo.id;
            lstCaseId.add(phyInfo.SPEN_Case__c);
            if(!System.isfuture())
            {
            SPEN_SAPQASCallout.sendSoapCallout(phyInfoId, lstCaseId);
            }
            
        }
        catch(Exception ex)
        {
            System.debug('In class SPEN_PhysicalInformationService : exception block='+ex.getMessage() +ex.getLineNumber() +ex.getStackTraceString());
            SEL_LoggingService.log(ex);
        }

    }

}