force-app/main/default/objects/SPEN_PhysicalInformation__c/SPEN_PhysicalInformation__c.object-meta.xml
<CustomObject>
    <description>This custom object is for connections process.</description>
    <label>Physical Information</label>
    <nameField>
        <displayFormat>PHYI-{00000}</displayFormat>
        <label>Physical Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physical Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PhysicalInformation__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Physical Information</relationshipLabel>
    <relationshipName>Physical_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_PhysicalInformation__c/fields/SPEN_ItemClass__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ItemClass__c</fullName>
    <label>Item Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IT-UITEM</fullName>
                <label>Physical information</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_PhysicalInformation__c/fields/SPEN_ItemID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ItemID__c</fullName>
    <externalId>true</externalId>
    <label>Item ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_PhysicalInformation__c/fields/SPEN_ItemProfile__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ItemProfile__c</fullName>
    <description>CRMD-5996 Connection Process</description>
    <label>Item Profile</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UIT00001</fullName>
                <label>Site layout plan</label>
            </value>
            <value>
                <fullName>UIT00002</fullName>
                <label>Billing address</label>
            </value>
            <value>
                <fullName>UIT00003</fullName>
                <label>Relocation drawing</label>
            </value>
            <value>
                <fullName>UIT00004</fullName>
                <label>Internal layout floor plans (flats only)</label>
            </value>
            <value>
                <fullName>UIT00005</fullName>
                <label>Load details</label>
            </value>
            <value>
                <fullName>UIT00006</fullName>
                <label>Unmetered information</label>
            </value>
            <value>
                <fullName>UIT00007</fullName>
                <label>Location plan</label>
            </value>
            <value>
                <fullName>UIT00008</fullName>
                <label>Meter Point Administration Number (MPAN)</label>
            </value>
            <value>
                <fullName>UIT00009</fullName>
                <label>Site address</label>
            </value>
            <value>
                <fullName>UIT00010</fullName>
                <label>Telephone number</label>
            </value>
            <value>
                <fullName>UIT00011</fullName>
                <label>Photograph(s)</label>
            </value>
            <value>
                <fullName>UIT00012</fullName>
                <label>Embedded generation information</label>
            </value>
            <value>
                <fullName>UIT000012</fullName>
                <isActive>false</isActive>
                <label>Embedded generation information1</label>
            </value>
            <value>
                <fullName>UIT000011</fullName>
                <isActive>false</isActive>
                <label>Photograph(s)1</label>
            </value>
            <value>
                <fullName>UIT000010</fullName>
                <isActive>false</isActive>
                <label>Telephone number1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_PhysicalInformation__c/fields/SPEN_ItemReceivedOn__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ItemReceivedOn__c</fullName>
    <description>CRMD-5996 Connection process</description>
    <label>Item Received On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_PhysicalInformation__c/fields/SPEN_ItemReceivedRemark__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ItemReceivedRemark__c</fullName>
    <description>CRMD-5996 Connection Process</description>
    <label>Item Received Remark</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_PhysicalInformation__c/fields/SPEN_ItemRequestedDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ItemRequestedDate__c</fullName>
    <description>CRMD-5996 Connection Process</description>
    <label>Item Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_PhysicalInformation__c/fields/SPEN_ItemRequestRemark__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ItemRequestRemark__c</fullName>
    <description>CRMD-5996 Connection Process</description>
    <label>Item Request Remark</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SPEN_PhysicalInformationSelector.cls
/*-----------------------------------------------------------------------------
DESCRIPTION :   Selector class of the Plot Queries.
LIBRARY     :   Salesforce Enterprise Library - Plot Queries
VERSION     :   1.0

HISTORY     :
Date            Author              Comment
25-Jul-2023     Akshay Pandit        Initial version
-----------------------------------------------------------------------------*/
public inherited sharing class SPEN_PhysicalInformationSelector {
    /**************************************************
    @Author: Akshay Pandit
    @Date: 25-Jul-2023 
    @purpose: Method to get Physical Information details from case.
    ***************************************************/
    public static List<SPEN_PhysicalInformation__c> getPhysicalInfoFromCase(Id caseId){
        List<SPEN_PhysicalInformation__c>	physicalInfoList = new List<SPEN_PhysicalInformation__c>();
        if(caseId != null)
        {
            physicalInfoList = 	[Select Id,SPEN_ItemID__c,SPEN_Case__c,SPEN_ItemClass__c,SPEN_ItemProfile__c,SPEN_ItemRequestedDate__c,SPEN_ItemRequestRemark__c,SPEN_ItemReceivedOn__c,SPEN_ItemReceivedRemark__c FROM SPEN_PhysicalInformation__c where SPEN_Case__c=: caseId WITH SECURITY_ENFORCED];
        }  	                       
        return physicalInfoList;     
    }

    public static SPEN_PhysicalInformation__c getPhysicalInfoFromPhyInfoIds(List<Id> phyInfoIds){
        SPEN_PhysicalInformation__c	physicalInfoRec;
        if(!phyInfoIds.isEmpty())
        {
            physicalInfoRec = [select id,SPEN_Case__c from SPEN_PhysicalInformation__c where id in : phyInfoIds WITH SECURITY_ENFORCED limit 1 ];
        }  	                       
        return physicalInfoRec;     
    }

    public static SPEN_PhysicalInformation__c getPhysicalInfoFromPhyInfoStrId(String phyInfoRef){
        SPEN_PhysicalInformation__c	physicalInfoRec;
        if(phyInfoRef != null)
        {
            physicalInfoRec = [Select Id,SPEN_ItemID__c,SPEN_Case__c,SPEN_ItemClass__c,SPEN_ItemProfile__c,SPEN_ItemRequestedDate__c,SPEN_ItemRequestRemark__c,SPEN_ItemReceivedOn__c,SPEN_ItemReceivedRemark__c,SPEN_Case__r.SPEN_SAPReference__c FROM SPEN_PhysicalInformation__c where id =: phyInfoRef WITH SECURITY_ENFORCED limit 1];
        }  	                       
        return physicalInfoRec;     
    }
}