force-app/main/default/objects/SPEN_CategoryDesignInformation__c/SPEN_CategoryDesignInformation__c.object-meta.xml
<CustomObject>
    <label>Category Design Information</label>
    <nameField>
        <displayFormat>CDI-{00000}</displayFormat>
        <label>Category Design Information Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Design Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CategoryDesignInformation__c/fields/SPEN_DesignInformationTemplate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DesignInformationTemplate__c</fullName>
    <label>Design Information Template</label>
    <referenceTo>SPEN_DesignInformationTemplate__c</referenceTo>
    <relationshipLabel>Category Design Informations</relationshipLabel>
    <relationshipName>Category_Design_Informations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_CategoryDesignInformation__c/fields/SPEN_WorkCategory__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkCategory__c</fullName>
    <label>Work Category</label>
    <referenceTo>SPEN_WorkCategory__c</referenceTo>
    <relationshipLabel>Category Design Informations</relationshipLabel>
    <relationshipName>Category_Design_Informations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_Job__c/SPEN_Job__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store L&amp;P Job records</description>
    <label>Job</label>
    <nameField>
        <label>Job Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Job__c/fields/SPEN_BusinessArea__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BusinessArea__c</fullName>
    <label>Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SPEN_LicenseArea__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Land &amp; Planning</fullName>
            </value>
            <value>
                <fullName>Business Transformation</fullName>
            </value>
            <value>
                <fullName>External Customer</fullName>
            </value>
            <value>
                <fullName>Internal Customer</fullName>
            </value>
            <value>
                <fullName>Land Solutions Policy &amp; Performance</fullName>
            </value>
            <value>
                <fullName>Licence Programmes</fullName>
            </value>
            <value>
                <fullName>Processes &amp; Technology</fullName>
            </value>
            <value>
                <fullName>Strategic Transmission Projects</fullName>
            </value>
            <value>
                <fullName>Transmission Operations</fullName>
            </value>
            <value>
                <fullName>Transmission Projects - Customer Connection</fullName>
            </value>
            <value>
                <fullName>Transmission Projects - Infrastructure</fullName>
            </value>
            <value>
                <fullName>Customer Resolution</fullName>
            </value>
            <value>
                <fullName>Customer Connections</fullName>
            </value>
            <value>
                <fullName>Distribution Network Operations</fullName>
            </value>
            <value>
                <fullName>Distribution Network Projects</fullName>
            </value>
            <value>
                <fullName>Estates</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Land Agent</fullName>
            </value>
            <value>
                <fullName>Land Solutions, Policy &amp; Performance</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Tree Department</fullName>
            </value>
            <value>
                <fullName>License Programmes</fullName>
            </value>
            <value>
                <fullName>HS2</fullName>
            </value>
            <value>
                <fullName>SPM 132 Operations</fullName>
            </value>
            <value>
                <fullName>SPM 132 Projects - Infrastructure</fullName>
            </value>
            <value>
                <fullName>SPM 132 Projects - Customer Connection</fullName>
            </value>
            <value>
                <fullName>Interal Customer</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
                <isActive>false</isActive>
                <label>CRM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Job__c/fields/SPEN_District__c.field-meta.xml
<CustomField>
    <fullName>SPEN_District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SPEN_LicenseArea__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Ayrshire &amp; Clyde South</fullName>
            </value>
            <value>
                <fullName>Central &amp; Fife</fullName>
            </value>
            <value>
                <fullName>Dee Valley/ Mid Wales</fullName>
            </value>
            <value>
                <fullName>Dumfries &amp; Galloway</fullName>
            </value>
            <value>
                <fullName>Edinburgh &amp; Borders</fullName>
            </value>
            <value>
                <fullName>Glasgow &amp; Clyde North</fullName>
            </value>
            <value>
                <fullName>Lanarkshire</fullName>
            </value>
            <value>
                <fullName>Merseyside</fullName>
            </value>
            <value>
                <fullName>Mid-Cheshire</fullName>
            </value>
            <value>
                <fullName>North Wales</fullName>
            </value>
            <value>
                <fullName>Wirral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Job__c/fields/SPEN_LicenseArea__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LicenseArea__c</fullName>
    <label>Licence Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Environmental Planning</fullName>
                <isActive>false</isActive>
                <label>Environmental Planning</label>
            </value>
            <value>
                <fullName>Land Assistant North</fullName>
                <isActive>false</isActive>
                <label>Land Assistant North</label>
            </value>
            <value>
                <fullName>Land Assistant South</fullName>
                <isActive>false</isActive>
                <label>Land Assistant South</label>
            </value>
            <value>
                <fullName>SPD</fullName>
            </value>
            <value>
                <fullName>SPM</fullName>
            </value>
            <value>
                <fullName>SPM 132</fullName>
            </value>
            <value>
                <fullName>SPT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Job__c/fields/SPEN_Work_Category__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Work_Category__c</fullName>
    <label>Work Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SPEN_LicenseArea__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CCT Customer Contact Enquiry</fullName>
            </value>
            <value>
                <fullName>Change of Owner</fullName>
            </value>
            <value>
                <fullName>Change of Owner Estate</fullName>
            </value>
            <value>
                <fullName>Change of Owner Farm</fullName>
            </value>
            <value>
                <fullName>Change of Owner Garden</fullName>
            </value>
            <value>
                <fullName>Change Of Vendor Details</fullName>
            </value>
            <value>
                <fullName>Completed Necessary Wayleave</fullName>
            </value>
            <value>
                <fullName>CRM Customer Complaint</fullName>
            </value>
            <value>
                <fullName>Damage Claim</fullName>
            </value>
            <value>
                <fullName>Decomissioning</fullName>
            </value>
            <value>
                <fullName>Decommissioning</fullName>
                <isActive>false</isActive>
                <label>Decommissioning</label>
            </value>
            <value>
                <fullName>District Day to Day</fullName>
            </value>
            <value>
                <fullName>External Land Search Request</fullName>
            </value>
            <value>
                <fullName>Fibre Optic Cable</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Finance Receipting</fullName>
                <isActive>false</isActive>
                <label>Finance Receipting</label>
            </value>
            <value>
                <fullName>Incorporated Rights - All</fullName>
            </value>
            <value>
                <fullName>Injurious Affection</fullName>
            </value>
            <value>
                <fullName>Land Enquiry</fullName>
            </value>
            <value>
                <fullName>Land Rights Enquiry</fullName>
            </value>
            <value>
                <fullName>LVSSA</fullName>
            </value>
            <value>
                <fullName>LVSSA Servitude/Easement ** temp w/l</fullName>
                <isActive>false</isActive>
                <label>LVSSA Servitude/Easement ** temp w/l</label>
            </value>
            <value>
                <fullName>LVSSB</fullName>
            </value>
            <value>
                <fullName>LVSSB Servitude/Easement ** temp w/l</fullName>
                <isActive>false</isActive>
                <label>LVSSB Servitude/Easement ** temp w/l</label>
            </value>
            <value>
                <fullName>Maintenance Works - Non Outage</fullName>
            </value>
            <value>
                <fullName>Maintenance Works - Outage</fullName>
            </value>
            <value>
                <fullName>Major Refurb No planning</fullName>
            </value>
            <value>
                <fullName>Major Refurb Planning</fullName>
            </value>
            <value>
                <fullName>Major Refurb S37</fullName>
            </value>
            <value>
                <fullName>New Marine Cable with Planning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Job__c/fields/SPEN_WorkCategory__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkCategory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Work Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SPEN_WorkCategory__c.SPEN_LicenseArea__c</field>
            <operation>equals</operation>
            <valueField>$Source.SPEN_LicenseArea__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SPEN_WorkCategory__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_WorkCategory__c/SPEN_WorkCategory__c.object-meta.xml
<CustomObject>
    <label>Work Category</label>
    <nameField>
        <label>Work Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_WorkCategory__c/fields/SPEN_LicenseArea__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LicenseArea__c</fullName>
    <description>This field holds license area information</description>
    <label>License Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Environmental Planning</fullName>
                <isActive>false</isActive>
                <label>Environmental Planning</label>
            </value>
            <value>
                <fullName>Land Assistant North</fullName>
                <isActive>false</isActive>
                <label>Land Assistant North</label>
            </value>
            <value>
                <fullName>Land Assistant South</fullName>
                <isActive>false</isActive>
                <label>Land Assistant South</label>
            </value>
            <value>
                <fullName>SPD</fullName>
            </value>
            <value>
                <fullName>SPM</fullName>
            </value>
            <value>
                <fullName>SPM 132</fullName>
            </value>
            <value>
                <fullName>SPT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_WorkCategoryMilestone__c/SPEN_WorkCategoryMilestone__c.object-meta.xml
<CustomObject>
    <label>Work Category Milestone</label>
    <nameField>
        <displayFormat>WCM-{00000}</displayFormat>
        <label>Work Category Milestone</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Category Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_WorkCategoryMilestone__c/fields/SPEN_WorkCategory__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkCategory__c</fullName>
    <description>It stores work category detail as parent to work category milestone</description>
    <label>Work Category</label>
    <referenceTo>SPEN_WorkCategory__c</referenceTo>
    <relationshipLabel>Work Category Milestones</relationshipLabel>
    <relationshipName>Work_Category_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SPEN_ContentDocuments_Test.cls
@IsTest
public class SPEN_ContentDocuments_Test {
    

    @IsTest
    public static void testJobDeleteContentDocumentLink()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAMELNPUSER);
        PermissionSetGroup externaluserPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_LnP_ExternalUser');
        
        UserRole externalRole = SPEN_TestDataFactory.createExternalUserRole('testExternalRole','External Distribution');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAMELNPUSER);
        user.UserRoleId = externalRole.Id;
        Database.insert(user);
        if (externaluserPSGroup.Status != 'Updated') 
        {
            Test.calculatePermissionSetGroup(externaluserPSGroup.Id);
        }
        PermissionSetAssignment externaluserAssign = new PermissionSetAssignment();
        externaluserAssign.AssigneeId = user.Id;
        externaluserAssign.PermissionSetGroupId = externaluserPSGroup.Id;
        insert externaluserAssign; 
        System.runAs(user) {
       
        SPEN_WorkCategory__c wc = SPEN_TestDataUtility.createWorkCategoryRecord('Test WC','SPD');
        SPEN_DesignInformationTemplate__c desInfTemp= SPEN_TestDataUtility.createDesignInfoTemplateRec('testDesignInfoTemplateData');
        SPEN_CategoryDesignInformation__c catDesInfo = SPEN_TestDataUtility.createCategoryDesignInfo(wc.Id,desInfTemp.Id);       
        List<SPEN_WorkCategoryMilestone__c> parentWCMs = SPEN_TestDataUtility.createWorkCategoryMilestoneRecord(wc.id,'Planning','Yes',2, null);
        Database.insert(parentWCMs);
        if(parentWCMs!= null){
            List<SPEN_WorkCategoryMilestone__c> ChildWCMs = SPEN_TestDataUtility.createWorkCategoryMilestoneRecord(wc.id,'Planning','Yes',3, parentWCMs[0].id );
            Database.insert(ChildWCMs);
        }
        List<SPEN_Job__c> job = SPEN_TestDataUtility.createJobRecord('Draft','Yes',wc.Id,'create job through Email',1);
        job[0].SPEN_LicenseArea__c = 'SPD';
        job[0].SPEN_Work_Category__c='CCT Customer Contact Enquiry';
        job[0].SPEN_District__c='Lanarkshire';
        job[0].SPEN_BusinessArea__c='Finance';
        job[0].SPEN_CircuitID__c='CI001';
        job[0].SPEN_CustomerType__c='Network';
        job[0].SPEN_ControlNumber__c='CN001';
        job[0].SPEN_OSGridReference__c='897654,987654';
        job[0].SPEN_JobTitle__c = 'CreatedJob#1';  
        job[0].Name = 'CreatedJob#1'; 
        Database.insert(job);
        Test.setMock(HttpCalloutMock.class, new SPEN_FileUploaderClassHttpMock());
            Test.startTest();
            
            ContentVersion contentVersion = new ContentVersion(
                Title = 'TestContent',
                PathOnClient = 'Testdoc.csv',
                VersionData = Blob.valueOf('TestContent'),
                IsMajorVersion = true
            );
            insert contentVersion;    
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            
            ContentDocumentLink cdli = New ContentDocumentLink();
            cdli.LinkedEntityId = job[0].Id;
            cdli.ContentDocumentId = documents[0].Id;
            cdli.shareType = 'V';
            Database.SaveResult sr = Database.insert(cdli, false);
            
            job[0].SPEN_JobStatus__c='Review';
            update job[0];            

            Database.DeleteResult dr = Database.delete(documents[0], false);
            System.assertEquals(false,dr.isSuccess());

            Test.stopTest();
        }
    }
}