force-app/main/default/objects/SPEN_CategoryDesignInformation__c/SPEN_CategoryDesignInformation__c.object-meta.xml
<CustomObject>
    <label>Category Design Information</label>
    <nameField>
        <displayFormat>CDI-{00000}</displayFormat>
        <label>Category Design Information Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Design Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_CategoryDesignInformation__c/fields/SPEN_DesignInformationTemplate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DesignInformationTemplate__c</fullName>
    <label>Design Information Template</label>
    <referenceTo>SPEN_DesignInformationTemplate__c</referenceTo>
    <relationshipLabel>Category Design Informations</relationshipLabel>
    <relationshipName>Category_Design_Informations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_CategoryDesignInformation__c/fields/SPEN_WorkCategory__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkCategory__c</fullName>
    <label>Work Category</label>
    <referenceTo>SPEN_WorkCategory__c</referenceTo>
    <relationshipLabel>Category Design Informations</relationshipLabel>
    <relationshipName>Category_Design_Informations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_Job__c/SPEN_Job__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store L&amp;P Job records</description>
    <label>Job</label>
    <nameField>
        <label>Job Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Job__c/fields/SPEN_LicenseArea__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LicenseArea__c</fullName>
    <label>Licence Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Environmental Planning</fullName>
                <isActive>false</isActive>
                <label>Environmental Planning</label>
            </value>
            <value>
                <fullName>Land Assistant North</fullName>
                <isActive>false</isActive>
                <label>Land Assistant North</label>
            </value>
            <value>
                <fullName>Land Assistant South</fullName>
                <isActive>false</isActive>
                <label>Land Assistant South</label>
            </value>
            <value>
                <fullName>SPD</fullName>
            </value>
            <value>
                <fullName>SPM</fullName>
            </value>
            <value>
                <fullName>SPM 132</fullName>
            </value>
            <value>
                <fullName>SPT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Job__c/fields/SPEN_WorkCategory__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkCategory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Work Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SPEN_WorkCategory__c.SPEN_LicenseArea__c</field>
            <operation>equals</operation>
            <valueField>$Source.SPEN_LicenseArea__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SPEN_WorkCategory__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Land_Interest__c/SPEN_Land_Interest__c.object-meta.xml
<CustomObject>
    <description>Created as part of ESC-122.</description>
    <label>Land Right</label>
    <nameField>
        <label>Land Right Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Land Rights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Land_Interest__c/fields/SPEN_Job__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Job__c</fullName>
    <label>Job</label>
    <referenceTo>SPEN_Job__c</referenceTo>
    <relationshipName>Land_Interests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_Land_Interest__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Negotiation</fullName>
            </value>
            <value>
                <fullName>Awaiting Design</fullName>
            </value>
            <value>
                <fullName>Land Right Issued</fullName>
            </value>
            <value>
                <fullName>Land Right Acquired</fullName>
            </value>
            <value>
                <fullName>Land Right Secured</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Internal Legal Instruction</fullName>
            </value>
            <value>
                <fullName>Draft Documents Issued</fullName>
            </value>
            <value>
                <fullName>Third Party Consent</fullName>
            </value>
            <value>
                <fullName>Draft Documents Agreed</fullName>
            </value>
            <value>
                <fullName>Legal Milestones Completed</fullName>
            </value>
            <value>
                <fullName>Consent Acquired</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/SPEN_MessagingTask__c.object-meta.xml
<CustomObject>
    <description>This object allows agents to set up and configure broadcast messaging via SMS, Voice Alerts, etc.</description>
    <label>Messaging Task</label>
    <nameField>
        <displayFormat>MST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messaging Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Shows the progress of the Message Task</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Planning__c/SPEN_Planning__c.object-meta.xml
<CustomObject>
    <label>Planning</label>
    <nameField>
        <label>Planning Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planning</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Planning__c/fields/SPEN_Job__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Job__c</fullName>
    <label>Job</label>
    <referenceTo>SPEN_Job__c</referenceTo>
    <relationshipLabel>Planning</relationshipLabel>
    <relationshipName>Plannings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPEN_Planning__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress-Date Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Feedback Pending</fullName>
            </value>
            <value>
                <fullName>Submitted to Local Authority</fullName>
            </value>
            <value>
                <fullName>With Public Inquiry</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved with Conditions</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>In Progress-Date Submiited</fullName>
                <isActive>false</isActive>
                <label>In Progress-Date Submiited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_WorkCategory__c/SPEN_WorkCategory__c.object-meta.xml
<CustomObject>
    <label>Work Category</label>
    <nameField>
        <label>Work Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_WorkCategory__c/fields/SPEN_LicenseArea__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LicenseArea__c</fullName>
    <description>This field holds license area information</description>
    <label>License Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Environmental Planning</fullName>
                <isActive>false</isActive>
                <label>Environmental Planning</label>
            </value>
            <value>
                <fullName>Land Assistant North</fullName>
                <isActive>false</isActive>
                <label>Land Assistant North</label>
            </value>
            <value>
                <fullName>Land Assistant South</fullName>
                <isActive>false</isActive>
                <label>Land Assistant South</label>
            </value>
            <value>
                <fullName>SPD</fullName>
            </value>
            <value>
                <fullName>SPM</fullName>
            </value>
            <value>
                <fullName>SPM 132</fullName>
            </value>
            <value>
                <fullName>SPT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_WorkCategoryMilestone__c/SPEN_WorkCategoryMilestone__c.object-meta.xml
<CustomObject>
    <label>Work Category Milestone</label>
    <nameField>
        <displayFormat>WCM-{00000}</displayFormat>
        <label>Work Category Milestone</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Category Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_WorkCategoryMilestone__c/fields/SPEN_WorkCategory__c.field-meta.xml
<CustomField>
    <fullName>SPEN_WorkCategory__c</fullName>
    <description>It stores work category detail as parent to work category milestone</description>
    <label>Work Category</label>
    <referenceTo>SPEN_WorkCategory__c</referenceTo>
    <relationshipLabel>Work Category Milestones</relationshipLabel>
    <relationshipName>Work_Category_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SPEN_ContentDocumentLink_Test.cls
@IsTest
@SuppressWarnings('PMD.SOQLSelectorPattern')
public class SPEN_ContentDocumentLink_Test {
    @IsTest
    public static void testContentDocumentLink()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user);
        if (devOpsPSGroup.Status != 'Updated') 
        {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);
        }
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.Id;
        insert devOpsAssign;
        System.runAs(user)
        {
            Test.startTest();
            List<SPEN_MessagingTask__c> sMsgtask = new List<SPEN_MessagingTask__c>();
            SPEN_MessagingTask__c sMsgtask1 = new SPEN_MessagingTask__c();
            sMsgtask1.SPEN_Status__c='New';   
            insert sMsgtask1;
            sMsgtask.add(sMsgtask1);
            
            ContentVersion contentVersion = new ContentVersion(
                Title = 'Test',
                PathOnClient = 'Test.csv',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true
            );
            insert contentVersion;    
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument where Title='Test'];
            ContentDocumentLink cdli = New ContentDocumentLink();
            cdli.LinkedEntityId = sMsgtask1.id;
            cdli.ContentDocumentId = documents[0].Id;
            cdli.shareType = 'V';
            insert cdli;
            Assert.IsNotNull(sMsgtask1);
            Test.stopTest();
        }
    }

     @IsTest
    public static void testJobContentDocumentLink()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAMELNPUSER);
        PermissionSetGroup externaluserPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_LnP_ExternalUser');
        
        UserRole externalRole = SPEN_TestDataFactory.createExternalUserRole('testExternalRole','External Distribution');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAMELNPUSER);
        user.UserRoleId = externalRole.Id;
        Database.insert(user);
        if (externaluserPSGroup.Status != 'Updated') 
        {
            Test.calculatePermissionSetGroup(externaluserPSGroup.Id);
        }
        PermissionSetAssignment externaluserAssign = new PermissionSetAssignment();
        externaluserAssign.AssigneeId = user.Id;
        externaluserAssign.PermissionSetGroupId = externaluserPSGroup.Id;
        insert externaluserAssign; 
        System.runAs(user) {
       
        SPEN_WorkCategory__c wc = SPEN_TestDataUtility.createWorkCategoryRecord('Test WC','SPD');

        SPEN_DesignInformationTemplate__c desInfTemp= SPEN_TestDataUtility.createDesignInfoTemplateRec('testDesignInfoTemplateData');
        SPEN_CategoryDesignInformation__c catDesInfo = SPEN_TestDataUtility.createCategoryDesignInfo(wc.Id,desInfTemp.Id);       
        List<SPEN_WorkCategoryMilestone__c> parentWCMs = SPEN_TestDataUtility.createWorkCategoryMilestoneRecord(wc.id,'Planning','Yes',2, null);
        Database.insert(parentWCMs);
        if(parentWCMs!= null){
            List<SPEN_WorkCategoryMilestone__c> ChildWCMs = SPEN_TestDataUtility.createWorkCategoryMilestoneRecord(wc.id,'Planning','Yes',3, parentWCMs[0].id );
            Database.insert(ChildWCMs);
        }
        List<SPEN_Job__c> job = SPEN_TestDataUtility.createJobRecord('Review','Yes',wc.Id,'create job through Email',1);
        job[0].SPEN_LicenseArea__c = 'SPD';
        job[0].SPEN_Work_Category__c='CCT Customer Contact Enquiry';
        job[0].SPEN_District__c='Lanarkshire';
        job[0].SPEN_BusinessArea__c='Finance';
        job[0].SPEN_CircuitID__c='CI001';
        job[0].SPEN_CustomerType__c='Network';
        job[0].SPEN_ControlNumber__c='CN001';
        job[0].SPEN_OSGridReference__c='897654,987554';
        job[0].SPEN_JobTitle__c = 'CreatedJob#1';  
        job[0].Name = 'CreatedJob#1';  
        Database.insert(job);
		Test.setMock(HttpCalloutMock.class, new SPEN_FileUploaderClassHttpMock());
            Test.startTest();
            
            ContentVersion contentVersion = new ContentVersion(
                Title = 'TestContent',
                PathOnClient = 'Testdoc.csv',
                VersionData = Blob.valueOf('TestContent'),
                IsMajorVersion = true
            );
            insert contentVersion;    
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            
            ContentDocumentLink cdli = New ContentDocumentLink();
            cdli.LinkedEntityId = job[0].Id;
            cdli.ContentDocumentId = documents[0].Id;
            cdli.shareType = 'V';
            Database.SaveResult sr = Database.insert(cdli, false);
            System.assertEquals(false,sr.isSuccess());
            Test.stopTest();
        }
    }
    
     @IsTest
    public static void testLIContentDocumentLink()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAMELNPUSER);
        PermissionSetGroup externaluserPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_LnP_ExternalUser');
        UserRole externalRole = SPEN_TestDataFactory.createExternalUserRole('testExternalRole','External Distribution');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAMELNPUSER);
        user.UserRoleId = externalRole.Id;
        Database.insert(user);
        if (externaluserPSGroup.Status != 'Updated') 
        {
            Test.calculatePermissionSetGroup(externaluserPSGroup.Id);
        }
        PermissionSetAssignment externaluserAssign = new PermissionSetAssignment();
        externaluserAssign.AssigneeId = user.Id;
        externaluserAssign.PermissionSetGroupId = externaluserPSGroup.Id;
        insert externaluserAssign; 
        System.runAs(user) {
        
        SPEN_WorkCategory__c wc = SPEN_TestDataUtility.createWorkCategoryRecord('Test WC','SPD');
        List<SPEN_Job__c> job = SPEN_TestDataUtility.createJobRecord('Draft','Yes',wc.Id,'create job through Email',1);
        job[0].SPEN_LicenseArea__c = 'SPD';
        job[0].SPEN_Work_Category__c='CCT Customer Contact Enquiry';
        job[0].SPEN_District__c='Lanarkshire';
        job[0].SPEN_BusinessArea__c='Finance';
        job[0].SPEN_CircuitID__c='CI001';
        job[0].SPEN_CustomerType__c='Network';
        job[0].SPEN_ControlNumber__c='CN001';
        job[0].SPEN_OSGridReference__c='897654,987654';
        job[0].SPEN_JobTitle__c = 'CreatedJob#1';  
        job[0].Name = 'CreatedJob#1'; 
        Database.insert(job);
		Test.setMock(HttpCalloutMock.class, new SPEN_FileUploaderClassHttpMock());
        SPEN_Land__c landRec= SPEN_TestDataUtility.createLandRec();
        SPEN_Land_Interest__c landIntRec = SPEN_TestDataUtility.createLandIntRec(landRec.Id,job[0].Id);
           
            Test.startTest();
            
            ContentVersion contentVersion = new ContentVersion(
                Title = 'TestContentLI',
                PathOnClient = 'TestdocLI.csv',
                VersionData = Blob.valueOf('TestContentLI'),
                IsMajorVersion = true
            );
            insert contentVersion;    
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            
            ContentDocumentLink cdli = New ContentDocumentLink();
            cdli.LinkedEntityId = landIntRec.Id;
            cdli.ContentDocumentId = documents[0].Id;
            cdli.shareType = 'V';
            Database.SaveResult sr = Database.insert(cdli, false);
            System.assertEquals(false,sr.isSuccess());
            Test.stopTest();
        }
    }
    
     @IsTest
    public static void testPlanningContentDocumentLink()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAMELNPUSER);
        PermissionSetGroup externaluserPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_LnP_ExternalUser');
        UserRole externalRole = SPEN_TestDataFactory.createExternalUserRole('testExternalRole','External Distribution');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAMELNPUSER);
        user.UserRoleId = externalRole.Id;
        Database.insert(user);
        if (externaluserPSGroup.Status != 'Updated') 
        {
            Test.calculatePermissionSetGroup(externaluserPSGroup.Id);
        }
        PermissionSetAssignment externaluserAssign = new PermissionSetAssignment();
        externaluserAssign.AssigneeId = user.Id;
        externaluserAssign.PermissionSetGroupId = externaluserPSGroup.Id;
        insert externaluserAssign; 
        System.runAs(user) {
        
        SPEN_WorkCategory__c wc = SPEN_TestDataUtility.createWorkCategoryRecord('Test WC','SPD');
        List<SPEN_Job__c> job = SPEN_TestDataUtility.createJobRecord('Draft','Yes',wc.Id,'create job through Email',1);
        job[0].SPEN_LicenseArea__c = 'SPD';
        job[0].SPEN_Work_Category__c='CCT Customer Contact Enquiry';
        job[0].SPEN_District__c='Lanarkshire';
        job[0].SPEN_BusinessArea__c='Finance';
        job[0].SPEN_CircuitID__c='CI001';
        job[0].SPEN_CustomerType__c='Network';
        job[0].SPEN_ControlNumber__c='CN001';
        job[0].SPEN_OSGridReference__c='897654,987655';
        job[0].SPEN_JobTitle__c = 'CreatedJob#1';  
        job[0].Name = 'CreatedJob#1'; 
        Database.insert(job);
		Test.setMock(HttpCalloutMock.class, new SPEN_FileUploaderClassHttpMock());
        SPEN_Planning__c planningRec= SPEN_TestDataUtility.createPlanningRec('Draft',job[0].Id);
            
            Test.startTest();
            
            ContentVersion contentVersion = new ContentVersion(
                Title = 'TestContentLI',
                PathOnClient = 'TestdocLI.csv',
                VersionData = Blob.valueOf('TestContentLI'),
                IsMajorVersion = true
            );
            insert contentVersion;    
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            
            ContentDocumentLink cdli = New ContentDocumentLink();
            cdli.LinkedEntityId = planningRec.Id;
            cdli.ContentDocumentId = documents[0].Id;
            cdli.shareType = 'V';
            Database.SaveResult sr = Database.insert(cdli, false);
            System.assertEquals(false,sr.isSuccess());
            Test.stopTest();
        }
    }
    
      @IsTest
    public static void testJobDeleteContentDocumentLink()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAMELNPUSER);
        PermissionSetGroup externaluserPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_LnP_ExternalUser');
        
        UserRole externalRole = SPEN_TestDataFactory.createExternalUserRole('testExternalRole','External Distribution');
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAMELNPUSER);
        user.UserRoleId = externalRole.Id;
        Database.insert(user);
        if (externaluserPSGroup.Status != 'Updated') 
        {
            Test.calculatePermissionSetGroup(externaluserPSGroup.Id);
        }
        PermissionSetAssignment externaluserAssign = new PermissionSetAssignment();
        externaluserAssign.AssigneeId = user.Id;
        externaluserAssign.PermissionSetGroupId = externaluserPSGroup.Id;
        insert externaluserAssign; 
        System.runAs(user) {
       
        SPEN_WorkCategory__c wc = SPEN_TestDataUtility.createWorkCategoryRecord('Test WC','SPD');
        SPEN_DesignInformationTemplate__c desInfTemp= SPEN_TestDataUtility.createDesignInfoTemplateRec('testDesignInfoTemplateData');
        SPEN_CategoryDesignInformation__c catDesInfo = SPEN_TestDataUtility.createCategoryDesignInfo(wc.Id,desInfTemp.Id);       
        List<SPEN_WorkCategoryMilestone__c> parentWCMs = SPEN_TestDataUtility.createWorkCategoryMilestoneRecord(wc.id,'Planning','Yes',2, null);
        Database.insert(parentWCMs);
        if(parentWCMs!= null){
            List<SPEN_WorkCategoryMilestone__c> ChildWCMs = SPEN_TestDataUtility.createWorkCategoryMilestoneRecord(wc.id,'Planning','Yes',3, parentWCMs[0].id );
            Database.insert(ChildWCMs);
        }
        List<SPEN_Job__c> job = SPEN_TestDataUtility.createJobRecord('Draft','Yes',wc.Id,'create job through Email',1);
        job[0].SPEN_LicenseArea__c = 'SPD';
        job[0].SPEN_Work_Category__c='CCT Customer Contact Enquiry';
        job[0].SPEN_District__c='Lanarkshire';
        job[0].SPEN_BusinessArea__c='Finance';
        job[0].SPEN_CircuitID__c='CI001';
        job[0].SPEN_CustomerType__c='Network';
        job[0].SPEN_ControlNumber__c='CN001';
        job[0].SPEN_OSGridReference__c='897654,987654';
        job[0].SPEN_JobTitle__c = 'CreatedJob#1';  
        job[0].Name = 'CreatedJob#1'; 
        Database.insert(job);
        Test.setMock(HttpCalloutMock.class, new SPEN_FileUploaderClassHttpMock());
            Test.startTest();
            
            ContentVersion contentVersion = new ContentVersion(
                Title = 'TestContent',
                PathOnClient = 'Testdoc.csv',
                VersionData = Blob.valueOf('TestContent'),
                IsMajorVersion = true
            );
            insert contentVersion;    
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            
            ContentDocumentLink cdli = New ContentDocumentLink();
            cdli.LinkedEntityId = job[0].Id;
            cdli.ContentDocumentId = documents[0].Id;
            cdli.shareType = 'V';
            Database.SaveResult sr = Database.insert(cdli, false);
            
            job[0].SPEN_JobStatus__c='Review';
            update job[0];            

            Database.DeleteResult dr = Database.delete(cdli, false);
            System.assertEquals(false,dr.isSuccess());

            Test.stopTest();
        }
    }

}