force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_Message__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Message__c</fullName>
    <description>It hold the message on IVR Message object</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/recordTypes/SMS.recordType-meta.xml
<RecordType>
    <fullName>SMS</fullName>
    <active>true</active>
    <label>SMS</label>
</RecordType>

force-app/main/default/objects/SPEN_Sms__c/SPEN_Sms__c.object-meta.xml
<CustomObject>
    <description>Represents a single SMS message.</description>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMSes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_CaseId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The case record that generated the SMS.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>SMSes</relationshipLabel>
    <relationshipName>SPEN_SMSes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_ContactId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The recipient of the SMS message.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SMSes</relationshipLabel>
    <relationshipName>SPEN_SMSes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <description>Indicates the event that triggered the SMS record to be created. In IVR scenarios, this is used to look up the message template.</description>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPAS Inquiry</fullName>
            </value>
            <value>
                <fullName>Supplier Inquiry</fullName>
            </value>
            <value>
                <fullName>Case Creation</fullName>
            </value>
            <value>
                <fullName>Merged from SP to Network</fullName>
            </value>
            <value>
                <fullName>3-Hour Comfort Call</fullName>
            </value>
            <value>
                <fullName>3rd Call Received</fullName>
            </value>
            <value>
                <fullName>Dropped Supply with Notice</fullName>
            </value>
            <value>
                <fullName>Dropped Supply without Notice</fullName>
            </value>
            <value>
                <fullName>Estimated Restoration Time Extended</fullName>
            </value>
            <value>
                <fullName>Incident Created</fullName>
            </value>
            <value>
                <fullName>Incident Restored</fullName>
            </value>
            <value>
                <fullName>Resource Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Resource Dispatched</fullName>
            </value>
            <value>
                <fullName>MPAS Out-Of-Area Inquiry</fullName>
            </value>
            <value>
                <fullName>Resource ETA Change</fullName>
            </value>
            <value>
                <fullName>Medically Dependent by District</fullName>
            </value>
            <value>
                <fullName>Planned Outage Communication</fullName>
            </value>
            <value>
                <fullName>On Demand</fullName>
            </value>
            <value>
                <fullName>Connections</fullName>
            </value>
            <value>
                <fullName>HV proactive contact</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>Complaint Case Creation</fullName>
            </value>
            <value>
                <fullName>GE Closure Survey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>SMSes</relationshipLabel>
    <relationshipName>SMSes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_IsProactive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IsProactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the customer was proactively contacted before incident restoration</description>
    <label>Is Proactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_Message__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Message__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Actual message sent to the customer.</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Represents the status of message deliverability.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Undelivered</fullName>
            </value>
            <value>
                <fullName>Potentially Duplicate</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <description>Used in IVR scenarios to inform the message template.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPAN Inquiry</fullName>
            </value>
            <value>
                <fullName>Supplier Inquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/fields/Survey_Invitation_Link__c.field-meta.xml
<CustomField>
    <fullName>Survey_Invitation_Link__c</fullName>
    <label>Survey Invitation Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Sms__c/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/SPEN_SurveySetting__mdt/SPEN_SurveySetting__mdt.object-meta.xml
<CustomObject>
    <description>CRMD-10382</description>
    <label>Survey Setting</label>
    <pluralLabel>Survey Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SPEN_SurveySetting__mdt/fields/SPEN_Active__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_SurveySetting__mdt/fields/SPEN_CaseOrigin__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CaseOrigin__c</fullName>
    <label>Case Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Phone</fullName>
                <default>true</default>
                <label>Phone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_SurveySetting__mdt/fields/SPEN_Proactive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Proactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be used for Incident related surveys where customeres were proactively contacted in prior messaging tasks</description>
    <inlineHelpText>To be used for Incident related surveys where customeres were proactively contacted in prior messaging tasks</inlineHelpText>
    <label>Proactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_SurveySetting__mdt/fields/SPEN_SurveyChannel__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SurveyChannel__c</fullName>
    <description>Channel used to send the survey</description>
    <inlineHelpText>Channel used to send the survey</inlineHelpText>
    <label>Survey Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Voice Alert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_SurveySetting__mdt/fields/SPEN_SurveyName__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SurveyName__c</fullName>
    <description>API name of the survey</description>
    <inlineHelpText>API name of the survey</inlineHelpText>
    <label>Survey Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_SurveySetting__mdt/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Connections Delivery</fullName>
                <default>true</default>
                <label>Connections Delivery</label>
            </value>
            <value>
                <fullName>Connections Quotation</fullName>
            </value>
            <value>
                <fullName>Faults</fullName>
            </value>
            <value>
                <fullName>General Enquiries</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Single Premise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/SPEN_VoiceAlert__c.object-meta.xml
<CustomObject>
    <label>Voice Alert</label>
    <nameField>
        <label>Voice Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voice Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_CalledInTelephone__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CalledInTelephone__c</fullName>
    <label>Called In Telephone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_Case__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CRMD-5392</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Voice Alerts</relationshipLabel>
    <relationshipName>Voice_Alerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_ContactId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Voice Alerts</relationshipLabel>
    <relationshipName>SPEN_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <label>Event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Voice Alerts</relationshipLabel>
    <relationshipName>SPEN_VoiceAlertIncident</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_IsProactive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IsProactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Proactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Various status for voice alert</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_SurveyInvitation__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SurveyInvitation__c</fullName>
    <label>Survey Invitation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SPEN_SurveyUtility.cls
public class SPEN_SurveyUtility {
    public static SurveyInvitation createSurveyInvitation(String communityId, String surveyId, String name, String channel, String type, boolean anonymousresponse, boolean guestUserResponse, Id caseId, Id incidentId, Id participantId, DateTime expirationDate) {
        SurveyInvitation sInv = new SurveyInvitation();
        sInv.CommunityId = communityId;
        sInv.Name = 'SI-' + name;
        sInv.SPEN_SurveyChannel__c = channel;
        sInv.SPEN_Type__c = type;
        sInv.OptionsCollectAnonymousResponse = false;
        sInv.OptionsAllowGuestUserResponse = true;
        sInv.SurveyId = surveyId;
        sInv.SPEN_Case__c = caseId;
        sInv.SPEN_Incident__c = incidentId;
        sInv.ParticipantId = participantId;
        return sInv;
    }
    public static List<SurveySubject> createSurveySubject(List<SurveyInvitation> sInvList){
        List<SurveySubject> sSubList = new List<SurveySubject>();
        //Create survey subject records
        for(SurveyInvitation sInv : sInvList){
            SurveySubject SS = new SurveySubject();
            SS.SubjectId = sInv.ParticipantId;
            SS.Name = 'SS' + sInv.Name;
            SS.ParentId = SInv.Id;
            system.debug(sInv.InvitationLink);
            sSubList.add(SS);		
        }
        return sSubList;
    }
    public static Map<String, Id> getSurveyIDs(List<String> surveyNames){
        Map<String, Id> surveyNameIdMap = new Map<String, Id>();
        if(!Test.isRunningTest())
        {
        	for(Survey surveyrec : [Select Id, Name, DeveloperName from Survey where Name in :surveyNames or  DeveloperName in :surveyNames ]){
            	surveyNameIdMap.put(surveyrec.Name, surveyrec.Id);
            	surveyNameIdMap.put(surveyrec.DeveloperName, surveyrec.Id);
        	}
        }
        else{
            surveyNameIdMap.put('surveyName', null);
            surveyNameIdMap.put('surveyDeveloperName', null);
        }
        return surveyNameIdMap;
        
    }
	public static OrgWideEmailAddress getSurveyOrgWideAddress(){
		//List<OrgWideEmailAddress> oweaList = new OrgWideEmailAddress();
        return [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress WHERE Address like '%survey%'];
	}
    
    public static void updateVoiceAlertWithInvitation(Set<Id> voiceAlertIds, String surveyType){
        try
        {
            Map<Id, SPEN_VoiceAlert__c> voiceAlertMap = new Map<Id, SPEN_VoiceAlert__c> ();
            for(SPEN_VoiceAlert__c va : [SELECT Id, Name, SPEN_IncidentId__c, SPEN_ContactId__c, SPEN_CalledInTelephone__c, SPEN_Event__c, SPEN_IsProactive__c, SPEN_Case__c FROM SPEN_VoiceAlert__c WHERE ID IN :voiceAlertIDs]){
                voiceAlertMap.put(va.Id, va);
            }
            if(!voiceAlertMap.isEmpty()){
                Map<Id,String> contactSurveyIdMap = new Map<Id, String>();
                Set<Id> sInvSet = new Set<Id>();
                String key;
                Map<String, String> surveySettingMap = new Map<String, String>();
                
                //Get Custom Metadata
                for(SPEN_SurveySetting__mdt surveySetting : [SELECT Id, SPEN_Active__c, SPEN_CaseOrigin__c, SPEN_Proactive__c, SPEN_SurveyChannel__c, SPEN_SurveyName__c, SPEN_Type__c FROM SPEN_SurveySetting__mdt WHERE SPEN_SurveyChannel__c = 'Voice Alert' and SPEN_Active__c = true]){
                    
                    if(surveyType.equalsIgnoreCase('Faults') && surveySetting.SPEN_Type__c.equalsIgnoreCase('Faults')){
                        if(surveySetting.SPEN_Proactive__c){
                            key = surveySetting.SPEN_Type__c + '|' + surveySetting.SPEN_Proactive__c;			 
                        }
                        else{
                            key = surveySetting.SPEN_Type__c + '|' + surveySetting.SPEN_Proactive__c;
                        }
                        surveySettingMap.put(key,surveySetting.SPEN_SurveyName__c);
                    } else if(surveyType.equalsIgnoreCase('Single Premise') && surveySetting.SPEN_Type__c.equalsIgnoreCase('Single Premise')){
                        key = surveySetting.SPEN_Type__c;
                        surveySettingMap.put(key,surveySetting.SPEN_SurveyName__c);
                    }
                    else if(surveyType.equalsIgnoreCase('General Enquiries') && surveySetting.SPEN_Type__c.equalsIgnoreCase('General Enquiries')){
                        key = surveySetting.SPEN_Type__c;
                        surveySettingMap.put(key,surveySetting.SPEN_SurveyName__c);
                    }	
                }
                system.debug('surveySettingMap>>'+surveySettingMap);
                //Run Survey Invitation Logic only if Surveys available
                if(!surveySettingMap.isEmpty()){
                    List<SurveyInvitation> sInvList = new List<SurveyInvitation>();
                    List<SurveySubject> sSubList = new List<SurveySubject>();	
                    Map<String,Id> surveyNameIdMap = new Map<String,Id>();
                    
                    //Get survey ids against surveys
                    surveyNameIdMap = getSurveyIDs(surveySettingMap.values());
                    system.debug('surveyNameIdMap>>'+surveyNameIdMap);
                    
                    if(!surveyNameIdMap.isEmpty()){
                        
                        List<Network> communityId = new List<Network>([select Id from Network where Name = :System.Label.SPEN_SurveyCommunityName]);
                        
                        //Survey Surveyrec = [Select Id,Name from Survey where Name = 'SPEN Survey Example'];
                        system.debug('communityId>>'+communityId);    
                        
                        //Create SurveyInvitation records
                        for(SPEN_VoiceAlert__c va : voiceAlertMap.values() ){
                            Id surveyId;
                            if(surveyType.equalsIgnoreCase('Faults')){
                                if(va.SPEN_IsProactive__c && surveySettingMap.containsKey('Faults|true')){
                                    surveyId = surveyNameIdMap.get(surveySettingMap.get('Faults|true'));
                                }
                                else if(!va.SPEN_IsProactive__c && surveySettingMap.containsKey('Faults|false')){
                                    surveyId = surveyNameIdMap.get(surveySettingMap.get('Faults|false'));
                                }
                            }
                            else if(surveyType.equalsIgnoreCase('Single Premise')){
                                surveyId = surveyNameIdMap.get(surveySettingMap.get('Single Premise')); 
                            }
                            else if(surveyType.equalsIgnoreCase('General Enquiries')){
                                surveyId = surveyNameIdMap.get(surveySettingMap.get('General Enquiries')); 
                            }         
                            
                            system.debug('surveyId>>'+surveyId); 
                            if(surveyId != null){
                                SurveyInvitation SInv = SPEN_SurveyUtility.createSurveyInvitation(communityId[0].id,surveyId,va.Name,'Voice Alert',surveyType, false, false,va.SPEN_Case__c, va.SPEN_IncidentId__c, va.SPEN_ContactId__c, null);				
                                sInvList.add(SInv);
                            }			
                        }
                        system.debug('sInvList>>'+sInvList);
                        
                        if(!sInvList.isEmpty()){
                            insert sInvList;
                            for(SurveyInvitation sInv : sInvList){
                                sInvSet.add(sInv.id);           
                            }
                            //Create survey subject records
                            for(SurveyInvitation sInv : [Select id, Name, InvitationLink, ParticipantId from surveyInvitation where id in :sInvSet]){
                                SurveySubject SS = new SurveySubject();
                                SS.SubjectId = sInv.ParticipantId;
                                SS.Name = 'SS' + sInv.Name;
                                SS.ParentId = SInv.Id;
                                system.debug(sInv.InvitationLink);
                                contactSurveyIdMap.put(sInv.ParticipantId, sInv.id);
                                sSubList.add(SS);		
                            }
                            system.debug('sSubList>>' + sSubList);
                            insert sSubList;
                        }
                    }
                    //Update VA record with Survey Invitation Link and Status
                    for(SPEN_VoiceAlert__c va : voiceAlertMap.values()){
                        String sInvLink;
                        if(contactSurveyIdMap.containsKey(va.SPEN_ContactId__c)){
                            sInvLink = contactSurveyIdMap.get(va.SPEN_ContactId__c);
                            va.SPEN_SurveyInvitation__c = sInvLink;
                        }                               
                    }
                    system.debug('voiceAlertMap>>'+voiceAlertMap);
                    update voiceAlertMap.values();
                }
            }
        }
        
        catch(Exception ex){
            SEL_LoggingService.log(ex);
            throw ex;
        }    
    }
    
    //Added by Govind 
    public static String getshortenURL(String uuId){
        String dumyUid;
        String shortenURL;
        String communityUrl;
        
        List<Domain> dnsName = [SELECT Id,HttpsOption,  Domain, DomainType FROM Domain where HttpsOption ='CommunityAlt'];
        List<Network> netwrokURL = [SELECT Name, UrlPathPrefix FROM Network where Name = :System.Label.SPEN_SurveyCommunityName];
        /*List<SurveyInvitation> sInvitation = [SELECT Id, InvitationLink, Name, UUID FROM SurveyInvitation WHERE UUID=:uuId];
        dumyUid=sInvitation.UUID;*/
        
        shortenURL = 'https:/'+ '/' + dnsName[0].Domain + '/'+ netwrokURL[0].UrlPathPrefix +'?uuid=' + uuId;
        system.debug('shortenURL==>' + shortenURL);
        return shortenURL;
        
    }
    
    public static void updateSMSWithInvitation(Set<Id> smsIdSet, String surveyType){
        String key; //Format : Type|Proactive, when case origin is included in future - update to Type|Proactive|Case Origin
        Map<String, String> surveySettingMap = new Map<String, String>();
        Map<Id,SPEN_SMS__c> smsMap = new Map <Id,SPEN_SMS__c> ([SELECT Id, Name, SPEN_IncidentId__c, SPEN_ContactId__c, SPEN_Message__c, SPEN_IsProactive__c, SPEN_CaseId__c FROM SPEN_SMS__c where id in :smsIdSet and SPEN_Status__c = 'Created']);
        try{      	
            for(SPEN_SurveySetting__mdt surveySetting : [SELECT Id, SPEN_Active__c, SPEN_CaseOrigin__c, SPEN_Proactive__c, SPEN_SurveyChannel__c, SPEN_SurveyName__c, SPEN_Type__c FROM SPEN_SurveySetting__mdt WHERE  SPEN_SurveyChannel__c = 'SMS' and SPEN_Active__c = true]){
                
                if(surveyType.equalsIgnoreCase('Faults') && surveySetting.SPEN_Type__c.equalsIgnoreCase('Faults'))
                {
                    if(surveySetting.SPEN_Proactive__c){
                        key = surveySetting.SPEN_Type__c + '|' + surveySetting.SPEN_Proactive__c;			 
                    }
                    else{
                        key = surveySetting.SPEN_Type__c + '|' + surveySetting.SPEN_Proactive__c;
                    }
                    surveySettingMap.put(key,surveySetting.SPEN_SurveyName__c);
                } 
                else if(surveyType.equalsIgnoreCase('Single Premise') && surveySetting.SPEN_Type__c.equalsIgnoreCase('Single Premise'))
                {
                    key = surveySetting.SPEN_Type__c;
                    surveySettingMap.put(key,surveySetting.SPEN_SurveyName__c);
                }
                else if(surveyType.equalsIgnoreCase('General Enquiries') && surveySetting.SPEN_Type__c.equalsIgnoreCase('General Enquiries'))
                {
                    key = surveySetting.SPEN_Type__c;
                    surveySettingMap.put(key,surveySetting.SPEN_SurveyName__c);
                }
                
            }
            system.debug('surveySettingMap>>'+surveySettingMap);
            
            if(!surveySettingMap.isEmpty()){
                Map<Id,String> contactSurveyLinkMap = new Map<Id, String>();
                Map<id,String> uiMap=new Map<id,String>();
                List<SurveyInvitation> sInvList = new List<SurveyInvitation>();
                List<SurveySubject> sSubList = new List<SurveySubject>();	
                Map<String,Id> surveyNameIdMap = new Map<String,Id>();
                String uuid;
                Id surveyId;
                SPEN_IVRMessageSelector ivrSel = new SPEN_IVRMessageSelector();
                SPEN_IVRMessage__c faultSPIntroMsg = ivrSel.selectByExternalId('SMS – Faults and SP – Survey Intro');
                String surveyIntroMsg = '';
                
                //Get survey ids against surveys
                surveyNameIdMap = getSurveyIDs(surveySettingMap.values());
                system.debug('surveyNameIdMap>>'+surveyNameIdMap);
                
                if(!surveyNameIdMap.isEmpty()){
                    Set<Id> sInvSet = new Set<Id>();
                    List<Network> communityId = new List<Network>([select Id from Network where Name = :System.Label.SPEN_SurveyCommunityName]);
                    system.debug('communityId>>'+communityId);   
                    //Create SurveyInvitation records
                    for(SPEN_SMS__c sms : smsMap.values() ){
                        if(surveyType.equalsIgnoreCase('Faults')){
                            if(sms.SPEN_IsProactive__c && surveySettingMap.containsKey('Faults|true')){
                                surveyId = surveyNameIdMap.get(surveySettingMap.get('Faults|true')); 
                            }
                            else if(!sms.SPEN_IsProactive__c && surveySettingMap.containsKey('Faults|false')){
                                surveyId = surveyNameIdMap.get(surveySettingMap.get('Faults|false')); 
                            }
                            surveyIntroMsg = faultSPIntroMsg.SPEN_IVRMessage__c;
                        }
                        else if(surveyType.equalsIgnoreCase('Single Premise')){
                            surveyId = surveyNameIdMap.get(surveySettingMap.get('Single Premise')); 
                            surveyIntroMsg = faultSPIntroMsg.SPEN_IVRMessage__c;
                        }
                        else if(surveyType.equalsIgnoreCase('General Enquiries')){
                            surveyId = surveyNameIdMap.get(surveySettingMap.get('General Enquiries')); 
                        }
                        system.debug('surveyId>>'+surveyId); 
                        if(surveyId != null){
                            SurveyInvitation SInv = createSurveyInvitation(communityId[0].id,surveyId,sms.Name,'SMS',surveyType, false, false,sms.SPEN_CaseId__c, sms.SPEN_IncidentId__c, sms.SPEN_ContactId__c, null);				
                            sInvList.add(SInv);
                        }			
                    }
                    system.debug('sInvList>>'+sInvList);
                    
                    if(!sInvList.isEmpty()){
                        insert sInvList; 
                        for(SurveyInvitation sInv : sInvList){
                            sInvSet.add(sInv.id);     
                            
                        }
                        //Create survey subject records
                        for(SurveyInvitation sInv : [Select id, Name, InvitationLink,UUId, ParticipantId from surveyInvitation where id in :sInvSet]){
                            uiMap.put(sInv.ParticipantId,sInv.UUId);
                            System.debug('uuid'+uuid);
                            SurveySubject SS = new SurveySubject();
                            SS.SubjectId = sInv.ParticipantId;
                            SS.Name = 'SS' + sInv.Name;
                            SS.ParentId = SInv.Id;
                            system.debug(sInv.InvitationLink);
                            contactSurveyLinkMap.put(sInv.ParticipantId, sInv.InvitationLink);
                            sSubList.add(SS);		
                        }
                        system.debug('sSubList>>' + sSubList);
                        insert sSubList;
                    }
                }
                //Update SMS record with Survey Invitation Link and Status
                for(SPEN_SMS__c sms : smsMap.values()){
                    String sInvLink;
                    if(contactSurveyLinkMap.containsKey(sms.SPEN_ContactId__c)){
                        sInvLink=getshortenURL(uiMap.get(sms.SPEN_ContactId__c));
                        System.debug('sInvLink'+sInvLink);
                        sms.SPEN_Message__c = sms.SPEN_Message__c + '\n\n' + surveyIntroMsg + ' ' + sInvLink;
                        sms.Survey_Invitation_Link__c = sInvLink;
                    }
                    sms.SPEN_Status__c = 'Ready';
                    
                }
                system.debug('smsMap>>'+smsMap);
                update smsMap.values();
            }
        }
        catch(Exception ex){
            SEL_LoggingService.log(ex);
            throw ex;
        }		
        
    }
    
    public static void sendSurveyEmails(Map<Id,Id> caseContactMap, Map<Id,String> caseEmailMap, String surveyType)
    {
        String key;
        Map<String, String> surveySettingMap = new Map<String, String>();
        List<String> lstTemplate = new List<String>();
        try{
            for(SPEN_SurveySetting__mdt surveySetting : [SELECT Id, SPEN_Active__c, SPEN_CaseOrigin__c, SPEN_Proactive__c, SPEN_SurveyChannel__c, SPEN_SurveyName__c, SPEN_Type__c,SPEN_EmailTemplate__c FROM SPEN_SurveySetting__mdt WHERE  SPEN_SurveyChannel__c = 'Email' and SPEN_Active__c = true])
            {
                if(surveyType.equalsIgnoreCase('General Enquiries') && surveySetting.SPEN_Type__c.equalsIgnoreCase('General Enquiries'))
                {
                    key = surveySetting.SPEN_Type__c;
                    surveySettingMap.put(key,surveySetting.SPEN_SurveyName__c);
                    lstTemplate.add(surveySetting.SPEN_EmailTemplate__c);
                }     			
            }
            system.debug('surveySettingMap>>'+surveySettingMap);
            
            if(!surveySettingMap.isEmpty())
            {
                Map<Id,String> contactSurveyLinkMap = new Map<Id, String>();
                Map<id,String> uiMap=new Map<id,String>();
                List<SurveyInvitation> sInvList = new List<SurveyInvitation>();
                List<SurveySubject> sSubList = new List<SurveySubject>();	
                Map<String,Id> surveyNameIdMap = new Map<String,Id>();
                List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
                String uuid;
                Id surveyId;
                Messaging.SingleEmailMessage mail;
                String conId;
                
                //Get survey ids against surveys
                surveyNameIdMap = getSurveyIDs(surveySettingMap.values());
                system.debug('surveyNameIdMap>>'+surveyNameIdMap);
                
                if(!surveyNameIdMap.isEmpty())
                {
                    Set<Id> sInvSet = new Set<Id>();
                    List<Network> communityId = new List<Network>([select Id from Network where Name = :System.Label.SPEN_SurveyCommunityName]); 
                    system.debug('communityId>>'+communityId);   
                    
                    for(Id caseId : caseContactMap.keySet())
                    {
                        if(surveyType.equalsIgnoreCase('General Enquiries'))
                        {
                            surveyId = surveyNameIdMap.get(surveySettingMap.get('General Enquiries')); 
                        }
                        if(surveyId != null)
                        {
                            SurveyInvitation SInv = createSurveyInvitation(communityId[0].id,surveyId,caseId,'Email',surveyType, false, false,caseId, null, caseContactMap.get(caseId), null);				
                            sInvList.add(SInv);
                        }
                    }
                    
                    if(!sInvList.isEmpty())
                    {
                        insert sInvList; 
                        for(SurveyInvitation sInv : sInvList)
                        {
                            sInvSet.add(sInv.id);     
                        }
                        //Create survey subject records
                        for(SurveyInvitation sInv : [Select id, Name, InvitationLink,UUId, ParticipantId from surveyInvitation where id in :sInvSet])
                        {
                            // uiMap.put(sInv.ParticipantId,sInv.UUId);
                            // System.debug('uuid'+uuid);
                            SurveySubject SS = new SurveySubject();
                            SS.SubjectId = sInv.ParticipantId;
                            SS.Name = 'SS' + sInv.Name;
                            SS.ParentId = SInv.Id;
                            system.debug(sInv.InvitationLink);
                            contactSurveyLinkMap.put(sInv.ParticipantId, sInv.InvitationLink);
                            sSubList.add(SS);		
                        }
                        system.debug('sSubList>>' + sSubList);
                        insert sSubList;
                        
                        //get org wide email adderess
                        Id oweaId = getSurveyOrgWideAddress().id;
                        
                        EmailTemplate emailTemplate = [select Id,Name, Subject, HtmlValue, Body from EmailTemplate where Name In : lstTemplate];
                        for(Id caseId : caseContactMap.keyset())
                        {
                            mail = new Messaging.SingleEmailMessage();
                            conId = caseContactMap.get(caseId);
                            mail.setWhatId(caseId);
                            String htmlBody = emailTemplate.HtmlValue;
                            htmlBody = htmlBody.replace('[[SURVEY_INVITATION_URL]]', contactSurveyLinkMap.get(conId));
                            mail.settargetobjectid(conId);
                            mail.setToAddresses(new List<String>{caseEmailMap.get(caseId)});
                            mail.setOrgWideEmailAddressId(oweaId);
                            mail.setSubject(emailTemplate.Subject);
                            mail.setHtmlBody(htmlBody);
                            mail.setTreatBodiesAsTemplate(true);
                            mail.setTreatTargetObjectAsRecipient(false);
                            
                            emailList.add(mail);								
                        }
                        if(!emailList.isEmpty()){
                            Messaging.sendEmail(emailList);
                        }	
                    }				
                }
            }
        }
        catch(Exception ex){
            SEL_LoggingService.log(ex);
            throw ex;
        }
    }
}