force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <externalId>true</externalId>
    <inlineHelpText>This value must not be changed if IVR uses this message template.</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/recordTypes/Zone.recordType-meta.xml
<RecordType>
    <fullName>Zone</fullName>
    <active>true</active>
    <label>Zone</label>
</RecordType>

force-app/main/default/objects/SPEN_Zone__c/SPEN_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <label>IVR Message Temporary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_Parent__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Zone</relationshipLabel>
    <relationshipName>Zone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SPEN_UpdateZoneDataBatchTest.cls
/**
 * @description       : This class is called from SPEN_UpdateZoneDataController and it will update
 *                      the zone record based on externalId.
 * @author            : ramesh.c.singh@accenture.com
 * @group             : 
 * @last modified on  : 12-21-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
@SuppressWarnings('PMD.SOQLSelectorPattern')
public class SPEN_UpdateZoneDataBatchTest {
    @isTest 
    private static void updateZoneRecordsTest()
    {
        Id profileId = SPEN_TestDataFactory.getProfile(SPEN_TestDataFactoryConstants.PROFILENAME);
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        Database.insert(user); 
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'SPEN_Zone_CRU'];
		insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps.Id);
        System.runAs(user)
        { 
            Test.startTest();
            //Added for Assign IVR Message
            SPEN_IVRMessage__c testIVRMessage = SPEN_TestDataFactory.createIVRMessage(1);
            insert testIVRMessage;
			
            //Added for Assign IVR Message
            SPEN_Zone__c testRegion = SPEN_TestDataFactory.createZoneRegionRecords(testIVRMessage.Id);
            
            testRegion.SPEN_ExternalId__c = 'OZ03';
            insert testRegion;
            SPEN_Zone__c testDistrict = SPEN_TestDataFactory.createZoneDistrictRecords(testIVRMessage.Id);
            testDistrict.SPEN_Parent__c=testRegion.Id;
            testDistrict.SPEN_ExternalId__c = 'ZW11';
            insert testDistrict;
            SPEN_Zone__c testZone = SPEN_TestDataFactory.createZoneRecords(testIVRMessage.Id);
            testZone.SPEN_Parent__c = testDistrict.Id;
            testZone.SPEN_ExternalId__c = testRegion.Id;
            //insert testZone;
            List<SPEN_Zone__c> lstZone = new List<SPEN_Zone__c>();
            lstZone.add(testZone);
            Database.SaveResult []str = Database.insert(lstZone,false);
            Assert.areEqual(True, str[0].isSuccess());
            Map<String,String> mapZoneIdToZoneName = new Map<String,String>();
            mapZoneIdToZoneName.put(testZone.SPEN_ExternalId__c,testZone.SPEN_Parent__c);
            mapZoneIdToZoneName.put(testDistrict.SPEN_ExternalId__c,testDistrict.SPEN_Parent__c);
            mapZoneIdToZoneName.put(testRegion.SPEN_ExternalId__c,testRegion.SPEN_Parent__c);
            //SPEN_UpdateZoneDataBatch objBatch1 = new SPEN_UpdateZoneDataBatch();
            SPEN_UpdateZoneDataBatch objBatch = new SPEN_UpdateZoneDataBatch(mapZoneIdToZoneName);
            Database.executeBatch(objBatch);
                
            Test.stopTest(); 
        }
    }
    
}