force-app/main/default/objects/SPEN_IVRMessage__c/SPEN_IVRMessage__c.object-meta.xml
<CustomObject>
    <description>Holds all the message templates encompassing IVR, SMS, etc.</description>
    <label>Message Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <externalId>true</externalId>
    <inlineHelpText>This value must not be changed if IVR uses this message template.</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <description>This should be renamed to Message Template, as SMS, IVR, etc., all use this to store centrally managed messages.</description>
    <inlineHelpText>Message Template. Do not replace keywords enclosed with &lt;&lt; and &gt;&gt; for SMS templates as those are used by the application.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_IVRMessage__c/recordTypes/Zone.recordType-meta.xml
<RecordType>
    <fullName>Zone</fullName>
    <active>true</active>
    <label>Zone</label>
</RecordType>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <description>External Id field for any reference data</description>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseDistrict__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseDistrict__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>21.6.23: as aligned with Lauren in context of CRMD-430: this field is not in use at all in PROD (populated for 5 records only) --&gt; NO LONGER RELEVANT &amp; candidate for deletion.</description>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SPEN_Zone__c.SPEN_Type__c</field>
            <operation>equals</operation>
            <value>District</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Premises (District)</relationshipLabel>
    <relationshipName>Premises1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <description>Select type from dropdown list.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Unmetered Supply</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Generators- HV/LV</fullName>
                <isActive>false</isActive>
                <label>Generators- HV/LV</label>
            </value>
            <value>
                <fullName>Generators- Renewable</fullName>
                <isActive>false</isActive>
                <label>Generators- Renewable</label>
            </value>
            <value>
                <fullName>Generators- Traditional</fullName>
                <isActive>false</isActive>
                <label>Generators- Traditional</label>
            </value>
            <value>
                <fullName>Large Business</fullName>
                <isActive>false</isActive>
                <label>Large Business</label>
            </value>
            <value>
                <fullName>Small Business</fullName>
                <isActive>false</isActive>
                <label>Small Business</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_Zone__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SPEN_Zone__c.SPEN_Type__c</field>
            <operation>equals</operation>
            <value>Zone</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/SPEN_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_BroadcastMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BroadcastMessage__c</fullName>
    <label>IVR  Message Assigned</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_IVRMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessage__c</fullName>
    <label>IVR Message Temporary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_IVRMessageTemplate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IVRMessageTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IVR Message Template</label>
    <referenceTo>SPEN_IVRMessage__c</referenceTo>
    <relationshipLabel>Zone</relationshipLabel>
    <relationshipName>Zone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_OverwriteToChild__c.field-meta.xml
<CustomField>
    <fullName>SPEN_OverwriteToChild__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overwrite To Child</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_Parent__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>SPEN_Zone__c</referenceTo>
    <relationshipLabel>Zone</relationshipLabel>
    <relationshipName>Zone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_SPD_SPM__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SPD_SPM__c</fullName>
    <formula>IF
(
(
/* Expected under parent: AYRSHIRE */
(Name = &quot;Ayrshire &amp; Clyde South&quot; || Name = &quot;AYR CENTRAL&quot; || Name = &quot;AYR NORTH&quot; || Name = &quot;AYRSHIRE&quot;|| Name = &quot;AYR SOUTH&quot; || Name = &quot;CLYDE SOUTH&quot;) ||
/* Expected under parent: CENTRAL &amp; FIFE */
(Name = &quot;Central &amp; Fife&quot; || Name = &quot;CENTRAL &amp; FIFE&quot; || Name = &quot;BATHGATE&quot; || Name = &quot;CENTRAL&quot; || Name = &quot;FIFE EAST&quot; || Name = &quot;FIFE WEST&quot; || Name = &quot;STIRLING&quot;) ||
/* Expected under parent: DUMFRIES */
(Name = &quot;Dumfries&quot; || Name = &quot;DUMFRIES&quot; || Name = &quot;STEWARTRY&quot; || Name = &quot;WIGTOWNSHIRE&quot;) ||
/* Expected under parent: EDINBURGH &amp; BORDERS */
(Name = &quot;EDINBURGH &amp; LOTHIANS&quot; || Name =&quot;Edinburgh &amp; Borders&quot;|| Name = &quot;EDINBURGH&quot; || Name = &quot;LOTHIANS&quot; || Name = &quot;GALASHIELS&quot; || Name = &quot;BERWICK&quot;) ||
/* Expected under parent: GLASGOW */
(Name = &quot;Glasgow &amp; Clyde North&quot; || Name = &quot;GLASGOW &amp; CLYDE NORTH&quot; || Name = &quot;CLYDE NORTH&quot; || Name = &quot;CLYDE CENTRAL&quot; || Name = &quot;GLASGOW NORTH&quot; || Name = &quot;GLASGOW SOUTH&quot; || Name = &quot;CLYDE(CENTRAL)&quot; || Name = &quot;Glasgow&quot; || Name = &quot;GLASGOW&quot;) ||
/* Expected under parent: LANARKSHIRE */
(Name = &quot;Lanarkshire&quot; || Name = &quot;LANARKSHIRE&quot; || Name = &quot;LANARK CENTRAL&quot; || Name = &quot;LANARK NORTH&quot; || Name = &quot;LANARK SOUTH&quot; || Name = &quot;LANARK WEST&quot; || Name = &quot;LANARK(CENTRAL)&quot;) || (Name = &quot;UNKNOWN&quot; || Name = &quot;Unknown&quot;)
),
&quot;SPD&quot;,
IF
(
(
/* Expected under parent: DEE VALLEY / MID WALES */
(Name = &quot;Dee Valley, Mid Wales and Oswestry&quot;|| Name = &quot;Dee Valley, Oswestry &amp; Mid Wales&quot;|| Name = &quot;DeeValley &amp; Mid Wales&quot; || Name = &quot;DEE VALLEY NORTH&quot; || Name = &quot;DEE VALLEY SOUTH&quot; || Name = &quot;OSWESTRY NORTH&quot; || Name = &quot;OSWESTRY SOUTH&quot; || Name = &quot;ABERYSTWYTH NORTH&quot; || Name = &quot;ABERYSTWYTH SOUTH&quot; || Name = &quot;NEWTOWN&quot;) ||
/* Expected under parent: MERSEYSIDE */
(Name = &quot;LIVERPOOL NORTH&quot; || Name = &quot;LIVERPOOL SOUTH&quot; || Name = &quot;ST HELENS&quot;|| Name = &quot;Merseyside&quot;|| Name = &quot;MERSEYSIDE&quot; || Name = &quot;WIDNES&quot;) ||
/* Expected under parent: MID CHESHIRE */
(Name = &quot;MID CHESHIRE NORTH&quot; || Name = &quot;MID CHESHIRE SOUTH&quot; || Name = &quot;WARRINGTON&quot; || Name = &quot;Mid Cheshire&quot; || Name = &quot;MID CHESHIRE&quot;) ||
/* Expected under parent: NORTH WALES */
(Name = &quot;CLWYD EAST&quot; || Name = &quot;CLWYD WEST&quot; || Name = &quot;GWYNEDD ERYRI&quot; || Name = &quot;GWYNEDD MENAI&quot; || Name = &quot;North Wales&quot; || Name = &quot;Shropshire(DeeValley,Oswestry &amp; Mid Wales District)&quot;|| Name = &quot;Shropshire (DeeValley, Oswestry &amp; Mid Wales District)&quot;|| Name = &quot;Northumberland(Edinburgh District)&quot; || Name = &quot;Northumberland (Edinburgh District)&quot;) ||
/* Expected under parent: WIRRAL */
(Name = &quot;CHESTER&quot; || Name = &quot;ELLESMERE PORT&quot; || Name = &quot;NORTH WIRRAL&quot; || Name = &quot;RUNCORN&quot; || Name = &quot;Wirral&quot; || Name = &quot;WIRRAL&quot; )
),
&quot;SPM&quot;,
&quot;NO SPD/SPM MATCH&quot;
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SPD/SPM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>District</fullName>
            </value>
            <value>
                <fullName>Zone</fullName>
            </value>
            <value>
                <fullName>Town</fullName>
            </value>
            <value>
                <fullName>Blanket</fullName>
                <isActive>false</isActive>
                <label>Blanket</label>
            </value>
            <value>
                <fullName>World</fullName>
                <isActive>false</isActive>
                <label>World</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_ZoneSelector.cls
/*-----------------------------------------------------------------------------
DESCRIPTION :   Selector class of the SPEN_Zone__c Queries.
LIBRARY     :   Salesforce Enterprise Library - SPEN_Zone__c Queries
VERSION     :   1.0

HISTORY     :
Date            Author              Comment
NOV-23-2022     Smita Raikar        Initial version
-----------------------------------------------------------------------------*/
public inherited sharing class SPEN_ZoneSelector {
    /**************************************************
       @Author: Smita Raikar
       @Date: 23/11/22
       @purpose: Method to get zone details.
       ***************************************************/
       public static List<SPEN_Zone__c> getZoneRecords(SPEN_Premise__c premiseRcrd){
           List<SPEN_Zone__c> zoneList = new List<SPEN_Zone__c>();
           if(premiseRcrd!=null && premiseRcrd.Id!=null){
                zoneList = [SELECT Id, Name,SPEN_IVRMessage__c,SPEN_BroadcastMessage__c,SPEN_Type__c 
                                FROM SPEN_Zone__c 
                                WHERE Id IN (Select SPEN_Zone__c from SPEN_Premise__c where Id=:premiseRcrd.Id) 
                                AND SPEN_Type__c='Zone' WITH SECURITY_ENFORCED];
           }
           return zoneList;     
       }
       
       /**************************************************
       @Author: Smita Raikar
       @Date: 24/11/22
       @purpose: Method to district details.
       ***************************************************/
       public static List<SPEN_Zone__c> getDistrictRecords(SPEN_Premise__c premiseRcrd){
           List<SPEN_Zone__c> districtList = new List<SPEN_Zone__c>();
           if(premiseRcrd!= null && premiseRcrd.Id!=null){
                districtList = [SELECT Id, Name,SPEN_IVRMessage__c,SPEN_BroadcastMessage__c,SPEN_Type__c 
                                    FROM SPEN_Zone__c 
                                    WHERE Id IN (Select SPEN_PremiseDistrict__c from SPEN_Premise__c where Id=:premiseRcrd.Id)
                                    AND SPEN_Type__c='District' WITH SECURITY_ENFORCED];
                }
           return districtList;     
       }
       /**************************************************
       @Author: Smita Raikar
       @Date: 24/11/22
       @purpose: Method to region details.
       ***************************************************/
       public static List<SPEN_Zone__c> getRegionRecords(SPEN_Premise__c premiseRcrd){
           List<SPEN_Zone__c> regionList = new List<SPEN_Zone__c>();
           if(premiseRcrd!= null && premiseRcrd.Id!=null){
                regionList = [SELECT Id, Name,SPEN_IVRMessage__c,SPEN_BroadcastMessage__c,SPEN_Type__c 
                                FROM SPEN_Zone__c 
                                WHERE Id in (Select SPEN_Zone__c from SPEN_Premise__c where Id=:premiseRcrd.Id) 
                                and SPEN_Type__c='Region' WITH SECURITY_ENFORCED];      
           }
           return regionList;     
       }
       /**************************************************
       @Author: Smita Raikar
       @Date: 24/11/22
       @purpose: Method to region details.
       ***************************************************/
       public static SPEN_Zone__c getRegionRecord(){
           SPEN_Zone__c region = new SPEN_Zone__c();
              region = [Select Id,Name,SPEN_BroadcastMessage__c,SPEN_IVRMessage__c,SPEN_IVRMessageTemplate__c,SPEN_OverwriteToChild__c,SPEN_Parent__c,SPEN_Type__c from SPEN_Zone__c where SPEN_Type__c='Region' WITH SECURITY_ENFORCED LIMIT 1];      
           return region;     
       }
       /**************************************************
       @Author: Smita Raikar
       @Date: 30/11/22
       @purpose: Method to district details.
       ***************************************************/
       public static List<SPEN_Zone__c> getDistrictDetails(Id regionId){
           List<SPEN_Zone__c> districtList = new List<SPEN_Zone__c>();
           if(regionId!= null ){
           districtList = [Select Id,Name,SPEN_BroadcastMessage__c,SPEN_IVRMessage__c,SPEN_IVRMessageTemplate__c,SPEN_OverwriteToChild__c,SPEN_Parent__c,SPEN_Type__c from SPEN_Zone__c where SPEN_Type__c='District'  AND SPEN_Parent__c=:regionId WITH SECURITY_ENFORCED];
           }
           return districtList;     
       }
       /**************************************************
       @Author: Smita Raikar
       @Date: 30/11/22
       @purpose: Method to get zone details.
       ***************************************************/
       public static List<SPEN_Zone__c> getZoneDetails(Id districtId){
           List<SPEN_Zone__c> zoneList = new List<SPEN_Zone__c>();
           if(districtId!= null ){
           zoneList = [Select Id,Name,SPEN_BroadcastMessage__c,SPEN_IVRMessage__c,SPEN_IVRMessageTemplate__c,SPEN_OverwriteToChild__c,SPEN_Parent__c,SPEN_Type__c from SPEN_Zone__c where SPEN_Type__c='Zone' AND SPEN_Parent__c=:districtId WITH SECURITY_ENFORCED];
           }
           return zoneList;     
       }
       /**************************************************
       @Author: Smita Raikar
       @Date: 31/01/23
       @purpose: Method to get zone details.
       @ModifiedBy: Debapriya Saha
       @ModifiedDate: 02.01.2023 (MM.DD.YYYY)
       ***************************************************/
       public static List<SPEN_Zone__c> getZoneRecordsByIds(Set<Id> zoneIds){
            List<SPEN_Zone__c> zoneLis=new List<SPEN_Zone__c>();
            if(zoneIds!=null && !zoneIds.isEmpty()){
                zoneLis= [Select Id,Name,SPEN_SPD_SPM__c from SPEN_Zone__c where ID IN :zoneIds WITH SECURITY_ENFORCED];
            } 
            return zoneLis;   
       }
           
       /**************************************************
       @Author: Bhagyashree Mandlik
       @Date: 31/01/23
       @purpose: Method to get ZoneTown details.
       ***************************************************/
       public static SPEN_Zone__c getZoneTownRecord(Id caseTownId){
           SPEN_Zone__c zoneList = new SPEN_Zone__c();
           
           if(caseTownId != null){
               zoneList =  [ SELECT  Id,Name,SPEN_BroadcastMessage__c,SPEN_IVRMessage__c,SPEN_IVRMessageTemplate__c,SPEN_Parent__c,SPEN_Type__c FROM SPEN_Zone__c WHERE Id=:caseTownId WITH SECURITY_ENFORCED];      
           }
           return zoneList;     
       }
       public static List<SPEN_Zone__c> getZoneRecordforInc (Set<String> incOperatingZone){
        List<SPEN_Zone__c> zoneList = new List<SPEN_Zone__c>();
        
        if(incOperatingZone != null && !incOperatingZone.isEmpty()){
            zoneList =  [SELECT Id,Name,SPEN_ExternalId__c,SPEN_Type__c FROM SPEN_Zone__c WHERE SPEN_ExternalId__c=:incOperatingZone WITH SECURITY_ENFORCED];      
        }
        return zoneList;     
    }
    //code below  to be moved in respective selector classes
    /**************************************************
     @Author: shubhi vijayvergia
     @Date: Jun-20-2023
     @purpose: Method to get child Zone
    ***************************************************/
    public static List<SPEN_Zone__c> getChildrenZone (List<Id> parentIdList, String type){
        List<SPEN_Zone__c> zoneList = new List<SPEN_Zone__c>();
        if(String.isNotBlank(type) && !parentIdList.isEmpty()){
            switch on type{
                when 'District'{
                    zoneList = [SELECT Id,Name,SPEN_BroadcastMessage__c,SPEN_IVRMessage__c,SPEN_IVRMessageTemplate__c,SPEN_OverwriteToChild__c,SPEN_Parent__c,SPEN_Type__c,SPEN_Parent__r.SPEN_Parent__c 
                                    FROM SPEN_Zone__c 
                                    WHERE (SPEN_Type__c=:type AND SPEN_Parent__c IN:parentIdList) OR (SPEN_Type__c='Zone' AND SPEN_Parent__r.SPEN_Parent__c IN:parentIdList)
                                    WITH SECURITY_ENFORCED];
                }
                when 'Zone'{
                    zoneList = [SELECT Id,Name,SPEN_BroadcastMessage__c,SPEN_IVRMessage__c,SPEN_IVRMessageTemplate__c,SPEN_OverwriteToChild__c,SPEN_Parent__c,SPEN_Type__c 
                                    FROM SPEN_Zone__c 
                                    WHERE SPEN_Type__c=:type AND SPEN_Parent__c IN:parentIdList
                                    WITH SECURITY_ENFORCED];
                }
            }
        }
        return zoneList;     
    }
   }