force-app/main/default/objects/SPEN_VoiceAlert__c/SPEN_VoiceAlert__c.object-meta.xml
<CustomObject>
    <label>Voice Alert</label>
    <nameField>
        <label>Voice Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voice Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_BroadcastMessage__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BroadcastMessage__c</fullName>
    <label>Broadcast Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_CalledInTelephone__c.field-meta.xml
<CustomField>
    <fullName>SPEN_CalledInTelephone__c</fullName>
    <label>Called In Telephone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_ContactId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Voice Alerts</relationshipLabel>
    <relationshipName>SPEN_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Voice Alerts</relationshipLabel>
    <relationshipName>SPEN_VoiceAlertIncident</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_VoiceAlert__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Various status for voice alert</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_VoiceAlertServiceBatch.cls
/*-----------------------------------------------------------------------------
DESCRIPTION :   Batch class to handle creation of voice alert in batch.
VERSION     :   1.0

HISTORY     :
Date            Author              Comment
DEC-01-2023     Shubhi Vijayvergia        Initial version
-----------------------------------------------------------------------------*/
public class SPEN_VoiceAlertServiceBatch implements Database.Batchable<sObject>,Database.RaisesPlatformEvents {
    List<Id> caseidList=new List<Id>();
    Id recordtypeId;
    String broadcastMessage;
    String status;
    public SPEN_VoiceAlertServiceBatch(List<Id> caseidList,String broadcastMessage, Id recordtypeId){
       this.caseidList=caseidList;
       this.broadcastMessage=broadcastMessage;
       this.recordtypeId=recordtypeId;
    }
    public Database.QueryLocator start (Database.BatchableContext bc)
    {
        return Database.getQueryLocator([select Id,SPEN_PreferredMethodofContact__c,SPEN_CallerTelephone__c,SPEN_Incident__c,ContactId
                                         from Case where Id in :caseidList]);
        
    }
    public void execute(Database.BatchableContext bc, List<Case> caseList)
    {
            List<SPEN_VoiceAlert__c> lstVoiceAlert = new List<SPEN_VoiceAlert__c>();
			for(Case c : caseList){
            if((c.SPEN_PreferredMethodofContact__c ==SPEN_ImpactedPremisesConstants.H_PREFEREDMETHODOFCONTACT && c.SPEN_CallerTelephone__c != null) || (c.SPEN_PreferredMethodofContact__c==null && c.SPEN_CallerTelephone__c != null))
            {
                SPEN_VoiceAlert__c objVoiceAlert = new SPEN_VoiceAlert__c();
                objVoiceAlert.SPEN_CalledInTelephone__c = c.SPEN_CallerTelephone__c;
                objVoiceAlert.SPEN_ContactId__c = c.ContactId;
                objVoiceAlert.RecordTypeId = recordtypeId;
                objVoiceAlert.SPEN_IncidentId__c =c.SPEN_Incident__c;
                objVoiceAlert.SPEN_BroadcastMessage__c = broadcastMessage;
                objVoiceAlert.SPEN_Status__c = SPEN_ImpactedPremisesConstants.SMSREADYSTATUS;
                lstVoiceAlert.add(objVoiceAlert);
            }
        }
        if(!lstVoiceAlert.isEmpty()){
            Database.SaveResult[] srList = Database.insert(lstVoiceAlert, false);
            SPEN_VoiceAlertService.isServiceCall(lstVoiceAlert);
        }

    }
    public void finish(Database.BatchableContext bc){
    }

}