force-app/main/default/objects/SPEN_MessagingTask__c/SPEN_MessagingTask__c.object-meta.xml
<CustomObject>
    <description>This object allows agents to set up and configure broadcast messaging via SMS, Voice Alerts, etc.</description>
    <label>Messaging Task</label>
    <nameField>
        <displayFormat>MST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messaging Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <description>Indicates what event triggered the creation of the Messaging Task record</description>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3-Hour Comfort Call</fullName>
            </value>
            <value>
                <fullName>3rd Call Received</fullName>
            </value>
            <value>
                <fullName>Dropped Supply with Notice</fullName>
            </value>
            <value>
                <fullName>Dropped Supply without Notice</fullName>
            </value>
            <value>
                <fullName>Estimated Restoration Time Extended</fullName>
            </value>
            <value>
                <fullName>Incident Created</fullName>
            </value>
            <value>
                <fullName>Incident Restored</fullName>
            </value>
            <value>
                <fullName>Resource Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Resource Dispatched</fullName>
            </value>
            <value>
                <fullName>On Demand</fullName>
            </value>
            <value>
                <fullName>HV proactive contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The incident record that created the Messaging Task</description>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Messaging Tasks</relationshipLabel>
    <relationshipName>SPEN_MessagingTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Shows the progress of the Message Task</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/recordTypes/Incident.recordType-meta.xml
<RecordType>
    <fullName>Incident</fullName>
    <active>true</active>
    <description>When the Messaging Task record is driven from an Incident event</description>
    <label>Incident</label>
</RecordType>

force-app/main/default/objects/SPEN_Zone__c/SPEN_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_Type__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>District</fullName>
            </value>
            <value>
                <fullName>Zone</fullName>
            </value>
            <value>
                <fullName>Town</fullName>
            </value>
            <value>
                <fullName>Blanket</fullName>
                <isActive>false</isActive>
                <label>Blanket</label>
            </value>
            <value>
                <fullName>World</fullName>
                <isActive>false</isActive>
                <label>World</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Zone__c/fields/SPEN_ZoneRegionFormula__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ZoneRegionFormula__c</fullName>
    <formula>IF( ISPICKVAL(SPEN_Type__c , &quot;Zone&quot;), SPEN_Parent__r.SPEN_Parent__r.Name ,&quot;NA&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zone Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SPEN_MessagingTaskService.cls
/**
* @Author : 		Accenture
* @Description : 	This class holds the service implemenation of messaging task funcitonality.
* @Version : 		1.0
*/
public class SPEN_MessagingTaskService {
	Public SPEN_MessagingTask__c messagingTaskReferrence;
    
    /**
    * @Description : 	This method takes responsibility of creating instance of SPEN_MessagingTask__c
    */
    //public String createMessagingTask(String event, String incident, String recordType, String owner, String status)
    public String createMessagingTask(String event, Id incident, Id recordType,Id owner, String status)
    {

        try{
        String queueName;
        Incident incRec=new Incident();
        Group msgTaskQueue= new Group(); 
        if(incident != Null){
            incRec= [SELECT Id, SPEN_ZoneRegionFormula__c FROM Incident WHERE Id =:incident];
        }
        If(incRec.SPEN_ZoneRegionFormula__c != Null && (incRec.SPEN_ZoneRegionFormula__c.containsIgnoreCase('North') || incRec.SPEN_ZoneRegionFormula__c.containsIgnoreCase('UNKNOWN'))){
            queueName='Messaging_Task_SPD';
        }
        else If(incRec.SPEN_ZoneRegionFormula__c != Null && incRec.SPEN_ZoneRegionFormula__c.containsIgnoreCase('South')){
            queueName='Messaging_Task_SPM';
        }
        if(queueName != Null){
        msgTaskQueue=[select id,CreatedBy.name from Group where Type ='Queue' and DeveloperName =:queueName];
        }
        messagingTaskReferrence = new SPEN_MessagingTask__c();
        messagingTaskReferrence.SPEN_Event__c = event;
        messagingTaskReferrence.SPEN_IncidentId__c = incident;
        messagingTaskReferrence.RecordTypeId = recordType;
        if(!Test.isRunningTest()){
        messagingTaskReferrence.OwnerId = msgTaskQueue.id;
        }
        messagingTaskReferrence.SPEN_Status__c = status;
        insert messagingTaskReferrence;
        return messagingTaskReferrence.id;
     }

    catch(Exception ex){
        SEL_LoggingService.log(ex);
        throw ex;
    }
	
    }

    public String createMessagingTaskIncCreated(String event, Id incident, Id recordType,String zoneDetail, String status)
    {
        try{
        String queueName;
        spen_zone__c zoneRegion =new spen_zone__c();
        //Incident incRec=new Incident(); 
        Group msgTaskQueue = new Group();
        if(zoneDetail != Null){
        zoneRegion=[select id,SPEN_ZoneRegionFormula__c from spen_zone__c where name =:zoneDetail and SPEN_Type__c ='Zone' limit 1];
        }
        //if(incident != Null){
        //incRec=[select Id,SPEN_ZoneRegionFormula__c from Incident where id=:incident];
        //}
        If(zoneRegion.SPEN_ZoneRegionFormula__c != Null && zoneRegion.SPEN_ZoneRegionFormula__c.containsIgnoreCase('North')){
            queueName='Messaging_Task_SPD';
        }
        else If(zoneRegion.SPEN_ZoneRegionFormula__c != Null && zoneRegion.SPEN_ZoneRegionFormula__c.containsIgnoreCase('South')){
            queueName='Messaging_Task_SPM';
        }

        if(queueName != Null){
        msgTaskQueue=[select id,CreatedBy.name from Group where Type ='Queue' and DeveloperName =:queueName];
        }
        messagingTaskReferrence = new SPEN_MessagingTask__c();
        messagingTaskReferrence.SPEN_Event__c = event;
        messagingTaskReferrence.SPEN_IncidentId__c = incident;
        messagingTaskReferrence.RecordTypeId = recordType;
        messagingTaskReferrence.OwnerId = msgTaskQueue.id;
        messagingTaskReferrence.SPEN_Status__c = status;
        insert messagingTaskReferrence;
        return messagingTaskReferrence.id;
    }
    catch(Exception ex){
        SEL_LoggingService.log(ex);
        throw ex;
    }
    }

}