force-app/main/default/objects/SPEN_MessagingTask__c/SPEN_MessagingTask__c.object-meta.xml
<CustomObject>
    <description>This object allows agents to set up and configure broadcast messaging via SMS, Voice Alerts, etc.</description>
    <label>Messaging Task</label>
    <nameField>
        <displayFormat>MST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messaging Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/Incident_Outage_Status__c.field-meta.xml
<CustomField>
    <fullName>Incident_Outage_Status__c</fullName>
    <label>Incident Outage Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_DroppedSupplyCheckbox__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DroppedSupplyCheckbox__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will get the value based on the conditions from apex triggers as backend field.</description>
    <label>DroppedSupplyCheckbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_Event__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Event__c</fullName>
    <description>Indicates what event triggered the creation of the Messaging Task record</description>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3-Hour Comfort Call</fullName>
            </value>
            <value>
                <fullName>3rd Call Received</fullName>
            </value>
            <value>
                <fullName>Dropped Supply with Notice</fullName>
            </value>
            <value>
                <fullName>Dropped Supply without Notice</fullName>
            </value>
            <value>
                <fullName>Estimated Restoration Time Extended</fullName>
            </value>
            <value>
                <fullName>Incident Created</fullName>
            </value>
            <value>
                <fullName>Incident Restored</fullName>
            </value>
            <value>
                <fullName>Resource Arrival On Site</fullName>
            </value>
            <value>
                <fullName>Resource Dispatched</fullName>
            </value>
            <value>
                <fullName>On Demand</fullName>
            </value>
            <value>
                <fullName>HV proactive contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_Incident_Outage_Flag__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Incident_Outage_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Incident Outage Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_IncidentId__c.field-meta.xml
<CustomField>
    <fullName>SPEN_IncidentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The incident record that created the Messaging Task</description>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Messaging Tasks</relationshipLabel>
    <relationshipName>SPEN_MessagingTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/fields/SPEN_Status__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Status__c</fullName>
    <description>Shows the progress of the Message Task</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_MessagingTask__c/recordTypes/Incident.recordType-meta.xml
<RecordType>
    <fullName>Incident</fullName>
    <active>true</active>
    <description>When the Messaging Task record is driven from an Incident event</description>
    <label>Incident</label>
</RecordType>

force-app/main/default/objects/SPEN_MessagingTask__c/recordTypes/OnDemand.recordType-meta.xml
<RecordType>
    <fullName>OnDemand</fullName>
    <active>true</active>
    <description>To be used to upload CSV and send communication</description>
    <label>OnDemand</label>
</RecordType>

force-app/main/default/classes/SPEN_MessagingTaskHandler.cls
/*-----------------------------------------------------------------------------------------
DESCRIPTION  :  CRMD-9211:Completed messaging tasks toggles are changing dependent on future outage state changes.
AUTHOR    :  Patan Shabbir Ali Khan
LIBRARY    :  Salesforce Enterprise Library 
VERSION    :  1.0

HISTORY    :
Date      		Author      	            Comment
21-11-2023    Patan Shabbir Ali Khan     Initial version
-----------------------------------------------------------------------------------------*/
public with sharing class SPEN_MessagingTaskHandler {
    public static void onBeforeInsert(List<SPEN_MessagingTask__c> newMessagingrecords){
        Set<Id> incidentIds = new Set<Id>();
        System.debug('OnBefore MessagigTask');
       // SPEN_Incident_Outage_Flag__c
       for(SPEN_MessagingTask__c mTask : newMessagingrecords){
            if(mTask.SPEN_IncidentId__c != null){
                incidentIds.add(mTask.SPEN_IncidentId__c);
            }
        }
        if(!incidentIds.isEmpty()){
            List<Incident> incList = [SELECT SPEN_Outage_State__c,SPEN_droppedsupply__c FROM Incident WHERE Id=: incidentIds WITH SECURITY_ENFORCED];
            if(incList.size() > 0){
                for(SPEN_MessagingTask__c mTask : newMessagingrecords){
                    if(incList[0].SPEN_Outage_State__c != null){
                        mTask.SPEN_Incident_Outage_Flag__c = true;
                        mTask.Incident_Outage_Status__c = incList[0].SPEN_Outage_State__c;
                    }
                     mTask.SPEN_DroppedSupplyCheckbox__c = incList[0].SPEN_droppedsupply__c;
                }
            }
        }

    }

    public static void onBeforeUpdate(List<SPEN_MessagingTask__c> newMessagingrecords){
        Map<String, List<String>> statusMap = new Map<String,List<String>>{'Completed'=> new List<String>{'New', 'In Progress', 'Cancelled'},'Cancelled'=> new List<String>{'New', 'In Progress', 'Completed'}};
        for(SPEN_MessagingTask__c mTask : newMessagingrecords){
            if(mTask.SPEN_Event__c == SPEN_ConstantData.ONDEMAND){
                SPEN_MessagingTask__c oldData= (SPEN_MessagingTask__c)Trigger.oldMap.get(mTask.Id);
                if(statusMap.get(oldData.SPEN_Status__c) != null){
                    if(mTask.SPEN_Status__c != oldData.SPEN_Status__c && statusMap.get(oldData.SPEN_Status__c).contains(mTask.SPEN_Status__c)) { //!SPEN_ConstantData.CHANGEDSTATUS.contains(oldData.SPEN_Status__c) && SPEN_ConstantData.CHANGEDSTATUS.contains(mTask.SPEN_Status__c)){
                        mTask.SPEN_Status__c.addError(SPEN_ConstantData.MESSAGINGTASKERRORMESSAGE);
                    }  
                }
            }
        }

    }
public static void onAfterInsert(List<SPEN_MessagingTask__c> newMessagingrecords){
        Id mTaskRecordTypeId = Schema.SObjectType.SPEN_MessagingTask__c.getRecordTypeInfosByName().get('Incident').getRecordTypeId();
            List<Incident> incidentTobeUpdated = new List<Incident>();
      		Set<Id> setOfIncidentIds = new Set<Id>();
            for(SPEN_MessagingTask__c msTask : newMessagingrecords){
                if(mTaskRecordTypeId == msTask.RecordTypeId){
                      setOfIncidentIds.add(msTask.SPEN_IncidentId__c);
                }
            }
         for(AggregateResult ar : [SELECT  SPEN_IncidentId__c, count(Id) totalCount  FROM SPEN_MessagingTask__c group by SPEN_IncidentId__c having SPEN_IncidentId__c IN :setOfIncidentIds])  {
      	  Incident inc = new Incident();
          inc.Id = String.valueOf(ar.get('SPEN_IncidentId__c'));
          inc.SPEN_TotalMessagingTaskPresent__c =  Integer.valueOf(ar.get('totalCount'));
          incidentTobeUpdated.add(inc);
      }
        if(!incidentTobeUpdated.isEmpty()){
            try{
                update incidentTobeUpdated;
            }
            catch(Exception ex){
                SEL_LoggingService.log(ex);
                throw ex;
       		 }
        }
    }
}