force-app/main/default/objects/SPEN_IVROperatinghours__c/SPEN_IVROperatinghours__c.object-meta.xml
<CustomObject>
    <description>IVR Operating hours object is operating on time based on start time and end time.</description>
    <label>IVR Operating hours</label>
    <nameField>
        <label>IVR Operating hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Operating hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_EndTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EndTime__c</fullName>
    <description>End time field will collect the ending time of IVR Operating hours</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isActive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isDaily__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isDaily__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDaily</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_RestrictEndDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RestrictEndDate__c</fullName>
    <label>Restrict End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_RestrictStartDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RestrictStartDate__c</fullName>
    <description>Restrict Start Date for Operating Hours</description>
    <label>Restrict Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_StartTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_StartTime__c</fullName>
    <description>Start time field will collect the starting time of IVR Operating hours</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/SPEN_IvrOperatingHoursSelector.cls
public with sharing class SPEN_IvrOperatingHoursSelector 
{   
    
    public static list<SPEN_IVROperatingHours__c> getIVROperatingHours(String iVRRecordTypename){
        list<SPEN_IVROperatingHours__c> listivr=new list<SPEN_IVROperatingHours__c>();       
        if(String.isNotBlank(iVRRecordTypename))  {
            try{
                listivr = [SELECT Id,SPEN_isActive__c, SPEN_isDaily__c,SPEN_StartTime__c, SPEN_EndTime__c,SPEN_RestrictStartDate__c, 
                            SPEN_RestrictEndDate__c FROM SPEN_IVROperatingHours__c
                            WHERE SPEN_isActive__c = true AND RecordType.Name = :iVRRecordTypename //WITH SECURITY_ENFORCED //201
                             limit 1];
            }catch(Exception e){
            	SEL_LoggingService.log(e);
        	}
        }
        return listivr;
    }
    //added by shubhi
    //usage in spen_ivroperatinghourshandler
    public static list<SPEN_IVROperatingHours__c> getIVROperatingHours(Set<Id> recidset,Set<Id> currentidset){
        list<SPEN_IVROperatingHours__c> listivr=new list<SPEN_IVROperatingHours__c>();       
        if(recidset!=null && currentidset!=null)  {
            listivr = [SELECT id,recordtypeid 
                FROM SPEN_IVROperatingHours__c
                WHERE recordtypeid IN :recidset and SPEN_isActive__c = TRUE and ID NOT IN :currentidset WITH SECURITY_ENFORCED];
        }
        return listivr;
    }
    //added by Sheker kulkacherla for remediation
    // usage: used in IncidentService and SPEN_BlockOutWindowPeriod Class
    public static SPEN_IVROperatingHours__c getIVROperatingHourTypeCheck(Id ivrRecordTypeId){
        SPEN_IVROperatingHours__c ivrTypeCheck = new SPEN_IVROperatingHours__c();
        try{
            if(ivrRecordTypeId != null) {
            ivrTypeCheck = [SELECT Id, Name,SPEN_StartTime__c,SPEN_EndTime__c, RecordTypeId
                        	FROM SPEN_IVROperatingHours__c
                    		WHERE SPEN_isActive__c = true AND RecordType.Id = :ivrRecordTypeId WITH SECURITY_ENFORCED LIMIT 1];
        	}
        }catch(Exception e){
            SEL_LoggingService.log(e);
        }
        return ivrTypeCheck;
    }
}