force-app/main/default/objects/SPEN_IVROperatinghours__c/SPEN_IVROperatinghours__c.object-meta.xml
<CustomObject>
    <description>IVR Operating hours object is operating on time based on start time and end time.</description>
    <label>IVR Operating hours</label>
    <nameField>
        <label>IVR Operating hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Operating hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_EndTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_EndTime__c</fullName>
    <description>End time field will collect the ending time of IVR Operating hours</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isActive__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_StartTime__c.field-meta.xml
<CustomField>
    <fullName>SPEN_StartTime__c</fullName>
    <description>Start time field will collect the starting time of IVR Operating hours</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/SPEN_BlockOutWindowPeriodClass.cls
public with sharing class SPEN_BlockOutWindowPeriodClass 
{
    public static Boolean checkBlackoutWindowPeriod(String typeCheck){
        Boolean result = false;
        if(String.isNotBlank(typeCheck)){
            Id recTypeIdOfBlackoutWindowRT = Schema.SObjectType.SPEN_IVROperatingHours__c.getRecordTypeInfosByName().get(typeCheck).getRecordTypeId();
            SPEN_IVROperatingHours__c lstIvrHour =SPEN_IvrOperatingHoursSelector.getIVROperatingHourTypeCheck(recTypeIdOfBlackoutWindowRT);
            //[select Id, Name,SPEN_StartTime__c,SPEN_EndTime__c, RecordTypeId from  SPEN_IVROperatingHours__c where RecordTypeId = :recTypeIdOfBlackoutWindowRT and SPEN_isActive__c = true WITH SECURITY_ENFORCED limit 1]; 
            if(lstIvrHour != null){
                result=SPEN_BlockOutWindowPeriodClass.findResult(lstIvrHour);
            }
        }
            return result;
    }
    public static Boolean findResult(SPEN_IVROperatingHours__c lstIvrHour){
        Boolean result = false;
        Boolean isStartTimegreater=lstIvrHour.SPEN_StartTime__c > lstIvrHour.SPEN_EndTime__c;
        Boolean isCurrentTimeFuture=System.now().time() < lstIvrHour.SPEN_StartTime__c && System.now().time() < lstIvrHour.SPEN_EndTime__c;
        Boolean isCurrentTimePast=System.now().time() > lstIvrHour.SPEN_StartTime__c && System.now().time() > lstIvrHour.SPEN_EndTime__c;
        if((lstIvrHour.SPEN_StartTime__c == null && lstIvrHour.SPEN_EndTime__c == null) 
            || (!isStartTimegreater && (isCurrentTimeFuture||isCurrentTimePast))
            || (isStartTimegreater && (System.now().time() < lstIvrHour.SPEN_StartTime__c && System.now().time() > lstIvrHour.SPEN_EndTime__c))){
            result = true;
        }
        return result;
    }

}