force-app/main/default/objects/SPEN_IVROperatinghours__c/SPEN_IVROperatinghours__c.object-meta.xml
<CustomObject>
    <description>IVR Operating hours object is operating on time based on start time and end time.</description>
    <label>IVR Operating hours</label>
    <nameField>
        <label>IVR Operating hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Operating hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_IVROperatinghours__c/fields/SPEN_isDaily__c.field-meta.xml
<CustomField>
    <fullName>SPEN_isDaily__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDaily</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SPEN_OutboundCommsCheckerService.cls
public with sharing class SPEN_OutboundCommsCheckerService {

    @AuraEnabled
    public static Boolean getCommHoursIfDaily(SPEN_IVROperatingHours__c recordIVR){
        try {
            Boolean sendVoiceAlert = false;
            if(recordIVR.SPEN_isDaily__c){
                List<SPEN_IVROperatingHours__c> sendDateAlert = SPEN_OutboundCommsCheckerSelector.getIfInRestricedDate(recordIVR.Id);
                if(sendDateAlert.size() > 0){
                    sendVoiceAlert = true;
                } else {
                    sendVoiceAlert = false;
                }
            } else{
                List<SPEN_IVROperatingHours__c> sendTimeAlert = SPEN_OutboundCommsCheckerSelector.getIfInStartEndTime(recordIVR.Id);
                if(sendTimeAlert.size() > 0){
                    sendVoiceAlert = true;
                } else {
                    sendVoiceAlert = false;
                }
            }
            return sendVoiceAlert;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}