force-app/main/default/objects/SPEN_TimeWriting__c/SPEN_TimeWriting__c.object-meta.xml
<CustomObject>
    <description>To log, capture and record the time spent across sub-processes and component tasks within MTM 2</description>
    <label>Time Writing</label>
    <nameField>
        <displayFormat>TW-{0000}</displayFormat>
        <label>Time Writing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Writing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_TimeWriting__c/fields/SPEN_HoursSpent__c.field-meta.xml
<CustomField>
    <fullName>SPEN_HoursSpent__c</fullName>
    <label>Hours Spent</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_TimeWriting__c/fields/SPEN_Role__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Department Manager</fullName>
            </value>
            <value>
                <fullName>Senior Member Of Staff</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
                <isActive>false</isActive>
                <label>Senior Management</label>
            </value>
            <value>
                <fullName>Standard</fullName>
                <isActive>false</isActive>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Support Staff</fullName>
                <isActive>false</isActive>
                <label>Support Staff</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_TimeWriting__c/fields/SPEN_Team__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Team__c</fullName>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System Design</fullName>
            </value>
            <value>
                <fullName>System Design Manager Approval</fullName>
            </value>
            <value>
                <fullName>Engineering Design</fullName>
            </value>
            <value>
                <fullName>Engineering Design Manager Approval</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Development Manager Approval</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Delivery Manager Approval</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Commercial Manager Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_TimeWriting__c/fields/SPEN_TotalCost__c.field-meta.xml
<CustomField>
    <fullName>SPEN_TotalCost__c</fullName>
    <label>Total Cost</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/SPEN_TransmissionApplicationFeeRules__c.object-meta.xml
<CustomObject>
    <description>This is an object to store the rules of calculating the Fixed Cumulative Application Fee Values. And provide the admin to edit the rules when necessary.</description>
    <label>Transmission Application Fee Rules</label>
    <nameField>
        <displayFormat>Rule-{0000}</displayFormat>
        <label>Rule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transmission Application Fee Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_DailyHours__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DailyHours__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>Daily Hours</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_DailyRate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_DailyRate__c</fullName>
    <description>This field is for Transmission Process.</description>
    <label>Daily Rate</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_Role__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Role__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Department manager</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Senior Member Of Staff</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Support Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_TransmissionApplicationFeeRules__c/fields/SPEN_Team__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Team__c</fullName>
    <description>This field is for Transmission Process</description>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System Design</fullName>
            </value>
            <value>
                <fullName>System Design Manager Approval</fullName>
            </value>
            <value>
                <fullName>Engineering Design</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Development Manager Approval</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Commercial Manager Approval</fullName>
            </value>
            <value>
                <fullName>Delivery Manager Approval</fullName>
            </value>
            <value>
                <fullName>Support Staff</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Offer Questions Time Spent</fullName>
            </value>
            <value>
                <fullName>Engineering Design Manager Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPEN_TimeWritingTriggerHandler.cls
/*-----------------------------------------------------------------------------
DESCRIPTION :   Handler class of the SPEN_TimeWriting__c Object Trigger.
LIBRARY     :   Salesforce Enterprise Library - Handler class of the SPEN_TimeWriting__c Object Trigger
VERSION     :   1.0

HISTORY     :
Date            Author              Comment
22-Sep-2023     Rohit Sharma        Initial version
-----------------------------------------------------------------------------*/
public with sharing class SPEN_TimeWritingTriggerHandler {
    
    public static void calculateTimeWritingFee(List<SPEN_TimeWriting__c> timeWritingList){
        try
        {
            List<SPEN_TransmissionApplicationFeeRules__c> transmissionApplicationVarFeeList=SPEN_TransmissionApplicationFeeSelector.getTransmissionApplicationFeeDetails('Variable');
            Decimal hourlyRate=0;
            for(SPEN_TimeWriting__c timeWritingInstance:timeWritingList)
            {
                hourlyRate=getDailyRatesByTeamAndRole(timeWritingInstance.SPEN_Team__c,timeWritingInstance.SPEN_Role__c,transmissionApplicationVarFeeList);
              //  system.debug('value of dailyRateis : '+hourlyRate);
                timeWritingInstance.SPEN_TotalCost__c=hourlyRate * timeWritingInstance.SPEN_HoursSpent__c;                
            }
        }catch(Exception ex){
            //System.debug('In class SPEN_TimeWritingTriggerHandler method calculateTimeWritingFee: exception block='+ex.getMessage());
            SEL_LoggingService.log(ex);
        }
		
	}
    public static Decimal getDailyRatesByTeamAndRole(String team, String role,List<SPEN_TransmissionApplicationFeeRules__c> transmissionApplicationVarFeeList)
    {
        Decimal rate=0;
        for(SPEN_TransmissionApplicationFeeRules__c transmissionApplicationFeeInstance : transmissionApplicationVarFeeList)
        {
            if((transmissionApplicationFeeInstance.SPEN_Team__c).equalsIgnoreCase(team) && (transmissionApplicationFeeInstance.SPEN_Role__c).equalsIgnoreCase(role))
            {
                rate=transmissionApplicationFeeInstance.SPEN_DailyRate__c/transmissionApplicationFeeInstance.SPEN_DailyHours__c;
                
            }
        }
        return rate;
    }
}