force-app/main/default/objects/SPEN_ContactPremise__c/SPEN_ContactPremise__c.object-meta.xml
<CustomObject>
    <label>Contact Premise</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Contact Premise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>Contact Premises</relationshipLabel>
    <relationshipName>Contact_Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_PremisePrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremisePrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, this contact is the primary contact the linked Premise</description>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_Role__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>PSR Contact</fullName>
                <label>PSR Contact (Primary)</label>
            </value>
            <value>
                <fullName>Alternative Contact</fullName>
            </value>
            <value>
                <fullName>Premise Owner</fullName>
            </value>
            <value>
                <fullName>PSR Contact (Alternative)</fullName>
            </value>
            <value>
                <fullName>Site Contact</fullName>
                <isActive>false</isActive>
                <label>Site Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Unique SPEN identifier for a premise</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/SPEN_PSR__c.object-meta.xml
<CustomObject>
    <description>PSR object has been set up to see all the PSR related information</description>
    <label>PSR</label>
    <nameField>
        <displayFormat>PSR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_ADQMLastSync__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ADQMLastSync__c</fullName>
    <description>Represents the last time the record is synchronized with ADQM.</description>
    <label>ADQM Last Sync</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Contact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_PSREffectiveFromDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PSREffectiveFromDate__c</fullName>
    <description>Date that the PSR category is effective from</description>
    <label>PSR Effective From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_PSREffectiveToDate__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PSREffectiveToDate__c</fullName>
    <description>Date that the PSR category is effective until</description>
    <label>PSR Effective To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_PSRVulnerabilityType__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PSRVulnerabilityType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PSR and Vulnerability Type</label>
    <referenceTo>SPEN_PSRVulnerabilityType__c</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSRVulnerabilityType__c/SPEN_PSRVulnerabilityType__c.object-meta.xml
<CustomObject>
    <description>PSR Type/Vulnerability Type object has been set up to store master data</description>
    <label>PSR and Vulnerability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSR and Vulnerability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SPEN_PSRTriggerHandler_Test.cls
@isTest
@SuppressWarnings('PMD.SOQLSelectorPattern')
public class SPEN_PSRTriggerHandler_Test {
	@testSetup static void setup() 
    {
        PermissionSetGroup devOpsPSGroup = SPEN_TestDataFactory.getPSGroup('SPEN_PersonaDevOpsUser');
        List<User> userList=new List<User>();
        User user = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        userList.add(user);
        User dataMigrationuser = SPEN_TestDataFactory.settestUser(SPEN_TestDataFactoryConstants.PROFILENAME);
        dataMigrationuser.FirstName='Data';
        dataMigrationuser.LastName='Migration';
		userList.add(dataMigrationuser);
        Database.insert(userList);
        if (devOpsPSGroup.Status != 'Updated') {
            Test.calculatePermissionSetGroup(devOpsPSGroup.Id);
        }
        PermissionSetAssignment devOpsAssign = new PermissionSetAssignment();
        devOpsAssign.AssigneeId = user.Id;
        devOpsAssign.PermissionSetGroupId = devOpsPSGroup.Id;
        insert devOpsAssign;
        PermissionSet ps1=SPEN_TestdataSelector.getPermissionSet('SPEN_AdqmDataMigrationBypass');
        insert new PermissionSetAssignment(AssigneeId = dataMigrationUser.id, PermissionSetId = ps1.Id);  
  		System.runAs(user)
        {   
            List<Account> accRec = SPEN_TestDataFactory.createAccounts('Test',SPEN_TestDataFactoryConstants.SINGLE_REC);
            insert accRec;
            Contact contact1= SPEN_TestDataFactory.createContacts(accRec[0].Id,1);
            contact1.SPEN_CustomerID__c = 'CustomerID1';
            contact1.LastName = 'White';
            insert contact1;
            
            Contact contact2= SPEN_TestDataFactory.createContacts(accRec[0].id,1);
            contact2.SPEN_CustomerID__c = 'CustomerID_2';
            contact2.LastName = 'WhiteNew';
            insert contact2;
            
            Contact contact3= SPEN_TestDataFactory.createContacts(accRec[0].Id,1);
            contact3.SPEN_CustomerID__c = 'CustomerID2';
            contact3.LastName = 'Mosby';
            insert contact3;
            
            
            List<SPEN_Premise__c> premiseList = SPEN_TestDataFactory.createListOfPremise(1);
            premiseList[0].SPEN_PremiseID__c = 'MyPremise';
            insert premiseList;
            
            List<SPEN_Premise__c> premiseList2 = SPEN_TestDataFactory.createListOfPremise(1);
            premiseList2[0].SPEN_PremiseID__c = 'MyPremise2';
            insert premiseList2;
            
            SPEN_ContactPremise__c cp = SPEN_TestDataFactory.createContactPremises(1,contact1.id,premiseList2[0].id);
            cp.SPEN_PremisePrimaryContact__c = true;
            cp.SPEN_Role__c = 'Customer';
            insert cp;
            List<SPEN_PSRVulnerabilityType__c> vulList = SPEN_TestDataFactory.createPSRVulnerabilityRecords();
            insert vulList;
            List<SPEN_PSR__c> psrList = SPEN_TestDataFactory.createPSRrecord(1);
            psrList[0].SPEN_PSREffectiveFromDate__c = System.today()-10;
            psrList[0].SPEN_PSREffectiveToDate__c = System.today()+15;
            psrList[0].SPEN_ADQMLastSync__c = System.today()-1;
            psrList[0].SPEN_Premise__c = premiseList[0].id;
            psrList[0].SPEN_Contact__c = contact1.id;
            psrList[0].SPEN_PSRVulnerabilityType__c = vulList[0].id;
            insert psrList;
            
            Assert.areEqual(cp.SPEN_Role__c,'Customer');
        }
    }
    @isTest
    public static void psrAfterUpdateTest(){
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);
		System.runAs(user)
        {
            Test.startTest();
        	Contact contact2 = [SELECT id FROM Contact WHERE LastName = 'Mosby' LIMIT 1];
            SPEN_Premise__c premise = [SELECT id FROM SPEN_Premise__c WHERE SPEN_PremiseID__c ='MyPremise' LIMIT 1]; 
            SPEN_PSRVulnerabilityType__c psrVulRec = [SELECT id FROM SPEN_PSRVulnerabilityType__c where id!=null LIMIT 1];
           
            SPEN_PSR__c psrRec = new SPEN_PSR__c();
            psrRec.SPEN_PSREffectiveFromDate__c = System.today()-10;
            psrRec.SPEN_PSREffectiveToDate__c = System.today()+15;
            psrRec.SPEN_ADQMLastSync__c = System.today()-1;
            psrRec.SPEN_Contact__c = contact2.id;
            psrRec.SPEN_PSRVulnerabilityType__c = psrVulRec.id;
            insert psrRec;
            try{
                psrRec.SPEN_Premise__c = premise.id;
                update psrRec;
                Assert.AreEqual(psrRec.SPEN_Contact__c,contact2.id);
            }catch(Exception e){
                Assert.isTrue(e!=null);
            }
            Test.stopTest();
        }
    }
    @isTest
    public static void psrAfterDeleteTest(){
        User user=SPEN_TestdataSelector.getuser(SPEN_TestDataFactoryConstants.FIRSTNAME);
        System.runAs(user)
        {
            Test.startTest();
            Contact contact2 = [SELECT id FROM Contact WHERE LastName = 'Mosby' LIMIT 1];
            SPEN_Premise__c premise = [SELECT id FROM SPEN_Premise__c WHERE SPEN_PremiseID__c ='MyPremise' LIMIT 1]; 
            SPEN_PSRVulnerabilityType__c psrVulRec = [SELECT id FROM SPEN_PSRVulnerabilityType__c where id!=null LIMIT 1];
            Map<Id,SPEN_PSR__c> psrNewMap = new Map<Id,SPEN_PSR__c>();
            Map<Id,SPEN_PSR__c> psrOldMap = new Map<Id,SPEN_PSR__c>();
            List<SPEN_PSR__c> psrList = new List<SPEN_PSR__c>();
            SPEN_PSR__c psrRec = new SPEN_PSR__c();
            psrRec.SPEN_PSREffectiveFromDate__c = System.today()-10;
            psrRec.SPEN_PSREffectiveToDate__c = System.today()+15;
            psrRec.SPEN_ADQMLastSync__c = System.today()-1;
            psrRec.SPEN_Contact__c = contact2.id;
            psrRec.SPEN_PSRVulnerabilityType__c = psrVulRec.id;
            insert psrRec;
            psrList.add(psrRec);
            SPEN_PSRTriggerHandler psrTH = new SPEN_PSRTriggerHandler();
            psrTH.beforeDelete(psrNewMap);
            psrTH.afterUndelete(psrNewMap);
            psrTH.beforeUpdate(psrNewMap,psrOldMap);
            
            try{
                delete psrRec;
                Assert.AreEqual(psrRec.SPEN_Contact__c,contact2.id);
            }catch(Exception e){
                Assert.isTrue(e!=null);
            }
            Test.stopTest();
        }
    }
}