force-app/main/default/objects/SPEN_ContactPremise__c/SPEN_ContactPremise__c.object-meta.xml
<CustomObject>
    <label>Contact Premise</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Contact Premise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_FullAddress__c.field-meta.xml
<CustomField>
    <fullName>SPEN_FullAddress__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>It will display full address field</description>
    <formula>SPEN_Premise__r.SPEN_FlatNumber__c &amp;&quot; &quot;&amp; SPEN_Premise__r.SPEN_BuildingNameNumber__c &amp;&quot; &quot;&amp; SPEN_Premise__r.SPEN_Street__c</formula>
    <label>FullAddress</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>Contact Premises</relationshipLabel>
    <relationshipName>Contact_Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_RelatedContact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelatedContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Premises</relationshipLabel>
    <relationshipName>Contact_Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_MPAN__c/SPEN_MPAN__c.object-meta.xml
<CustomObject>
    <description>MPAN object is used to see MPAN related data.</description>
    <label>MPAN/Meter</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>MPAN Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPAN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_MPAN__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>MPAN</relationshipLabel>
    <relationshipName>MPAN</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PostCodeMDM__c/SPEN_PostCodeMDM__c.object-meta.xml
<CustomObject>
    <description>CRMD-5815 : Object to store post codes and associated local authorities and LSOAs</description>
    <label>Post Code MDM</label>
    <nameField>
        <displayFormat>PC-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Code MDM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PostCodeMDM__c/fields/SPEN_LocalAuthority__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LocalAuthority__c</fullName>
    <description>CRMD-5815 : Stores Local Authority Code related to the post code</description>
    <inlineHelpText>Please enter the code</inlineHelpText>
    <label>Local Authority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SPEN_LocalAuthority</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_PostCodeMDM__c/fields/SPEN_LSOA__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LSOA__c</fullName>
    <description>CRMD-5815 : LSOA associated with Post Code</description>
    <label>LSOA</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_PostCodeMDM__c/fields/SPEN_PostCode__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PostCode__c</fullName>
    <description>CRMD-5815 : Stores post code</description>
    <externalId>true</externalId>
    <label>Post Code</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/Local_Authority__c.field-meta.xml
<CustomField>
    <fullName>Local_Authority__c</fullName>
    <description>CRMD-9191</description>
    <label>Local Authority</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_Button_Validation__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Button_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Button Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_ConsentToSharePSRGiven__c.field-meta.xml
<CustomField>
    <fullName>SPEN_ConsentToSharePSRGiven__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consent To Share PSR Given</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_FullAddress__c.field-meta.xml
<CustomField>
    <fullName>SPEN_FullAddress__c</fullName>
    <description>Flat Number + Building + Street + Area + Town + Post Code
(Combination of all other Premise Fields)</description>
    <formula>IF( NOT(ISBLANK(SPEN_PlotNumber__c)), SPEN_PlotNumber__c &amp;&quot; &quot;&amp; SPEN_FlatNumber__c &amp;&quot; &quot;&amp; SPEN_BuildingNameNumber__c &amp;&quot; &quot;&amp; SPEN_Street__c &amp;&quot; &quot; &amp;SPEN_Area__c &amp;&quot; &quot;&amp; SPEN_Town__c &amp;&quot; &quot;&amp; SPEN_PostCode__c, SPEN_FlatNumber__c &amp;&quot; &quot;&amp; SPEN_BuildingNameNumber__c &amp;&quot; &quot;&amp; SPEN_Street__c &amp;&quot; &quot; &amp;SPEN_Area__c &amp;&quot; &quot;&amp; SPEN_Town__c &amp;&quot; &quot;&amp; SPEN_PostCode__c)</formula>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_LocalAuthority__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LocalAuthority__c</fullName>
    <description>Pick your local authority.</description>
    <label>Local Authority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ayrshire Council</fullName>
            </value>
            <value>
                <fullName>Ceredigion (Nr Aber)</fullName>
            </value>
            <value>
                <fullName>Cheshire East/West/Chester</fullName>
            </value>
            <value>
                <fullName>Clackmannan Council</fullName>
            </value>
            <value>
                <fullName>Dumfries Council</fullName>
            </value>
            <value>
                <fullName>East Dunbartonshire Council</fullName>
            </value>
            <value>
                <fullName>East Lothian Council</fullName>
            </value>
            <value>
                <fullName>Edinburgh Council</fullName>
            </value>
            <value>
                <fullName>Falkirk Council</fullName>
            </value>
            <value>
                <fullName>Fife Council</fullName>
            </value>
            <value>
                <fullName>Glasgow City Council</fullName>
            </value>
            <value>
                <fullName>Halton</fullName>
            </value>
            <value>
                <fullName>Knowsley</fullName>
            </value>
            <value>
                <fullName>Liverpool City</fullName>
            </value>
            <value>
                <fullName>Midlothian Council</fullName>
            </value>
            <value>
                <fullName>North Lanarkshire Council</fullName>
            </value>
            <value>
                <fullName>NORTH WALES EAST HUB</fullName>
            </value>
            <value>
                <fullName>NORTH WALES WEST HUB</fullName>
            </value>
            <value>
                <fullName>Northumberland County Council</fullName>
            </value>
            <value>
                <fullName>Renfrewshire Council / West Dumbartonshire</fullName>
            </value>
            <value>
                <fullName>Scottish Borders Council</fullName>
            </value>
            <value>
                <fullName>Shropshire</fullName>
            </value>
            <value>
                <fullName>South Lanarkshire Council</fullName>
            </value>
            <value>
                <fullName>St Helens</fullName>
            </value>
            <value>
                <fullName>Stirling Council</fullName>
            </value>
            <value>
                <fullName>Warrington</fullName>
            </value>
            <value>
                <fullName>West Lothian</fullName>
            </value>
            <value>
                <fullName>Wirral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_LSOA__c.field-meta.xml
<CustomField>
    <fullName>SPEN_LSOA__c</fullName>
    <description>CRMD-9191 : Backend field</description>
    <label>LSOA</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_MPAN__c.field-meta.xml
<CustomField>
    <fullName>SPEN_MPAN__c</fullName>
    <description>A text box to capture MPAN number to be sent to ADQM.</description>
    <label>MPAN</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_NewArea__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NewArea__c</fullName>
    <label>New Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_NewFlatNumber__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NewFlatNumber__c</fullName>
    <label>New Flat number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_NewPostcode__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NewPostcode__c</fullName>
    <label>New Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_NewPremiseNumber__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NewPremiseNumber__c</fullName>
    <label>New Building Name/Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_NewStreet__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NewStreet__c</fullName>
    <label>New Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_NewTown__c.field-meta.xml
<CustomField>
    <fullName>SPEN_NewTown__c</fullName>
    <label>New Town</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PostCode__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PostCode__c</fullName>
    <description>It takes the premise postal code</description>
    <externalId>true</externalId>
    <label>Post Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/SPEN_LocalAuthority.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Argyll &amp; Bute</fullName>
    </customValue>
    <customValue>
        <fullName>Ceredigion</fullName>
    </customValue>
    <customValue>
        <fullName>Cheshire East</fullName>
    </customValue>
    <customValue>
        <fullName>Cheshire West &amp; Chester</fullName>
    </customValue>
    <customValue>
        <fullName>Clackmannanshire</fullName>
    </customValue>
    <customValue>
        <fullName>Conwy</fullName>
    </customValue>
    <customValue>
        <fullName>Cumbria</fullName>
    </customValue>
    <customValue>
        <fullName>Denbighshire</fullName>
    </customValue>
    <customValue>
        <fullName>Dumfries &amp; Galloway</fullName>
    </customValue>
    <customValue>
        <fullName>East Ayrshire</fullName>
    </customValue>
    <customValue>
        <fullName>East Dunbartonshire</fullName>
    </customValue>
    <customValue>
        <fullName>East Lothian</fullName>
    </customValue>
    <customValue>
        <fullName>East Renfrewshire</fullName>
    </customValue>
    <customValue>
        <fullName>Edinburgh City</fullName>
    </customValue>
    <customValue>
        <fullName>Falkirk</fullName>
    </customValue>
    <customValue>
        <fullName>Fife</fullName>
    </customValue>
    <customValue>
        <fullName>Flintshire</fullName>
    </customValue>
    <customValue>
        <fullName>Glasgow City</fullName>
    </customValue>
    <customValue>
        <fullName>Greater Manchester</fullName>
    </customValue>
    <customValue>
        <fullName>Gwynedd</fullName>
    </customValue>
    <customValue>
        <fullName>Halton</fullName>
    </customValue>
    <customValue>
        <fullName>Inverclyde</fullName>
    </customValue>
    <customValue>
        <fullName>Isle of Anglesey</fullName>
    </customValue>
    <customValue>
        <fullName>Knowsley</fullName>
    </customValue>
    <customValue>
        <fullName>Lancashire</fullName>
    </customValue>
    <customValue>
        <fullName>Lancaster</fullName>
    </customValue>
    <customValue>
        <fullName>Liverpool</fullName>
    </customValue>
    <customValue>
        <fullName>Midlothian</fullName>
    </customValue>
    <customValue>
        <fullName>North Ayrshire</fullName>
    </customValue>
    <customValue>
        <fullName>North Lanarkshire</fullName>
    </customValue>
    <description>CRMD- 5450 For Local Authority Values</description>
    <masterLabel>Local Authority</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Premises.cls
public with sharing class Premises 
{
    //CRMD-9191 Start
    public static void beforePremiseUpdate(Map<Id,sObject> premiseNewMap,Map<Id,sObject> premiseOldMap)
    {
         List<SPEN_Premise__c> premiseListNew = (List<SPEN_Premise__c>)premiseNewMap.values();
         Map<Id,SPEN_Premise__c> premiseListOld = (Map<Id,SPEN_Premise__c>)premiseOldMap;
        Set<String> PostCodeSet = new Set<String>();
        try
        {
            for(SPEN_Premise__c premise:premiseListNew)
            {
                if(premise.SPEN_PostCode__c != premiseListOld.get(premise.Id).SPEN_PostCode__c)
                {                    PostCodeSet.add(premise.SPEN_PostCode__c);
                }
            }
            List<SPEn_PostcodeMDM__c> postcodeMDMList = [SELECT Id, SPEN_PostCode__c, SPEN_LocalAuthority__c,SPEN_LSOA__c FROM SPEN_PostCodeMDM__c where SPEN_PostCode__c IN: PostCodeSet];
            Map<String,SPEn_PostcodeMDM__c> postcodeMDMMap = new Map<String,SPEn_PostcodeMDM__c> ();
            for(SPEn_PostcodeMDM__c postCode:postcodeMDMList)
            {
                postcodeMDMMap.put(postCode.SPEN_PostCode__c,postCode);
            }
             for(SPEN_Premise__c premise:premiseListNew)   
                {
                    if(!postcodeMDMMap.isEmpty())
                    {
                        SPEn_PostcodeMDM__c pcode = postcodeMDMMap.get(premise.SPEN_PostCode__c);
                        premise.Local_Authority__c = pcode.SPEN_LocalAuthority__c; 
premise.SPEN_LSOA__c = pcode.SPEN_LSOA__c;//CRMD-9191 feedback
                    }
                }
            
        }
        catch(exception e){
            SEL_LoggingService.log(e);
        }
    }
    
     public static void beforePremiseInsert(List<sObject> premiseNewList)
    {
        try
        {
            List<SPEN_Premise__c> premiseListNew = (List<SPEN_Premise__c>)premiseNewList;
            Set<String> PostCodeSet = new Set<String>();
            if(!premiseListNew.isEmpty())
            {
                
               
                for(SPEN_Premise__c premise:premiseListNew)   
                {
                    if(premise.SPEN_PostCode__c!=NULL)
                    {
                        PostCodeSet.add(premise.SPEN_PostCode__c);
                    }
                }
                List<SPEn_PostcodeMDM__c> postcodeMDMList = [SELECT Id, SPEN_PostCode__c, SPEN_LocalAuthority__c,SPEN_LSOA__c FROM SPEN_PostCodeMDM__c where SPEN_PostCode__c IN: PostCodeSet];
                Map<String,SPEn_PostcodeMDM__c> postcodeMDMMap = new Map<String,SPEn_PostcodeMDM__c> ();
                for(SPEn_PostcodeMDM__c postCode:postcodeMDMList)
                {
                    postcodeMDMMap.put(postCode.SPEN_PostCode__c,postCode);
                }
                for(SPEN_Premise__c premise:premiseListNew)   
                {
                    if(!postcodeMDMMap.isEmpty())
                    {
                        SPEn_PostcodeMDM__c pcode = postcodeMDMMap.get(premise.SPEN_PostCode__c);
                        premise.Local_Authority__c = pcode.SPEN_LocalAuthority__c; 
                        premise.SPEN_LSOA__c = pcode.SPEN_LSOA__c;//CRMD-9191 feedback
                    }
                }
            }
        }
        catch(exception e){
            SEL_LoggingService.log(e);
        }
    }
    //CRMD-9191 End
    public static void afterPremiseUpdate(Map<Id, sObject> premiseNewMap, Map<Id, sObject> premiseOldMap)
    {
        List<SPEN_Premise__c> premiseNewList = (List<SPEN_Premise__c>)premiseNewMap.values();
        Map<Id,SPEN_Premise__c> premiseOldMapData = (Map<Id,SPEN_Premise__c>)premiseOldMap;
        Map<Id,SPEN_Premise__c> premiseNewMapData = (Map<Id,SPEN_Premise__c>)premiseNewMap;
        Set<Id> premiseIds = new Set<Id> ();
        //formula limit - START
        Set<Id> premiseIdsForNonBypassCasesSet = new Set<Id>();
        //formula limit - END
        for(SPEN_Premise__c premRec : premiseNewList)
        {
            if(premRec.SPEN_ConsentToSharePSRGiven__c != premiseOldMapData.get(premRec.Id).SPEN_ConsentToSharePSRGiven__c)
            {
                premiseIds.add(premRec.Id);
            }
             //formula limit - START
            if(premRec.SPEN_FullAddress__c != premiseOldMapData.get(premRec.Id).SPEN_fullAddress__c)
            {
                premiseIdsForNonBypassCasesSet.add(premRec.Id);
            }
            
        }
        if(!premiseIdsForNonBypassCasesSet.isEMpty())
        {
            List<Case> caseToBeUpdatedList = new List<Case>();
            List<Case> csList = [Select Id,SPEN_addressPremise__c,SPEN_Bypass__c from Case where SPEN_addressPremise__c IN:premiseIdsForNonBypassCasesSet AND SPEN_Bypass__c = false]; // Check if 3pd record type is needed?
            for(Case cs:csList)
            {
                 SPEN_Premise__c premise = premiseNewMapData.get(cs.SPEn_addressPremise__c);
                 cs.SPEN_Bypass_FullAddress__c  = premise.SPEN_Fulladdress__c;
                
                caseToBeUpdatedList.add(cs);
            }
            update caseToBeUpdatedList;
        }
        //formula limit - END
        List<Contact> contactsTobeUpdated = new List<Contact>();
        if(!premiseIds.isEmpty())
        {
            for(SPEN_ContactPremise__c cpRec : SPEN_ContactPremisesSelector.getContactPremises(premiseIds))
            {
                Contact conRec = new Contact(Id = cpRec.SPEN_RelatedContact__c);
                conRec.SPEN_PSRSynctoADQM__c = true;
                contactsTobeUpdated.add(conRec);
            }
        }
        try{
            if(!contactsTobeUpdated.isEmpty())
            {
                update contactsTobeUpdated;
            }
        }
        catch(Exception ex)
        {
            SEL_LoggingService.log(ex);
            throw ex;
        }
        
    }
    public static void beforeInsert(List<SPEN_Premise__c> newrecords){
        for(SPEN_Premise__c currentRecord : newrecords){
            if(currentRecord.SPEN_MPAN__c != Null && (currentRecord.SPEN_NewFlatNumber__c != null || currentRecord.SPEN_NewArea__c != null || currentRecord.SPEN_NewTown__c != null || currentRecord.SPEN_NewPremiseNumber__c  != null || currentRecord.SPEN_NewStreet__c != null || currentRecord.SPEN_NewPostcode__c != null)){
                currentRecord.SPEN_Button_Validation__c = true;
            }
        }
    }
    public static void beforeUpdate(List<SPEN_Premise__c> newrecords){
        for(SPEN_Premise__c currentRecord : newrecords){
            SPEN_Premise__c oldData = (SPEN_Premise__c) Trigger.oldMap.get(currentRecord.Id);
            if(!currentRecord.SPEN_Button_Validation__c){
                if(currentRecord.SPEN_MPAN__c != Null && (currentRecord.SPEN_NewFlatNumber__c != oldData.SPEN_NewFlatNumber__c || currentRecord.SPEN_NewArea__c != oldData.SPEN_NewArea__c || currentRecord.SPEN_NewTown__c != oldData.SPEN_NewTown__c || currentRecord.SPEN_NewPremiseNumber__c  != oldData.SPEN_NewPremiseNumber__c || currentRecord.SPEN_NewStreet__c != oldData.SPEN_NewStreet__c || currentRecord.SPEN_NewPostcode__c != oldData.SPEN_NewPostcode__c )){
                    currentRecord.SPEN_Button_Validation__c = true;
                }
            }
            
        }
    }
}