force-app/main/default/objects/SPEN_ContactPremise__c/SPEN_ContactPremise__c.object-meta.xml
<CustomObject>
    <label>Contact Premise</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Contact Premise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>Contact Premises</relationshipLabel>
    <relationshipName>Contact_Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_PremisePrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremisePrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, this contact is the primary contact the linked Premise</description>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_RelatedContact__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelatedContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Premises</relationshipLabel>
    <relationshipName>Contact_Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_RelationshipWithPremise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_RelationshipWithPremise__c</fullName>
    <label>Relationship with Premise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Tenant</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Friends</fullName>
            </value>
            <value>
                <fullName>Neighbours</fullName>
            </value>
            <value>
                <fullName>Property Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_ContactPremise__c/fields/SPEN_Role__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>PSR Contact</fullName>
                <label>PSR Contact (Primary)</label>
            </value>
            <value>
                <fullName>Alternative Contact</fullName>
            </value>
            <value>
                <fullName>Premise Owner</fullName>
            </value>
            <value>
                <fullName>PSR Contact (Alternative)</fullName>
            </value>
            <value>
                <fullName>Site Contact</fullName>
                <isActive>false</isActive>
                <label>Site Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/SPEN_Premise__c.object-meta.xml
<CustomObject>
    <description>Premise object has been set up to see all the Premise related information</description>
    <label>Premise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_BuildingNameNumber__c.field-meta.xml
<CustomField>
    <fullName>SPEN_BuildingNameNumber__c</fullName>
    <externalId>true</externalId>
    <label>Building Name/Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_FlatNumber__c.field-meta.xml
<CustomField>
    <fullName>SPEN_FlatNumber__c</fullName>
    <description>It holds the premise flat number</description>
    <label>Flat Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PostCode__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PostCode__c</fullName>
    <description>It takes the premise postal code</description>
    <externalId>true</externalId>
    <label>Post Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPEN_Premise__c/fields/SPEN_PremiseID__c.field-meta.xml
<CustomField>
    <fullName>SPEN_PremiseID__c</fullName>
    <description>Unique SPEN identifier for a premise</description>
    <externalId>true</externalId>
    <label>Premise ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/SPEN_PSR__c.object-meta.xml
<CustomObject>
    <description>PSR object has been set up to see all the PSR related information</description>
    <label>PSR</label>
    <nameField>
        <displayFormat>PSR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_Premise__c.field-meta.xml
<CustomField>
    <fullName>SPEN_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>SPEN_Premise__c</referenceTo>
    <relationshipLabel>PSRs</relationshipLabel>
    <relationshipName>PSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPEN_PSR__c/fields/SPEN_SpecificVulnerability__c.field-meta.xml
<CustomField>
    <fullName>SPEN_SpecificVulnerability__c</fullName>
    <formula>If(AND(NOT(SPEN_PSREffectiveToDate__c  &lt;  TODAY()),NOT(ISBLANK(SPEN_PSREffectiveToDate__c  )), SPEN_PSRVulnerabilityType__r.SPEN_SpecificVulnerability__c) , true, if(AND(ISBLANK(SPEN_PSREffectiveToDate__c  ), SPEN_PSRVulnerabilityType__r.SPEN_SpecificVulnerability__c),true,false))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Specific Vulnerability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SPEN_ContactPremisesSelector.cls
/*-----------------------------------------------------------------------------
DESCRIPTION :   Selector class of the SPEN_ContactPremise__c Queries.
LIBRARY     :   Salesforce Enterprise Library - SPEN_ContactPremise__c Queries
VERSION     :   1.0

HISTORY     :
Date            Author              Comment
OCT-31-2022     Smita Raikar        Initial version
-----------------------------------------------------------------------------*/
public inherited sharing class SPEN_ContactPremisesSelector {
	/**************************************************
	   @Author: Smita Raikar
	   @Date: 31/10/22
	   @purpose: Method to get contact premise details.
	   ***************************************************/
        public static List<SPEN_ContactPremise__c> getPremiseContactInfo(Case caseRecord){
            List<SPEN_ContactPremise__c> conPremiseInfo = new List<SPEN_ContactPremise__c>();
            if(caseRecord != null){
                conPremiseInfo = [SELECT  Id,Name,SPEN_Premise__c,SPEN_RelatedContact__c,SPEN_RelationshipWithPremise__c,SPEN_Role__c,SPEN_Premise__r.SPEN_BuildingNameNumber__c
                                  FROM SPEN_ContactPremise__c
                                  WHERE SPEN_Premise__r.SPEN_PostCode__c=:caseRecord.SPEN_PostcodeW2C__c  AND
                                  (SPEN_Premise__r.SPEN_BuildingNameNumber__c =: caseRecord.SPEN_BuildingNumberW2C__c OR
                                   SPEN_Premise__r.SPEN_BuildingNameNumber__c =: caseRecord.SPEN_BuildingNameW2C__c OR 
                                   SPEN_Premise__r.SPEN_BuildingNameNumber__c =: caseRecord.SPEN_BuildingNameNumberW2C__c OR
                                  SPEN_Premise__r.SPEN_FlatNumber__c=:caseRecord.SPEN_FlatNumberW2C__c)
                                ];
               
            }
            return conPremiseInfo;     
        }
	   public static Map<String,String> getPremiseForContact(Set<Id> conIds)
	   {
		   Map<String,String> contactPremiseMap = new Map<String,String>();
		   for(SPEN_ContactPremise__c contactPremiseObj : [SELECT Id,Name,SPEN_Premise__r.SPEN_PremiseID__c,SPEN_RelatedContact__r.SPEN_CustomerID__c,SPEN_Premise__c,SPEN_RelatedContact__c,SPEN_RelationshipWithPremise__c FROM SPEN_ContactPremise__c WHERE SPEN_RelatedContact__c =:conIds]){
			   If(contactPremiseObj.SPEN_Premise__r.SPEN_PremiseID__c == contactPremiseObj.SPEN_RelatedContact__r.SPEN_CustomerID__c){
				   contactPremiseMap.put(contactPremiseObj.SPEN_RelatedContact__c,contactPremiseObj.SPEN_Premise__c);
			   }
															   
		   }
		   return contactPremiseMap;
	   }
	   public static List<SPEN_ContactPremise__c> getCPIsConPresentInfo(Id conId, Id premId){
		List<SPEN_ContactPremise__c> returnList = new List<SPEN_ContactPremise__c>();
			List<SPEN_ContactPremise__c> conP = [SELECT Id, SPEN_RelatedContact__c, SPEN_Premise__c, SPEN_PremisePrimaryContact__c FROM SPEN_ContactPremise__c WHERE SPEN_Premise__c=:premId AND SPEN_RelatedContact__c=:conId];
			if(conP.size()>0){
				returnList = conP;
			}
			return returnList;
		}
	   public static List<SPEN_ContactPremise__c> getCPPrimaryConInfo(Id premId, Boolean isPrimary){
		List<SPEN_ContactPremise__c> returnList = new List<SPEN_ContactPremise__c>();
			List<SPEN_ContactPremise__c> conPrem = [SELECT Id, SPEN_RelatedContact__c, SPEN_Premise__c, SPEN_PremisePrimaryContact__c FROM SPEN_ContactPremise__c WHERE SPEN_Premise__c=:premId AND SPEN_PremisePrimaryContact__c=:isPrimary];       
			if(conPrem.size()>0){
				returnList = conPrem;
			}
			return returnList;
	   }
    public static List<SPEN_ContactPremise__c> getConPremise(Id contactId){
        List<SPEN_ContactPremise__c> getConPremiseRecords;
            getConPremiseRecords =[SELECT Id,SPEN_Premise__c,SPEN_Premise__r.SPEN_PremiseId__c,SPEN_RelatedContact__c
                               		  FROM SPEN_ContactPremise__c
                                      WHERE SPEN_RelatedContact__c =: contactId
                              		  WITH SECURITY_ENFORCED];
           return getConPremiseRecords;
    }
    
    public static List<SPEN_ContactPremise__c> getContactPremises(Set<Id> premiseIds)
    {
        return [Select Id,SPEN_RelatedContact__c
               FROM SPEN_ContactPremise__c
               WHERE SPEN_Premise__c IN: premiseIds
               WITH SECURITY_ENFORCED];
    }
    public List<SPEN_ContactPremise__c> selectByCustomerContactExternalId(Set<String> conUniqueIds)
	{
		return [Select Id
               FROM SPEN_ContactPremise__c
               WHERE SPEN_RelatedContact__c IN: conUniqueIds
               WITH SECURITY_ENFORCED];
	}
	public List<SPEN_ContactPremise__c> getCPRecordsAfterInsert(Set<Id> setCPIds)
	{// 5199 Related changes: Added required field 
		return [SELECT id,SPEN_RelatedContact__c, SPEN_RelatedContact__r.recordtype.developername,
				SPEN_Premise__r.SPEN_PremiseID__c, SPEN_Role__c,SPEN_RelatedContact__r.SPEN_CustomerID__c,SPEN_RelatedContact__r.SPEN_RequireSynctoADQM__c,
                SPEN_RelatedContact__r.SPEN_ContactRole__c
				FROM SPEN_ContactPremise__c
				WHERE id IN: setCPIds];
	}
	public static Map<Id,Id> checkPremiseForContact(Set<Id> conIds)
    {
        Map<Id,Id> conIdPremieIdMap = new Map<Id,Id>();
        for(SPEN_ContactPremise__c cpRec : [Select SPEN_RelatedContact__c,SPEN_Premise__c
                                           FROM SPEN_ContactPremise__c
                                           WHERE SPEN_RelatedContact__c IN: conIds])
        {
            conIdPremieIdMap.put(cpRec.SPEN_RelatedContact__c,cpRec.SPEN_Premise__c);
        }
        return conIdPremieIdMap;
    }
  // 5199 Related change start
    public static Map<Id, String> checkForExistingConPremRecord(Id contactId,Set<String> setOfContactRoles){
        Set<String> setOfRoles = new Set<String>();
        if(!setOfContactRoles.isEmpty()){
            setOfRoles = setOfContactRoles;
        }else{
            setOfRoles = new Set<String>{'Customer', 'Alternative Contact', 'PSR Contact', 'PSR Contact (Alternative)', 'Premise Owner'};
        }
        
        Map<Id, String> mapOfContactTaggedWithOthers = new Map<Id, String>();

		List<SPEN_ContactPremise__c> returnList = new List<SPEN_ContactPremise__c>();
        try{
            returnList = [SELECT Id, SPEN_RelatedContact__c, SPEN_Premise__c, SPEN_Premise__r.Name, SPEN_Role__c FROM SPEN_ContactPremise__c  WHERE  SPEN_RelatedContact__c = :contactId and SPEN_Premise__c != null and SPEN_Role__c IN :setOfRoles LIMIT 1];
            if(!returnList.isEmpty() && returnList[0].SPEN_Premise__c !=null){
                String finalMessage = returnList[0].SPEN_Role__c +'ConnectedWith'+returnList[0].SPEN_Premise__r.Name;
                mapOfContactTaggedWithOthers.put(contactId, finalMessage);
            }
        }Catch(Exception ex){
            SEL_LoggingService.log(ex);
        }
        return mapOfContactTaggedWithOthers;
	}
    // 5199 Related change end
    /***********************************************************
    @Author: Shubhi Vijayvergia
    @Date: 11/22/2023
    @purpose: Method for SPEN_ImpactedPremise
    ***************************************************************/ 
    public static List<SPEN_ContactPremise__c> getConPremiseRecordsFromPremiseIds(Set<String> premiseIds){
        List<SPEN_ContactPremise__c> getConPremiseRecords = new List<SPEN_ContactPremise__c>();
        if(!premiseIds.isEmpty())
        {
            getConPremiseRecords = [Select Id,SPEN_Premise__c,
                                    SPEN_Premise__r.SPEN_PremiseId__c,SPEN_RelatedContact__c,
                                    SPEN_RelatedContact__r.SPEN_SpecificVulnerability__c,
                                    SPEN_RelatedContact__r.SPEN_PSR__c
                                    FROM SPEN_ContactPremise__c
                                    WHERE SPEN_Premise__r.SPEN_PremiseId__c IN:premiseIds 
                                    AND SPEN_Role__c = 'Customer'];
        }
        return getConPremiseRecords;
    }
}